### PR TITLE
Fix - IgxCombo - Change combo default height to 40, itemsMaxHeight scales w/ item Height - 8.0.x

### LINKED ISSUE #5184: [igx-combo] Combo has incorrect default itemHeight and itemMaxHeight
## Description  
Since `displayDensity` is now defined for combo items, the default item height should be brought down from `48` (current default) to `40` (comfortable). The `itemsMaxHeight` default value should also be brought down from `480` (current) to `400` (10 * newHeight).

Furthermore, the combo's `itemsMaxHeight` should always default to 10 * itemHeight.  

 * igniteui-angular version: 8.0.x, 7.3.x
 * browser: N/A

## Steps to reproduce  
1. `<igx-combo [displayDensity]="'comfortable'">` w/o specifying anything in `[itemHeight]` input
2. Observe the items

## Result  
Combo items are larger than `40px` even when no `itemHeight` input is specified

## Expected result  
Combo items are `40px`, the list contains `10` items.

### PR DESCRIPTION
**Pull request by ViktorSlavov**
Closes #5184 

### Additional information (check all that apply):
 - [x] Bug fix
 - [x] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [x] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/combo/combo.component.ts [hunk 1]
```diff
@@ -578,7 +579,16 @@ export class IgxComboComponent extends DisplayDensityBase implements IgxComboBas
      * ```
     */
     @Input()
-    public itemsMaxHeight = 480;
+    public get itemsMaxHeight(): number {
+        if (this._itemsMaxHeight === null || this._itemsMaxHeight === undefined) {
+            return this.itemHeight * 10;
```
Comment (wnvko) [inline projects/igniteui-angular/src/lib/combo/combo.component.ts]: I would change this to:
this._itemsMaxHeight = this.itemHeight * 10;
this way we have single return.
10 could be const too.

Comment (ViktorSlavov) [reply projects/igniteui-angular/src/lib/combo/combo.component.ts]: I agree that 10 should be a const - thanks for pointing it out!
We cannot do `this._itemsMaxHeight = this.itemHeight * 10`, as it would break the functionality - the next time we change item height, `this._itemsMaxHeight !== null` and we will not enter the `if` statement - the value won't change and the list will not scale to contain 10 items.
