### PR TITLE
fix(filtering): Refactor the grid filtering row #4967

### LINKED ISSUE #4967: Condition chip in filter row cannot be toggled with mouse click
## Description  
Condition chip in filter row cannot be toggle with mouse click.

 * igniteui-angular version: 7.2.x, 7.3.x
 * browser: any

## Steps to reproduce  

1. Run the "Grid Column Groups" dev demo.
2. Add a filter condition for the **ContactName** column.
3. Click the newly added condition chip to put it in edit mode.
3. Click the newly added condition chip again to commit it.

## Result  
Chip is committed and then reverts back in edit mode.

## Expected result  
Chip is committed.

## Attachments  

filterRow

### PR DESCRIPTION
**Pull request by astaev**
Closes #4967 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts [hunk 1]
```diff
@@ -527,44 +534,55 @@ export class IgxGridFilteringRowComponent implements AfterViewInit {
...
-        } else if (this.expression === expression) {
+        } else if (this.expression === item.expression) {
             this.resetExpression();
         }
     }
 
+    /**
+     *  Event handler for chip selected event.
+     */
+    public onChipSelected(eventArgs: IChipSelectEventArgs) {
```
Comment (DiyanDimitrov) [inline projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts]: Do we need this method? We should extract a `toggleSelection` method which should be called in `onChipClick` and `onChipKeyDown` in order to avoid code duplication.

File: projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts [hunk 2]
```diff
@@ -386,6 +391,8 @@ export class IgxGridFilteringRowComponent implements AfterViewInit {
      */
     public clearInput() {
         this.value = null;
+        const selectedChip = this.expressionsList.findIndex(ex => ex.isSelected === true);
```
Comment (DiyanDimitrov) [inline projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts]: Rename `selectedChip` to `selectedIndex`. Should we always delete the selected item when clearing the input?

File: projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts [hunk 3]
```diff
@@ -79,8 +79,13 @@ export class IgxGridFilteringRowComponent implements AfterViewInit {
             this._column = val;
 
             this.expressionsList = this.filteringService.getExpressions(this._column.field);
+            const selectedChip = this.expressionsList.find(ex => ex.isSelected);
 
+            if (selectedChip) {
+                this.expression = selectedChip.expression;
```
[the remark this answers is not in the document]
Comment (astaev) [reply projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts]: Removing it.

File: projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts [hunk 4]
```diff
@@ -364,8 +369,8 @@ export class IgxGridFilteringRowComponent implements AfterViewInit {
      * Commits the value of the input.
      */
     public commitInput() {
-        this.expressionsList.forEach(ex => ex.isSelected = false);
-        this.chipsArea.chipsList.forEach(chip => chip.selected = false);
+        const selectedChip = this.expressionsList.filter(ex => ex.isSelected === true);
```
[the remark this answers is not in the document]
Comment (astaev) [reply projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts]: Done

File: projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts (hunk 2 above)
Comment (astaev) [reply projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts]: That is fixing the issue with the empty chip - when click the X input button.

Comment (astaev) [reply projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts]: Addressed

File: projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts (hunk 1 above)
Comment (astaev) [reply projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts]: Selection handler is now removed

File: projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts [hunk 5]
```diff
@@ -6050,3 +6021,13 @@ function verifyChipVisibility(fix, index: number, shouldBeFullyVisible: boolean)
     expect(chipRect.left >= visibleChipAreaRect.left && chipRect.right <= visibleChipAreaRect.right)
         .toBe(shouldBeFullyVisible, 'chip[' + index + '] visibility is incorrect');
 }
+
+function ClickElemAndBlur(clickElem, blurElem) {
```
Comment (DiyanDimitrov) [inline projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts]: Use camel case for the function name.
