### PR TITLE
fix(gridforof): adding master reassignment for scrambled horizontal dirs - 7.2

### LINKED ISSUE #4505: When hide/show columns the grid has empty space
## Description  
When hide/show columns the grid has empty space

 * igniteui-angular version: 7.2
 * browser: n/a

## Steps to reproduce  

1. Open dev sample gridSummary
2. Scroll vertically to bottom
3. Click button Hide to hide column UnitsInStock
4. Click button Hide again to show column
5. Click button Hide to hide column UnitsInStock
6. Scroll horizontal to the end

Note1: This is reproducible in 7.2 and also in PR #4476 
Note2: This is not reproducible in 7.1
## Result  
Grid has empty space

## Expected result  
Grid should not have empty space

## Attachments  

image

### LINKED ISSUE #4568: [igx-grid] some cells are not rendered when resizing window.
## Description  
Some cells are not rendered when resizing window.

 * igniteui-angular version: 7.2.5
 * browser: N/A

## Steps to reproduce  

1. Make browser window size down.
2. Run the attached sample.
3. Vertical scroll down to the middle.
4. Horizontal scroll right to the middle.
5. Click maximize button of the browser.

## Result  
Some cells are not rendered.

### Before maximizing
before

### After maximizing
after

## Expected result  
Cells should be rendered.

## Attachments  
[igx-grid-rendering-cell-issue.zip](https://github.com/IgniteUI/igniteui-angular/files/3087742/igx-grid-rendering-cell-issue.zip)

### LINKED ISSUE #4648: [igx-grid]  after being grouped then resized, horizontal scrolling causes column header misalignment with data cell
## Description  
After being grouped then resized, horizontal scrolling causes column header. misalignment with data cell.

 * igniteui-angular version: 7.2.6
 * browser: N/A

## Steps to reproduce  

1. Go to https://stackblitz.com/edit/igx-grid-misalignment-issue-726
2. Group by any column.
3. Resize any column.
4. Horizontal scroll gradually.

## Result  
After step 4, column headers get misalignment with data cells.
result

## Expected result  
Column headers should align with data cells.

### LINKED ISSUE #4720: Cells content is misaligned when group by a column and scroll horizontal
## Description  
Cells content is misaligned when group by a column and scroll horizontal

 * igniteui-angular version: 7.3
 * browser: n/a

## Steps to reproduce  

1. Edit dev sample gridGroupBy and for column Salary set pinned to false
2. Open the sample
3. Group by column CompanyName
4. Scroll horizontal

## Result  
Cell content is misaligned and when try to navigate with keyboard an error is shown

## Expected result  
Cells should be correct and should be able to navigate with keyboard

## Attachments  
image

### PR DESCRIPTION
**Pull request by ChronosSF**
Closes #4568
Closes #4648
Closes #4720 
Closes #4505 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/grid-base.component.ts [hunk 1]
```diff
@@ -2531,6 +2532,7 @@ export abstract class IgxGridBaseComponent extends DisplayDensityBase implements
         @Optional() @Inject(DisplayDensityToken) protected _displayDensityOptions: IDisplayDensityOptions) {
         super(_displayDensityOptions);
         this.resizeHandler = () => {
+            this.resetForOfCache();
```
Comment (rkaraivanov) [inline projects/igniteui-angular/src/lib/grids/grid-base.component.ts]: What about the `onColumnResized` event handler?

File: projects/igniteui-angular/src/lib/directives/for-of/for_of.sync.service.ts [hunk 2]
```diff
@@ -22,8 +22,8 @@ export class IgxForOfSyncService {
     /**
      * @hidden
      */
-    public setMaster(directive: IgxGridForOfDirective<any>) {
-        if (!this._master[directive.igxForScrollOrientation]) {
+    public setMaster(directive: IgxGridForOfDirective<any>, forced = false) {
+        if (forced || !this._master[directive.igxForScrollOrientation]) {
```
Comment (rkaraivanov) [inline projects/igniteui-angular/src/lib/directives/for-of/for_of.sync.service.ts]: If `_master` is a Map type, can we use the Map API -> `set(), has(), delete()`

File: projects/igniteui-angular/src/lib/grids/grid-base.component.ts (hunk 1 above)
Comment (ChronosSF) [reply projects/igniteui-angular/src/lib/grids/grid-base.component.ts]: I guess,  instead of trying to assign the top-most hor dir as master every time it would cause a cache or chunkSize change, we could have the service be informed by the grid that horizontal changes will be made, so that it will cause the update outside of the changeDetection cycle. It will require some refactoring inside the GridForOf code tho. I'll experiment with it a little.

Comment (ChronosSF) [reply projects/igniteui-angular/src/lib/grids/grid-base.component.ts]: I guess, instead of trying to assign the top-most hor dir as master every time it would cause a cache or chunkSize change, we could have the service be informed by the grid that horizontal changes will be made, so that it will cause the update outside of the change detection cycle. It will require some refactoring inside the GridForOf code tho (e.g. the calcMaxChunkSize should be able to work of a parameter sent by the grid, not just the igxForOf input). I'll experiment with it a little.

Not sure I am fond of creating a "detection" patch like that but then again I am not fond of having to reset master on now 3 places inside the grid either. There is probably no win-win solution for this.

If the syncService wasn't giving the 10% rendering speed improvement I'd have removed it a month ago probably. It just doesn't play well with all the other perf optimization's we've made.

Comment (ChronosSF) [reply projects/igniteui-angular/src/lib/grids/grid-base.component.ts]: > Is it possible to make the sync service inform the master cache (either through event/direct call) to recalculate the chunk size cache based on some grid interaction (resizing namely)?

I guess, instead of trying to assign the top-most hor dir as master every time it would cause a cache or chunkSize change, we could have the service be informed by the grid that horizontal changes will be made, so that it will cause the update outside of the change detection cycle. It will require some refactoring inside the GridForOf code tho (e.g. the calcMaxChunkSize should be able to work of a parameter sent by the grid, not just the igxForOf input). I'll experiment with it a little.

Not sure I am fond of creating a "detection" patch like that but then again I am not fond of having to reset master on now 3 places inside the grid either. There is probably no win-win solution for this.

If the syncService wasn't giving the 10% rendering speed improvement I'd have removed it a month ago probably. It just doesn't play well with all the other perf optimization's we've made.

**Comment by ChronosSF** [comment]
@rkaraivanov ,  @mpavlinov , resetting on the width setter doesn't seem to affect performance in a measurable way. I think this is ready for test.
