### PR TITLE
fix(expansion-panel): make header interaction cancelable - master

### LINKED ISSUE #8190: onInteraction event of the igxExpansionPanelHeaderComponent is not cancelable
## Description  
In regards to a customer requirement of being able to toggle the panel by clicking on the expand/collapse indicator exclusively determined that this event can not be cancelled, which is the best approach for achieving such behavior.

 * igniteui-angular version: 9.1.x, 10.1.x
 * browser: any

## Steps to reproduce  

1. Run this sample: https://stackblitz.com/edit/expansion-panel-cancelable-on-interaction-event
2. Click on the expand indicator
3. Click on the panel`s header

## Result  
Expansion panel is toggled via both expand indicator and panel`s header.

## Expected result  
To have a mechanism for triggering toggling only from the expansion indicator.

### PR DESCRIPTION
**Pull request by ViktorSlavov**
Closes #8190 
Make `onInteraction` event cancelable  

### Additional information (check all that apply):
 - [ ] Bug fix
 - [x] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [x] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [x] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [x] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/expansion-panel/expansion-panel.component.ts [hunk 1]
```diff
@@ -229,7 +229,7 @@ export class IgxExpansionPanelComponent implements IgxExpansionPanelBase, AfterC
         }
         this.playCloseAnimation(
             () => {
-                this.onCollapsed.emit({ event: evt, panel: this });
+                this.onCollapsed.emit({ event: evt, panel: this, owner: this });
```
Comment (wnvko) [inline projects/igniteui-angular/src/lib/expansion-panel/expansion-panel.component.ts:232]: please update the comments for this event, as  it is not pointing in TS part the correct type of the event - `IExpansionPanelEventArgs`. It looks like this now:
```
     * ```typescript
     *  handleCollapsed(event: {
     *  panel: IgxExpansionPanelComponent,
     *  event: Event
     * })
     * ```
```

File: projects/igniteui-angular/src/lib/expansion-panel/expansion-panel.component.ts [hunk 2]
```diff
@@ -253,7 +253,7 @@ export class IgxExpansionPanelComponent implements IgxExpansionPanelBase, AfterC
         this.cdr.detectChanges();
         this.playOpenAnimation(
             () => {
-                this.onExpanded.emit({ event: evt, panel: this });
+                this.onExpanded.emit({ event: evt, panel: this, owner: this });
```
Comment (wnvko) [inline projects/igniteui-angular/src/lib/expansion-panel/expansion-panel.component.ts:256]: please update the comments for this event, as  it is not pointing in TS part the correct type of the event - `IExpansionPanelEventArgs`. It looks like this now:
```
     * ```typescript
     *  handleExpanded(event: {
     *  panel: IgxExpansionPanelComponent,
     *  event: Event
     * })
     * ```
```

**Review by wnvko — CHANGES_REQUESTED** [review]

**Review by wnvko — APPROVED** [review]
