### PR TITLE
fix(drag): Improve dom check to support ShadowDom as well.

### LINKED ISSUE #13321: Using ShadowDom encapsulation prevents draggable elements from dragging.
## Description  
When using ShadowDom encapsulation currently prevents draggable elements from dragging due to changes in #12966

 * igniteui-angular version: 16.1.x
 * browser: any

## Steps to reproduce  

1.Open drag and drop sample
2. Set encapsulation to ShadowDom
3. Try interacting with the samples

## Result  
IgxDrag directive does not drag elements correctly when using ShadowDom

## Expected result  
IgxDrag directive should work as expected when using ShadowDom

### PR DESCRIPTION
**Pull request by skrustev**
Closes #13321

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/directives/drag-drop/drag-drop.directive.ts [hunk 1]
```diff
@@ -918,7 +918,7 @@ export class IgxDragDirective implements AfterContentInit, OnDestroy {
         // Set pointer capture so we detect pointermove even if mouse is out of bounds until ghostElement is created.
         const handleFound = this.dragHandles.find(handle => handle.element.nativeElement === event.target);
         const targetElement = handleFound ? handleFound.element.nativeElement : event.target || this.element.nativeElement;
-        const targetValid = document.body.contains(targetElement);
+        const targetValid = this.isElementInDOM(targetElement);
```
Comment (MayaKirova) [inline projects/igniteui-angular/src/lib/directives/drag-drop/drag-drop.directive.ts:921]: If we just want to check if element is in the DOM it might be simpler to use the `isConnected` API. It's supported in all major browsers (https://caniuse.com/mdn-api_node_isconnected) and I think we've already used it in some cases for the `ForOf`.

**Review by MayaKirova — CHANGES_REQUESTED** [review]

**Review by MayaKirova — APPROVED** [review]
