### PR TITLE
Ttonev/fix 9318 master

### LINKED ISSUE #9318: Accessibility Issue with empty Grid
## Description  
Describe the issue.

 * igniteui-angular version: 11.1.7
 * browser: Microsoft Edge (Chromium)

## Steps to reproduce  

1. Define an igx-grid element and set its _emptyGridMessage_ attribute to a value like "No data available"
2. Run an accessibility tool (like FastPass - https://accessibilityinsights.io/downloads/)

## Result  
**Path**
.igx-grid__tbody

**snippet**
<div igxgridbody="" role="rowgroup" class="igx-grid__tbody">

**How to fix**
Fix the following: Required ARIA child role not present: row

## Expected result  
No accessibility warnings

## Attachments  
Empty Grid

## Potential Solution
As per the attached image, adding the _role="row"_ attribute to the interior <div> and then also added the _role="gridcell"_ to the internal <span> - which contains the content for the _emptyGridMessage_ property - was one way to resolve the alert/warning.

### PR DESCRIPTION
**Pull request by tishko0**
Closes #9318 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Review by hanastasov — DISMISSED** [review]

File: projects/igniteui-angular/src/lib/grids/grid-base.directive.ts [hunk 1]
```diff
@@ -4576,6 +4576,7 @@ export abstract class IgxGridBaseDirective extends DisplayDensityBase implements
     public filter(name: string, value: any, conditionOrExpressionTree?: IFilteringOperation | IFilteringExpressionsTree,
         ignoreCase?: boolean) {
         this.filteringService.filter(name, value, conditionOrExpressionTree, ignoreCase);
+        this.cdr.detectChanges();
```
Comment (hanastasov) [inline projects/igniteui-angular/src/lib/grids/grid-base.directive.ts:4579]: Is that needed?

File: projects/igniteui-angular/src/lib/grids/grid-base.directive.ts [hunk 2]
```diff
@@ -3008,7 +3008,7 @@ export abstract class IgxGridBaseDirective extends DisplayDensityBase implements
     /**
      * @hidden @internal
      */
-    private get hasNoData(): boolean {
+    public get hasNoData(): boolean {
```
Comment (hanastasov) [inline projects/igniteui-angular/src/lib/grids/grid-base.directive.ts:3011]: Since `hasNoData` will not be used in the template, keep its accessor to be private.

**Review by hanastasov — CHANGES_REQUESTED** [review]
Change the `hasNoData` accessor to what it was befrfe

File: projects/igniteui-angular/src/lib/grids/grid/grid.component.html [hunk 3]
```diff
@@ -96,7 +96,7 @@
 </div>
 
 <div igxGridBody (keydown.control.c)="copyHandler($event)" (copy)="copyHandler($event)" class="igx-grid__tbody" role="rowgroup">
-    <div class="igx-grid__tbody-content" tabindex="0" (keydown)="navigation.handleNavigation($event)" (focus)="navigation.focusTbody($event)"
+    <div class="igx-grid__tbody-content" tabindex="0" [attr.role]="dataView.length ? null : 'row'" (keydown)="navigation.handleNavigation($event)" (focus)="navigation.focusTbody($event)"
```
Comment (kdinev) [inline projects/igniteui-angular/src/lib/grids/grid/grid.component.html:99]: With Angular 12 you can use the `??` operator!

**Review by kdinev — CHANGES_REQUESTED** [review]

**Review by kdinev — APPROVED** [review]

**Comment by GibletJr** [comment]
I appears that this fix (9318) has been released with 10.2.23.  Is it also part of 11.1.11 or will it be part of 11.1.12 or a future release?

**Comment by kdinev** [comment]
@GibletJr The fix is also included in `11.1.11`.

**Comment by GibletJr** [comment]
@kdinev - confirmed that the fix is in release in 11.1.11 and resolves the issue for igx-grid; however, found that igx-hierarchical-grid application of the same resolution.

**Comment by kdinev** [comment]
@tishko0 @MayaKirova @ChronosSF Could you please check why this fix has not applied to the `igx-hierarchical-grid`?

**Comment by GibletJr** [comment]
@kdinev - thanks for pushing for the change on igx-hierarchical-grid as well.  Is there a separate git issue that I should use to track its completion?

**Comment by GibletJr** [comment]
@ChronosSF / @kdinev  - still looking for confirmation on pickup and ETA on applying this change to igx-hierarchical-grid?

**Comment by ChronosSF** [comment]
I reopened the original issue and we'll provide a fix asap.
