### PR TITLE
Set the internal value of the range picker with present ngModels on its projected inputs

### LINKED ISSUE #7353: Calendar does not select the range corresponding to dates in the inputs
## Description  
In `IgxDateRangePicker` when `ngModel` is set on the inputs when calendar opens the corresponding range of dates is not selected.

 * igniteui-angular version: 9.1.x
 * browser: all

## Steps to reproduce  

1. Run the dev samples.
2. Go to DateRange sample.
3. Open the calendar under `Template-driven form` - `Single template with initial value on inputs` (the fifth sample in the middle column).

## Result  
There is no selected range in the calendar.

## Expected result  
The dates in the calendar should be selected according to the range in the inputs of the component.

### PR DESCRIPTION
**Pull request by jackofdiamond5**
Closes #7353

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.ts [hunk 1]
```diff
@@ -915,13 +917,23 @@ export class IgxDateRangePickerComponent extends DisplayDensityBase
...
+        // their ngModels - we should generate our initial control value
+        if ((!this.value || (!this.value.start && !this.value.end)) && this.hasProjectedInputs && !this._ngControl) {
+            const start = this.projectedInputs.find(i => i instanceof IgxDateRangeStartComponent);
+            const end = this.projectedInputs.find(i => i instanceof IgxDateRangeEndComponent);
+            const value = {
+                start: start.dateTimeEditor.value,
+                end: end.dateTimeEditor.value
+            };
+
+            if (start.dateTimeEditor.ngControl && end.dateTimeEditor.ngControl) {
```
Comment (wnvko) [inline projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.ts:930]: this check is not necessary. Go ahead and set the field like this:
```
this._value = value;
```
Calling `updateValue` will do the same and will set the values of the projected inputs. But you just took the values from them. Actually you can simplify this to:
```
this._value = {
    start: start.dateTimeEditor.value,
    end: end.dateTimeEditor.value
};
```
