### PR TITLE
fix(igxHierarchicalGrid): Recalc childgrid sizes when parent grid dat…

### LINKED ISSUE #4435: In igxHierarchicalGrid after a filtered row gets expanded, its horizontal scrollbar is not fully visible if the Filtering gets reset
## Description  
In igxHierarchicalGrid, if a filtered record gets expanded, its horizontal scrollbar is not fully visible once the Filtering conditions are cleared. 

 * igniteui-angular version: 7.2.x
 * browser: N/A

## Steps to reproduce  

1. Run the attached sample
2. Filter the Artist column by "Ahmad" - only a single row should be visible
3. Expand the filtered row
4. Remove the filtering condition so that all records are visible again

## Result  
The horizontal scrollbar of the expanded child grid is not fully visible - its right arrow is missing (refer to the first screenshots below). If the user expands another row, its scrollbar is displayed correctly - screenshot 2.

## Expected result  
The horizontal scrollbar of the child grid should be visible

## Attachments  
Sketch1

Sketch2

[HGridKeyboardNav.zip](https://github.com/IgniteUI/igniteui-angular/files/3033493/HGridKeyboardNav.zip)

### PR DESCRIPTION
**Pull request by MayaKirova**
…a changes.

Closes #4435  

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts [hunk 1]
```diff
@@ -370,6 +370,13 @@ export class IgxHierarchicalGridComponent extends IgxHierarchicalGridBaseCompone
                     }
                 });
             });
+            this.parent.verticalScrollContainer.onDataChanged.pipe(takeUntil(this.destroy$)).subscribe(() => {
```
Comment (ChronosSF) [inline projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts]: Will this work in-depth. If multiple descendants need to get reflowed because of a parent. This binds to a parent but will the reflow cause an onDataChanged for the children to get updated?

Comment (MayaKirova) [reply projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts]: Applied changes to reflow children that have percentage width as well.
