### PR TITLE
Use ngControl for combo validation

### LINKED ISSUE #4286: Combo in form is marked as invalid when the value is empty, even there isn't a validator
## Description  
Combo, placed in a form, is marked as invalid when the combo's value is empty, even there isn't a validator defined.

 ## Steps to reproduce  

1. Open combo in a form [sample](https://stackblitz.com/angular/xlgolklgrae).
2. Go to the HTML page and find igx-combo
3. Remove the required attribute, so that favorite genre is not needed to submit the form.
4. Select the first item in the combo and deselect it, so that combo field is empty.

## Result  
The combo is marked as invalid.

## Expected result  
The combo should not be marked is invalid, because there isn't validator defined.
This should be verified with combo inside a reactive form.

## Attachments  
image

### PR DESCRIPTION
**Pull request by Lipata**
- When there isn't a validator defined - no style is applied and `valid` returns `IgxComboState.INITIAL`
- When there is a validator defined - invalid style is applied and `valid` returns `IgxComboState.INVALID` when the combo is on focus and is blurred.
- When there is a validator defined - valid style is applied and `valid` returns `IgxComboState.VALID` when combo on focus and no style are applied and `valid` returns `IgxComboState.INITIAL` when the combo is blurred.
>Note: The behaviors above are the same as in the `igx-input`

Closes #4286   

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/combo/combo.component.ts [hunk 1]
```diff
@@ -1274,6 +1287,10 @@ export class IgxComboComponent extends DisplayDensityBase implements IgxComboBas
      */
     public ngAfterViewInit() {
         this.filteredData = [...this.data];
+
+        if (this.ngControl) {
+            this._statusChanges$ = this.ngControl.statusChanges.subscribe(this.onStatusChanged.bind(this));
```
Comment (ViktorSlavov) [inline projects/igniteui-angular/src/lib/combo/combo.component.ts]: Could this subscription be with a `takeUntil` pipe? It would still prevent memory leaks w/o the need of manually unsubbing in `ngOnDestroy`.
```
this._statusChanges$ = this.ngControl.statusChanges.pipe(takeUntil(this.destroy$)).subscribe(this.onStatusChanged.bind(this))
```

File: projects/igniteui-angular/src/lib/combo/combo.component.ts [hunk 2]
```diff
@@ -1263,6 +1273,7 @@ export class IgxComboComponent extends DisplayDensityBase implements IgxComboBas
      * @hidden @internal
      */
     public ngOnInit() {
+        this.ngControl = this.injector.get(NgControl, null);
```
Comment (damyanpetev) [inline projects/igniteui-angular/src/lib/combo/combo.component.ts]: 🕶
