### PR TITLE
Removed any type and added more descriptive types in GridComponent.

### LINKED ISSUE #2776: Grid api uses the "any" type instead of more descriptive types in some components.
### Description  
Using the type any in some places isn't meaningful enough for the one who uses the components.
 * igniteui-angular version: 
 * browser: 

### Steps to reproduce  

1. Open angular api
2. Open https://staging.infragistics.local/products/ignite-ui-angular/docs/typescript/classes/igxgridcomponent.html#groupsrowlist for example
3. Instead `QueryList<any>` the get groupsRowList() should be of type `QueryList<IgxGridGroupByRowComponent>` which is far more descriptive.

### Grid components where changes should be applied:
- [x] grid.component.ts

### Attachments  
anyscreenshot

### PR DESCRIPTION
**Pull request by MartinKamenov**
Closes #2776  .  

~~Additional information related to this pull request:
Added parameter to the event emitter of the onDensityChanged event of type 
IDensityChangedEventArgs.~~

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grid/grid.component.ts [hunk 1]
```diff
@@ -147,6 +147,11 @@ export interface IColumnMovingEndEventArgs {
     cancel: boolean;
 }
 
+export interface IDensityChangedEventArgs {
```
Comment (kdinev) [inline projects/igniteui-angular/src/lib/grid/grid.component.ts]: This will not be needed with #2804.

File: projects/igniteui-angular/src/lib/grid/grid.component.ts [hunk 2]
```diff
@@ -560,6 +565,7 @@ export class IgxGridComponent implements OnInit, OnDestroy, AfterContentInit, Af
 	 * @memberof IgxGridComponent
      */
     public set displayDensity(val: DisplayDensity | string) {
+        const currentDisplayDensity = this._displayDensity;
```
Comment (kdinev) [inline projects/igniteui-angular/src/lib/grid/grid.component.ts]: Same applies here. This will not be needed with #2804.
