### PR TITLE
fix(schematics): ng add for all projects #11761

### LINKED ISSUE #11761: ng add igniteui-angular is throwing exception for 14
## Description  
`ng add igniteui-angular` is throwing exception for 14, because "defaultProject" config in angular.json is deprecated.

 * igniteui-angular version: 14.0.1

## Steps to reproduce  

1. npm i -g @angular/cli 
2. npm i -g @igniteui/angular-schematics
3. ng new
4. ng add igniteui-angular

## Result  
```console
Cannot read properties of undefined (reading 'targets')
```

## Expected result  
igniteui-angular project is added to the project generated with angular cli.

## Temporary workaround
After `ng new`, go to the angular.json and add manually:

```
  "projects": {
	...
  },
  "defaultProject": "proj_14"
```

### PR DESCRIPTION
**Pull request by Lipata**
Closes #11761 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by Lipata** [comment]
@kdinev now `ng add` is adding `igniteui-angular` configurations to all the available projects in the app.  This change is also available in 14.0.x branch and require the following changes in the `igniteui-cli`: https://github.com/IgniteUI/igniteui-cli/pull/1048.

File: projects/igniteui-angular/schematics/ng-add/add-normalize.ts [hunk 1]
```diff
@@ -14,47 +14,51 @@ export const scssImport =
...
-        const name = Object.keys(resetPackage)[0];
-        return addPackageToPkgJson(host, name, resetPackage[name], 'dependencies');
-    }
-    return false;
+                break;
+            default:
+                break;
+        }
+
+        if (addPackage) {
```
Comment (kdinev) [inline projects/igniteui-angular/schematics/ng-add/add-normalize.ts:57]: I believe this should be outside of the projects forEach loop.

File: projects/igniteui-angular/schematics/utils/dependency-handler.ts [hunk 2]
```diff
@@ -156,24 +156,26 @@ const addHammerToConfig =
...
+        for (const pkg of Object.keys(pkgJson.dependencies)) {
+            const version = pkgJson.dependencies[pkg];
+            const entry = DEPENDENCIES_MAP.find(e => e.name === pkg);
+            if (!entry || entry.target === PackageTarget.NONE) {
+                continue;
+            }
+            switch (pkg) {
+                case 'hammerjs':
+                    logIncludingDependency(context, pkg, version);
+                    addPackageToPkgJson(tree, pkg, version, entry.target);
```
Comment (kdinev) [inline projects/igniteui-angular/schematics/utils/dependency-handler.ts:170]: Again, shouldn't the `package.json` update be outside of the loop?

**Review by kdinev — CHANGES_REQUESTED** [review]

**Review by kdinev — APPROVED** [review]
