### PR TITLE
fix(button-group): button selection not visible in disabled mode

### LINKED ISSUE #5788: There is no difference between active and selected buttons in button group
## Description  
There is no difference between active and selected buttons in button group

 * igniteui-angular version: 8.2
 * browser: n/a

## Steps to reproduce  

1. pen the Button Group dev demo.
2. In the 'Templated buttons. Vertical' click on first button
3. Press tab key

## Result  
Button1 and Button2 have same background color, but one is selected and the other one is active

## Expected result  
There should be difference in the background colors

## Attachments  
image

### LINKED ISSUE #5796: In disabled button group there should be indication for selected button
## Description  
In disabled button group there should be indication for selected button

 * igniteui-angular version: 8.2
 * browser: n/a

## Steps to reproduce  

1. Open dev sample buttonGroup
2. Look at the 'Multiple Selection Horizontal Disabled' buttons group

## Result  
Button Italic is selected but there is no difference with other buttons

## Expected result  
There should be indication for selected button

## Attachments  
image

### PR DESCRIPTION
**Pull request by simeonoff**
Closes #5796 Closes #5788

There was not discernible difference between selected buttons and
disabled buttons when the button group is disabled. Also, the active and
selected buttons now have different background colors.

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/buttonGroup/buttonGroup.component.ts [hunk 1]
```diff
@@ -298,10 +298,6 @@ export class IgxButtonGroupComponent extends DisplayDensityBase implements After
         const button = this.buttons[index];
         const buttonElement = button.nativeElement;
 
-        if (buttonElement.classList.contains('igx-button--disabled')) {
```
Comment (nrobakova) [inline projects/igniteui-angular/src/lib/buttonGroup/buttonGroup.component.ts]: This should be removed from deselectButton method also, because now when have single selection the selection of disabled button is not removed
