### PR TITLE
Recalculate summaries when row is updated

### LINKED ISSUE #4949: Child summaries disappears when edit a cell and press tab on click on cell in same row when rowEditable is true
## Description  
Child summaries disappears when edit a cell and press tab on click on cell in same row when rowEditable is true

 * igniteui-angular version: 7.3
 * browser: n/a

## Steps to reproduce  

1.Open dev sample treeGridFlatData
2. Click button rootAndChildLevels
3. Select the Enable Row Editing
4. Double click on cell in column Salary and row ID 4
5. Change its value
6. Press tab key or click on a cell in same row

## Result  
The child summaries are empty

## Expected result  
The child summaries should be displayed

## Attachments  
image

### PR DESCRIPTION
**Pull request by ddincheva**
Closes #4949 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/grid-base.component.ts [hunk 1]
```diff
@@ -3713,13 +3713,6 @@ export abstract class IgxGridBaseComponent extends DisplayDensityBase implements
         this.gridAPI.clear_sort(name);
     }
 
-    /**
-     * @hidden
-     */
-    @DeprecateMethod('There is no need to call clearSummaryCache method.The summary cache is cleared automatically when needed.')
```
Comment (kdinev) [inline projects/igniteui-angular/src/lib/grids/grid-base.component.ts]: Add a changelog update that the deprecated methods have now been removed.
