### PR TITLE
fix(Pivot): Filtering strategy does not work for complex objects in P…

### LINKED ISSUE #10890: [igxPivot] Filtering out any of the values from the row or columns causes the data content to disappear.
## Description  
In the Pivot Grid Hierarchy sample, filtering out any of the values via the excel style filtering causes no cells to be rendered in the data rows.

 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Open the Pivot Grid Hierarchy dev sample.
2. Filter out 1 values from either a row dimension or column dimension via its excels style filter.

## Result  
The content disappears. Note that the pipes return correct results, however no cells are rendered in the grid to show them:

image

## Expected result  
The filtered values are shown in the data area.

## Attachments  
Attach a sample if available, and screenshots, if applicable.

### PR DESCRIPTION
**Pull request by mddragnev**
…ivot

Closes #10890   

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/data-operations/filtering-strategy.ts [hunk 1]
```diff
@@ -139,3 +140,23 @@ export class FormattedValuesFilteringStrategy extends FilteringStrategy {
         return value;
     }
 }
+
+export class PivotFilteringStrategy extends FilteringStrategy {
```
Comment (MayaKirova) [inline projects/igniteui-angular/src/lib/data-operations/filtering-strategy.ts:144]: This looks very similar to the existing DimensionValuesFilteringStrategy. Can't we re-use that one?

File: projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-filtering.service.ts [hunk 2]
```diff
@@ -42,6 +43,7 @@ export class IgxPivotFilteringService extends IgxFilteringService {
         this.prepare_filtering_expression(filteringTree, fieldName, term, conditionOrExpressionsTree, ignoreCase, fieldFilterIndex);
         dim.filter = filteringTree;
         grid.filteringPipeTrigger++;
+        grid.filterStrategy = new PivotFilteringStrategy();
```
Comment (MayaKirova) [inline projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-filtering.service.ts:46]: In case the user has set a custom filter strategy, for example:

```
<igx-pivot-grid  [filterStrategy]="noopFilterStrategy" ...>
```

This will probably overwrite it. 

We should not overwrite it if the user has set a different one.

**Review by MayaKirova — CHANGES_REQUESTED** [review]

**Review by MayaKirova — APPROVED** [review]

**Comment by skrustev** [comment]
Setting the filtering condition initially in the pivot configuration also seems to not render the pivot grid correctly:

1. Open the hierarchical pivot grid
2. Set for the `City` dimension the following filter:


```
    public cityFilter = new FilteringExpressionsTree(FilteringLogic.And);
   //...
        {
            memberName: 'City',
            memberFunction: (data) => data.Seller.City,
            enabled: true,
            filter: this.cityFilter
        },
//...

    constructor() {
        this.cityFilter.filteringOperands = [
            {
                condition: IgxStringFilteringOperand.instance().condition('equals'),
                fieldName: 'City',
                searchVal: 'Sofia'
            }
        ];
    }
```

**Comment by mddragnev** [comment]
@skrustev should be good now.

**Review by MayaKirova — APPROVED** [review]
