### PR TITLE
fix(igx-cell): Focus and IME input handlers

### LINKED ISSUE #4314: igx-grid: Uncommitted IME text gets lost when Enter key is pressed in an edit cell template.
## Description  
Uncommitted IME text gets lost  when Enter key is pressed in an edit cell template.

 * igniteui-angular version:  7.2.0
 * browser: IE11

## Steps to reproduce  

1.Run the sample.
2.Double click any cell in "col2" column.
3.Enable IME input.
4.Enter some characters.
5.Press Enter key.

## Result  
Inputs get lost.

## Expected result  
Inputs should be committed.

## Attachments  
Attach a sample if available, and screenshots, if applicable.  
[igxGrid.zip](https://github.com/IgniteUI/igniteui-angular/files/2964839/igxGrid.zip)

### PR DESCRIPTION
**Pull request by rkaraivanov**
Also fixed a wrong import path that broke the AoT build

Closes #4314 #1780

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code
 - [x] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/cell.component.ts [hunk 1]
```diff
@@ -259,41 +259,34 @@ export class IgxGridCellComponent implements OnInit, OnChanges, OnDestroy {
...
      * let isCellInEditMode = this.cell.inEditMode;
      * ```
      * @memberof IgxGridCellComponent
      */
-
-     // TODO: Deprecate
-    /**
-     * @deprecated
-     */
     get inEditMode(): boolean {
```
Comment (damyanpetev) [inline projects/igniteui-angular/src/lib/grids/cell.component.ts]: @rkaraivanov Can you also add the deprecation decorator for a runtime warning?
