### PR TITLE
fix(*): Make context templateId more complicated object with type and…

### LINKED ISSUE #9781: IgxHierarchicalGrid - Checkbox ‘checked’ state is rest when a row is expanded.
## Description  
Checkbox ‘checked’ state is rest when a row is expanded.
This happens after reloading the data source.

 * igniteui-angular version: 12.0.5
 * browser: Chrome
 
## Steps to reproduce  

1.	Run the attached sample igxHGrid.zip.
2.	Click ‘LOAD’ button.
3.	Expand the second row.
4.	Click ‘RELOAD’ button.
5.	Expand the second row.
6.	Check any checkbox on the child grid.
7.	Expand the parent grid’s first row .

## Result  
Checkbox is unchecked.

## Expected result  
Checkbox is unchanged.

## Attachments  
Attach a sample if available, and screenshots, if applicable.  

[igxHGrid.zip](https://github.com/IgniteUI/igniteui-angular/files/6698366/igxHGrid.zip)

### PR DESCRIPTION
**Pull request by mddragnev**
… rowID

Closes #9781   

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Review by MayaKirova — CHANGES_REQUESTED** [review]

File: projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts [hunk 1]
```diff
@@ -547,18 +547,23 @@ export class IgxHierarchicalGridComponent extends IgxHierarchicalGridBaseDirecti
...
                     index: this.dataView.indexOf(rowData)
                 };
             }
         } else {
             return {
                 $implicit: this.isGhostRecord(rowData) || this.isAddRowRecord(rowData) ? rowData.recordRef : rowData,
-                templateID: 'dataRow',
+                templateID: {
+                    type: 'dataRow',
+                    rowID: null
```
Comment (MayaKirova) [inline projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts:565]: Also in general we do use igx template outlet to cache rows, but since the template outlet is a more generic directive and is not necessarily associated with rows it would be better for the property to be called just "id".

File: projects/igniteui-angular/src/lib/directives/template-outlet/template_outlet.directive.ts [hunk 2]
```diff
@@ -33,7 +33,7 @@ export class IgxTemplateOutletDirective implements OnChanges {
      * The embedded views cache. Collection is key-value paired.
      * Key is the template id, value is the embedded view for the related template.
      */
-    private _embeddedViewsMap: Map<string, EmbeddedViewRef<any>> = new Map();
+    private _embeddedViewsMap: Map<string, Map<any, EmbeddedViewRef<any>>> = new Map();
```
Comment (MayaKirova) [inline projects/igniteui-angular/src/lib/directives/template-outlet/template_outlet.directive.ts:36]: You can also update the description above the collection so that it's up to date.

**Review by MayaKirova — APPROVED** [review]

**Review by dkamburov — APPROVED** [review]

**Review by gedinakova — APPROVED** [review]
