### PR TITLE
Always reinit pinned columns state - 7.3.x #4905

### LINKED ISSUE #4905: Pinned area is not updated when columns collection is changed
## Description  
When a column, that is pinned, is removed from the columns collection it is not removed from the pinned columns area.

 * igniteui-angular version: 7.2.x, 7.3.x
 * browser: N/A

## Steps to reproduce  

1. Run [this ](https://stackblitz.com/edit/angular-xfci94)sample.
2. Click "Remove column" button in order to remove "Fax" column,
3. Observe pinned columns.

## Result  
"Fax" column is not removed from the pinned area
## Expected result  
"Fax" column to be removed from the pinned area

### PR DESCRIPTION
**Pull request by VMihalkov**
Closes #4905 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/grid-base.component.ts [hunk 1]
```diff
@@ -4502,9 +4502,8 @@ export abstract class IgxGridBaseComponent extends DisplayDensityBase implements
      * @hidden
      */
     protected reinitPinStates() {
-        if (this.hasColumnGroups) {
-            this._pinnedColumns = this.columnList.filter((c) => c.pinned);
-        }
+        this._pinnedColumns = this.columnList.filter((c) => c.pinned);
+
```
Comment (MayaKirova) [inline projects/igniteui-angular/src/lib/grids/grid-base.component.ts]: There are some whitespaces that need to be removed from here. Currently the build fails with the following error: ERROR: projects/igniteui-angular/src/lib/grids/grid-base.component.ts:4510:1 - trailing whitespace

File: projects/igniteui-angular/src/lib/grids/grid-base.component.ts [hunk 2]
```diff
@@ -4502,9 +4502,8 @@ export abstract class IgxGridBaseComponent extends DisplayDensityBase implements
      * @hidden
      */
     protected reinitPinStates() {
-        if (this.hasColumnGroups) {
-            this._pinnedColumns = this.columnList.filter((c) => c.pinned);
-        }
+        this._pinnedColumns = this.columnList.filter((c) => c.pinned);
```
Comment (MayaKirova) [inline projects/igniteui-angular/src/lib/grids/grid-base.component.ts]: There are also some failing tests possibly due to the order of the pinned columns not being retained when the state is reinitialized (specifically when columns are moved in the pinned area).
This can probably be fixed by sorting the columns by their original order in the _pinnedColumns collection before setting it.

**Comment by PavlovVasil** [comment]
The same[ issue with the MCH](https://github.com/IgniteUI/igniteui-angular/pull/4977#issuecomment-503606503) reproduces in 7.3.x as well
