### PR TITLE
fix(esf): reset forOf startIndex on esf columnChange

### LINKED ISSUE #14043: Regression on #7698 - IgxGrid ExcelStyleFilter dialog does not show items correctly
I'm working with Infragistics 17 and the same problem reported and fixed on v. 11 is happening to me.
The checkbox filter disappear after using the scroll bar and filtering using checkbox filter. Same steps as before:

https://github.com/IgniteUI/igniteui-angular/issues/7698

I wrote a comment on the original ticket, but haven't heard from anyone in 5 days. Ty.

### PR DESCRIPTION
**Pull request by onlyexeption**
Closes #14043 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.ts [hunk 1]
```diff
@@ -229,6 +229,10 @@ export class IgxExcelStyleSearchComponent implements AfterViewInit, OnDestroy {
         });
         esf.columnChange.pipe(takeUntil(this.destroy$)).subscribe(() => {
             this.virtDir?.resetScrollPosition();
+
+            if (this.virtDir) {
+                this.virtDir.state.startIndex = 0;
```
Comment (MayaKirova) [inline projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.ts:234]: I'm not sure why this is necessary. Is perhaps the scrollbar already hidden at the time you are trying to reset it?
I also cannot reproduce the issue as is described in the original issue  steps in 17.1.x:
filtring

Am I perhaps missing something or are steps slightly different?

Comment (onlyexeption) [reply projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.ts:234]: You can reproduce the issue in the ESF templates sample below. 
Since we're reusing the `IgxGridExcelStyleFilteringComponent` and we do not reset the `startIndex` anymore (from #13688), it doesnt reset when changing the column.

[screen-capture.webm](https://github.com/IgniteUI/igniteui-angular/assets/19392175/f883ea5e-19e7-491b-a074-058783ccbdef)

Notice how the startIndex of the second column is 14.

**Review by MayaKirova — CHANGES_REQUESTED** [review]
I think it would be best to add a test specifically for this scenario so it does not get regressed anymore.

**Review by gedinakova — APPROVED** [review]
