### PR TITLE
fix(tabs): update tabs if selectedIndex = -1

### LINKED ISSUE #9820: IgxTabs: Dynamically adding a tab is not working properly
## Description  
If you dynamically add a tab which should be directly selected the tab content is displayed but the tab is not selected.

 * igniteui-angular version: 12.0.6
 * browser: Chrome 91

## Steps to reproduce  
``` html
<igx-tabs #tabGroup>
  <igx-tab-item *ngFor="let tab of tabs" [selected]="tab.selected">
    <igx-tab-header>
      {{tab.header}}
    </igx-tab-header>
    <igx-tab-content>
      content of {{tab.header}}
    </igx-tab-content>
  </igx-tab-item>
</igx-tabs>

<button (click)="addTab()">open new tab</button>
<p>selected index: {{tabGroup.selectedIndex}}</p>
```
``` js
tabs = [
  { header: 'Tab 1', selected: false },
  { header: 'Tab 2', selected: true }
];

addTab() {
  this.tabs.forEach(tab => (tab.selected = false));
  this.tabs.push({ header: 'Tab 3', selected: true });
}
```

click button to execute addTab()

## Result  
The content of the new tab is displayed but the tab doesn't get selected.
The `selectedIndex` of IgxTabs is set to -1;

## Expected result  
The new tab should be selected and the `selectedIndex` should be correctly updated.

## Attachments  
https://stackblitz.com/edit/angular-ivy-2wwec2

### PR DESCRIPTION
**Pull request by onlyexeption**
Closes #9820 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/tabs/tabs.directive.ts [hunk 1]
```diff
@@ -196,33 +200,32 @@ export abstract class IgxTabsDirective extends IgxCarouselComponentBase implemen
...
                 // Select the tab on the same index the previous selected tab was
                 Promise.resolve().then(() => {
                     this.updateSelectedTabs(null);
                 });
+            } else if (this.selectedIndex >= this.items.length) {
+                // Select the last tab
+                Promise.resolve().then(() => {
+                    this.selectedIndex = this.items.length - 1;
+                });
             }
```
Comment (gedinakova) [inline projects/igniteui-angular/src/lib/tabs/tabs.directive.ts:228]: I believe we should also check for -1 and if that's the case we should set selectedIndex to 0;
```suggestion
          } else if (this.selectedIndex >= this.items.length) {
                // Select the last tab
                Promise.resolve().then(() => {
                    this.selectedIndex = this.items.length - 1;
                });
            } else {
                Promise.resolve().then(() => {
                    this.selectedIndex = 0;
                });
            }

```

**Review by gedinakova — CHANGES_REQUESTED** [review]

**Review by gedinakova — APPROVED** [review]
