### PR TITLE
fix(simple-combo): hide x icon button when no value is selected with reactive forms - 18.1.x

### LINKED ISSUE #14551: Simple ComboBox displays 'x' icon by default but no value is selected
## Description  
When using reactive forms (not via ngModel) the Simple ComboBox shows the 'x' icon by default even if there is/was no value selected yet.

The normal ComboBox seems to work fine.

 * igniteui-angular version: 18.0.5
 * browser: all

## Steps to reproduce  

TypeScript:
`formControl: FormControl = new FormControl();`

Html:
`<igx-simple-combo [formControl]="formControl"></igx-simple-combo>`

## Result  
The Simple ComboBox shows the 'x' icon to remove the currently selected value but nothing is selected actually.

## Expected result  
The Simple ComboBox should not show the 'x' icon because no value was selected initially.

## Attachments  
image

### PR DESCRIPTION
**Pull request by georgianastasov**
Closes #14551  

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts [hunk 1]
```diff
@@ -138,7 +138,12 @@ export class IgxSimpleComboComponent extends IgxComboBaseDirective implements Co
     }
 
     protected get hasSelectedItem(): boolean {
-        return !!this.selectionService.get(this.id).size;
+        if (this.comboInput.value === '') {
```
Comment (jackofdiamond5) [inline projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts:141]: The problem is that because the simple combo can accept `falsy` values, during initialization of the `FormControl`, such a value is inserted in the selection service. IMO instead of filtering these out, we should be preventing the selection service from receiving such `falsy` values that are not considered valid by the `FormControl`'s required validator. This should only apply if the component is part of a reactive form or has `ngModel`; otherwise it should allow any `falsy` value to be added to the selection service with the exception of `undefined` since iirc we use it to signify that no value is selected.

**Review by jackofdiamond5 — APPROVED** [review]

**Review by jackofdiamond5 — APPROVED** [review]
