### PR TITLE
hide Overlays when scroll grid

### LINKED ISSUE #4099: Calendar should be closed when scrolling is initiated
## Description  
Calendar should be under the edited cell when scroll 

 * igniteui-angular version: 7.2
 * browser: N/A

## Steps to reproduce  

1. Open dev sample gridCellEditing
2. Open cell in column OrderDate in edit mode
3. Open calendar
4. Start scroll vertical or horizontal

Note: when scroll horizontal and the cell is no longer visible the calendar should be closed(Now it is done only for vertical scroll)

## Result  
The calendar is no longer under the edited cell

## Expected result  
Calendar should be closed when scrolling is initiated

## Attachments  
Attach a sample if available, and screenshots, if applicable.  

image

### PR DESCRIPTION
**Pull request by nrobakova**
Closes #4099  

### Additional information (check all that apply):
 - [ x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by MayaKirova** [comment]
Note: Should be tested with all possible overlays the grid may display, including:
- filtering overlays (simple and excel style).
- edit row overlay (this one should stay open on scroll)
- toolbar overlays
- editor overlays (in case anything other than the date picker uses an overlay).

This includes all grids as the change is in the base class.

File: projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts [hunk 1]
```diff
@@ -676,29 +663,13 @@ export class IgxHierarchicalGridComponent extends IgxHierarchicalGridBaseCompone
 
     private hg_verticalScrollHandler(event) {
         this.scrollTop = event.target.scrollTop;
-        this.hideOverlays();
     }
 
-    public onContainerScroll() {
-        this.hideOverlays();
```
Comment (MayaKirova) [inline projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts]: This should not be removed. In scenarios where the child grid has larger width than the parent a scrollbar is rendered. Currently  when scrolling via that scrollbar overlays will not close, as a result they may go outside the scope of their parent container:

image

File: projects/igniteui-angular/src/lib/grids/grid-base.component.ts [hunk 2]
```diff
@@ -2448,22 +2447,23 @@ export abstract class IgxGridBaseComponent extends DisplayDensityBase implements
...
-        }
+    /**
+    * @hidden
+    * @internal
+    */
+    public hideOverlays() {
+        this.overlayIDs.forEach(overlayID => {
+            this.overlayService.hide(overlayID);
+            // blur in case some editor somewhere decides to move focus back
+            this.overlayService.onClosed.pipe(
```
Comment (bkulov) [inline projects/igniteui-angular/src/lib/grids/grid-base.component.ts]: There is another subscription for `this.overlayService.onClosed` event in method `_setupListeners()`. I suggest removing this subscription from here and moving `this.nativeElement.focus()` there. I know this code is only moved to a different location but I think it could be improved.

Comment (nrobakova) [reply projects/igniteui-angular/src/lib/grids/grid-base.component.ts]: @bkulov  I tried this, but focusing the this.nativeElement in all the cases will break the keyboard navigation and in the hgrid there is flickering. We do not need to focus native element in all the cases when overlay is closed, only in case when hide it from hideOverlays. The other way is to empty the overlayIDs in hideOverlays, but when the overlay is not closed by the hideOverlays, the array will not be correct. That is why I will leave it this way.
