### PR TITLE
fix(pivot-grid): added createRow method for grid based events

### LINKED ISSUE #14970: `cellClick`'s event args in Pivot Grid not all resolvable
## Description  
Tring to use some of the getters in the cellClick's event args for igxPivotGrid result in exceptions.

 * igniteui-angular version: n/a
 * browser: n/a

## Steps to reproduce  

1. Open any of the pivot samples and bind to `cellClick`
2. Try to console log event.cell.row

## Result  
An exception is thrown when the event handler is hit.

## Expected result  
No exceptions and the row data to include the proper values.

## Attachments  
n/a

### PR DESCRIPTION
**Pull request by tishko0**
Closes #14970   

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.component.ts [hunk 1]
```diff
@@ -2510,4 +2511,20 @@ export class IgxPivotGridComponent extends IgxGridBaseDirective implements OnIni
...
+     */
+     public createRow(index: number, data?: any): RowType {
+        let row: RowType;
+
+        const dataIndex = this._getDataViewIndex(index);
+        const rec = data ?? this.dataView[dataIndex];
+
+
+        if (!row && rec) {
+            row = new IgxGridRow(this, index, rec);
```
Comment (skrustev) [inline projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.component.ts:2526]: I don't think the IgxGridRow is a good representation of the PivotRow. It has a lot of setters and getters that should be overridden to not do anything or return always false if you look at the IgxPivotRowComponent. I think a new IgxPivotGridRow class should be introduced in this case.

**Review by skrustev — CHANGES_REQUESTED** [review]

**Review by skrustev — CHANGES_REQUESTED** [review]

File: projects/igniteui-angular/src/lib/grids/grid-public-row.ts [hunk 2]
```diff
@@ -791,3 +791,42 @@ export class IgxSummaryRow implements RowType {
...
+    public grid: GridType;
+    private _data?: any;
+
+    constructor(grid: GridType, index: number, data?: any) {
+        this.grid = grid;
+        this.index = index;
+        this._data = data && data.addRow && data.recordRef ? data.recordRef : data;
+    }
+
+    public get data(): any {
```
Comment (skrustev) [inline projects/igniteui-angular/src/lib/grids/grid-public-row.ts:806]: Each public property should have a comment description as well.

**Review by skrustev — CHANGES_REQUESTED** [review]

**Review by skrustev — APPROVED** [review]

**Comment by skrustev** [comment]
I assume you have checked that all methods are working correctly. 
I have suspicion that the `select` getter and setter might not work judging by how it is implemented in the IgxPivotRow, so make sure it works along with everything in the IgxPivotGridRow

**Review by skrustev — APPROVED** [review]

**Review by skrustev — DISMISSED** [review]

**Review by skrustev — DISMISSED** [review]

**Review by skrustev — APPROVED** [review]
