### PR TITLE
fix(grid-filtering): prevent page hanging when using remote data

### LINKED ISSUE #8602: Page is getting hanged after filtering on any column in IgxTreeGrid
## Description  
When I tried to filter the tree grid data using the filter textbox, I got the below warning:
igniteui-angular.js:11695 Component with id:4 is already removed!
and the whole page is getting hanged.

## Steps to reproduce  

1. Run the demo provided in [this](https://www.infragistics.com/products/ignite-ui-angular/angular/components/treegrid/remote-data-operations) topic.
2. Open the second column filter and enter some text.
3. Remove characters, one by one so it will change the filter.
4. Add characters.

## Result  
I got the below warning:
igniteui-angular.js:11695 Component with id:4 is already removed!
and the whole page is getting hanged.

## Expected result  
The page should continue to work as expected.

### PR DESCRIPTION
**Pull request by onlyexeption**
Closes #8602 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/grid-base.directive.ts [hunk 1]
```diff
@@ -6481,16 +6480,14 @@ export abstract class IgxGridBaseDirective extends DisplayDensityBase implements
             const overlaySettings: OverlaySettings = {
```
Comment (DiyanDimitrov) [inline projects/igniteui-angular/src/lib/grids/grid-base.directive.ts:6480]: Loading overlaySettings could be moved to a private member like the `rowEditSettings` instead of creating them on each `open` call.

File: projects/igniteui-angular/src/lib/grids/grid-base.directive.ts [hunk 2]
```diff
@@ -6481,16 +6480,14 @@ export abstract class IgxGridBaseDirective extends DisplayDensityBase implements
...
                 outlet: this.loadingOutlet,
                 closeOnOutsideClick: false,
-                positionStrategy: new ContainerPositionStrategy()
+                positionStrategy: new ContainerPositionStrategy(),
```
Comment (DiyanDimitrov) [inline projects/igniteui-angular/src/lib/grids/grid-base.directive.ts:6483]: Remove coma.

File: projects/igniteui-angular/src/lib/grids/grid-base.directive.ts [hunk 3]
```diff
@@ -6481,16 +6480,14 @@ export abstract class IgxGridBaseDirective extends DisplayDensityBase implements
...
+            if (this.loadingOverlay.collapsed) {
+                this.loadingOverlay.open(overlaySettings);
             }
         } else {
-            if (this._loadingId) {
-                this.overlayService.hide(this._loadingId);
-                this._loadingId = null;
+            if (!this.loadingOverlay.collapsed) {
+                this.loadingOverlay.close();
             }
```
Comment (DiyanDimitrov) [inline projects/igniteui-angular/src/lib/grids/grid-base.directive.ts:6491]: There is no need to check `collapsed` property. It is checked internally in the toggle methods.

**Review by DiyanDimitrov — CHANGES_REQUESTED** [review]

**Review by skrustev — APPROVED** [review]

**Review by DiyanDimitrov — APPROVED** [review]
