### PR TITLE
fix(combo): selectable unique falsy values #11610

### LINKED ISSUE #11610: IgxCombo: Cannot select falsy values
## Description  
IgxCombo can't select items with falsy values like false, null or empty string.

Related to #11357

 * igniteui-angular version: 13.1.16
 * browser: Chrome

## Result  
Falsy values can't be selected.

## Expected result  
Falsy values should be selectable.

## Attachments  
https://stackblitz.com/edit/angular-obbbi4

### PR DESCRIPTION
**Pull request by kdinev**
Closes #11610   
Related #10952 

** NOTE FOR TESTING **: Please verify that the scenario in [this conversation](https://github.com/IgniteUI/igniteui-angular/issues/10952) is also covered by the fix!

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts [hunk 1]
```diff
@@ -388,7 +380,7 @@ export class IgxSimpleComboComponent extends IgxComboBaseDirective implements Co
             return true;
         }
         const searchValue = this.searchValue || this.comboInput.value;
-        return !!searchValue && value.toString().toLowerCase().includes(searchValue.trim().toLowerCase());
+        return !!searchValue && value.toString().toLowerCase().includes(searchValue.toLowerCase());
```
Comment (ChronosSF) [inline projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts:383]: In general search implementations trim user input before searching. Think this trim might have been removed accidently.

File: projects/igniteui-angular/src/lib/combo/combo.pipes.ts [hunk 2]
```diff
@@ -29,7 +17,7 @@ export class IgxComboFilteringPipe implements PipeTransform {
         if (!searchValue || !shouldFilter) {
             return collection;
         } else {
-            const searchTerm = filteringOptions.caseSensitive ? searchValue.trim() : searchValue.toLowerCase().trim();
+            const searchTerm = filteringOptions.caseSensitive ? searchValue : searchValue.toLowerCase();
```
Comment (ChronosSF) [inline projects/igniteui-angular/src/lib/combo/combo.pipes.ts:20]: Same as the simple-combo comment.

**Review by ChronosSF — CHANGES_REQUESTED** [review]

**Review by ChronosSF — DISMISSED** [review]

**Review by wnvko — APPROVED** [review]
