### PR TITLE
Editors properly update their validity state on resetForm - 10.2.x

### LINKED ISSUE #9526: IgxDatePicker does not reset its state upon resetForm
### Description  
IgxDatePicker does not reset its state upon resetForm. Is there any configuration missing in the implementation?

 * igniteui-angular version: 11.1.10
 * browser: n/a

### Steps to reproduce  
1. Run the sample (https://stackblitz.com/edit/github-yrdu1t-uv6ki9?file=src%2Fapp%2Fscheduling%2Fdatepicker%2Fdatepicker-sample-6%2Fdatepicker-sample-6.component.html)
2. Input date on IgxDatePicker
3. Enter any string on IgxInput
4. Manually clear values on IgxDatePicker and IgxInput
5. Click "RESET FORM" button

### Result  
IgxDatePicker remain its required error.

### Expected result  
Required error on IgxDatePicker is cleared.

### Note
If we skip the step 4, the error state of the IgxDatePicker is cleared.

### Attachment
IgxDatePicker_behavior

### PR DESCRIPTION
**Pull request by jackofdiamond5**
Closes #9526

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts [hunk 1]
```diff
@@ -977,15 +977,18 @@ export class IgxDatePickerComponent implements IDatePicker, ControlValueAccessor
     }
 
     protected onStatusChanged() {
-        if ((this._ngControl.control.touched || this._ngControl.control.dirty) &&
-            (this.inputDirective && this._ngControl.control.validator || this._ngControl.control.asyncValidator)) {
-            if (this.inputGroup.isFocused) {
-                this.inputDirective.valid = this._ngControl.valid ? IgxInputState.VALID : IgxInputState.INVALID;
+        if (this.inputDirective) {
+            if ((this._ngControl.control.touched || this._ngControl.control.dirty) &&
+                (this.inputDirective && this._ngControl.control.validator || this._ngControl.control.asyncValidator)) {
```
Comment (wnvko) [inline projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts:982]: do not need to check for `inputDirective` again here - at this point it is truthy.

**Review by wnvko — CHANGES_REQUESTED** [review]

**Review by wnvko — APPROVED** [review]
At one point we should extract all the content from `statusChanged` in single place. We have a lot of code repetition in each component.
