### PR TITLE
Should not add child row to deleted parent row

### LINKED ISSUE #5237: Cascade deleting a parent in the treegrid causes added rows to appear at the root level
## Description  
When you cascade delete a parent row in the tree grid and you attempt to add a child row to it, once you commit the changes, the newly-added rows appear at the root level.

 * igniteui-angular version: 7.3.x. 8.0.x
 * browser: n/a

## Steps to reproduce  

1. Open [this sample](https://stackblitz.com/angular/nlbjabndomq)
2. Collapse all rows.
3. Press the `DELETE` button on the first row. (First Name = Andrew)
4. Expand the first row.
5. Press the `ADD CHILD ROW` button on the second child (First Name = Laura)
6. Observe - a `deleted` row (with ID = 25) is added
7. Commit the changes
8. Observe

## Result  
The added row (with ID = 25) is added at the root level.

## Expected result  
You should not be able to add children to deleted rows.

## Attachments  

Annotation 2019-06-27 173459

Annotation 2019-06-27 173556

### PR DESCRIPTION
**Pull request by wnvko**
Add a check if the parent row has a deleted state. If so do not add child row.

Closes #5237 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.ts [hunk 1]
```diff
@@ -601,6 +601,13 @@ export class IgxTreeGridComponent extends IgxGridBaseComponent implements IGridD
     public addRow(data: any, parentRowID?: any) {
         if (parentRowID) {
             super.endEdit(true);
+
+            const state = this.transactions.getState(parentRowID);
+            // we should not allow adding of rows as child of deleted row
+            if (state && state.type === TransactionType.DELETE) {
+                return;
```
Comment (DiyanDimitrov) [inline projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.ts]: Shouldn't we throw error instead of failing silently?

Comment (wnvko) [reply projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.ts]: Yeah, will add this.
