### PR TITLE
fix(date-time-editor): increment/decrement date portions with arrow up/down keys in shadow DOM

### LINKED ISSUE #11410: Date picker does not increment/decrement its values using arrow keys
## Description  
Date picker does not increment/decrement its values using arrow keys up/down. Hint: please, investigate how it interacts with shadow DOM.

## Steps to reproduce  

1. [Open this sample](https://stackblitz.com/edit/angular-kytxtl?file=src%2Fapp%2Fdatepicker-sample-1%2Fdatepicker-sample-1.component.html)
2. Try using arrow key up or down
3. Only the date is changing, but the month and the year values stay the same

## Result  
Only the day section gets incremented/decremented no matter where the cursor is positioned.

## Expected result  
The section where the cursor is positioned gets incremented/decremented.

### PR DESCRIPTION
**Pull request by viktorkombov**
Closes #11410 

### Additional information (check all that apply):
 - [X] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Review by jackofdiamond5 — CHANGES_REQUESTED** [review]

**Review by jackofdiamond5 — APPROVED** [review]

File: projects/igniteui-angular/src/lib/directives/date-time-editor/date-time-editor.directive.ts [hunk 1]
```diff
@@ -242,7 +242,8 @@ export class IgxDateTimeEditorDirective extends IgxMaskDirective implements OnCh
   }
 
   private get targetDatePart(): DatePart {
-    if (this.document.activeElement === this.nativeElement) {
+    if (this.document.activeElement === this.nativeElement ||
```
Comment (jackofdiamond5) [inline projects/igniteui-angular/src/lib/directives/date-time-editor/date-time-editor.directive.ts:245]: PS since this is a bug fix we should add a comment with the following `<initials> <date> <Issue Number|Issue Link> <Comment for the change>`.

**Review by jackofdiamond5 — APPROVED** [review]

**Review by Lipata — APPROVED** [review]
