### PR TITLE
Grid: fix sorting in chrome 7.1.x

### LINKED ISSUE #4376: Gird - sorting is not working with the new Chrome version
## Description  
DragDrop directive **stePointerCapture()** method breaks the click HostListener in the header component in Chrome browser.

 * igniteui-angular version: all
 * browser: Chorme

## Steps to reproduce  

1. Update chrome to Version **73.0.3683.86 (Official Build) (64-bit)**
2. Run any dev demo that has sortable columns
3. Try sorting a column.

## Result  
Sorting is not working.

## Expected result  
Sorting works.

### PR DESCRIPTION
**Pull request by SAndreeva**
Closes #4376 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/grid-header-group.component.ts [hunk 1]
```diff
@@ -8,7 +8,8 @@ import {
     forwardRef,
     ChangeDetectionStrategy,
     ChangeDetectorRef,
-    DoCheck
+    DoCheck,
+    HostListener
```
Comment (bkulov) [inline projects/igniteui-angular/src/lib/grids/grid-header-group.component.ts]: Is this `HostListener` needed?
