### PR TITLE
fix(migration): Remove --no-lock-file flag

### LINKED ISSUE #10884: Migrations don't work with modern yarn (2+) versions
## Description  
When `ng update` migrations against the package are ran with newer yarn versions they throw an error. This is due to the installation phase needed for Ng language service.

 * igniteui-angular version: 13.0.8
 * browser: N/A

## Steps to reproduce  

1. Create a project w/ yarn (`ng new --package-manager yarn`)
2. Update the project's version of yarn (`yarn set version berry`)
2. Add Ignite UI for Angular to the project w/ older version (`ng add igniteui-angular@12`)
3. Attempt to update with `ng update igniteui-angular`

## Result  
image
From the logs:
```
[error] SyntaxError: Unexpected token E in JSON at position 0
    at JSON.parse (<anonymous>)
    at tryInstallPackage (igniteui-angular\migrations\common\util.js:100:63)
    at UpdateChanges.applyChanges (igniteui-angular\migrations\common\UpdateChanges.js:127:42)
```

This is due to:
https://github.com/IgniteUI/igniteui-angular/blob/ed17d4eecdcd2065ef13942282ecb8ca0f2b4b7f/projects/igniteui-angular/migrations/common/util.ts#L102-L111

Apparently, newer versions of yarn add do not support the `--no-lock-file` argument and even newer versions still throw for unrecognized arguments. The error thrown from the catch is also kind of funny, might've meant stringify or something :)

## Expected result  
The migrations should work as expected. We might consider our options, we can simply fix the catch and let _most_ migrations work, but I think it'd still be better if Ng LS-dependent features work as well, even if we end up touching the lock file. Will need to try it first.

## Attachments  
[yarnTest.zip](https://github.com/IgniteUI/igniteui-angular/files/7914766/yarnTest.zip)

### PR DESCRIPTION
**Pull request by dafo**
Closes #10884

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Review by Lipata — APPROVED** [review]

File: projects/igniteui-angular/migrations/common/util.ts [hunk 1]
```diff
@@ -100,15 +100,15 @@ export const tryInstallPackage = (context: SchematicContext, packageManager: str
...
+                execSync(`${packageManager} add ${pkg}`, { stdio: 'ignore' });
                 break;
             case 'npm':
                 execSync(`${packageManager} i ${pkg} --no-save --no-audit`, { stdio: 'ignore' });
                 break;
         }
         context.logger.debug(`${pkg} installed successfully.`);
     } catch (e) {
-        context.logger.warn(`Could not install ${pkg}.`, JSON.parse(e));
+        context.logger.warn(`Could not install ${pkg}.`, e.stringify());
```
Comment (jackofdiamond5) [inline projects/igniteui-angular/migrations/common/util.ts:111]: Is there a reason why we don't use `JSON.stringify` here but a `stringify` method that's on the error object?

**Review by jackofdiamond5 — DISMISSED** [review]
