### PR TITLE
fix(grid): make the cell required in cell template context

### LINKED ISSUE #12538: igxCell template directive exposes "cell" as possibly undefined
## Description  

Add a custom cell template.

Try to use anything from "cell" context:
image

 * igniteui-angular version: 15.0.6
 * browser: N/A

## Steps to reproduce  

1. Add a grid with custom cell template:
   ```html
   <igx-grid #grid [data]="data">
    <igx-column dataType="string" field="Name">
        <ng-template igxCell let-cell="cell">
            <!-- Implement row deleting inside the cell template itself -->
            <span tabindex="0" (keydown.delete)="grid.deleteRow(cell.row.index)">{{ cell.value | titlecase }}</span>
        </ng-template>
    </igx-column>
    <igx-column dataType="boolean" field="Subscribtion">
        <ng-template igxCell let-cell="cell">
            <input type="checkbox" [ngModel]="cell.value" (ngModelChange)="cell.update($event)" />
        </ng-template>
    </igx-column>
   <igx-grid>
   ```
2. Try to use anything from `let-cell`

## Result  

> Object is possibly 'undefined'.ngtsc(2532)
image

## Expected result  
Since this is a cell template, my understanding is that "cell" should always be defined.

### PR DESCRIPTION
**Pull request by dkamburov**
Closes #12538   

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/cell.component.ts [hunk 1]
```diff
@@ -210,10 +210,11 @@ export class IgxGridCellComponent implements OnInit, OnChanges, OnDestroy, CellT
      *
      * @memberof IgxGridCellComponent
      */
-    public get context(): any {
+    public get context(): IgxCellTemplateContext {
         const ctx = {
```
Comment (pmoleri) [inline projects/igniteui-angular/src/lib/grids/cell.component.ts:214]: Alternate implementation to avoid setting a fake value in the ctx initialization.

```typescript
        const getCellType = () => this.getCellType(true);
        const ctx = {
            $implicit: this.value,
            additionalTemplateContext: this.column.additionalTemplateContext,
            get cell() {
                /* Turns the `cell` property from the template context object into lazy-evaluated one.
                 * Otherwise on each detection cycle the cell template is recreating N cell instances where
                 * N = number of visible cells in the grid, leading to massive performance degradation in large grids.
                 */
                return getCellType();
            }
        };
        if (this.editMode) {
            ctx['formControl'] = this.formControl;
        }
        if (this.isInvalid) {
            ctx['defaultErrorTemplate'] = this.defaultErrorTemplate;
        }
        return ctx;
```

Comment (dkamburov) [reply projects/igniteui-angular/src/lib/grids/cell.component.ts:215]: Yes, good point. Thanks, Pablo!

**Review by pmoleri — APPROVED** [review]
