### PR TITLE
fix(tabs): add third div to wrap the tab headers

### LINKED ISSUE #9496: The scroll buttons' visibility is not correctly set when changing the tab alignment
## Description  
The scroll buttons are not displayed correctly when the tab alignment is changed to center or end and some of the header content is not visible. 

 * igniteui-angular version: all
 * browser: all

## Steps to reproduce  

1. Open the Tabs dev demos.
2. Go to the Alignment demo.
3. Resize the window so the right scroll button is visible.
4. Click the Center button to change the tab alignment to center.
5. Observe the first tab header

## Result  
The left scroll button is not visible and the tab header is not fully displayed.

## Expected result  
The left scroll button should be visible if the header of the button is not fully displayed

## Attachments   
ButtonsVisibility

### PR DESCRIPTION
**Pull request by mtsvyatkova**
Closes #9496 

### Additional information (check all that apply):
 - [X] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [X] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/tabs/tabs/tabs.component.ts [hunk 1]
```diff
@@ -161,7 +167,7 @@ export class IgxTabsComponent extends IgxTabsDirective implements AfterViewInit,
     /** @hidden */
     public resolveHeaderScrollClasses() {
         return {
-            'igx-tabs__header-scroll': true,
+            // 'igx-tabs__header-scroll': true,
```
Comment (astaev) [inline projects/igniteui-angular/src/lib/tabs/tabs/tabs.component.ts:170]: Remove this one

**Review by astaev — APPROVED** [review]

**Review by kdinev — APPROVED** [review]
