### PR TITLE
fix(hierarchical-grid): do not use hierarchy pipe data when data is explicitly set by user - 17.0.x

### LINKED ISSUE #13881: IgxHierarchicalGrid: child grid data is cleared on expand
## Description  
In igx-hierarchical-grid with load on demand expanding a second parent row would clear the data of the child grid in the previously expanded row.

 * igniteui-angular version: 17.0.x, 16.1.x
 * browser: 

## Steps to reproduce  

1. Open [this](https://www.infragistics.com/products/ignite-ui-angular/angular/components/hierarchicalgrid/load-on-demand) sample
2. Expand the first row
3. Expand the second row in the parent grid

## Result  
The data of the first row island is cleared
image

## Expected result  
The data should not be changed

## Attachments  
Attach a sample if available, and screenshots, if applicable.

### PR DESCRIPTION
**Pull request by ddaribo**
Closes #13881 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts [hunk 1]
```diff
@@ -113,8 +113,9 @@ export class IgxChildGridRowComponent implements AfterViewInit, OnInit {
 
     public set data(value: any) {
         this._data = value;
-        if (this.hGrid) {
+        if (this.hGrid && !this.hGrid.dataSetByUser) {
             this.hGrid.data = this._data.childGridsData[this.layout.key];
+            this.hGrid.dataSetByUser = false;
```
Comment (MayaKirova) [inline projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts:118]: I'm not a fan of having to set this back to false any time the data is set internally. Maybe refactoring it a bit so that there's a setDataInternal method we can use for any internal operation that does not set this `dataSetByUser` flag?

**Review by MayaKirova — APPROVED** [review]

**Comment by dkamburov** [comment]
@ddaribo Looks good, just make sure to apply the latest changes to the other branches as well.

**Review by dkamburov — APPROVED** [review]
