### PR TITLE
Fixes column width not updating when grouping is cleared

### LINKED ISSUE #10081: IgxGrid: the grid is being shrunk when the grouping for particular column has been cleared
## Description  
When Group By feature is enabled and IgxGrid doesn’t have column widths defined, clearing grouping for particular column shrinks the grid.

 * igniteui-angular version: any
 * browser: any

## Steps to reproduce  

1. Open the following sample - [here](https://stackblitz.com/edit/github-rhnftm-fjchfu?file=src%2Fapp%2Fgrid%2Fgrid-column-hiding-toolbar-sample%2Fgrid-column-hiding-toolbar-sample.component.ts).
2. Clear the grouping for the "ContactTitle" column.

## Result  
The grid will be shrunk.

## Expected result  
The grid should be not shrunk.

## Attachments  
group-by-issue

### PR DESCRIPTION
**Pull request by 3phase**
Closes #10081

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Review by viktorkombov — APPROVED** [review]

File: projects/igniteui-angular/src/lib/grids/grid/grid.component.ts [hunk 1]
```diff
@@ -672,6 +672,7 @@ export class IgxGridComponent extends IgxGridBaseDirective implements GridType,
      */
     public clearGrouping(name?: string | Array<string>): void {
         this._gridAPI.clear_groupby(name);
+        this.calculateGridSizes();
         this.notifyChanges(true);
```
Comment (MayaKirova) [inline projects/igniteui-angular/src/lib/grids/grid/grid.component.ts:676]: notifyChanges can be removed since its main purpose is to force reflow calculation on the next detection cycle. But with this change the calculation is already done explicitly so there's no point to calculate again on the next detection cycle.
