### PR TITLE
fix(excel-style-filtering): implemented new position strategy for esf only

### LINKED ISSUE #6670: Excel Style filter option to be responsive
## Description  
I am using the Excel Style Filter option in the IgxGrid but this is not responsive to the small devices. 

## Result  
This should be responsive to mobile devices or the small devices.

## Attachments  
If I am using this in the Mobile preview option. 
MicrosoftTeams-image
It's Fine But if we rotate the mobile screen.
MicrosoftTeams-image (1)

I would request to @DiyanDimitrov to please check this and help me with this issue.

### PR DESCRIPTION
**Pull request by igdmdimitrov**
Closes #6670

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/services/overlay/position/auto-elastic-position-strategy.ts [hunk 1]
```diff
@@ -0,0 +1,28 @@
+import { ConnectedFit, Size } from './../utilities';
+import { AutoPositionStrategy } from './auto-position-strategy';
+
+/**
+ * TODO
```
Comment (wnvko) [inline projects/igniteui-angular/src/lib/services/overlay/position/auto-elastic-position-strategy.ts]: please add description here

File: projects/igniteui-angular/src/lib/services/overlay/position/auto-elastic-position-strategy.ts [hunk 2]
```diff
@@ -0,0 +1,28 @@
...
+ */
+export class AutoElasticPositionStrategy extends AutoPositionStrategy {
+    /** @inheritdoc */
+    position(contentElement: HTMLElement, size: Size, document?: Document, initialCall?: boolean): void {
+        this._forceFit = true;
```
Comment (wnvko) [inline projects/igniteui-angular/src/lib/services/overlay/position/auto-elastic-position-strategy.ts]: we do not need this, or I cannot imagine a case when this would help :)

File: projects/igniteui-angular/src/lib/services/overlay/position/auto-elastic-position-strategy.ts [hunk 3]
```diff
@@ -0,0 +1,28 @@
...
+        super.position(contentElement, size, document, initialCall);
+    }
+
+    /** @inheritdoc */
+    protected fitInViewport(element: HTMLElement, connectedFit: ConnectedFit) {
+        const heightOverflow = connectedFit.contentElementRect.height - connectedFit.viewPortRect.height;
+        if (heightOverflow > 0) {
+            element.style.width = 'auto';
```
Comment (wnvko) [inline projects/igniteui-angular/src/lib/services/overlay/position/auto-elastic-position-strategy.ts]: do not set the width to `auto`. Instead add logic to check if the content goes out in horizontal direction and set element's `width` as done for `height`

File: projects/igniteui-angular/src/lib/services/overlay/position/auto-elastic-position-strategy.ts (hunk 2 above)
Comment (igdmdimitrov) [reply projects/igniteui-angular/src/lib/services/overlay/position/auto-elastic-position-strategy.ts]: Now using method shouldFitInViewPort(...)

File: projects/igniteui-angular/src/lib/services/overlay/position/auto-elastic-position-strategy.ts (hunk 3 above)
Comment (igdmdimitrov) [reply projects/igniteui-angular/src/lib/services/overlay/position/auto-elastic-position-strategy.ts]: As we discussed this strategy will be only used for the excel style filtering, so leaving the width to 'auto'.
