### PR TITLE
enhancement(moving): Move pointerDown and pointerMove logic to avoid needing additional custom attributes.

### LINKED ISSUE #12874: Web components and Blazor grids with moving and pinning throws error when unpinning a column
## Description  
Having web components or blazor grid with moving and pinning throws error when unpinning a column.
Open that sample https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/grids/grid/column-moving

Note the header template: 
```
public webGridPinHeaderTemplate = (ctx: IgcColumnTemplateContext) => {

        const column = (ctx as any).column;
        return html`<div>
                     <span style="float:left">${column.field}</span>
                     <span style="float:right" @pointerdown=${(e: any) => this.toggleColumnPin(column.field)}>📌</span>
                   </div>`;
        };
```
See that the span has pointerdown event that pins/unpins a column. There is something with that pointerdown event and with drag-drop directive pointerdown.

NOTE: Note that if you change the event to click - the button stops working
 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Open this sample https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/grids/grid/column-moving
2. Unpin a column

## Result  
There is an error in the console

## Expected result  
There should be no error in the console.
If the event handler is set on click it should work like in Angular

### PR DESCRIPTION
**Pull request by skrustev**
Fix drag directive eating up event for children.

Closes #12874

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [x] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [x] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by dkamburov** [comment]
@skrustev I've cherry-picked this commit to **angular-elements** branch and the issue started reproducing again. It was fixed beforehand and no error was thrown.

File: projects/igniteui-angular/src/lib/directives/drag-drop/drag-drop.directive.ts [hunk 1]
```diff
@@ -909,7 +909,7 @@ export class IgxDragDirective implements AfterContentInit, OnDestroy {
 
         // Set pointer capture so we detect pointermove even if mouse is out of bounds until ghostElement is created.
         const handleFound = this.dragHandles.find(handle => handle.element.nativeElement === event.currentTarget);
-        const targetElement = handleFound ? handleFound.element.nativeElement : this.element.nativeElement;
+        const targetElement = handleFound ? handleFound.element.nativeElement : event.target || this.element.nativeElement;
```
Comment (dkamburov) [inline projects/igniteui-angular/src/lib/directives/drag-drop/drag-drop.directive.ts:912]: @skrustev this is the line that causes the same error to appear again in Webcomponents - 
image

Comment (skrustev) [reply projects/igniteui-angular/src/lib/directives/drag-drop/drag-drop.directive.ts:909]: @dkamburov This more or less caused the pinning happening on `pointerdown` instead of the usual `click` event. As per the sample, it can be seen that when the pin icon is clicked to pin the column, the focus moves the the `ProductName` column and the pointer down is also triggered for that column, but for some reason the `event.target` remains the icon of the previous column which has been recreated and the current `event.target` is no in the DOM.

I've added a check though in the IgxDragDirective to make sure the target is present in the DOM, so no error should be thrown now. 

But still we should probably fix that in the sample as well when this PR is merged, to pin/unpin the column on `click` instead of `pointerdown`

**Comment by sdimchevski** [comment]
I like that you have to move at least a little for the "Drag a column header <here>" indicator to show. It was a little aggressive previously just on a click to show it as I would expect to select the cell this way.

I also think you shouldn’t be able to grab and drag the column by clicking on an internal element like sort arrows, 3-dot menus, etc.

**Comment by dkamburov** [comment]
@skrustev please resolve conflicts

File: projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-row-dimension-content.component.html [hunk 2]
```diff
@@ -13,16 +13,15 @@
 
 <ng-template #headerTemplate let-column>
     <div class='igx-grid__tr--header igx-grid__row-indentation--level-{{getLevel()}}'>
-        <igx-icon [attr.draggable]=" false" (click)="toggleRowDimension($event)">
+        <igx-icon [attr.draggable]="false" (click)="toggleRowDimension($event)">
```
Comment (MayaKirova) [inline projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-row-dimension-content.component.html:16]: I assume here [attr.draggable] can also be removed.

File: projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-row-dimension-content.component.html [hunk 3]
```diff
@@ -13,16 +13,15 @@
...
             {{ getExpandState() ? 'expand_more' : 'chevron_right'}}</igx-icon>
         {{column.header}}
     </div>
 </ng-template>
 
 <ng-template #headerDefaultTemplate let-column>
-
     <div class='igx-grid__tr--header igx-grid__row-indentation--level-{{getLevel()}}'>
-        <igx-icon style='flex-shrink: 0;' [attr.draggable]=" false">
+        <igx-icon style='flex-shrink: 0;' [attr.draggable]="false">
```
Comment (MayaKirova) [inline projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-row-dimension-content.component.html:24]: I assume here [attr.draggable] can also be removed.

File: projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-row-dimension-content.component.html (hunk 2 above)
Comment (skrustev) [reply projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-row-dimension-content.component.html:16]: We've decided to not remove the `attr.draggable` from the grid yet, to be sure that the behavior remains the same.

**Review by MayaKirova — APPROVED** [review]

**Review by MayaKirova — APPROVED** [review]
