### PR TITLE
fix: (igx-snackbar) Add aria-live attr to the message container.

### LINKED ISSUE #8929: a11y: Improve snackbar accessibility
## Description  
Provide an accessible experience for igx-snackbar.

`aria-live` should be added to the message and by default should be `polite`.
The user should be able to change that, for example, `aria-live="assertive"` or `aria-live="off"`

 * igniteui-angular version: 11.1.x
 * browser: all

### PR DESCRIPTION
**Pull request by desig9stein**
Closes #8929

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Review by simeonoff — APPROVED** [review]

File: projects/igniteui-angular/src/lib/snackbar/snackbar.component.ts [hunk 1]
```diff
@@ -200,6 +220,13 @@ export class IgxSnackbarComponent {
      */
     public snackbarMessage = '';
 
+    /**
+     * @hidden
+     * @internal
+     */
+    public ariaLiveValue = 'polite';
```
Comment (kdinev) [inline projects/igniteui-angular/src/lib/snackbar/snackbar.component.ts:227]: You don't need a getter/setter, since there's nothing else in the setter, but setting the underlying field value. Remove the getter/setter, make this `ariaLive` field the input and hostbind it and remove it from the template.
```typescript
    /**
     * Sets/gets the `aria-live` attr of the snackbar message container.
     * If not set, the `aria-live` will be `polite`;
     * ```html
     * <igx-snackbar [ariaLive]="'polite'"></igx-snackbar>
     * ```
     * ```typescript
     * let snackbarAriaLive = this.snackbar.ariaLive;
     * ```
     *
     * @memberof IgxSnackbarComponent
     */
    @Input()
    @HostBinding('attr.aria-live')
    public ariaLiveValue = 'polite';
```

File: projects/igniteui-angular/src/lib/snackbar/snackbar.component.html [hunk 2]
```diff
@@ -1,6 +1,6 @@
 <div class="igx-snackbar" *ngIf="isVisible" (@slideInOut.start)="snackbarAnimationStarted($event)" (@slideInOut.done)="snackbarAnimationDone($event)"
     [@slideInOut]="isVisible">
-    <div class="igx-snackbar__message" [@fadeInOut]="isVisible">
+    <div [attr.aria-live]="ariaLiveValue" class="igx-snackbar__message" [@fadeInOut]="isVisible">
```
Comment (kdinev) [inline projects/igniteui-angular/src/lib/snackbar/snackbar.component.html:3]: Remove this because of the `HostBinding`

**Review by kdinev — CHANGES_REQUESTED** [review]

**Review by kdinev — APPROVED** [review]
