### PR TITLE
fix(drop-down): remove shadow when list is empty #3977

### LINKED ISSUE #3977: There is a shadow, when autocomplete list is empty
## Description  
When autocomplete is filtered so that there are no items left, there is still a shadow.

## Attachments  
image

### PR DESCRIPTION
**Pull request by Lipata**
Closes #3977

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/drop-down/drop-down.component.ts [hunk 1]
```diff
@@ -524,6 +524,13 @@ export class IgxDropDownComponent extends IgxDropDownBaseDirective implements ID
         }
     }
 
+    /**
+     * @hidden @internal
+     */
+    public listClass() {
```
Comment (kdinev) [inline projects/igniteui-angular/src/lib/drop-down/drop-down.component.ts:530]: Getter?

File: projects/igniteui-angular/src/lib/drop-down/drop-down.component.html [hunk 2]
```diff
@@ -1,4 +1,4 @@
-<div class="igx-drop-down__list" igxToggle [style.width]="width"
+<div [ngClass]="listClass()" igxToggle [style.width]="width"
```
Comment (simeonoff) [inline projects/igniteui-angular/src/lib/drop-down/drop-down.component.html:1]: I would drop the ngClass directive in favor of host-binding the two classes.

File: projects/igniteui-angular/src/lib/drop-down/drop-down.component.ts (hunk 1 above)
Comment (simeonoff) [reply projects/igniteui-angular/src/lib/drop-down/drop-down.component.ts:530]: I think I would either change the return signature of this method to be an object with the keys holding the class names where the values are expressions that evaluate to boolean based on whether the list has items in it or not.
The other option is to make a getter like @kdinev suggested, which returns the length of the list and to which the `--empty` class gets host-bound.

Comment (Lipata) [reply projects/igniteui-angular/src/lib/drop-down/drop-down.component.ts]: @kdinev, @simeonoff I've now applied the comments from @rkaraivanov: https://github.com/IgniteUI/igniteui-angular/pull/7628#discussion_r444686832. @simeonoff, as you can see the value, is an object with keys holding the class names. However, in that case, where we have more like an `if-else` case, maybe it is clear to use that expression `[ngClass]="{ items.length > 0 ?  'igx-drop-down__list': 'igx-drop-down__list--empty'}"` ?

@simeonoff, as you've also said the other option is to have a getter with `@HostBinding('attr.class')`. It seems both options can be applied, and I prefer the first one only because the expression that is used is short and don't need to be in the .ts file.
