### PR TITLE
Optimize _calcMaxChunkSize performance - 7.1.x

### LINKED ISSUE #3409: TreeGrid has empty space when Summaries are enabled and expand/collapse
### Description  
TreeGrid has empty space when Summaries are enabled and expand/collapse

 * igniteui-angular version: 7.1.x
 * browser: N/A

### Steps to reproduce  

1. Open dev sample treeGridFlatData
2. Enable summaries for root and child
3. Scroll down to can row with id 3 to be the first visible row
4. Collapse row with id 15
5. Expand row with id 15

### Result  
TreeGrid has empty space and after scroll it is fixed

### Expected result  
TreeGrid should not have empty space

### Attachments  
Attach a sample if available, and screenshots, if applicable.  
image

### PR DESCRIPTION
**Pull request by DiyanDimitrov**
Closes #3409 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts [hunk 1]
```diff
@@ -960,14 +960,7 @@ export class IgxForOfDirective<T> implements OnInit, OnChanges, DoCheck, OnDestr
...
-                length = dimension === this.igxForSizePropName ? arr.length + 1 : arr.length;
-                if (dimension === 'height') {
-                    const maxItemSize = arr.reduce((pr, c) => Math.max(pr, this._getItemSize(c, dimension)), 0);
-                    if (sum - availableSize < maxItemSize) {
-                        // add one more for vertical smooth scroll
-                        length++;
-                    }
-                }
+                length = arr.length + 1;
                 arr.splice(0, 1);
```
Comment (rkaraivanov) [inline projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts]: Maybe `array.shift()` instead of splicing just for the first element?

Comment (DiyanDimitrov) [reply projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts]: Agree. I will change that. Also it seems that shift is a lot faster than splice https://stackoverflow.com/questions/10742369/javascript-shift-versus-splice-are-these-statements-equal.
