### PR TITLE
fix(grid): update group summaries when new row is added via UI

### LINKED ISSUE #12606: Grid group summaries are not updated when new row is added via UI
## Description  
When using row editing and adding a new row the group summaries are not updated correctly

## Steps to reproduce 

[Edit: Angular repro steps]
1. Open https://stackblitz.com/edit/angular-xnw231
2. Under the Reorder level 5 start adding a new row (<kbd>ALT</kbd> + <kbd>+</kbd> or from row action)
3. Enter the same value (5) for reorder level as the group 
4. Finish the row add (Done)
5. Inspect the summary state
---

1. run sample (note after npm install infragistics modules will need to be copied from @infragistics upto node_modules folder)
2. drag last name into grouping area
3. press <kbd>ALT</kbd> + <kbd>+</kbd> to add a new row
4. update the new row with the same last name as the group it is in
5. after updating all fields in the row press the "Done" button

## Result  
group summary is not updated (for example count still reflects old count)

[Edit: Additionally the summaries update ***after*** additional edit, seems like the add doesn't refresh the summary cache perhaps]
grid-group-summary-row-add

## Expected result  
group summary should be updated to reflect newly added row

## Attachments  
Attach a sample if available, and screenshots, if applicable.
[CurrTestGrid.zip](https://github.com/IgniteUI/igniteui-webcomponents/files/10540399/CurrTestGrid.zip)

### PR DESCRIPTION
**Pull request by ddaribo**
Closes #12606

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/grid-base.directive.ts [hunk 1]
```diff
@@ -5065,6 +5065,7 @@ export abstract class IgxGridBaseDirective extends DisplayDensityBase implements
         this.crudService.endEdit(true);
         this.selectionService.clearHeaderCBState();
         this.summaryService.clearSummaryCache();
+        this.pipeTrigger++;
```
Comment (skrustev) [inline projects/igniteui-angular/src/lib/grids/grid-base.directive.ts:5068]: I feel like `pipeTrigger` in this case would be too much triggering all pipes, since it is already triggered once in the `endAddRow` in the `crud.servise.ts`. I see there is a `summaryPipeTrigger` which might suit better in this case.
