### PR TITLE
fix(grid): adjust overlay hiding logic

### LINKED ISSUE #9426: Excel-style filtering and scrolling - igxOverlay.detach was called with wrong id:16
## Description  
Excel-style filtering dialog is closed on scrolling with the following error - igxOverlay.detach was called with wrong id:16

 * igniteui-angular version: should be reproducible with the alpha version before the fix that we did: 11.2.0-alpha.5
 * The fix that we implemented for the time being - https://github.com/IgniteUI/igniteui-angular/pull/9334/commits/59ec60b5bbc77190350a30c51497bca1a6cec086

## Steps to reproduce  

1. Open excel-style filtering and scroll down - warning is thrown and the dialog is closed
2. I am unable to open it afterwards

## Result  
igxOverlay.detach was called with wrong id:16

### PR DESCRIPTION
**Pull request by DiyanDimitrov**
Closes #9426

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/grid-base.directive.ts [hunk 1]
```diff
@@ -3163,10 +3163,13 @@ export abstract class IgxGridBaseDirective extends DisplayDensityBase implements
      */
     public hideOverlays() {
         this.overlayIDs.forEach(overlayID => {
-            if (this.overlayService.getOverlayById(overlayID)?.visible) {
+            const overlay = this.overlayService.getOverlayById(overlayID);
+
+            if (overlay?.visible && !overlay.closeAnimationPlayer?.hasStarted()) {
                 this.overlayService.hide(overlayID);
+
+                this.nativeElement.focus();
```
Comment (wnvko) [inline projects/igniteui-angular/src/lib/grids/grid-base.directive.ts:3171]: if there is an overlay which is closing, `hasStarted == true`, and user starts to scroll this will not focus the native element. Not sure if this is an issue. Otherwise LGTM.

**Review by wnvko — APPROVED** [review]

File: projects/igniteui-angular/src/lib/grids/grid-base.directive.ts (hunk 1 above)
Comment (DiyanDimitrov) [reply projects/igniteui-angular/src/lib/grids/grid-base.directive.ts:3171]: We want to focus the native element only if closing the overlay is caused by the scroll. If closing has started before the scroll we shouldn't change the focus.
