### PR TITLE
Selected item scroll position based on position strategy - 11.1.x

### LINKED ISSUE #9171: IgxSelect dropdown is not positioned correctly in IE11
## Description  
IgxSelect dropdown is not positioned correctly in IE11.

 * igniteui-angular version: 11.1.3
 * browser: IE11

## Steps to reproduce  

1. Start the attached reproducible sample and open http://localhost:4200/ in IE11.
2. Open the dropdown.
3. Select an item around at the end of the list. For example, select "Item 87".
4. Open the dropdown.

## Result  
The dropdown is displayed at the bottom of the window.
image

## Expected result  
The dropdown is displayed at the position where IgxSelect is located as it is when "Item0" is selected.

## Attachments  
[cas34222-app1.zip](https://github.com/IgniteUI/igniteui-angular/files/6161981/cas34222-app1.zip)

### PR DESCRIPTION
**Pull request by IvayloG**
Closes #9171

This fix as well:
1) Removes #3921 Force item scroll before measuring in IE11, due to base scrollToItem delay
2) Updates #7435 fix

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/select/select.component.ts [hunk 1]
```diff
@@ -454,7 +459,15 @@ export class IgxSelectComponent extends IgxDropDownComponent implements IgxSelec
         if (args.cancel) {
             return;
         }
-        this.scrollToItem(this.selectedItem);
+    }
+
+    /** @hidden @internal */
+    public onToggleContentAppended() {
+        if (this.selectedItem && !(this._overlayCached.positionStrategy instanceof SelectPositioningStrategy)) {
```
Comment (damyanpetev) [inline projects/igniteui-angular/src/lib/select/select.component.ts:466]: While the cached object will likely work, it's kind of odd - the overlay service already has that stored with the actual values and the append event receives arguments with the Id, so if you inject the service you can get the overlay info with this id and access the position setting in use to check it. Something like:
```ts
const info = this.overlayService.getOverlayById(event.Id);
if (info?.settings?.positionStrategy instanceof SelectPositioningStrategy) return;
super.onToggleContentAppended();
```

**Review by damyanpetev — APPROVED** [review]
