### PR TITLE
Resolving null height virtualization slowdown - 7.2

### LINKED ISSUE #4839: [igx-grid] rendering performance becomes extremely poor when binding data after initialization.
## Description  
`igx-grid` rendering performance becomes extremely poor when binding data after initialization.

 * igniteui-angular version: 7.2.9
 * browser: N/A

## Steps to reproduce  

1. Run the attached sample [igx-grid-sample.7.2.9-binding-data-performance-issue.zip](https://github.com/IgniteUI/igniteui-angular/files/3196578/igx-grid-sample.7.2.9-binding-data-performance-issue.zip). 
2. Click "load data" button(A data of 10000 rows x 200 columns will be bound).

## Result  
Something is wrong with `igx-grid` and it won't render rows. It ends up browser freeze.

About the following gif, the grid on the left hand is running on `igniteui-angular@7.1.15`, whereas, the grid on the right hand is running on `igniteui-angular@7.2.9`. 
diff-7 1 15-7 2 9

## Expected result  
`igx-grid` rendering performance on `v7.2.9` should be as fast as `v7.1.15`.

## Attachments  
[igx-grid-sample.7.2.9-binding-data-performance-issue.zip](https://github.com/IgniteUI/igniteui-angular/files/3196578/igx-grid-sample.7.2.9-binding-data-performance-issue.zip)

[igx-grid-sample.7.1.15.zip](https://github.com/IgniteUI/igniteui-angular/files/3196579/igx-grid-sample.7.1.15.zip)

### PR DESCRIPTION
**Pull request by ChronosSF**
Closes #4839   

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts [hunk 1]
```diff
@@ -257,6 +260,14 @@ export class IgxHierarchicalGridComponent extends IgxHierarchicalGridBaseCompone
         return !!this.childLayoutKeys.length;
     }
 
+    /**
+     * @hidden
+
+    protected get rowBasedHeight() {
```
Comment (rkaraivanov) [inline projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts]: Can't we delete this?
