### PR TITLE
Close excel style filter dialog on scroll

### LINKED ISSUE #4038: Excel style filtering is not styled correctly when used for child grid in IgxHieararchicalGrid
## Description  
Excel style filtering is not styled correctly when used for child grid

 * igniteui-angular version: * 7.2.x
 * browser: N/A

## Steps to reproduce  

1. Edit the Hierarchical grid sample to have excel style filtering
2. Open the sample
3. Expand a row
4. Open excel style filtering dialog for a child

## Result  
The horizontal scroll is overlapping the filtering dialog and when scrolling the parent grid stays on its place

## Expected result  
Filtering dialog should be styled correctly when used in child grid

## Attachments  

hierarchical_filtering4

### LINKED ISSUE #4041: Field's name instead of header is shown in Excel filtering UI.
## Description  
If field's header does not match field name, the header should be shown in the filtering UI.

 * igniteui-angular version: 7.2.x
 * browser: N/A

## Steps to reproduce  

1. Launch DEV demos
2. Change the header of one of the columns in Grid Column Moving demo
3. Run the demos
4. Open Excel filtering drop-down

## Result  
The field's name is displayed on the top.

## Expected result  
The field's header should be displayed as users may not be familiar with the underlying data.

### LINKED ISSUE #4043: Excel filter style dialog does not update its position on container scroll.
## Description  
When grid is in a scrollable container and excel filter dialog is opened scrolling vertically/horizontally does not update the filter dialog position. 

Note: This affects the HierarchicalGrid, since the children grids are usually in a scrollable container.

 * igniteui-angular version: 7.2.x
 * browser: N/A

## Steps to reproduce  

1. Open the Grid Column Moving sample
2. Edit it so that grid is in a scrollable div.
3. Open the dialog and scroll the container div horizontally/vertically.

## Result  
Dialog remain opened in the same location.

## Expected result  
Dialog should either move so that it remains next to its related target element or close.

## Attachments  
image

### PR DESCRIPTION
**Pull request by sstoyanovIG**
Closes #4043 
Closes #4038 
Closes #4041   

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/grid/grid.component.ts [hunk 1]
```diff
@@ -26,6 +26,7 @@ import { IgxFilteringService } from '../filtering/grid-filtering.service';
 import { IGroupingExpression } from '../../data-operations/grouping-expression.interface';
 import { IgxColumnResizingService } from '../grid-column-resizing.service';
 import { IgxGridSummaryService } from '../summaries/grid-summary.service';
+import { IgxOverlayService } from '../../services';
```
Comment (bkulov) [inline projects/igniteui-angular/src/lib/grids/grid/grid.component.ts]: Import this from `../../services/index`.

File: projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts [hunk 2]
```diff
@@ -36,6 +36,7 @@ import { IgxGridSummaryService } from '../summaries/grid-summary.service';
 import { IgxHierarchicalGridBaseComponent } from './hierarchical-grid-base.component';
 import { takeUntil } from 'rxjs/operators';
 import { IgxTemplateOutletDirective } from '../../directives/template-outlet/template_outlet.directive';
+import { IgxOverlayService } from '../../services';
```
Comment (bkulov) [inline projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts]: Import this from `../../services/index`.

File: projects/igniteui-angular/src/lib/grids/hierarchical-grid/row-island.component.ts [hunk 3]
```diff
@@ -27,7 +27,7 @@ import { IgxHierarchicalGridAPIService } from './hierarchical-grid-api.service';
 import { DOCUMENT } from '@angular/common';
 import { IgxFilteringService } from '../filtering/grid-filtering.service';
 import { IDisplayDensityOptions, DisplayDensityToken } from '../../core/displayDensity';
-import { TransactionService, Transaction, State } from '../../services';
+import { TransactionService, Transaction, State, IgxOverlayService } from '../../services';
```
Comment (bkulov) [inline projects/igniteui-angular/src/lib/grids/hierarchical-grid/row-island.component.ts]: Proper import is from `../../services/index`.

File: projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.ts [hunk 4]
```diff
@@ -28,7 +28,7 @@ import { TransactionService, HierarchicalTransaction, HierarchicalState, Transac
 import { DOCUMENT } from '@angular/common';
 import { IgxGridNavigationService } from '../grid-navigation.service';
 import { mergeObjects } from '../../core/utils';
-import { IgxHierarchicalTransactionService } from '../../services';
+import { IgxHierarchicalTransactionService, IgxOverlayService } from '../../services';
```
Comment (bkulov) [inline projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.ts]: Import this from `../../services/index`.

File: projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-custom-dialog.component.ts [hunk 5]
```diff
@@ -94,7 +94,7 @@ export class IgxExcelStyleCustomDialogComponent implements AfterViewInit {
     constructor(private cdr: ChangeDetectorRef) {}
 
     ngAfterViewInit(): void {
-        this._customDialogOverlaySettings.outlet = this.grid.outletDirective;
+        this._customDialogOverlaySettings.outlet = this.grid.rootGrid ? this.grid.rootGrid.outletDirective : this.grid.outletDirective;
```
Comment (bkulov) [inline projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-custom-dialog.component.ts]: Use the newly introduced property `this.grid.outlet` here.

File: projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.ts [hunk 6]
```diff
@@ -182,11 +181,7 @@ export class IgxGridExcelStyleFilteringComponent implements OnDestroy {
         this.overlayService = overlayService;
         this.overlayComponentId = overlayComponentId;
 
-        this._subMenuOverlaySettings.outlet = this.grid.outletDirective;
-
-        this.chunkLoaded = this.grid.headerContainer.onChunkPreload.pipe(takeUntil(this.destroy$)).subscribe(() => {
-            this.closeDropdown();
-        });
+        this._subMenuOverlaySettings.outlet = this.grid.rootGrid ? this.grid.rootGrid.outletDirective : this.grid.outletDirective;
```
Comment (bkulov) [inline projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.ts]: Use the newly introduced property `this.grid.outlet` here.

File: projects/igniteui-angular/src/lib/grids/grid-header.component.ts [hunk 7]
```diff
@@ -225,7 +225,7 @@ export class IgxGridHeaderComponent implements DoCheck, OnInit, OnDestroy {
             }
 
             this._filterMenuOverlaySettings.positionStrategy.settings.target = headerTarget;
-            this._filterMenuOverlaySettings.outlet = this.grid.outletDirective;
+            this._filterMenuOverlaySettings.outlet = this.grid.rootGrid ? this.grid.rootGrid.outletDirective : this.grid.outletDirective;
```
Comment (bkulov) [inline projects/igniteui-angular/src/lib/grids/grid-header.component.ts]: Use the newly introduced property `this.grid.outlet` here.
