### PR TITLE
Use IgxSelect instead of IgxDropdown #7072

### LINKED ISSUE #7072: Excel style filtering cannot close drop down
## Description  
Custom filter drop down cannot be closed while clicking on the input

 * igniteui-angular version: 9.0.9
 * browser: all

## Steps to reproduce  

1. Open [ESF sample](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/excel_style_filtering.html).
2. Click on filter in `Order Date` column.
3. In the ESF select `Date Filter -> Before`.
4. Click on `Before` input.
5. Click on `Before` input, again.

## Result  
Drop down remains open.

## Expected result  
Drop down should be closed.

## Attachments  
Attach a sample if available, and screenshots, if applicable.

### PR DESCRIPTION
**Pull request by onlyexeption**
Closes #7072 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-default-expression.component.ts [hunk 1]
```diff
@@ -11,14 +11,15 @@ import {
...
-import { IgxDropDownItemComponent, IgxDropDownComponent } from '../../../drop-down/public_api';
-import { IgxInputGroupComponent, IgxInputDirective } from '../../../input-group/public_api';
 import { DataType, DataUtil } from '../../../data-operations/data-util';
 import { IFilteringOperation } from '../../../data-operations/filtering-condition';
-import { OverlaySettings, ConnectedPositioningStrategy, CloseScrollStrategy } from '../../../services/public_api';
+import { OverlaySettings, ConnectedPositioningStrategy, AbsoluteScrollStrategy  } from '../../../services/public_api';
 import { KEYS, IBaseEventArgs } from '../../../core/utils';
 import { FilteringLogic } from '../../../data-operations/filtering-expression.interface';
 import { DisplayDensity } from '../../../core/density';
+import { IgxSelectComponent } from '../../../select/select.component';
```
Comment (IvayloG) [inline projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-default-expression.component.ts:20]: Regarding latest import changes, I believe we should import from the available public_api files (where available)

import { IgxSelectComponent } from '../../../select/public_api';
