### PR TITLE
fix(HierarchicalGrid): Handle various overlay scenarios in Hierarchic…

### LINKED ISSUE #4090: When open a date picker from the child grid its position is not correct
## Description  
When open a date picker from the child grid its position is not correct

 * igniteui-angular version: 7.2
 * browser: N/A

## Steps to reproduce  

1. Edit dev sample hierarchicalGridUpdating and add [dataType]="'date'" to column OrderDate
2. Expand first row
3. In the child grid double click on cell in column OrderDate and OrderID 11011
4. Open DatePicked

Note: This is also reproducible in sample: https://staging.infragistics.local/products/ignite-ui-angular/angular/components/hierarchicalgrid/row_editing.html
## Result  
DatePicked is under the root rows

## Expected result  
DatePicker should be over the root rows

## Attachments  
Attach a sample if available, and screenshots, if applicable.  
image

### LINKED ISSUE #4095: Overlay elements are not fully visible in child grid if they need to show outside the bounds of their owner grid.
## Description  
Elements that show in overlay like the Done/Cancel buttons or editors that open additional lists/dialogs like the DatePicker may be hidden behind parent grid elements.

Describe the issue.

 * igniteui-angular version: 7.2.x
 * browser: N/A

## Steps to reproduce  

1. Open a hierarchical grid with row editing sample.
2. Start editing for a row and open an DatePicker editor.

## Result  
In case the UI element needs to show outside the bounds of its owner grid it may be overlapped by other elements, for example:

image
In the above screenshot the Done/Cancel buttons need to be displayed above the child grid row, but are not visible.

Similarly the date picker also gets cut off:
image

## Expected result  
Elements should be attached to their root grid element so that they display on top.
Since the main grid has overflow: visible to prevent those elements from showing outside their root grid container, all overlays should probably close.

### PR DESCRIPTION
**Pull request by MayaKirova**
…alGrid. Attach overlays to root grid and handle hiding/showing in case target element is no longer in view.

Closes #4095 
Closes #4090 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them
 
### Notes: 
1)	What to test:
This should be tested with all components that show in an overlay, including (but not limited to):
- Editors  that drop-down some other elements  - like date picker.
- Toolbar that display drop-downs (hiding, pinning UI etc.)
- Filter UI – both normal and excel style.

For now the overlays will close on scroll.

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts [hunk 1]
```diff
@@ -588,9 +596,72 @@ export class IgxHierarchicalGridComponent extends IgxHierarchicalGridBaseCompone
...
+        if (!this.document.body.contains(elem)) {
+            // element is not in DOM
+            return false;
+        }
+        const elemClientRect = elem.getBoundingClientRect();
+        const gridClientRect = this.rootGrid.tbody.nativeElement.getBoundingClientRect();
+        const diffBottom =  elemClientRect.bottom - gridClientRect.bottom;
+        const diffTop = elemClientRect.bottom - elem.offsetHeight -  gridClientRect.top;
+
+            if (diffBottom > 0 || diffTop < 0) {
```
Comment (bkulov) [inline projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts]: You could use `return diffBottom > 0 || diffTop < 0;` here.

File: projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts [hunk 2]
```diff
@@ -588,9 +596,72 @@ export class IgxHierarchicalGridComponent extends IgxHierarchicalGridBaseCompone
...
+                return true;
+            }
+    }
+
+    private _isInHorizontalView(elem) {
+        const elemClientRect = elem.getBoundingClientRect();
+        const gridClientRect = this.rootGrid.tbody.nativeElement.getBoundingClientRect();
+        const diffLeft =  elemClientRect.left - gridClientRect.left;
+        const diffRight =  gridClientRect.right + elem.offsetWidth - elemClientRect.right;
+        if (diffRight < 0 || diffLeft < 0) {
```
Comment (bkulov) [inline projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts]: You could use `return diffRight < 0 || diffLeft < 0;` here.

**Comment by mpavlinov** [comment]
@MayaKirova 
- [ ] The date picker doesn't move when the grid is scrolled in cell edit mode. In row edit mode it scrolls with the row.
- [ ] In Row Edit mode the "Done/Cancel" overlay is not positioning correctly when scrolling the grid.

**Comment by MayaKirova** [comment]
@mpavlinov Change in expected behavior - overlays should now close on scroll.

**Comment by mpavlinov** [comment]
@MayaKirova I both cell/row edit mode it throws an exception in the cell/row gets out of viewport:

Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?
    at DefaultDomRenderer2.push../node_modules/@angular/platform-browser/fesm5/platform-browser.js.DefaultDomRenderer2.insertBefore (http://localhost:4200/vendor.js:74864:20)
    at BaseAnimationRenderer.push../node_modules/@angular/platform-browser/fesm5/animations.js.BaseAnimationRenderer.insertBefore (http://localhost:4200/vendor.js:73504:23)
    at DebugRenderer2.push../node_modules/@angular/core/fesm5/core.js.DebugRenderer2.insertBefore (http://localhost:4200/vendor.js:65725:23)

File: projects/igniteui-angular/src/lib/grids/grid-base.component.ts [hunk 3]
```diff
@@ -2350,23 +2353,6 @@ export abstract class IgxGridBaseComponent extends DisplayDensityBase implements
...
             this.parentVirtDir.onChunkLoad.emit(this.headerContainer.state);
         });
-
-        if (this.allowFiltering && this.filterMode === FilterMode.excelStyleFilter) {
-            this.closeExcelStyleDialog();
-        }
-    }
-
-    private closeExcelStyleDialog() {
-        const excelStyleMenu = this.outlet.nativeElement.getElementsByClassName('igx-excel-filter__menu igx-toggle')[0];
```
Comment (damyanpetev) [inline projects/igniteui-angular/src/lib/grids/grid-base.component.ts]: Would love for this to go away (😄), BUT in the Grid now the excel filter dialog can be opened and the grid scrolled horizontally and it just stays there.
Don't think that's intended.

Comment (MayaKirova) [reply projects/igniteui-angular/src/lib/grids/grid-base.component.ts]: OK.

File: projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts [hunk 4]
```diff
@@ -588,9 +592,31 @@ export class IgxHierarchicalGridComponent extends IgxHierarchicalGridBaseCompone
...
+        this.hideOverlays();
     }
 
     private hg_horizontalScrollHandler(event) {
         this.scrollLeft = event.target.scrollLeft;
+        this.hideOverlays();
+    }
+
+    private hideOverlays() {
+        const allOverlays = (this.overlayService as any)._overlayInfos;
```
Comment (mpavlinov) [inline projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts]: @MayaKirova This should be rewritten so that the grid keeps the ids of the opened overlays and just iterates over the collection to close them.

File: projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts [hunk 5]
```diff
@@ -588,9 +592,31 @@ export class IgxHierarchicalGridComponent extends IgxHierarchicalGridBaseCompone
...
+        const mainOverlays = allOverlays.filter((o) => o.settings.outlet === this.outletDirective);
+        if (mainOverlays.length > 0) {
+            mainOverlays.forEach(overlay => {
+                this.overlayService.hide(overlay.id);
+                // blur in case some editor somewhere decides to move focus back
+                this.overlayService.onClosed.pipe(
+                    filter(o => o.id === overlay.id),
+                    takeUntil(this.destroy$)).subscribe(() => {
+                        (document.activeElement as any).blur();
```
Comment (mpavlinov) [inline projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts]: @MayaKirova @ChronosSF We need to check whether calling blur in the destroy event of the igxFocus directive will work.

File: projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts [hunk 6]
```diff
@@ -588,9 +592,31 @@ export class IgxHierarchicalGridComponent extends IgxHierarchicalGridBaseCompone
 
     private hg_verticalScrollHandler(event) {
         this.scrollTop = event.target.scrollTop;
+        this.hideOverlays();
+    }
+
+    public onContainerScrol() {
```
Comment (kdinev) [inline projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts]: Method is misspelled.

File: projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts (hunk 5 above)
Comment (MayaKirova) [reply projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts]: @mpavlinov No. It does not.

File: projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts [hunk 7]
```diff
@@ -588,9 +604,27 @@ export class IgxHierarchicalGridComponent extends IgxHierarchicalGridBaseCompone
...
+    }
+
+    private hideOverlays() {
+        this._overlayIDs.forEach(overlayID => {
+            this.overlayService.hide(overlayID);
+            // blur in case some editor somewhere decides to move focus back
+            this.overlayService.onClosed.pipe(
+                filter(o => o.id === overlayID),
+                takeUntil(this.destroy$)).subscribe(() => {
+                    (document.activeElement as any).blur();
```
Comment (ChronosSF) [inline projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts]: @kdinev , atm we don't have a better solution for this as it seems to be caused by the for-of optimization with moving views around. However, the ViewRef that it works with has no public properties that will allow us to target blur detached elements.

This fix has better performance than anything that can be done in for-of.

File: src/app/hierarchical-grid-updating/hierarchical-grid-updating.sample.ts [hunk 8]
```diff
@@ -70,6 +70,14 @@ export class HierarchicalGridUpdatingSampleComponent implements AfterViewInit {
 
     gridCreated(event: IGridCreatedEventArgs, rowIsland: IgxRowIslandComponent) {
         this.remoteService.getData({ parentID: event.parentID, level: rowIsland.level, key: rowIsland.key }, (data) => {
+            if (rowIsland.key === 'Orders') {
```
Comment (ChronosSF) [inline src/app/hierarchical-grid-updating/hierarchical-grid-updating.sample.ts]: @kdinev, we can't use a pipe for this because the child grids don't have data properties and their data is set on application level through an event subscription.

File: projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts (hunk 7 above)
Comment (damyanpetev) [reply projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts]: Perhaps focusing the H Grid (what happens right now when you scroll normally) instead of random element blur would be better and should fail gracefully if the grid is already focused.
This, of course, assumes that the grid keeps its `tabindex` and remains focusable.

Comment (MayaKirova) [reply projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts]: @damyanpetev Agreed.
