### PR TITLE
fix(igxPivot): Move dimension instance between dimension collections …

### LINKED ISSUE #10818: [Pivot] Filtering still applies if filtering dimension is moved to row, remove all filters and moved to filters area again
## Description  
Describe the issue.

 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Open pivot sample
2. Move SellerName chip to row dimensions and remove all filters
3. Move it back to filters area
4. Observe that the filtering still applies

## Result  
The filtering applies

## Expected result  
The filtering should not apply

## Attachments  

filtering

### PR DESCRIPTION
**Pull request by MayaKirova**
…without disabling it.

Closes #10818   

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-header-row.component.ts [hunk 1]
```diff
@@ -275,25 +275,23 @@ export class IgxPivotHeaderRowComponent extends IgxGridHeaderRowComponent {
...
                 return;
             }
-            dims.forEach(element => {
-                element.enabled = false;
-            });
-
+            const dimType = this.getDimensionsType(dim);
             const currentDimChild = currentDim.find(x => x && x.memberName === dragId);
             if (currentDimChild) {
                 currentDimChild.enabled = true;
```
Comment (mddragnev) [inline projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-header-row.component.ts:286]: Is there a case after your changes where currentDimChild wil not be undefined?

**Review by mddragnev — APPROVED** [review]

File: projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-header-row.component.ts (hunk 1 above)
Comment (MayaKirova) [reply projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-header-row.component.ts:286]: Yes. I think that check can be removed.
