### PR TITLE
fix(Pivot): Sort column dimensions recursively and pass correct dimen…

### LINKED ISSUE #11804: [Pivot] Sorting column dimension with memberFunction passes wrong data object
## Description  
Sorting column dimensions with memberFunction passes wrong data object.

 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Open pivot dev sample
2. Add the following configuration of rows and columns
```
columns: [
            {
                memberName: 'City',
                memberFunction: (data) => {
                    const city = data['City'];
                    console.log(data);
                    const cityLength = city.length;
                    return city;
                },
                enabled: true,
                width: '100px'
            },
        ],
        rows: [
            {
                memberName: 'SellerName',
                enabled: true,
            }
        ],
```
3. Sort by clicking on the column chip
4.  Observe the console

## Result  
Screenshot 2022-06-30 at 18 23 17

See what object is logged right before the error. 

## Expected result  
It should be a data object. You can compare with sorting the rows.

## Attachments  
Attach a sample if available, and screenshots, if applicable.

### PR DESCRIPTION
**Pull request by mddragnev**
…sion and object to the sorting

Closes #11804   

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/data-operations/pivot-sort-strategy.ts [hunk 1]
```diff
@@ -47,13 +48,17 @@ export class DefaultPivotSortingStrategy extends DefaultSortingStrategy {
...
         this.dimension = PivotUtil.flatten(enabledDimensions).find(x => x.memberName === key);
+        this.pivotConfiguration = grid.pivotConfiguration;
         const reverse = (dir === SortingDirection.Desc ? -1 : 1);
         const cmpFunc = (obj1, obj2) => this.compareObjects(obj1, obj2, key, reverse, ignoreCase, this.getFieldValue, isDate, isTime);
         return this.arraySort(data, cmpFunc);
     }
 
     protected getFieldValue(obj: any, key: string, isDate: boolean = false, isTime: boolean = false): any {
-        let resolvedValue = PivotUtil.extractValueFromDimension(this.dimension, obj) || obj[0];
+        const isColumn = PivotUtil.flatten(this.pivotConfiguration.columns).find(dim => dim.memberName === this.dimension.memberName);
```
Comment (MayaKirova) [inline projects/igniteui-angular/src/lib/data-operations/pivot-sort-strategy.ts:58]: Not a fan of conditionally changing the way the data is retrieved. obj should always be the original data object IMO.

File: projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.component.ts [hunk 2]
```diff
@@ -2060,6 +2059,24 @@ export class IgxPivotGridComponent extends IgxGridBaseDirective implements OnIni
         return cols;
     }
 
+    private sortColumnFields(fields: Map<string, any>, expressions: any): Map<string,any> {
```
Comment (MayaKirova) [inline projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.component.ts:2062]: Might be simpler to just sort the original data before the Map is generated, like we do for the rows in the pivot pipes. Something like:

```
protected autogenerateColumns() {
...
        const expressions = PivotSortUtil.generateDimensionSortingExpressions(this.columnDimensions);
        const sortedData = DataUtil.sort(cloneArray(data, true), expressions, this.sortStrategy, this);
```

And then just use the sorted data when generating the unique values. They should be generated in the correct order, without the need to sort them again later.

            fieldsMap = PivotUtil.getFieldsHierarchy(
                sortedData,
                this.columnDimensions,
                PivotDimensionType.Column,
                this.pivotKeys
            );

Or at least they will be consistent with how the rows are sorted.
In both case for dates there will be issues since they get sorted as strings and not as actual date object. But I don't think that can be resolved without introducing some custom displayValue function or custom compare function.

File: projects/igniteui-angular/src/lib/data-operations/pivot-sort-strategy.ts [hunk 3]
```diff
@@ -47,6 +48,7 @@ export class DefaultPivotSortingStrategy extends DefaultSortingStrategy {
         const allDimensions = grid.allDimensions;
         const enabledDimensions = allDimensions.filter(x => x && x.enabled);
         this.dimension = PivotUtil.flatten(enabledDimensions).find(x => x.memberName === key);
+        this.pivotConfiguration = grid.pivotConfiguration;
```
Comment (MayaKirova) [inline projects/igniteui-angular/src/lib/data-operations/pivot-sort-strategy.ts:51]: I don't think think pivotConfiguration is used anymore. It can be removed.

**Review by MayaKirova — APPROVED** [review]

**Review by MayaKirova — APPROVED** [review]
