### PR TITLE
Fix scrollbar jump in FireFox when grid needs to autosize (100% height of container that has no size).

### LINKED ISSUE #9705: Page with two grids is srolled to the top on changing the second grid perPage or auto size
## Description  
The browser window scrollbar is scrolled back to the top when the second grid column is resized via double click or its perPage property is changed. This behavior is reproducible only in Mozilla and when the grids' height is not set.

 * igniteui-angular version: 12.1
 * browser: Mozilla

## Steps to reproduce  

1. Open [this](https://stackblitz.com/edit/srollable-igx-grids-one-page-du2qbq?file=src/app/grid/grid-row-editing-sample/grid-row-editing-sample.component.html) sample in a new window using Mozilla
2. Scroll the browser scrollbar to the bottom
3. Double-click on the second grid column border in order to resize the column or change the perPage value

## Result  
The page is scrolled back to the top

## Expected result  
The scrollbar position should not be changed

## Attachments  
Attach a sample if available, and screenshots, if applicable.

### PR DESCRIPTION
**Pull request by MayaKirova**
Closes #9705  

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Review by kdinev — APPROVED** [review]

File: projects/igniteui-angular/src/lib/grids/grid-base.directive.ts [hunk 1]
```diff
@@ -6523,7 +6524,7 @@ export abstract class IgxGridBaseDirective extends DisplayDensityBase implements
         let res = !this.nativeElement.parentElement ||
             this.nativeElement.parentElement.clientHeight === 0 ||
             this.nativeElement.parentElement.clientHeight === renderedHeight;
-        if (!isChromium()) {
+        if (!isChromium() && !isFireFox()) {
```
Comment (kdinev) [inline projects/igniteui-angular/src/lib/grids/grid-base.directive.ts:6527]: I think the grid should use the `PlatformUtil` rather than to have separate implementation for `isChromium` or `isFireFox`.

**Review by kdinev — CHANGES_REQUESTED** [review]

File: projects/igniteui-angular/src/lib/grids/grid-base.directive.ts [hunk 2]
```diff
@@ -6523,7 +6522,7 @@ export abstract class IgxGridBaseDirective extends DisplayDensityBase implements
         let res = !this.nativeElement.parentElement ||
             this.nativeElement.parentElement.clientHeight === 0 ||
             this.nativeElement.parentElement.clientHeight === renderedHeight;
-        if (!isChromium()) {
+        if (!this.platform.isChromium && !this.platform.isFirefox) {
```
Comment (kdinev) [inline projects/igniteui-angular/src/lib/grids/grid-base.directive.ts:6525]: @MayaKirova If possible, remove the method from the `selection.service`. I found only one other reference to this method inside the selection service and it can also be replaced with the platform util property check.

**Review by kdinev — CHANGES_REQUESTED** [review]

**Review by kdinev — APPROVED** [review]
