### PR TITLE
fix(dropdown,select): add igxFor DI alias for tree-shaking

### LINKED ISSUE #13677: select and drop down don't tree-shake `igxForOf`

### PR DESCRIPTION
**Pull request by damyanpetev**
Closes #13677
Note I've intentionally kept the token internal and kept it out of the public export.
Also didn't add the full public API, just the bits needed internally.

Before in issue above and after:
image
image

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/drop-down/drop-down.component.ts [hunk 1]
```diff
@@ -343,6 +343,7 @@ export class IgxDropDownComponent extends IgxDropDownBaseDirective implements ID
             return;
         }
         let targetScroll = this.virtDir.getScrollForIndex(this.selectedItem.index);
+        // TODO: This logic _cannot_ be right, those are optional user-provided inputs that can be strings with units, refactor:
         const itemsInView = this.virtDir.igxForContainerSize / this.virtDir.igxForItemSize;
```
Comment (damyanpetev) [inline projects/igniteui-angular/src/lib/drop-down/drop-down.component.ts:347]: @Lipata Added this comment since there's no way this logic is correct:
`igxForItemSize` and `igxForContainerSize` are documented accepting strings with units (like `'500px'`) and as such this is only written for/tested with a narrow scenario. Evaluate the need for this logic entirely, I'm assuming the `igxFor` should already have a method to scroll to a specific item so all of those calculations could be replaced with `scrollTo(this.selectedItem.index)` ideally and the props can be removed from the token. Can add in this PR if you're up for testing

File: projects/igniteui-angular/src/public_api.ts [hunk 2]
```diff
@@ -19,7 +19,9 @@ export * from './lib/directives/drag-drop/public_api';
 export * from './lib/directives/filter/filter.directive';
 export * from './lib/directives/focus/focus.directive';
 export * from './lib/directives/focus-trap/focus-trap.directive';
-export * from './lib/directives/for-of/for_of.directive';
+export {
+    IgxForOfContext, IgxForOfDirective, IForOfState, IgxGridForOfContext, IgxGridForOfDirective
+} from './lib/directives/for-of/for_of.directive';
```
Comment (damyanpetev) [inline projects/igniteui-angular/src/public_api.ts:24]: The star export also included a random `getTypeNameForDebugging` function and `IForOfDataChangingEventArgs` for an internal event, which I skipped along with the new token
// CC @kdinev

File: projects/igniteui-angular/src/lib/drop-down/drop-down.component.ts (hunk 1 above)
Comment (damyanpetev) [reply projects/igniteui-angular/src/lib/drop-down/drop-down.component.ts:347]: Okay, tested with `scrollTo(this.selectedItem.index)` which works but just barely gets the item in view, often at the bottom of the list, which I assume is not the goal. However, the Combo overrides this method with 
```ts
this.virtDir.getScroll().scrollTop = this._scrollPosition;
```
And `this._scrollPosition` is something the dropdown maintains and that seems to work just fine. Except it no longer tries to center, but I think we can reduce this code a bit if we're okay with a minor behavior change that will have the combo and virtual dd behaving the same way. Might be worth it.

**Review by kdinev — APPROVED** [review]

File: projects/igniteui-angular/src/lib/drop-down/drop-down.component.ts (hunk 1 above)
Comment (Lipata) [reply projects/igniteui-angular/src/lib/drop-down/drop-down.component.ts:347]: As we talked - when re-opening a combo, it positiones the selected item in the middle and this is for both - local and remote binding. You are right that we can reduce that amount of code, but I prefer not to change that functionality - because of the slight UI behavior change and the need to change it for local and remote in order to keep the consistency.

**Review by Lipata — APPROVED** [review]
