### PR TITLE
fix(igxHierarchicalGrid): Fix columnList for root and children not updated and row islands not having access to children. 

### LINKED ISSUE #4337: Changing columns dynamically in the Hierarchical Grid resets root column list to contain child columns.
## Description  
Changing columns list after initial load of the Hierarchical Grid resets the columns list so that the root grid contains columns from all children.

 * igniteui-angular version: 7.2.x
 * browser: All

## Steps to reproduce  

1. Open https://stackblitz.com/edit/angular-rxuf9h
2. Observe the root grid columns.

## Result  
The root grid contains the columns from all children.

## Expected result  
The root grid should only have columns corresponding to it and not contain columns from the children.

### PR DESCRIPTION
**Pull request by skrustev**
Closes #4337

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them
 
**Note:** Please test with various scenarios that change the column collection for row islands on only level with expanded/collapsed child grids and etc.

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/hierarchical-grid/child-grid-row.component.ts [hunk 1]
```diff
@@ -169,7 +169,11 @@ export class IgxChildGridRowComponent implements AfterViewInit, OnInit {
         }
         const layouts = this.hGrid.childLayoutList.toArray();
         layouts.forEach((l) => this.hGrid.hgridAPI.registerLayout(l));
-        this.parentGrid.hgridAPI.registerChildGrid(this.rowData.rowID, this.layout.key, this.hGrid);
+        this.parentGrid.hgridAPI.registerChildGrid(this.rowData.rowID, this.layout.id, this.hGrid);
+        if (this.parentGrid.parent) {
```
Comment (MayaKirova) [inline projects/igniteui-angular/src/lib/grids/hierarchical-grid/child-grid-row.component.ts]: @skrustev Instead of registering everything on the root grid service and branching the logic that accessed the child grids it may be better to inject separate services for the layout instances and have each track its own children (currently layouts use the root grid's API service).
