### PR TITLE
fix(igxGridSummary): column with summary outside of viewport not working

### LINKED ISSUE #1407: Summary not working when we have identical width and it is applied to column outside of the view port
### Description  
Summary not working correctly when we have column with identical widths and enabled summary per column which is not visible

### Steps to reproduce  

1. Open grid summary sample
2. Set hasSummary to true for OrderDate column
3. Try to add or delete row.

### Result  
There is no update into summary section.

### Expected result  
Summaries should be updated based on the added/deleted rows.

### PR DESCRIPTION
**Pull request by Aleksandyr**
when we have column with summary applied and it is outside of the
viewport and we have indentical width per column summary doesn't reflect
on any changes

Closes #1407

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grid/grid.component.ts [hunk 1]
```diff
@@ -482,6 +486,10 @@ export class IgxGridComponent implements OnInit, OnDestroy, AfterContentInit, Af
         this.calcWidth = this._width && this._width.indexOf('%') === -1 ? parseInt(this._width, 10) : 0;
         this.calcHeight = 0;
         this.calcRowCheckboxWidth = 0;
+        this._subscribeOnRowAdded$ = this.onRowAdded.subscribe(() => this.clearSummaryCache());
```
Comment (rkaraivanov) [inline projects/igniteui-angular/src/lib/grid/grid.component.ts]: Use the `takeUntil(this.destroy$)` for unsubscribing when the grid is destroyed. Don't manage subscribtions 'manually'.

File: projects/igniteui-angular/src/lib/grid/grid.component.ts [hunk 2]
```diff
@@ -539,6 +547,22 @@ export class IgxGridComponent implements OnInit, OnDestroy, AfterContentInit, Af
         this.zone.runOutsideAngular(() => this.document.defaultView.removeEventListener('resize', this.resizeHandler));
         this.destroy$.next(true);
         this.destroy$.complete();
+
+        if (this._subscribeOnRowAdded$) {
```
Comment (rkaraivanov) [inline projects/igniteui-angular/src/lib/grid/grid.component.ts]: The `unsubscribe` should be in the `onDestroy` hook. Use the approach in the previous comment and this whole code snippet is redundant.
