### PR TITLE
fix(tooltip): remove unnecessary div creation

### LINKED ISSUE #10723: Tooltip is moving when it is used with flex and gap
## Description  
When tooltip is used with flex with gap, it is initially hidden, but once it's triggering is leaving a lingering non-hidden div behind.

## Result  
When the component appear it is moving slightly to the left side.

## Expected result  
The tooltip component should stay on the same position as when it is not hovered.

## Attachments  
Here is an example of the bug: [StackBlitz](https://stackblitz.com/edit/github-h8flju?file=src/app/app.component.html)

### PR DESCRIPTION
**Pull request by Volen99**
Closes #10723

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Review by Svetloslav15 — APPROVED** [review]

File: projects/igniteui-angular/src/lib/services/overlay/overlay.ts [hunk 1]
```diff
@@ -577,16 +576,6 @@ export class IgxOverlayService implements OnDestroy {
         return info;
     }
 
-    private placeElementHook(element: HTMLElement): HTMLElement {
-        if (!element.parentElement) {
-            return null;
-        }
-
-        const hook = this._document.createElement('div');
```
Comment (wnvko) [inline projects/igniteui-angular/src/lib/services/overlay/overlay.ts:585]: we are using element hook to return the overlay element at its original position. If we do not do this overlay will change the original markup which is not desired.
To fix the issue you can set the `display` of the hook element to `none` like this:
```
hook.style.display = 'none';
```

**Review by wnvko — CHANGES_REQUESTED** [review]

File: projects/igniteui-angular/src/lib/services/overlay/overlay.ts (hunk 1 above)
Comment (Volen99) [reply projects/igniteui-angular/src/lib/services/overlay/overlay.ts:585]: Oh, I see. That was very helpful, I was really wondering what was the reason behind this hook. Will do so ✔

**Review by wnvko — APPROVED** [review]

**Review by Svetloslav15 — APPROVED** [review]

**Review by hanastasov — APPROVED** [review]
