### PR TITLE
fix(date-picker): Renaming of mode values #4143

### LINKED ISSUE #4143: DatePickerInteractionMode enum should contain the same values as TimePickerInteractionMode - dropdown and dialog
## Description  
DatePickerInteractionMode enum should contain the same values as TimePickerInteractionMode - dropdown and dialog

 * igniteui-angular version: 7.2
 * browser: NA

## Steps to reproduce  

1. igx-date-picker mode accepts readonly and editable modes
2.  igx-time-picker mode accepts dialog and dropdown modes

## Result  
Inconsistence

## Expected result  
igx-date-picker mode to accept dialog and dropdown modes

### PR DESCRIPTION
**Pull request by sboykova**
Closes #4143

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/core/enums.ts [hunk 1]
```diff
@@ -0,0 +1,8 @@
+/**
+ * This enumeration is used to configure whether the date/time picker has an editable input with drop down
+ * or is readonly - the date/time is selected only through a dialog.
+ */
+export const enum InteractionMode {
+    DROPDOWN = 'dropdown',
```
Comment (kdinev) [inline projects/igniteui-angular/src/lib/core/enums.ts]: Make the enum values capitalized, not all CAPS. I will update the contributing.md with this guidance. 

```
 export const enum InteractionMode {
  DropDown = 'dropdown',
  Dialog = "dialog"
}
```
