### PR TITLE
fix(excel-style-filtering): reset filter value

### LINKED ISSUE #14841: The filter value in external filtering is not reset
## Description  
The filter value in external excel style filtering is not reset when the same condition is selected as the previous filter

 * igniteui-angular version: 17.2, 18.1
 * browser: n/a

## Steps to reproduce  

1. Open this [demo](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/excel-style-filtering#demo)
1. Select ProductName column and click on Text filter
2. Choose Starts With, enter filter value and apply the filter
3. Select QuantityPerUnit column and click on Text filter
4. Choose Starts With as filter condition
5. Observe the filter value field

## Result  
The filter value contains the value of the previously applied filter.

## Expected result  
The filter value input should be empty.

## Attachments  
igx-grid-external-filter

### PR DESCRIPTION
**Pull request by igdmdimitrov**
Closes #14841 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-conditional-filter.component.ts [hunk 1]
```diff
@@ -41,7 +41,7 @@ export class IgxExcelStyleConditionalFilterComponent implements OnDestroy {
     public subMenu: IgxDropDownComponent;
 
     protected get filterNumber() {
-        return this.esf.expressionsList.length;
+        return this.esf.expressionsList.filter(e => e.expression.fieldName === this.esf.column.field && e.expression.condition).length;
```
Comment (gedinakova) [inline projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-conditional-filter.component.ts:44]: Shouldn't the expressionsList always be filterted with these conditions (meaning that we filter on initializing it) instead of having to add the same conditions in a few places?

File: projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-conditional-filter.component.ts [hunk 2]
```diff
@@ -145,7 +145,9 @@ export class IgxExcelStyleConditionalFilterComponent implements OnDestroy {
     public onSubMenuSelection(eventArgs: ISelectionEventArgs) {
         if (this.esf.expressionsList && this.esf.expressionsList.length &&
             this.esf.expressionsList[0].expression.condition.name !== 'in') {
-            this.customDialog.expressionsList = this.esf.expressionsList;
+            this.customDialog.expressionsList = this.esf.expressionsList.filter(e => e.expression.fieldName === this.esf.column.field && e.expression.condition);
```
Comment (gedinakova) [inline projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-conditional-filter.component.ts:148]: Same as above

**Review by gedinakova — CHANGES_REQUESTED** [review]

**Review by gedinakova — APPROVED** [review]

**Review by Otixa — APPROVED** [review]

File: ROADMAP.md [hunk 3]
```diff
@@ -4,15 +4,24 @@
...
-1. Angular 19 support
+1. Tile Manager - new component [#239](https://github.com/IgniteUI/igniteui-angular/issues/239)
 2. Query Builder component update [#14979](https://github.com/IgniteUI/igniteui-angular/issues/14979)
+3. IgxBannerComponent - Support collapsed input [#14890](https://github.com/IgniteUI/igniteui-angular/issues/14890)
+4. Update of the carousel component [#15025](https://github.com/IgniteUI/igniteui-angular/issues/15025)
 
 ## Going down the road
 
-1. Tile Manager - new component [#239](https://github.com/IgniteUI/igniteui-angular/issues/239)
+1. Provide an option to modify the default enter edit mode conditions, to e.g. allow edit mode start on a single click [#14658](https://github.com/IgniteUI/igniteui-angular/issues/14658)
```
Comment (Otixa) [inline ROADMAP.md:14]: Should changes to this file be part of this branch? 🤔

**Review by Otixa — APPROVED** [review]
Approved, contingent on the changes to README/ROADMAP/SECURITY being intentional/inconsequential.

**Review by gedinakova — APPROVED** [review]
