### PR TITLE
Fix for column moving in grouped columns

### LINKED ISSUE #4094: Excel Style Filtering - when there is a hidden column RIGHT button should be disabled when moving a column to the end
## Description  
RIGHT button is not disabled when moving a column to the end in Excel Style Filtering dialog

 * igniteui-angular version: 7.2
 * browser: N/A

## Steps to reproduce  

1. Open **Column Moving** dev demo.
2. Open excel filter on the **ConatctName** column and hide it.
3. Open excel filter on the **ContactTitle** column and start clicking on the RIGHT button until reaching the end.
4. Scroll and observe.

## Result  
RIGHT button stays enabled, although the column cannot be moved further on.

## Expected result  
RIGHT button becomes disabled.

### LINKED ISSUE #4113: Error is thrown when move column to right (Column groups)
## Description  

 * igniteui-angular version: 7.2.x
 * browser: all

## Steps to reproduce  

1. Open Column Groups Dev Sample
2. Enable excel style filtering
3. Start moving column 'ID'  to right to the last visible position

## Result  
image

## Expected result  
No error should be thrown and right button should be disabled.

### LINKED ISSUE #4114: Can not move a column to left if the previous column is column group
## Description  

 * igniteui-angular version: 7.2.x
 * browser: all

## Steps to reproduce  

1. Open Column Groups Dev Sample
2. Enable excel style filtering
3. Move "ID" column to left

## Result  
The column is not moved.

## Expected result  
The column should be moved. 
**The buttons move left and right should be enabled/disabled properly, when the column is part from column group.**

### PR DESCRIPTION
**Pull request by sstoyanovIG**
Closes #4114
Closes #4113 
Closes #4094    

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-column-moving.component.ts [hunk 1]
```diff
@@ -22,34 +22,45 @@ export class IgxExcelStyleColumnMovingComponent {
...
+        } else {
+            targetColumn = this.findColumn(moveDirection, this.grid.unpinnedColumns);
+        }
+        this.grid.moveColumn(this.column, targetColumn, moveDirection);
+    }
+
+    private findColumn(moveDirection: number, columns: IgxColumnComponent[]) {
+        let index = columns.indexOf(this.column);
+        if (moveDirection === 0) {
+            while (index >= 0) {
```
Comment (bkulov) [inline projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-column-moving.component.ts]: Should be `index > 0` to avoid exception if the start index is 0.
