### PR TITLE
fix(input-group): allow runtime changes to type, prefix/suffix

### LINKED ISSUE #7455: Changing the type of input-group from 'line' to 'fluent' removes the label
## Description  
Setting the type dynamically of the input-group to fluent removes the label.

 * igniteui-angular version: 9.1.x
 * browser: N\A

## Steps to reproduce  

1. Open https://stackblitz.com/edit/angular-smtaro
2. Click the button to apply 'fluent' `type` to the input-groups

The input-group does not have `type` specified, which defaults into 'line'. If the type is applied initially the label is rendered as expected.

## Result  
The label of the input-group is removed.

## Expected result  
The label should still render after the type of input-group is changed.

## Attachments  
inp-group

### PR DESCRIPTION
**Pull request by simeonoff**
This change is needed to accommodate for runtime changes to the `type` prop.

Closes #7455

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by simeonoff** [comment]
@dkamburov Could you please verify this PR?

File: projects/igniteui-angular/src/lib/input-group/input-group.component.ts [hunk 1]
```diff
@@ -10,44 +10,55 @@ import {
...
+    bootstrap,
+    indigo,
+    search,
+    fluent_search,
 }
 
+/**
+ * Determines the Input Group type.
+ */
+export type IgxInputGroupType = keyof typeof IgxInputGroupEnum;
```
Comment (damyanpetev) [inline projects/igniteui-angular/src/lib/input-group/input-group.component.ts:48]: 👍

File: projects/igniteui-angular/src/lib/input-group/input-group.component.ts [hunk 2]
```diff
@@ -200,48 +187,18 @@ export class IgxInputGroupComponent extends DisplayDensityBase implements IgxInp
...
-                    break;
-                case IgxInputGroupType.BOOTSTRAP:
-                    this.isBootstrap = true;
-                    break;
-                default: break;
-            }
-
-            this._type = type;
-        }
+    public set type(value: IgxInputGroupType) {
```
Comment (damyanpetev) [inline projects/igniteui-angular/src/lib/input-group/input-group.component.ts:196]: Minor thing (can be ignored): if this doesn't require logic anymore, it could be just a normal property with the default value assigned :)

PS: Looking at the description & code - do I see right or did `fluentSearch` never quite worked before?

Comment (simeonoff) [reply projects/igniteui-angular/src/lib/input-group/input-group.component.ts:196]: Might be. I am looking forward to further reducing the amount of types allowed to just - box, border, line, and search. There's a lot of work to be done on the styling side for this to happen.
