### PR TITLE
Localization applied to grid's editing row message

### LINKED ISSUE #14625: Localization not applied to grid editing messages
## Description  
When using the IgniteUI Angular grid with any available localization, the message regarding row edits and hidden columns remains in English, while other parts of the grid are correctly localized.

 * igniteui-angular version: 18.0.x
 * browser: any

## Steps to reproduce  

1. Set up a grid with a supported localization (e.g., French, German, etc.).
2. Enable row editing.
3. Observe the message displayed when editing a row.

## Result  
The message remains in English, as shown in the attached screenshot.

## Expected result  
The message should be localized according to the selected locale.

## Attachments  
[Sample](https://codesandbox.io/p/devbox/floral-smoke-359m29?workspaceId=916d0153-dc8f-4a13-9938-2eab0eb12ed8&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clz6xzkzi0006356jixnxaz0k%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clz6xzkzi0002356jqei0ic87%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clz6xzkzi0004356jh3674i2i%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clz6xzkzi0005356jpila05jk%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clz6xzkzi0002356jqei0ic87%2522%253A%257B%2522id%2522%253A%2522clz6xzkzi0002356jqei0ic87%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clz6xzkzi0005356jpila05jk%2522%253A%257B%2522id%2522%253A%2522clz6xzkzi0005356jpila05jk%2522%252C%2522activeTabId%2522%253A%2522clzs66egl001e356jxq9gbq6v%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A4200%252C%2522id%2522%253A%2522clz6y4zdg006r356j5zini5vw%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%2522%257D%252C%257B%2522type%2522%253A%2522SETUP_TASKS%2522%252C%2522id%2522%253A%2522clzs61vhr001d356kf2rgo7jq%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A4200%252C%2522id%2522%253A%2522clzs66egl001e356jxq9gbq6v%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clz6xzkzi0004356jh3674i2i%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clz6xzkzi0003356jiaxbg1wc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522node%2520node_modules%252F%2540angular%252Fcli%252Fbin%252Fng%2520serve%2520-o%2520--disable-host-check%2522%257D%255D%252C%2522id%2522%253A%2522clz6xzkzi0004356jh3674i2i%2522%252C%2522activeTabId%2522%253A%2522clz6xzkzi0003356jiaxbg1wc%2522%257D%257D%252C%2522showDevtools%2522%253Afalse%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

image

### PR DESCRIPTION
**Pull request by Zneeky**
Closes #14625   

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/core/i18n/grid-resources.ts [hunk 1]
```diff
@@ -277,6 +278,7 @@ export const GridResourceStringsEN: IGridResourceStrings = {
     igx_grid_pinning_uncheck_all_label: 'Unpin All',
     igx_grid_row_edit_btn_done: 'Done',
     igx_grid_row_edit_btn_cancel: 'Cancel',
+    igx_grid_row_edit_text: "You have {0} changes in this row and {1} hidden columns",
     igx_grid_toolbar_actions_filter_prompt: 'Filter columns list ...',
```
Comment (ddaribo) [inline projects/igniteui-angular/src/lib/core/i18n/grid-resources.ts:282]:
```suggestion
    igx_grid_row_edit_text: 'You have {0} changes in this row and {1} hidden columns',
```
Single quotes to be consistent

**Review by ddaribo — CHANGES_REQUESTED** [review]

**Review by ddaribo — APPROVED** [review]
