### PR TITLE
Filter grid correctly with case insensitive duplicate records - master

### LINKED ISSUE #14906: Excel style filtering is not working correctly with lower/upper case values
## Description  
Excel style filtering is not working correctly with lower/upper case values when more than 2 values are selected

 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Open this [sample](https://codesandbox.io/p/devbox/weathered-forest-hfhkks)
2. Open the excel style dialog for column 'field2'
3. Enter 'Harald_' into the Search field
4. Press 'Apply'

## Result  
'Harald_a1' value is missing and 'Harald_A1' is displayed

## Expected result  
'Harald_a1' and 'Harald_A1' values should be displayed

## Attachments
grid-excel-style-filter

### PR DESCRIPTION
**Pull request by MonikaKirkova**
Closes #14906 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-filtering.component.ts [hunk 1]
```diff
@@ -509,6 +509,11 @@ export class IgxGridExcelStyleFilteringComponent extends BaseFilteringComponent
     private renderValues() {
         this.filterValues = this.generateFilterValues();
         this.generateListData();
+        this.expressionsList.forEach(expr => {
+            if (expr.expression.condition.name === 'in' && this.column.dataType === GridColumnDataType.String) {
```
Comment (gedinakova) [inline projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-filtering.component.ts:513]: I don't think we need the condition check but we may want to check the column's filteringIgnoreCase prop (because if false, the modification is not needed).
```suggestion
            if (this.column.dataType === GridColumnDataType.String && this.column.filteringIgnoreCase) {
```

**Review by gedinakova — CHANGES_REQUESTED** [review]

**Review by gedinakova — APPROVED** [review]

**Review by gedinakova — APPROVED** [review]
