### PR TITLE
Remove refreshSearch form the escape_editMode method

### LINKED ISSUE #4902: An error is returned when a row is opened in edit mode and click to search the next item
## Description  
An error is returned when a row is opened in edit mode and click to search the next item

 * igniteui-angular version: 7.3
 * browser: n/a

## Steps to reproduce  

1. Open dev sample treeGrid
2. Select the Enable RowEditing
3. In the search type Owner
4. Double click on a cell to open the row editing
5. In the search click next

## Result  
An error in console is previewed, the cell editmode is closed, but the row is not

## Expected result  
There should be no errors and the rowediting should be closed

## Attachments  
image

### PR DESCRIPTION
**Pull request by nrobakova**
Closes #4902   

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/grid-base.component.ts [hunk 1]
```diff
@@ -5041,7 +5041,10 @@ export abstract class IgxGridBaseComponent extends DisplayDensityBase implements
             return 0;
         }
 
-        this.endEdit(false);
+        const editModeCell = this.crudService.cell;
```
Comment (rkaraivanov) [inline projects/igniteui-angular/src/lib/grids/grid-base.component.ts]: I don't think this is necessary. Maybe remove the call to `refreshSearch()` in the `escape_editMode()` API service method.
There were changes to the highlight directive cdr cycle and I believe calling `refreshSearch` is not needed in most instances.
