### PR TITLE
fix(grid): hides editing row when scrolling horizontally

### LINKED ISSUE #8023: igx-grid: row edit overlay disappears
## Description  
Describe the issue.

 * igniteui-angular version:  9 ~ 10
 * browser:  Chrome and  Firefox

## Steps to reproduce  

See example here 
https://stackblitz.com/edit/igx-grid-row-edit-bfz6ui

1. Make the browser window narrow enough until the grid cannot fit horizontally 
2. Double click cell to open the row edit overlay, keep pressing TAB to jump to right until it scrolls to right 
3. .The edit overlay disappears

## Result  
The edit overlay disappears, while it is still in row edit mode

## Expected result  
The edit overlay shouldn't disappear after the grid scrolls horizontally

### PR DESCRIPTION
**Pull request by simeonoff**
Closes #8023  

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Review by Lipata — DISMISSED** [review]

File: projects/igniteui-angular/src/lib/grids/grid-base.directive.ts [hunk 1]
```diff
@@ -3021,8 +3023,12 @@ export abstract class IgxGridBaseDirective extends DisplayDensityBase implements
                 return;
             }
 
-            if (this.overlayService.getOverlayById(event.id)?.settings?.outlet === this.outlet &&
-                this.overlayIDs.indexOf(event.id) < 0) {
+            if (overlaySettings?.outlet === this.outlet && this.overlayIDs.indexOf(event.id) === -1) {
+                // do not hide the overlay if it's attached to a row for editing purposes
+                if (overlaySettings.positionStrategy instanceof RowEditPositionStrategy) {
```
Comment (nrobakova) [inline projects/igniteui-angular/src/lib/grids/grid-base.directive.ts:3028]: the RowEditPositionStrategy can be used from other component, because it is public.
The IgxToggleDirective should be extended to return the overlayId and we can check if the rowEditingOverlay overlay id is different than the event.id

**Review by nrobakova — CHANGES_REQUESTED** [review]

File: projects/igniteui-angular/src/lib/grids/grid-base.directive.ts [hunk 2]
```diff
@@ -3021,8 +3023,12 @@ export abstract class IgxGridBaseDirective extends DisplayDensityBase implements
                 return;
             }
 
-            if (this.overlayService.getOverlayById(event.id)?.settings?.outlet === this.outlet &&
-                this.overlayIDs.indexOf(event.id) < 0) {
+            // do not hide the overlay if it's attached to a row
+            if (this.rowEditingOverlay.overlayId === event.id) {
```
Comment (MayaKirova) [inline projects/igniteui-angular/src/lib/grids/grid-base.directive.ts:3027]: Should also check if this.rowEditingOverlay exists since it probably won't in grids that don't have row editing.

**Review by MayaKirova — CHANGES_REQUESTED** [review]

**Review by MayaKirova — DISMISSED** [review]

**Review by wnvko — APPROVED** [review]

**Review by nrobakova — DISMISSED** [review]

**Review by Lipata — APPROVED** [review]

**Review by wnvko — APPROVED** [review]

**Review by Lipata — APPROVED** [review]
