### PR TITLE
[igxPivot] Ensure that bottom level dimensions get populated regardless of expansion.

### LINKED ISSUE #10639: [igxPivot] When all dimensions are initially collapsed and first dimension has children the second dimension data does not display correctly.
## Description  
When all dimensions are initially collapsed ([defaultExpandState] = 'false' or not set) and first dimension has children the second dimension data does not display correctly.

 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Run the pivot-hierarchy sample with config:
```
columns: [
            {
                memberName: 'AllSeller',
                memberFunction: () => 'All Sellers',
                enabled: true,
                childLevel:
                {
                    memberName: 'Seller',
                    memberFunction: (data) => data.Seller.Name,
                    enabled: true,
                },
            },
        ],
        rows: [
            {
                memberName: 'AllProduct',
                memberFunction: () => 'All Products',
                enabled: true,
                childLevel:
                {
    
                    memberName: 'Product',
                    memberFunction: (data) => data.Product.Name,
                    enabled: true
                }
            },
            {
                memberName: 'City',
                memberFunction: (data) => data.Seller.City,
                enabled: true,
            },
        ],
```

## Result  
Observe that the second dimension does not show its values.

image

## Expected result  
Should show all unique City values as rows.

Note: Works as expected if [defaultExpandState] = 'true' .

## Attachments  
Attach a sample if available, and screenshots, if applicable.

### PR DESCRIPTION
**Pull request by skrustev**
Closes #10639

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-util.ts [hunk 1]
```diff
@@ -82,7 +82,8 @@ export class PivotUtil {
         pivotKeys: IPivotKeys,
         lvl: number,
```
Comment (skrustev) [inline projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-util.ts:83]: I am also not sure if this check for the combined lvl depth is needed, since we go in depth of the current dimension, not all combined.

File: projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-util.ts [hunk 2]
```diff
@@ -97,12 +98,12 @@ export class PivotUtil {
                 expansionStates.get(expansionRowKey);
             if (rec[field + '_' + pivotKeys.records] &&
                 rec[field + '_' + pivotKeys.records].length > 0 &&
-                isExpanded && lvl > 0) {
+                ((isExpanded && lvl > 0)  || (maxDimLvl == currDimLvl))) {
```
Comment (skrustev) [inline projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-util.ts:101]: More specifically this `lvl > 0`

Comment (MayaKirova) [reply projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-util.ts:101]: Should be fine with just the new level check but I'll test it to make sure.

**Comment by MayaKirova** [comment]
@skrustev 
I'm not sure whether the expand/collapse pipe should be the one adding the flat dimension's data in the root. It should only resolve expand/collapse state hence it should only add child data records when a record is expanded, but in this scenario nothing is expanded initially. IMO the row pipe should be the one generating the root data with the 'All' + Berlin,  'All' + London etc. combinations and the expand pipe should only add the products after when 'All' is expanded. 

In some cases it seems that the row pipes does add records to the root which combined with the changes in this PR seems to add the same records multiple times. For example if you use the following config:

```
 columns: [
            
        ],
        rows: [
            new IgxPivotDateDimension(
                {
                    memberName: 'Date',
                    enabled: true
                },
                {
                    months: false
                }
            ),
            {
                memberFunction: (data) => data.ProductCategory,
                memberName: 'ProductCategory',
                enabled: true
            },
            {
                memberName: 'Country',
                enabled: true
            }
        ],
```
You'll see that the same records are added 3 times in the root:

image

Probably because with this config the row pipe adds the Product Category records to the root:
image

And then the expand pipe adds them again.

**Review by MayaKirova — APPROVED** [review]

**Review by dkamburov — APPROVED** [review]
