### PR TITLE
Exit edit mode on collapse/expand

### LINKED ISSUE #4761: Cell in edit mode is not correct when expand a row
## Description  
Row editing buttons are not in correct position when expand a row in a child grid

 * igniteui-angular version: 7.3
 * browser: n/a

## Steps to reproduce  

1. Open dev sample hierarchicalGridUpdating
2. Expand first row
3. In the child grid double click on a cell in row with id 3
4. Row edit template is opened
5. In the child grid expand row with id 1
6. Scroll to row 3

Note1: Same is valid for the root grid
Note2: same is valid for cell editing

## Result  
Cell in row 2 is in edit mode and Done/Cancel buttons are under row 3

## Expected result  
Cell in edit mode should be in row 3

## Attachments  
image

### LINKED ISSUE #5044: Cell in edit mode is not correct when expand collapse group row
## Description  
Cell in edit mode is not correct when expand collapse group row

 * igniteui-angular version: 7.3.x
 * browser: n/a

## Steps to reproduce  

1. Open dev sample gridGroupBy
2. Group by column Country
3. Click on cell in 4th row
4. Collapse the first row

This issue is related to the bug #4761 
This issue is not reproducible in 7.1.x, but it is reproducible in 7.2.x and 7,3,x 

## Result  
The cell in edit mode is not in correct row

## Expected result  
The cell in edit mode should not be changed

## Attachments  
Attach a sample if available, and screenshots, if applicable.

### PR DESCRIPTION
**Pull request by wnvko**
When hierarchical/grouped grid expand or collapse its rows we should exit edit mode.

Closes #4761   
Closes #5044 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-row.component.ts [hunk 1]
```diff
@@ -93,6 +94,20 @@ export class IgxHierarchicalRowComponent extends IgxRowComponent<IgxHierarchical
         });
     }
 
+    private endEdit(grid: IgxHierarchicalGridComponent) {
+        while (grid.parent) {
```
Comment (MayaKirova) [inline projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-row.component.ts]: There is already a getter for the rootGrid that you can use --> grid.rootGrid

Comment (wnvko) [reply projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-row.component.ts]: thank you
changed :)
