### PR TITLE
Fixed columns and data mismatch in exported Excel file #9872

### LINKED ISSUE #9872: Excel Exporter misalignment between headers and exported data
## Description  
The column headers are exported in the correct order but the underlying data does not correspond to the headers. This happens when new keys are appended to the initial data source.

 * igniteui-angular version: 12.0.7
 * browser: any

## Steps to reproduce  

1. Open the following [sample](https://stackblitz.com/edit/github-p3jcbl-bczqqf?file=src/app/grid/grid-sample-pinning/grid-toolbar-pinning.component.ts)
2. Export the grid

## Result
There is a misalignment between the headers and the data.  
image

## Expected result  
Data should match its headers.
image

## Attachments  
Attach a sample if available, and screenshots, if applicable.

### PR DESCRIPTION
**Pull request by gedinakova**
Closes #9872 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/services/excel/worksheet-data.ts [hunk 1]
```diff
@@ -31,6 +32,10 @@ export class WorksheetData {
         return !this.rowCount || !this.columnCount;
     }
 
+    // public get keys(): string[] {
+    //     return this._keys;
+    // }
+
```
Comment (igdmdimitrov) [inline projects/igniteui-angular/src/lib/services/excel/worksheet-data.ts:38]: Remove comment

**Review by igdmdimitrov — APPROVED** [review]
