### PR TITLE
Calculate viewIndex properly for each type of row

### LINKED ISSUE #9548: viewIndex returns incorrect value if flat grid is grouped
## Description  
When flat grid is grouped, `viewIndex` will return incorrect value.

 * igniteui-angular version: 12.0.rc.0

## Steps to reproduce  

1. Open Row API dev demo
2. Group the flat grid
3. Log row state and see values for `index` and `viewIndex`

### PR DESCRIPTION
**Pull request by hanastasov**
Closes #9548 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [x] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/grid-public-row.ts [hunk 1]
```diff
@@ -453,10 +475,23 @@ export class IgxGroupByRow implements RowType {
         return children;
     }
 
+    /**
+     * Returns the view index calculated per the grid page.
+     */
+    public get viewIndex(): number {
+        if (this.grid.groupingExpressions.length) {
+            const firstRowGroupInd = this.grid.groupingFlatResult.indexOf(this.grid.dataView[0]);
```
Comment (zdrawku) [inline projects/igniteui-angular/src/lib/grids/grid-public-row.ts:483]: As we saw, this index is not correct while testing with paging

**Review by zdrawku — CHANGES_REQUESTED** [review]

File: projects/igniteui-angular/src/lib/grids/grid-public-row.ts [hunk 2]
```diff
@@ -549,6 +584,34 @@ export class IgxSummaryRow implements RowType {
...
+                if (grid.groupingExpressions.length) {
+                    const firstRowGroupInd = grid.groupingFlatResult.indexOf(this.grid.dataView[0]);
+                    const precedingGroupedRecs = grid.groupingFlatResult.filter((r, ind) =>
+                        this.grid.isGroupByRecord(r) && ind < firstRowGroupInd);
+                        return firstRowGroupInd + precedingGroupedRecs.filter(gr => this.grid.isExpandedGroup(gr)).length + this.index;
+                }
+            } else if (this.grid instanceof IgxTreeGridComponent) {
+                const grid = this.grid as IgxTreeGridComponent;
+                if (grid.summaryCalculationMode !== GridSummaryCalculationMode.rootLevelOnly) {
+                    const firstRowIndex = grid.processedExpandedFlatData.indexOf(grid.dataView[0].data);
```
Comment (zdrawku) [inline projects/igniteui-angular/src/lib/grids/grid-public-row.ts:603]: Same as above applies to the TreeGrid as well, while using paging the returned index is incorrect. I have 7 rows (indexes from 0-6) on the first page (5 regular and 2 summary rows) and the viewIndex of the first row of page 2 should be with value 7, not 8

**Review by zdrawku — CHANGES_REQUESTED** [review]

**Review by zdrawku — CHANGES_REQUESTED** [review]
When we have a Detail View, its index is not considered on pagination.

Same applies for HierarchicalGrid as well.

**Review by zdrawku — APPROVED** [review]
