### PR TITLE
Fix IgxButton has incorrect CSS class when setting new type - 7.3.x

### LINKED ISSUE #5404: IgxButton: The type property setter does not work correctly
## Description
The IgxButtonDirective type property setter does not set a new CSS class but it appends the new CSS class.

 * igniteui-angular version: 7.3.x
 * browser: All

## Steps to reproduce  

1. Open dev demos

2. Edit the "button.sample.html" file, by adding the following to the first button:
"#firstButton (click)="buttonHandler($event)""

3. Edit the "button.sample.ts" file, by adding the following after the last field definition:
@ViewChild('firstButton', { read: IgxButtonDirective, static: true})
public aButton: IgxButtonDirective;

public buttonHandler(e) {
    this.aButton.type = 'outlined';
    // type can be one of these 'flat', 'raised', 'outlined', 'fab', 'icon'
}

4. Start dev demos and load the Button directive sample
5. Press the first button in the sample.
6. Inspect the same button in browser's dev tools

## Result  
After setting the type property to outlined the button's class is the following:
"igx-button--flat igx-button--outlined"
Also it does not looks like the other outlined buttons.

## Expected result  
The other buttons on the page with default type "outlined" have the following CSS class, which is the correct:
"igx-button--outlined"

### PR DESCRIPTION
**Pull request by rmkrmk**
Closes #5404

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/directives/button/button.directive.ts [hunk 1]
```diff
@@ -66,18 +76,26 @@ export class IgxButtonDirective extends DisplayDensityBase {
...
      * @memberof IgxButtonDirective
      */
-    @Input('igxButton') set type(value: string) {
-        this._type = value || this._type;
-        this._renderer.addClass(this.nativeElement, `${this._cssClass}--${this._type}`);
+    @Input('igxButton')
+    set type(value: string) {
+        const newValue = value ? value : this._defaultType;
+        if (this._type !== newValue) {
+            this._renderer.removeClass(this.nativeElement, `${this._cssClassPrefix}--${this._type}`);
```
Comment (DiyanDimitrov) [inline projects/igniteui-angular/src/lib/directives/button/button.directive.ts]: We should not remove the class if the old type is empty.

Comment (rmkrmk) [reply projects/igniteui-angular/src/lib/directives/button/button.directive.ts]: This will just try to remove it. If there is no such class it will just do nothing.
