### PR TITLE
fix(carousel): support for keyboard navigation #1139

### LINKED ISSUE #1139: Carousel: Arrow keys do not work consistently for swiping left/right the images.
### Description  
Arrow keys do not work consistently for swiping left/right the images. 

### Steps to reproduce  

1. Open a caroucel sample like: https://staging.infragistics.local/products/ignite-ui-angular/angular/components/carousel.html
2. Try navigating via the keyboard arrows left and right after interacting with the caroucel's image/arrows/navigation (if enabled)

### Result  
**In Chrome:** After clicking on the image, only the first navigation by arrow key swipes the image.
**In Edge/IE:** The images do not swipe no matter where the last user interaction was (click on the image, click on an arrow or the bottom nav)

### Expected result  
Arrow keys navigation should work in all above cases.

### PR DESCRIPTION
**Pull request by hanastasov**
Closes #1139

### CODE REVIEW

File: src/carousel/carousel.component.ts [hunk 1]
```diff
@@ -404,6 +405,16 @@ export class IgxCarouselComponent implements OnDestroy {
             }, this.interval);
         }
     }
+
+    @HostListener("keydown.arrowright", ["$event"])
+    public onKeydownArrowRight(event) {
```
Comment (Aleksandyr) [inline src/carousel/carousel.component.ts]: I think that the event parameter is unnecessary here. Respectively the passage of the argument through the HostListener too.

File: src/carousel/carousel.component.ts [hunk 2]
```diff
@@ -404,6 +405,16 @@ export class IgxCarouselComponent implements OnDestroy {
...
+        this.next();
+    }
+
+    @HostListener("keydown.arrowleft", ["$event"])
+    public onKeydownArrowLeft(event) {
```
Comment (Aleksandyr) [inline src/carousel/carousel.component.ts]: I think that the event parameter is unnecessary here. Respectively the passage of the argument through the HostListener too.
