### PR TITLE
fix(migrations): resolve package for checks in seperate process #8254

### LINKED ISSUE #8254: Migrating templates with UpdateChanges does not work if @angular/language-service is not installed
## Description  
The new functionality https://github.com/IgniteUI/igniteui-angular/issues/7966 for UpdateChanges allows the modification of `ts` and `html` files with the  `members.json` migration. This adds a potential dependency requirement - `@angular/language-service` to `igniteui-angular`.

## To consider
We can either add the dependency or create an install task that silently (`--no-save`) installs the `@angular/language-service` before running the migrations. After all migrations have completed, we could again run a task that uninstalls it.

### PR DESCRIPTION
**Pull request by damyanpetev**
This prevents our check from caching the package json result
which will prevent the package from loading correctly after install

Closes #8254  

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/migrations/common/ServerHost.ts [hunk 1]
```diff
@@ -75,6 +75,7 @@ export class ServerHost implements ts.server.ServerHost {
         try {
             const paths = [initialPath];
             if (moduleName === CUSTOM_TS_PLUGIN_NAME) {
+                moduleName = CUSTOM_TS_PLUGIN_PATH;
```
Comment (jackofdiamond5) [inline projects/igniteui-angular/migrations/common/ServerHost.ts:78]: 👀

**Review by jackofdiamond5 — APPROVED** [review]
