### PR TITLE
fix(GroupBy): Fix error thrown when expanding a groupby row. 

### LINKED ISSUE #4179: Expanding a group row while at the bottom of the grid throws error
## Description  
Error is thrown when having two collapsed group rows at the bottom and we try to expand the upper one.

 * igniteui-angular version: 7.2.x
 * browser: All

## Steps to reproduce  

1. Run the Grid Search sample.
2. Group by `Contact Title` column.
3. Scroll to the bottom of the grid using mouse wheel.
4. Collapse `Sales Representative` group.
5. Collapse `Sales Manager` group.
6. Expand the `Sales Manager` group.

**Note**: There are other scenarios that this is reproduced by also expanding while having collapsed groups, but this seems to be the one of the more consistent scenarios.

## Result  
The following error is thrown:
ERROR TypeError: Cannot read property 'forEach' of undefined

## Expected result  
There should be no error thrown.

### PR DESCRIPTION
**Pull request by skrustev**
Closes #4179

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/grid-base.component.ts [hunk 1]
```diff
@@ -4856,14 +4856,14 @@ export abstract class IgxGridBaseComponent extends DisplayDensityBase implements
         if (args.context['templateID'] === 'dataRow' && args.context['$implicit'] === args.oldContext['$implicit']) {
             args.view.detectChanges();
             const row = this.getRowByIndex(args.context.index);
-            if (row) {
+            if (row && row instanceof IgxRowComponent) {
```
Comment (DiyanDimitrov) [inline projects/igniteui-angular/src/lib/grids/grid-base.component.ts]: The reason for this issue is that we have a groupBy row and a grid row with the same index. We have to search only in the `dataRowList` like this:
`const row = this.dataRowList.find((r) => r.index === args.context.index);`

Comment (DiyanDimitrov) [reply projects/igniteui-angular/src/lib/grids/grid-base.component.ts]: Also I have noticed that there is no test added for this scenario. It would be nice if we have such.

Comment (skrustev) [reply projects/igniteui-angular/src/lib/grids/grid-base.component.ts]: Well yes, this is the other way that could be fixed. I can change it.
There is already a test that covers this that for some was passing.

Comment (DiyanDimitrov) [reply projects/igniteui-angular/src/lib/grids/grid-base.component.ts]: It looks ok, but I was thinking if a similar issue comes up with the horizontal scrolling. It would be better to fix the row finding there as well.

Comment (skrustev) [reply projects/igniteui-angular/src/lib/grids/grid-base.component.ts]: There is no issue for the horizontal scrolling because there is basically the same check I used earlier that covers these scenarios instead of parsing the dataRowList directly. Either way will work.
