### PR TITLE
Filter grid correctly with case insensitive duplicate records - 18.2.x

### LINKED ISSUE #14906: Excel style filtering is not working correctly with lower/upper case values
## Description  
Excel style filtering is not working correctly with lower/upper case values when more than 2 values are selected

 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Open this [sample](https://codesandbox.io/p/devbox/weathered-forest-hfhkks)
2. Open the excel style dialog for column 'field2'
3. Enter 'Harald_' into the Search field
4. Press 'Apply'

## Result  
'Harald_a1' value is missing and 'Harald_A1' is displayed

## Expected result  
'Harald_a1' and 'Harald_A1' values should be displayed

## Attachments
grid-excel-style-filter

### PR DESCRIPTION
**Pull request by MonikaKirkova**
Closes #14906 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/data-operations/filtering-condition.ts [hunk 1]
```diff
@@ -60,8 +60,9 @@ export class IgxFilteringOperand {
     /**
      * @hidden
      */
-    protected findValueInSet(target: any, searchVal: Set<any>) {
-        return searchVal.has(target);
+    protected findValueInSet(target: any, searchVal: Set<any>, ignoreCase?: boolean) {
```
Comment (gedinakova) [inline projects/igniteui-angular/src/lib/data-operations/filtering-condition.ts:63]: This would convert non-string data types to strings as well. I don't think it is a good idea to change the most basic logic for all filtering operands' findValueInSet() method in order to address a very concrete scenario possibly in the ESF only. Please revisit the approach.

**Review by gedinakova — CHANGES_REQUESTED** [review]

**Review by gedinakova — APPROVED** [review]
