### PR TITLE
 fix(hgrid): Expose onGridInitialized output #6860

### LINKED ISSUE #6860: Using onGridCreated on a row island throws an error
## Description  
When the `onGridCreated` event is used for a given child row and when `detectChanges` is called on the event's grid, multiple errors are thrown (see attached image).

The most common usecase of `onGridCreated` concerns the load on demand feature, which suggests using an http request (or a similar task). The execution of that request may require some time and is going to be resolved in a different event loop. When the user decides not to use any requests (and promises), the event's grid seems to be not yet registered and one has to create a new macrotask by themselves, as for instance `setTimeout`, which works as a proper workaround of the issue.

The upmentioned behavior could be observed in the following sample:
https://stackblitz.com/edit/bug-igx-hierarchical-grid-shachm,
while the workaround with `setTimeout` is to be found here:
https://stackblitz.com/edit/bug-igx-hierarchical-grid-d1rxf9

## Attachments
image

### PR DESCRIPTION
**Pull request by dkamburov**
Closes #6860

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by MayaKirova** [comment]
@dkamburov 
It seems that the additional change detection fully initializes the child grid before triggering the onGridCreated event so now if you try to subscribe to an initialization event like the onColumnInit:
event.grid.onColumnInit.subscribe(x => console.log('emitted'));
It will never fire.

**Comment by MayaKirova** [comment]
@dkamburov You could force the child grid to register in its API service instead of calling detect changes, for example:

        this.hGrid._setupServices();
        this.layout.onGridCreated.emit({
            owner: this.layout,
            parentID: this.rowData.rowID,
            grid: this.hGrid
        });

This should ensure the grid registered before the event is emitted.

File: projects/igniteui-angular/src/lib/grids/hierarchical-grid/row-island.component.ts [hunk 1]
```diff
@@ -138,6 +138,20 @@ export class IgxRowIslandComponent extends IgxHierarchicalGridBaseDirective
     @Output()
     public onGridCreated = new EventEmitter<IGridCreatedEventArgs>();
 
+    /**
```
Comment (MayaKirova) [inline projects/igniteui-angular/src/lib/grids/hierarchical-grid/row-island.component.ts:141]: Description and code snippet should be updated to match what is added in the ReadMe.
