### PR TITLE
fix(column): use minWidth when sizing columns - master

### LINKED ISSUE #16057: `minWidth` doesn't override the default 136px min width when autosizing columns without width
## Description  
In a grid with columns that don't have width set, the width defaults to 136px with the property `minWidth` that should affect this (by spec) not having any effect.

 * igniteui-angular version: latest
 * browser: n/a

## Steps to reproduce  

1. Open https://stackblitz.com/edit/d37qt97a-gqnfqw6y 
2. Observe the column widths of columns after the first one

## Result  
The columns disregard the min width and render at the default width of 136px

## Expected result  
The columns to render at the specified minWidth of 44px (as they are overflowing the container anyway, even at 44px)

### PR DESCRIPTION
**Pull request by RivaIvanova**
Closes #16057  

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/columns/column.component.ts [hunk 1]
```diff
@@ -1012,6 +1012,7 @@ export class IgxColumnComponent implements AfterContentInit, OnDestroy, ColumnTy
             return;
         }
         this._defaultMinWidth = value;
+        this.minWidthSetByUser = true;
```
Comment (MayaKirova) [inline projects/igniteui-angular/src/lib/grids/columns/column.component.ts]: I don't think you need an additional prop, since we already have the getter for `userSetMinWidthPx` that returns the user set min width (if there is one). You could directly use that.

File: projects/igniteui-angular/src/lib/grids/grid-base.directive.ts [hunk 2]
```diff
@@ -8008,4 +8010,16 @@ export abstract class IgxGridBaseDirective implements GridType,
...
         this._rowCount += 1; // include header row
     }
+
+    private setPossibleMinColumnWidth(column: IgxColumnComponent): void {
+        if (this.columnWidthSetByUser || this.width == null) {
+            return;
+        }
+
+        if (column.minWidthSetByUser || column.hidden) {
+            this._columnWidth = this._possibleColumnWidth;
```
Comment (MayaKirova) [inline projects/igniteui-angular/src/lib/grids/grid-base.directive.ts]: I don't see why the default width of the columns on the grid level (associated with the `columnWidth` prop) would change based on the individual props on each column. That should be constant and apply for all columns, regardless of whether any of them have individual min-widths.

File: projects/igniteui-angular/src/lib/grids/grid-base.directive.ts [hunk 3]
```diff
@@ -5534,8 +5535,8 @@ export abstract class IgxGridBaseDirective implements GridType,
         computedWidth -= this.featureColumnsWidth();
 
         const columnWidth = !Number.isFinite(sumExistingWidths) ?
-            Math.max(computedWidth / columnsToSize, this.minColumnWidth) :
-            Math.max((computedWidth - sumExistingWidths) / columnsToSize, this.minColumnWidth);
+            Math.max(computedWidth / columnsToSize, this.defaultHeaderGroupMinWidth) :
```
Comment (MayaKirova) [inline projects/igniteui-angular/src/lib/grids/grid-base.directive.ts]: `defaultHeaderGroupMinWidth` is a property we intent to remove, since it's a hardcoded left-over from the display density property deprecation. I'd prefer if we don't use it anymore.

File: projects/igniteui-angular/src/lib/grids/columns/column.component.ts [hunk 4]
```diff
@@ -2699,4 +2706,26 @@ export class IgxColumnComponent implements AfterContentInit, OnDestroy, ColumnTy
...
+     * @hidden
+     */
+    public set minWidthSetByUser(value: boolean) {
+        this._minWidthSetByUser = value;
+    }
+
+    /**
+     * @hidden
+     */
+    public get minWidthSetByUser(): boolean {
```
Comment (MayaKirova) [inline projects/igniteui-angular/src/lib/grids/columns/column.component.ts]: Probably don't need this getter and setter.

File: projects/igniteui-angular/src/lib/grids/columns/column.component.ts [hunk 5]
```diff
@@ -2699,4 +2706,26 @@ export class IgxColumnComponent implements AfterContentInit, OnDestroy, ColumnTy
...
+        return this._minWidthSetByUser;
+    }
+
+    private getPossibeWidth(): string {
+        const possibleWidth = this.grid.getPossibleColumnWidth();
+        if (!this.minWidthSetByUser && parseFloat(possibleWidth) < this.grid.minColumnWidth) {
```
Comment (MayaKirova) [inline projects/igniteui-angular/src/lib/grids/columns/column.component.ts]: Can check `userSetMinWidthPx` instead.

**Review by MayaKirova — APPROVED** [review]

**Review by ChronosSF — APPROVED** [review]
