### PR TITLE
Aria grid errors

### LINKED ISSUE #7037: Scan with Accessibility Insights for Web reports issues with igx-grid
## Description  
FastPass with  "Accessibility Insights for Web" tool  reports issues related to igx-grid.

AIWReport

This sample has Paging feature enabled. However, I believe that issues will be present for other features as well.
 * igniteui-angular version: 9.0
 * browser: Chrome

## Steps to reproduce  

1. Enable [Accessibility Insights for Web](https://chrome.google.com/webstore/detail/accessibility-insights-fo/pbjjkligggfmakdaogkfomddhfmpjeni?hl=en) in Chrome
2. Run the attached sample in Chrome.
3. Click this button 
Capturhhhe
 and select "FastPass" in order to run a scan.
4. Observe the results
## Result  
Capture
If expanded every section gives additional information - Path, Snippet and How to fix. For example:
Capppture

## Expected result  
The "FastPass" to run without failed instances.

## Attachments  

[grid-paging.zip](https://github.com/IgniteUI/igniteui-angular/files/4416246/grid-paging.zip)

### PR DESCRIPTION
**Pull request by zdrawku**
Closes #7037 

Changes:
- Added tooltips for paginator action buttons along with i18n properties
- `thead` role="rowGroup" to the igx-grid. Already fixed in hierarchical grid and tree grid
- Added `igx-grid-summary-row` and `igx-grid-summary-cell` roles 
- `aria-disabled` to the disabled paginator buttons along with small refactoring 

### Additional information (check all that apply):
 - [x] Bug fix
 - [x] New functionality
 - [x] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [x] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [x] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/paginator/paginator.component.ts [hunk 1]
```diff
@@ -177,6 +178,38 @@ export class IgxPaginatorComponent extends DisplayDensityBase {
...
+   public lastPageLabel = CurrentResourceStrings.PaginatorResStrings.igx_paginator_last_page_button_text;
+
+   /**
+    * An @Input property, sets a tooltip text for the next page button label
+    * The default is 'Next page' localized string.
+    * @memberof IgxPaginatorComponent
+    */
+   @Input()
+   public nextPageLabel = CurrentResourceStrings.PaginatorResStrings.igx_paginator_next_page_button_text;
+
```
Comment (ddincheva) [inline projects/igniteui-angular/src/lib/paginator/paginator.component.ts:212]: In order to be consistent with the other components in the library, can you please expose a single property, to store all the necessary resource strings , rather to provide a 5 separate properties. You can see the igx-Carousel componet as a reference:
```
    @Input()
    set resourceStrings(value: IPaginatorResourceStrings) {
        this._resourceStrings = Object.assign({}, this._resourceStrings, value);
    }

    get resourceStrings(): IPaginatorResourceStrings{
        return this._resourceStrings;
    }
```
