### PR TITLE
fix(chip): improve accessibility

### LINKED ISSUE #8935: a11y: Improve chip accessibility
## Description  
Provide an accessible experience for igx-checkbox.

1. Add role="listbox" to the chip area
2. Add role="option"  to the chip
3. Add aria-label that describes the icon action for the remove icon.

## Attachments  
Attach a sample if available, and screenshots, if applicable.

### PR DESCRIPTION
**Pull request by SisIvanova**
Closes #8935 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/chips/chips-area.component.ts [hunk 1]
```diff
@@ -84,6 +84,17 @@ export class IgxChipsAreaComponent implements DoCheck, AfterViewInit, OnDestroy
...
+     * Returns the `role` attribute of the chips area.
+     *
+     * @example
+     * ```typescript
+     * let chipsAreaRole = this.chipsArea.role;
+     * ```
+     */
+     @HostBinding('attr.role')
+     public role = 'listbox';
+
```
Comment (simeonoff) [inline projects/igniteui-angular/src/lib/chips/chips-area.component.ts:97]: I think we also need to add a default `aria-label` as this is a `listbox`;

**Review by simeonoff — COMMENTED** [review]
I think we also need to add a default aria-label to the chip area as it has `listbox` as role.

File: projects/igniteui-angular/src/lib/chips/chips-area.component.ts [hunk 2]
```diff
@@ -95,6 +95,18 @@ export class IgxChipsAreaComponent implements DoCheck, AfterViewInit, OnDestroy
...
+     * Returns the `aria-label` attribute of the chips area.
+     *
+     * @example
+     * ```typescript
+     * let ariaLabel = this.chipsArea.ariaLabel;
+     * ```
+     *
+     */
+     @HostBinding('attr.aria-label')
+     public ariaLabel = 'chips-area';
```
Comment (simeonoff) [inline projects/igniteui-angular/src/lib/chips/chips-area.component.ts:108]:
```suggestion
     public ariaLabel = 'chip area';
```

**Review by simeonoff — COMMENTED** [review]
Remove the dash, otherwise the screen readers will pronounce it and it will sound strange.

**Review by simeonoff — APPROVED** [review]
