### PR TITLE
Close filter condition dropdownon on tab key pressed

### LINKED ISSUE #4612: Filter condition dropdown is not closed on tab navigation
## Description  
Filter condition dropdown is not closed on tab navigation.

 * igniteui-angular version: 7.2.x
 * browser: NA

## Steps to reproduce  

1. Open the "Grid Search" dev demo.
2. Scroll the grid horizontally to the last column - "Contract".
3. Click the "Filter" chip of the "Contract" column.
4. Open the filter condition dropdown.
5. Press tab several times until the first cell in the grid is focused.

## Result  
When navigating the first grid cell the dropdown closes and the cell loses focus.

## Expected result  
The dropdown should be closed when the focus is moved out of the input group and the first grid cell should stay focused when navigated.

### PR DESCRIPTION
**Pull request by nrobakova**
Closes #4612  

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts [hunk 1]
```diff
@@ -234,12 +237,9 @@ export class IgxGridFilteringRowComponent implements AfterViewInit {
         this.isKeyPressed = true;
 
         if (this.column.dataType === DataType.Boolean) {
-            if ((event.key === KEYS.ENTER || event.key === KEYS.SPACE || event.key === KEYS.SPACE_IE) &&
-            this.dropDownConditions.collapsed) {
-                this.toggleConditionsDropDown(this.inputGroupPrefix.nativeElement);
-                event.stopPropagation();
-                return;
-            } else if ((event.key === KEYS.ESCAPE || event.key === KEYS.ESCAPE_IE) && !this.dropDownConditions.collapsed) {
```
Comment (bkulov) [inline projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts]: Why we're not handling Esc key anymore? That way pressing the Esc key will directly close the filtering row instead of closing the dropdown.

Comment (nrobakova) [reply projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts]: With my changes when dataType is Boolean and click on input or press Enter/Space the focus is moved to the dropdown. If we change the focus of drop down(for example click on input or click tab key) it will be closed so we do not need this check.
