### PR TITLE
Derive possible heights after markForCheck() is called #3467

### LINKED ISSUE #3467: IgxTreeGrid does not respect its parent container height
* igniteui-angular version:  7.1.0

### Steps to reproduce  

1. Go to https://stackblitz.com/angular/ymaoxnveolm
(you can use the treegris FinjS demo as it is populated with thousands of records)

### Result  
- Grid takes the whole available height, not regarding its parent container height
- if the grid has large data, it will expand its size for every row that comes, thus resulting in very bad performance when large data sets are loaded

### Expected result  TreeGrid to respect its parent container height

### PR DESCRIPTION
**Pull request by hanastasov**
Closes #3467 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/grid-base.component.ts [hunk 1]
```diff
@@ -2295,15 +2295,16 @@ export abstract class IgxGridBaseComponent extends DisplayDensityBase implements
      * @hidden
      */
     public ngAfterContentInit() {
+        this._pipeTrigger++;
```
Comment (DiyanDimitrov) [inline projects/igniteui-angular/src/lib/grids/grid-base.component.ts]: This line of code is not needed.
