### PR TITLE
fix(igxInput): #3550 Setting required input value updates valid state.

### LINKED ISSUE #3550: Setting required IgxInput's value not via typing does not clear the invalid style.
### Description  
Setting required IgxInput's value by updating the bound property would not clear the invalid (red) style class from the input.

 * igniteui-angular version: all
 * browser: N/A

### Steps to reproduce  

1. Run the attached sample
2. Click in the input then click outside > the input turns red because it's a required field
3. Click the button 

### Result  
The input's value is populated but the invalid style remains applied.

### Expected result  
Setting a valid value in any way should clear the invalid style.

### Attachments  

[InputValueSample.zip](https://github.com/IgniteUI/igniteui-angular/files/2740734/InputValueSample.zip)

### PR DESCRIPTION
**Pull request by gedinakova**
Closes #3550   

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/directives/input/input.directive.ts [hunk 1]
```diff
@@ -52,6 +52,9 @@ export class IgxInputDirective implements AfterViewInit, OnDestroy {
     @Input('value')
     set value(value: any) {
         this.nativeElement.value = value;
+        if (!this.ngControl && this._hasValidators) {
```
Comment (rkaraivanov) [inline projects/igniteui-angular/src/lib/directives/input/input.directive.ts]: This piece of code is repeated again in the [input event handler](https://github.com/IgniteUI/igniteui-angular/pull/3564/files#diff-6f41a12bd84d5e6d3bad3cad109e10c3R150) Can we abstract it away, say as `checkValidity()` that returns an `IgxInputState` rather than copy it as it is?
