### PR TITLE
fix(*): lint warnings

### LINKED ISSUE #8882: ESLint: Fix warnings for DT-owned components
List of components to fix:

- [x] Avatar Component - @SisIvanova 
- [x] Badge Component - @SisIvanova 
- [x] Button Directive - @SisIvanova 
- [x] Button Group Component - @simeonoff 
- [x] Card Component - @SisIvanova 
- [x] Checkbox Component - @simeonoff 
- [x] Icon Component - @SisIvanova 
- [x] Layout Directive - @SisIvanova 
- [x] Radio Group Directive - @simeonoff 
- [x] Ripple Directive - @SisIvanova 
- [x] Snackbar Component - @simeonoff 
- [x] Switch Component - @simeonoff 
- [x] Toast Component - @simeonoff

### PR DESCRIPTION
**Pull request by SisIvanova**
Closes #8882  

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [x] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/card/card.component.ts [hunk 1]
```diff
@@ -348,15 +348,15 @@ export class IgxCardActionsComponent implements OnInit, OnChanges {
 
     constructor(@Optional() @Inject(IgxCardComponent) public card: IgxCardComponent) { }
 
-    ngOnChanges(changes: SimpleChanges) {
+    public ngOnChanges(changes: SimpleChanges) {
```
Comment (simeonoff) [inline projects/igniteui-angular/src/lib/card/card.component.ts:351]: This should also be marked as hidden and internal

File: projects/igniteui-angular/src/lib/card/card.component.ts [hunk 2]
```diff
@@ -348,15 +348,15 @@ export class IgxCardActionsComponent implements OnInit, OnChanges {
...
         for (const prop in changes) {
             if (prop === 'vertical') {
                 this.isVerticalSet = true;
             }
         }
     }
 
-    ngOnInit() {
+    public ngOnInit() {
```
Comment (simeonoff) [inline projects/igniteui-angular/src/lib/card/card.component.ts:359]: as well as this one

**Review by simeonoff — CHANGES_REQUESTED** [review]

**Review by simeonoff — APPROVED** [review]
