### PR TITLE
fix(icon): Deferred icon loading with OnPush

### LINKED ISSUE #7024: igx-icon problems when using SVG and OnPush
## Description  
When using OnPush I can't see the icons until some change occurs in the component that is using them.

 * igniteui-angular version: 9.0.1
 * browser: FF & Chrome (any afaik)

## Steps to reproduce  

Example at: https://stackblitz.com/edit/igx-icon-onpush
 - Start from igx-icon + svg sample  (works)
 - Use changeDetection OnPush (stops working)
 - Move icons initialization code to App constructor, still not working.

## Result  
Can't see the igx-icon instances

## Expected result  
Icons should load

### PR DESCRIPTION
**Pull request by rkaraivanov**
The icon service exposes a new event when loading icons.
The icons are now subscribed to it and run local change detection when
needed.

Closes #7024

### Additional information (check all that apply):
 - [x] Bug fix
 - [x] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/icon/icon.component.ts [hunk 1]
```diff
@@ -120,10 +120,15 @@ export class IgxIconComponent implements OnInit {
...
 
-    constructor(private _el: ElementRef, private iconService: IgxIconService) {
+    constructor(
+            private _el: ElementRef,
+            private iconService: IgxIconService,
+            private ref: ChangeDetectorRef) {
         this.el = _el;
         this.font = this.iconService.defaultFontSet;
         this.iconService.registerFontSetAlias('material', 'material-icons');
+        this.iconService.iconLoaded.pipe(first(e => e.name === this.iconName && e.fontSet === this.font))
```
Comment (damyanpetev) [inline projects/igniteui-angular/src/lib/icon/icon.component.ts:130]: There's a chance this subscription won't be fulfilled if the svg fails to load or something. Or maybe the icon doesn't have name set even. Shouldn't we make sure the subscription is disposed either way?

Comment (rkaraivanov) [reply projects/igniteui-angular/src/lib/icon/icon.component.ts:130]: Good catch!
