### PR TITLE
Close igxSelect on Shift+Tab keys

### LINKED ISSUE #4164: IgxSelect does not close on Shift+Tab
## Description  
When IgxSelect is active and items list is opened if you press Tab key drop down closes. This is ok. However if IgxSelect is active and items list is opened, if you press Shift+Tab keys drop down does not close

 * igniteui-angular version: 7.2.x
 * browser: all

## Steps to reproduce  

1. Go to Select demo.
2. Click on select to open it.
3. Press Shift+Tab key combination.

## Result  
Select's items list does not close.

## Expected result  
Select's items list should close as it does on Tab key press.

## Attachments  
Attach a sample if available, and screenshots, if applicable.

### PR DESCRIPTION
**Pull request by IvayloG**
Closes  #4164

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/select/select-navigation.directive.ts [hunk 1]
```diff
@@ -53,7 +53,7 @@ export class IgxSelectItemNavigationDirective extends IgxDropDownItemNavigationD
             }
         }
 
-        if (!this.target.collapsed && (key === 'tab')) {
+        if (!this.target.collapsed && (key === 'tab' || (event.shiftKey && key === 'tab'))) {
```
Comment (damyanpetev) [inline projects/igniteui-angular/src/lib/select/select-navigation.directive.ts]: So either a tab (with or w/o shift) or a tab w/ shift? Isn't it all the same then?

File: projects/igniteui-angular/src/lib/select/select.component.ts [hunk 2]
```diff
@@ -269,7 +269,6 @@ export class IgxSelectComponent extends IgxDropDownComponent implements IgxSelec
     ngAfterContentInit() {
         this._overlayDefaults = {
             modal: false,
-            closeOnOutsideClick: true,
```
Comment (damyanpetev) [inline projects/igniteui-angular/src/lib/select/select.component.ts]: This should be explicit false though, as the default settings of the underlying overlay service have that enabled.

File: projects/igniteui-angular/src/lib/select/select-navigation.directive.ts [hunk 3]
```diff
@@ -17,11 +17,11 @@ export class IgxSelectItemNavigationDirective extends IgxDropDownItemNavigationD
 
     /** Captures keydown events and calls the appropriate handlers on the target component */
     handleKeyDown(event: KeyboardEvent) {
-        if (!event || event.shiftKey) {
```
Comment (damyanpetev) [inline projects/igniteui-angular/src/lib/select/select-navigation.directive.ts]: Was the shift here excluded for a reason before?

Comment (IvayloG) [reply projects/igniteui-angular/src/lib/select/select-navigation.directive.ts]: If the Shift check is present, it will not allow to navigate (when collapsed) through the items pressing Shift + Up/Down arrow keys. I prefer to revert this, as we have never specified it is possible to use Shift + Up/Down arrow keys for this interaction (Currently, the user can navigate and select list items with up and down arrow keys.).

**Comment by IvayloG** [comment]
@damyanpetev Can you check the requested changes?
