### PR TITLE
fix(tabs): Fixed selectedIndex run-time change #4245

### LINKED ISSUE #4245: selectedIndex doesn't switch tab.
## Description  
Programmatically setting selected tab index via selectedIndex property doesn't update UI. 

 * igniteui-angular version: 7.2.0
 * browser: Google Chrome

## Steps to reproduce  

1. Run sample (npm install, npm start)
2. Click Play button

## Result  
The favorites (middle) tab does not become selected 

## Expected result  
The favorites (middle) tab becomes selected. 

## Attachments  
See attachment. See screenshot illustrating that the newly selectedtabitem is Favorites although the UI isn't refreshed. 
[tab-demo-app.zip](https://github.com/IgniteUI/igniteui-angular/files/2947282/tab-demo-app.zip)

igxtabIssue

### PR DESCRIPTION
**Pull request by sboykova**
Closes #4245

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/tabs/tabs.component.ts [hunk 1]
```diff
@@ -279,7 +279,18 @@ export class IgxTabsComponent implements IgxTabsBase, AfterViewInit, OnDestroy {
         }
     }
 
-    private resetSelectionOnCollectionChanged() {
+    private setSelectedGroup(): void {
+        requestAnimationFrame(() => {
```
Comment (bkulov) [inline projects/igniteui-angular/src/lib/tabs/tabs.component.ts]: Is there a reason why we need to always set selection in animation frame? I saw a couple more `setTimeout` methods in this file. Do we really need those?

Comment (sboykova) [reply projects/igniteui-angular/src/lib/tabs/tabs.component.ts]: Yes, we need requestAnimationFrame here in order to have all content rendered before selecting a group.
