### PR TITLE
fix(excel-export): sucessfully export hgrid with skipped columns

### LINKED ISSUE #10257: IgxHierarchicalGrid Excel Exporter: including header of a canceled columnExporting column and misaligning data
## Description  
When exporting an IgxHierarchicalGrid to Excel and canceling the export of columns (for child grids), their headers are still exported, while the data is shifted and therefore misaligned:

Original grid:

hgrid

Exported grid. The canceled-to-export columns are "Debut" from parent level and "Billboard Review" of child grid:

exported-hgrid

 * igniteui-angular version: 11.1.x, 12.1.x, 
 * browser: any

## Steps to reproduce  

1. Open [this ](https://stackblitz.com/edit/igxhierarchicalgrid-excel-export-exclude-columns?file=src%2Fapp%2Fgrid%2Fhierarchical-grid-excel-export%2Fhierarchical-grid-excel-export.component.html)sample
2. Export the grid to Excel
3. Open the Excel file and epand the first row

## Result  
See above attached pictures.
[Here ](https://stackblitz.com/edit/igxhierarchicalgrid-excel-export-exclude-columns-erbxzr?file=src/app/grid/hierarchical-grid-excel-export/hierarchical-grid-excel-export.component.ts)is a sample with version 11.1.26, where the same occurs for the top-level grid as well.

## Expected result  
Not to include the columns, whose export is canceled.

### PR DESCRIPTION
**Pull request by onlyexeption**
Closes #10257

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/services/exporter-common/base-export-service.ts [hunk 1]
```diff
@@ -344,35 +356,72 @@ export abstract class IgxBaseExporter {
...
+            if (targetCol.columnGroupParent !== null) {
+                this.calculateColumnSpans(targetCol, mapRecord, span);
+            }
+
+            if (targetCol.columnSpan === 0) {
+                targetCol.skip = true;
+            }
+        }
+    }
+
```
Comment (gedinakova) [inline projects/igniteui-angular/src/lib/services/exporter-common/base-export-service.ts:389]: The behavior seems OK now. I suggest a little optimization of the code as follows:
```suggestion
    /** Update column spans of parent columns & skip child columns exporting. */
    private calculateColumnSpans(column: IColumnInfo, mapRecord: IColumnList, span: number) {
        if (column.columnGroupParent !== null) {
            const parentCol = mapRecord.columns.filter(c => c.columnGroup === column.columnGroupParent)[0];
            this.calculateColumnSpans(parentCol, mapRecord, span);
        }

        if (column.columnGroup && column.skip) {
            this.skipAllChildColumns(column, mapRecord);
        }

        column.columnSpan -= span;
    }

    /** Recursively skip all child columns of a group column. */
    private skipAllChildColumns(column: IColumnInfo, mapRecord: IColumnList) {
        const children = mapRecord.columns.filter(c => c.columnGroupParent === column.columnGroup);
        children.forEach(c => {
            c.skip = true;
            if (c.columnGroup) this.skipAllChildColumns(c, mapRecord);
        });
    }
```

**Review by gedinakova — CHANGES_REQUESTED** [review]

**Review by gedinakova — APPROVED** [review]
