### PR TITLE
fix(HierarchicalGrid): Fix and test for #4239. Update parent grid vir…

### LINKED ISSUE #4239: When child grids does not have set height and expand a row in child grid scrollbars are not updated and there is empty space on the grid
## Description  
When child grids does not have set height and expand a row in child grid scrollbars are not updated and there is empty space on the grid

 * igniteui-angular version: 7.2
 * browser: N/A

## Steps to reproduce  

1. Open https://stackblitz.com/edit/angular-nwupfn-uty1cd?file=src/app/hierarchical-grid/hierarchical-grid-display-density/hierarchical-grid-density.component.html
2. Scroll down to the last row
3. Expand it
4. Expand child row
5. Look at the 3th level grid

## Result  
On step 4 the scroll is not updated. After move scroll in the child grid there is an empty space

## Expected result  
The grids should not have empty space and the scrollbars should be updated

## Attachments  
image

image

### PR DESCRIPTION
**Pull request by MayaKirova**
…tualization sizes and scrollbar when nested child with no height is expanded.

Closes #4239

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts [hunk 1]
```diff
@@ -116,7 +116,17 @@ export class IgxHierarchicalGridComponent extends IgxHierarchicalGridBaseCompone
     * @memberof IgxHierarchicalGridComponent
     */
     @Input()
-    public hierarchicalState: HierarchicalStateRecord[] = [];
+    public get hierarchicalState() {
+        return this._hierarchicalState;
+    }
+    public set hierarchicalState(val) {
+        this._hierarchicalState = val;
+        if (this.parent) {
```
Comment (skrustev) [inline projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts]: Shouldn't this apply only when height is not set?

**Comment by MartinKamenov** [comment]
@mpavlinov @MayaKirova 
After 3rd level of last parent row is expanded in the attached sample the space on the bottom of the child grid is still visible.
This should be resolved after [this pr](https://github.com/IgniteUI/igniteui-angular/pull/3972) is merged, since the space is produced by the sample's configuration which doesn't set explicitly the heights of the child grids.
emptyafterhGrid

**Comment by mpavlinov** [comment]
@MartinKamenov Yes, this is already logged as another issue.
