### PR TITLE
Download a single file when exporting an empty grid to csv - 16.0.x

### LINKED ISSUE #13056: Export CSV - empty data
## Description  
When I try to  export a CSV file and the table is empty, it downloads two files:

`public exportDataToCsv(): void {
    this.csvExportService.export(this.grid, new IgxCsvExporterOptions('File', CsvFileTypes.CSV));
  } `

 * igniteui-angular version: 14.0.6
 * browser: 

## Steps to reproduce  
Export a file from an empty table

## Result  
Download 2 files

## Expected result  
Download one file

## Attachments  
image
image

### PR DESCRIPTION
**Pull request by georgianastasov**
Closes #13056  

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/services/csv/csv-exporter.ts [hunk 1]
```diff
@@ -75,7 +75,7 @@ export class IgxCsvExporterService extends IgxBaseExporter {
     }
 
     private exportFile(data: string, fileName: string, fileType: string): void {
-        const blob = new Blob(['\ufeff', data], { type: fileType });
+        const blob = new Blob(data ? ['\ufeff', data] : ['', data], { type: fileType });
```
Comment (onlyexeption) [inline projects/igniteui-angular/src/lib/services/csv/csv-exporter.ts:78]: you can use `[data ? '\ufeff' : '', data]`

File: projects/igniteui-angular/src/lib/services/csv/csv-exporter-grid.spec.ts [hunk 2]
```diff
@@ -11,7 +11,8 @@ import { IgxTreeGridComponent } from '../../grids/tree-grid/public_api';
 import { ReorderedColumnsComponent,
         GridIDNameJobTitleComponent,
         ProductsComponent,
-        ColumnsAddedOnInitComponent } from '../../test-utils/grid-samples.spec';
+        ColumnsAddedOnInitComponent, 
+        EmptyGridComponent} from '../../test-utils/grid-samples.spec';
```
Comment (onlyexeption) [inline projects/igniteui-angular/src/lib/services/csv/csv-exporter-grid.spec.ts:15]: add a space after the closing brace

**Review by onlyexeption — APPROVED** [review]
