### PR TITLE
Use new schematics API

### LINKED ISSUE #8850: ng add igniteui-angular throws error
## Description  
**ng add igniteui-angular** throws follwoing error:
An unhandled exception occurred: 
Cannot find **module '@schematics/angular/utility/config'**
Require stack:
_C:\TEST\dell\node_modules\igniteui-angular\schematics\utils\dependency-handler.js
C:\TEST\dell\node_modules\igniteui-angular\schematics\ng-add\index.js
C:\TEST\dell\node_modules\@angular-devkit\schematics\tools\export-ref.js
C:\TEST\dell\node_modules\@angular-devkit\schematics\tools\index.js
C:\TEST\dell\node_modules\@angular\cli\utilities\json-schema.js
C:\TEST\dell\node_modules\@angular\cli\models\command-runner.js
C:\TEST\dell\node_modules\@angular\cli\lib\cli\index.js
C:\Users\IGanchev\AppData\Roaming\npm\node_modules\@angular\cli\lib\init.js
C:\Users\IGanchev\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng_

 * igniteui-angular version: **11.0.12**
 
**Environment:**
@angular-devkit/architect       0.1101.1
@angular-devkit/build-angular   0.1101.1
@angular-devkit/core            11.1.1
@angular-devkit/schematics      11.1.1
@angular/cli                    11.1.1
@schematics/angular             11.1.1
@schematics/update              0.1101.1
rxjs                            6.6.3
typescript                      4.1.3

## Steps to reproduce  

1. create a new angular CLI project --> **ng new testApp**
2. navigate to the testApp folder and run -->  **ng add igniteui-angular**

## Result  
An error ocurs:
image

## Expected result  
No errors

## Attachments  
Attach a sample if available, and screenshots, if applicable.

### PR DESCRIPTION
**Pull request by IvayloG**
Closes #8850

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/schematics/ng-add/index.ts [hunk 1]
```diff
@@ -49,40 +39,46 @@ const enableWebAnimationsAndGridSupport = (tree: Tree, targetFile: string, polyf
...
+      const build = project.targets.get('build');
+      let polyfillsData = tree.read(polyfillsFile).toString();
+      if (build.options[targetProperty] !== undefined) {
         // If project targets angular cli version >= 7.3
-        workspace.projects[workspace.defaultProject].architect.build.options[targetProperty] = true;
+        build.options[targetProperty] = true;
         enableWebAnimationsAndGridSupport(tree, polyfillsFile, polyfillsData);
-        overwriteJsonFile(tree, 'angular.json', workspace);
-        } else {
+        workspaces.writeWorkspace(workspace, workspaceHost);
```
Comment (damyanpetev) [inline projects/igniteui-angular/schematics/ng-add/index.ts:56]: @jackofdiamond5  If the read is async... isn't the write as well?

File: projects/igniteui-angular/schematics/ng-add/index.ts [hunk 2]
```diff
@@ -49,40 +39,46 @@ const enableWebAnimationsAndGridSupport = (tree: Tree, targetFile: string, polyf
...
+    const { workspace } = await workspaces.readWorkspace(tree.root.path, workspaceHost);
     if (options.polyfills) {
-        const workspace = getWorkspace(tree);
-        const targetProperty = 'es5BrowserSupport';
-        const project = workspace.projects[workspace.defaultProject];
-        const polyfillsFile = getConfigFile(project, 'polyfills');
-        const propertyExists = propertyExistsInWorkspace(targetProperty, workspace);
-        let polyfillsData = tree.read(polyfillsFile).toString();
-        if (propertyExists) {
+      const targetProperty = 'es5BrowserSupport';
```
Comment (damyanpetev) [inline projects/igniteui-angular/schematics/ng-add/index.ts:47]: I believe this is no longer in use and this functionality probably doesn't do what it's supposed to

**Review by damyanpetev — APPROVED** [review]
