### PR TITLE
Outlet prop for timepicker dialog mode working correctly - 7.3.x

### LINKED ISSUE #5076: Time Picker: outlet property not working in dialog mode in 7.3.x
## Description  
Outlet property not working in dialog mode

 * igniteui-angular version: 7.3.x
 * browser: all

## Steps to reproduce  

1. Set outlet on time picker in dialog mode
2. Open the dialog.

## Result  
Exception thrown, dialog not rendered correctly.

## Expected result  
No exception thrown, dialog is rendered correctly.

### PR DESCRIPTION
**Pull request by VladB93**
Closes #5076  

### Additional information (check all that apply):
 - [X] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [X] All relevant tags have been applied to this PR
 - [X] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts [hunk 1]
```diff
@@ -366,7 +366,6 @@ export class IgxTimePickerComponent implements
      */
     @Input()
     public overlaySettings: OverlaySettings;
-
```
Comment (bkulov) [inline projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts]: Please don't remove this line so the comment bellow will be more readable.
