### PR TITLE
fix(igxGrid): Grid should render all columns when grid width is set to null.

### LINKED ISSUE #5288: Grid width set to `null` is not rendering grid columns at all.
## Description  
Setting grid with to `null` does not render columns at all making the grid empty and that is why rows render as 1px in height.
The same is for Tree Grid and Hierarchical Grid.

 * igniteui-angular version: 7.3.x
 * browser: any

## Steps to reproduce  

1. Open the "gridColumnResizing" demo sample
2. Set the width of the grid to `null`.
3. Observe the rendered grid.

## Result  
The grid is not rendering any columns.

## Expected result  
The grid should render all columns in the grid without horizontal virtualization. If there is vertical virtualization it should not be affected.

## Attachments  
width-null

### PR DESCRIPTION
**Pull request by MayaKirova**
Closes #5288  

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/grid-base.component.ts [hunk 1]
```diff
@@ -642,6 +642,22 @@ export abstract class IgxGridBaseComponent extends DisplayDensityBase implements
...
 
+    /**
+     * @hidden
+    */
+    @HostBinding('style.width')
+    get hostWidth() {
+        if (this.width === null && this.columnList && this.columnList.length > 0) {
+            let width = this.columnList.reduce((sum, item) => sum + parseInt((item.width || item.defaultWidth), 10), 0);
+            if (this.hasVerticalSroll()) {
+                width += this.scrollWidth;
```
Comment (skrustev) [inline projects/igniteui-angular/src/lib/grids/grid-base.component.ts]: I think it should add also the features columns width and etc.
Otherwise for example if Row Selection is enabled it will create scrollbar because the column containing checkboxes is not taken into account.

**Comment by ChronosSF** [comment]
Check the comments in https://github.com/IgniteUI/igniteui-angular/pull/5396

**Comment by ChronosSF** [comment]
Check the new issues in #5397

**Comment by ChronosSF** [comment]
@MayaKirova, the only issue still remaining is that the row drag column remains as empty area after row drag is disabled:

row_drag

**Comment by MayaKirova** [comment]
@ChronosSF Please re-test.
