### PR TITLE
fix(grid): recreate columns when data changes with autoGenerate enabled - master

### LINKED ISSUE #14315: Grid does not recreate its columns collection after data change
## Steps to reproduce  

1. Add grid with `autoGenerate` set to true
2. 2. In ngOnInit, set `this.grid.shouldGenerate = true`

**Result 1:**
See console:
image

3. Change the collection that is bound to the grid `data` property
```
this.data = this.data3;
```

## Result  
Grid does not recreate its columns based on the new data bound to the `data` input property

## Expected result  
Grid to recreate its columns based on the new data bound to the `data` input property and No errors to be thrown initially.

### PR DESCRIPTION
**Pull request by georgianastasov**
Closes #14315  

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Review by hanastasov — CHANGES_REQUESTED** [review]
This fixes it for flat grid, but not for Hierarchical one. Please review all other grids as well.

**Comment by georgianastasov** [comment]
@hanastasov I've reviewed the other grid structures (tree grid and hierarchical grid) and confirmed that the fix applies identically to them as well.

**Comment by georgianastasov** [comment]
After a discussion with @hanastasov, it turns out that our initial assumption was correct. The `shouldGenerate` property can be completely removed from all grid structures (grid, tree grid, hierarchical grid and pivot grid). Instead, we can rely solely on the `autoGenerate` property.

Upon reviewing the implementation, we found that the `shouldGenerate` property essentially performs the same function as `autoGenerate`, making it redundant. By removing `shouldGenerate`, we simplify the grid generation process and avoid any confusion.

**Comment by hanastasov** [comment]
> After a discussion with @hanastasov, it turns out that our initial assumption was correct. The `shouldGenerate` property can be completely removed from all grid structures (grid, tree grid, hierarchical grid and pivot grid). Instead, we can rely solely on the `autoGenerate` property.
> 
> Upon reviewing the implementation, we found that the `shouldGenerate` property essentially performs the same function as `autoGenerate`, making it redundant. By removing `shouldGenerate`, we simplify the grid generation process and avoid any confusion.

In addition to deprecating the `shouldGenerate`:
- setting a value to `shouldGenerate` via the public API should assign the same value to `autoGenerate`, in order to keep customers code working with no behavior changes

**Review by MayaKirova — APPROVED** [review]
I'm fine with the change. Just make sure to test remote scenarios since there the data is changed via the setter.

**Comment by georgianastasov** [comment]
> I'm fine with the change. Just make sure to test remote scenarios since there the data is changed via the setter.

@MayaKirova Could you tell me a little more specifically what scenarios to test exactly and where? For which component and which file should I focus on? Should I create a new test for this or stay with the current tests and test it locally?

**Comment by MayaKirova** [comment]
@georgianastasov The things that come to mind are [remote operations](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/remote-data-operations), like paging, virtualization, sorting, filtering, load on demand etc. 
Also something like the [live data sample](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/live-data#angular-live-data-update-example)  where the data changes constantly. We really don't want a scenario where "autoGenerate" is enabled and updates on the data cause the grid to constantly keep re-creating the columns.

File: projects/igniteui-angular/src/lib/grids/grid/grid.component.ts [hunk 1]
```diff
@@ -1367,4 +1369,10 @@ export class IgxGridComponent extends IgxGridBaseDirective implements GridType,
         }
         return val;
     }
+
+    private shouldRegenerateColumns(oldData: any[] | null | undefined, newData: any[] | null | undefined): boolean {
```
Comment (dkamburov) [inline projects/igniteui-angular/src/lib/grids/grid/grid.component.ts:1373]: Could've add it as protected in the grid-base and reuse in the three grids instead if repeating it.

**Review by dkamburov — DISMISSED** [review]

**Comment by georgianastasov** [comment]
I have tested all the mentioned scenarios including remote operations (paging, virtualization, sorting, filtering, load on demand), and live data updates where the data changes constantly. I have not encountered any problems, obstacles, or issues. The columns are not recreated in any of these scenarios, as noted. For better verification, someone from our team will also test all scenarios.

**Comment by ChronosSF** [comment]
@georgianastasov , @MayaKirova , is this going to be included only in the latest branch or is it a fix? All other PRs seem to have been closed.

**Comment by MayaKirova** [comment]
@ChronosSF It does introduce a breaking change, so it should only go in the latest version IMO.

File: projects/igniteui-angular/migrations/update-18_1_0/changes/members.json [hunk 2]
```diff
@@ -24,6 +24,16 @@
             "definedIn": [
                 "IgxPaginatorComponent"
             ]
```
Comment (ChronosSF) [inline projects/igniteui-angular/migrations/update-18_1_0/changes/members.json:26]: Since 18.1 is already released these migrations should be moved to a 18.2 migration

**Review by ChronosSF — CHANGES_REQUESTED** [review]

**Comment by ChronosSF** [comment]
Adding do-not-merge so that we can have the mass merges for more time. We'll merge this once a few more new features line up for being added to master.

**Review by dkamburov — DISMISSED** [review]

**Review by ChronosSF — DISMISSED** [review]

**Review by hanastasov — APPROVED** [review]
