### PR TITLE
Recalculate grid sizes if group area is shown/hidden

### LINKED ISSUE #9296: showGroupArea property - missing documentation and breaks layout
## Description  
`showGroupArea` property is not documented in the API documentation. Also, when it is being toggled, the grid miscalculates its
layout leaving "holes" in the grid body. 

 * igniteui-angular version: latest
 * browser: all

## Steps to reproduce  

1. Open the dev group by demo
2. Group by a column and then disable/enable the property through the "Show/Hide Groupable row" button.

## Result  
There is a "hole" in the grid row area.

## Expected result  
There should no be a "hole" in the grid row area.

### PR DESCRIPTION
**Pull request by mddragnev**
Closes #9296 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/grid/grid.component.ts [hunk 1]
```diff
@@ -775,12 +775,28 @@ export class IgxGridComponent extends IgxGridBaseDirective implements GridType,
...
+     */
     @Input()
     public get showGroupArea(): boolean {
         return this._showGroupArea;
     }
     public set showGroupArea(value: boolean) {
         this._showGroupArea = value;
+        if (!this._init) {
+            this.calculateGridSizes();
+        }
```
Comment (rkaraivanov) [inline projects/igniteui-angular/src/lib/grids/grid/grid.component.ts:799]:
```suggestion
        this.notifyChanges(true);
```
Let's defer the calculation for the next cycle not in the middle of the setter

**Review by rkaraivanov — CHANGES_REQUESTED** [review]

**Review by rkaraivanov — APPROVED** [review]
