### PR TITLE
fix(grid): trigger range selection in mozilla

### LINKED ISSUE #9502: Can not perform range selection with drag and drop starting from tree cell
## Description  

 * igniteui-angular version: all
 * browser: Mozilla Fifefox

## Steps to reproduce  

1. Open grid sample with master-detail or tree grid with enabled multi-cell selection
2. Perform pointer down on the first cell of the first column 
3. Start dragging the mouse

## Result  
What is the actual result after following the steps to reproduce?
TreeCellFirefox
MasterDetailsFirefox

## Expected result  
What is the expected result after following the steps to reproduce?
Range selection should be created

### PR DESCRIPTION
**Pull request by Aleksandyr**
Closes #9502

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/cell.component.ts [hunk 1]
```diff
@@ -16,7 +16,7 @@
 } from '@angular/core';
 import { IgxTextHighlightDirective } from '../directives/text-highlight/text-highlight.directive';
 import { GridBaseAPIService } from './api.service';
-import { PlatformUtil } from '../core/utils';
+import { isFirefox, PlatformUtil } from '../core/utils';
```
Comment (ddincheva) [inline projects/igniteui-angular/src/lib/grids/cell.component.ts:19]: Aleks, this import is not used, please remove it.

File: projects/igniteui-angular/src/lib/grids/cell.component.ts [hunk 2]
```diff
@@ -813,7 +813,9 @@ export class IgxGridCellComponent implements OnInit, OnChanges, OnDestroy {
      * @internal
      */
     public pointerdown = (event: PointerEvent) => {
-        event.preventDefault();
+        if(this.platformUtil.isFirefox) {
+            event.preventDefault();
+        }
```
Comment (ddincheva) [inline projects/igniteui-angular/src/lib/grids/cell.component.ts:818]: Can you consider moving this check below the check for cell selection mode because we break the default behavior and the user cannot make a text selection? We need this logic only in case we have range selection enabled.

**Review by ddincheva — CHANGES_REQUESTED** [review]

**Review by ddincheva — DISMISSED** [review]

File: projects/igniteui-angular/src/lib/grids/cell.component.ts [hunk 3]
```diff
@@ -820,6 +820,9 @@ export class IgxGridCellComponent implements OnInit, OnChanges, OnDestroy {
             this.activate(event);
             return;
         }
+        if(this.platformUtil.isFirefox) {
```
Comment (kdinev) [inline projects/igniteui-angular/src/lib/grids/cell.component.ts:823]: You will prevent twice if you have a left click under firefox.

**Review by kdinev — CHANGES_REQUESTED** [review]

**Review by kdinev — APPROVED** [review]
