### PR TITLE
Fix for #1388

### LINKED ISSUE #1388: igx-tabs-group gets error when ngIf is applied to it.
### Steps to reproduce  

1. Go to https://stackblitz.com/edit/igx-tabs-group-ngif-issue
2. Open a browser console.

### Result  
An error is thrown and tab layout is off.

>ERROR TypeError: Cannot read property 'toArray' of undefined
    at IgxTabsGroupComponent.get [as index] (igx-tabs-group-ngif-issue.stackblitz.io/turbo_modules/igniteui-angular@5.3.1/tabs/tabs-group.component.js:52)
    at IgxTabsGroupComponent.get [as labelledBy] (igx-tabs-group-ngif-issue.stackblitz.io/turbo_modules/igniteui-angular@5.3.1/tabs/tabs-group.component.js:22)
    at Object.eval [as updateRenderer] (ng:///AppModule/TabsSample1Component.ngfactory.js:18)
    at Object.debugUpdateRenderer [as updateRenderer] (igx-tabs-group-ngif-issue.stackblitz.io/turbo_modules/@angular/core@5.2.11/bundles/core.umd.js:14773)
    at checkAndUpdateView (igx-tabs-group-ngif-issue.stackblitz.io/turbo_modules/@angular/core@5.2.11/bundles/core.umd.js:13887)
    at callViewAction (igx-tabs-group-ngif-issue.stackblitz.io/turbo_modules/@angular/core@5.2.11/bundles/core.umd.js:14233)
    at execEmbeddedViewsAction (igx-tabs-group-ngif-issue.stackblitz.io/turbo_modules/@angular/core@5.2.11/bundles/core.umd.js:14191)
    at checkAndUpdateView (igx-tabs-group-ngif-issue.stackblitz.io/turbo_modules/@angular/core@5.2.11/bundles/core.umd.js:13883)
    at callViewAction (igx-tabs-group-ngif-issue.stackblitz.io/turbo_modules/@angular/core@5.2.11/bundles/core.umd.js:14233)
    at execComponentViewsAction (igx-tabs-group-ngif-issue.stackblitz.io/turbo_modules/@angular/core@5.2.11/bundles/core.umd.js:14165)

image

### Expected result  
No error is thrown.

### PR DESCRIPTION
**Pull request by sboykova**
Closes #1388.

### CODE REVIEW

File: projects/igniteui-angular/src/lib/tabbar/tabbar.component.ts [hunk 1]
```diff
@@ -177,12 +171,18 @@ export class IgxTabPanelComponent implements AfterContentInit {
...
+
     private _tabTemplate: TemplateRef<any>;
+    private _nativeElement: ElementRef;
 
     @ContentChild(IgxTabTemplateDirective, { read: IgxTabTemplateDirective })
     protected tabTemplate: IgxTabTemplateDirective;
 
-    constructor(private _tabBar: IgxBottomNavComponent) {
+    constructor(private _tabBar: IgxBottomNavComponent, private _element: ElementRef) {
+        this._nativeElement = _element;
```
Comment (bkulov) [inline projects/igniteui-angular/src/lib/tabbar/tabbar.component.ts]: You don't need this private field _nativeElement and the public get nativeElement property. Just use _element which is defined in the constructor.

File: projects/igniteui-angular/src/lib/tabs/tabs-group.component.ts [hunk 2]
```diff
@@ -72,13 +66,21 @@ export class IgxTabsGroupComponent implements AfterContentInit {
...
     @ContentChild(IgxTabItemTemplateDirective, { read: IgxTabItemTemplateDirective })
     protected tabTemplate: IgxTabItemTemplateDirective;
 
-    constructor(@Inject(forwardRef(() => IgxTabsComponent))
-    private _tabs: IgxTabsComponent) {
+    constructor(
+        @Inject(forwardRef(() => IgxTabsComponent))
+        private _tabs: IgxTabsComponent,
+        private _element: ElementRef) {
+        this._nativeElement = _element;
```
Comment (bkulov) [inline projects/igniteui-angular/src/lib/tabs/tabs-group.component.ts]: Same as my previous comment. Use _element.
