### PR TITLE
fix(excel-exporter): export correct number of rows#12086

### LINKED ISSUE #12086: Export  to excel one row of igx-grid with two levels of multi column headers
## Description  
An igx-grid component with multi-column header and export to excel option is used.
When we have two levels of multi-column headers and we have exactly one row in the grid, it is not exported to the excel file and it remains empty containing only the headers.
This also happens if there are three levels of multi-column headers and exactly two rows in the grid, or if there are four levels of multi-column headers and exactly three rows in a grid, etc.

 * igniteui-angular version: 13.2 14.1
 * browser: All

## Steps to reproduce  

1. Export grid to excel.

## Result  
The result after performing the reproduction steps is that the excel file is empty and these rows have not been exported.

## Expected result  
The expected result is that the rows are exported and they are in the excel file.

## Attachments  
A sample of two levels of multi-column headers and one row can be found [here](https://stackblitz.com/edit/angular-cjci6y-fytqmc?file=src/app/grid/single-row-export/single-row-export.component.html).
A sample of three levels of multi-column headers and two rows can be found [here](https://stackblitz.com/edit/angular-cjci6y-jpyiuw?file=src/app/grid/single-row-export/single-row-export.component.html).
A sample of four levels of multi-column headers and three rows can be found [here](https://stackblitz.com/edit/excel-exporter-two-rows-3nj1du?file=src/app/grid/single-row-export/single-row-export.component.html).

### PR DESCRIPTION
**Pull request by georgianastasov**
Closes #12086   

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Review by onlyexeption — DISMISSED** [review]

File: projects/igniteui-angular/src/lib/services/excel/excel-files.ts [hunk 1]
```diff
@@ -229,9 +229,9 @@ export class WorksheetFile implements IExcelFile {
 
         let recordHeaders = [];
 
-        yieldingLoop(worksheetData.rowCount - 1, 1000,
+        yieldingLoop(worksheetData.rowCount - worksheetData.multiColumnHeaderRows - 1, 1000,
             (i) => {
-                if (!worksheetData.isEmpty){
+                if (!worksheetData.isEmpty) {
```
Comment (onlyexeption) [inline projects/igniteui-angular/src/lib/services/excel/excel-files.ts:234]: fix spacing

**Review by onlyexeption — APPROVED** [review]
