### PR TITLE
fix(avatar): src is not encoded as URI

### LINKED ISSUE #14965: Avatar component fails to display images with spaces or special characters in file names
## Description  
When using the Avatar component, images with file names containing spaces or special characters do not display correctly. The issue arises because the component does not handle URL encoding for file names, which leads to broken image links. However, the native HTML  element can display these images without issues. While a workaround will be applied in CodeGen, the Avatar component should also be fixed to ensure correct rendering of image file names containing spaces or special characters.

 * igniteui-angular version: latest
 * browser: any

## Steps to reproduce  

1. Add an Avatar component to the page and set the src attribute to an image file with spaces or special characters in its name (e.g., "profile pic.jpg" or "profile@icon.png").
2. Load the page.

## Result  
The Avatar component fails to display the image. Instead, an empty image icon appears.

image

## Expected result  
The Avatar component should display the image correctly, similar to how the native HTML  element handles URLs with spaces or special characters by automatically encoding them.

image

### PR DESCRIPTION
**Pull request by simeonoff**
Closes #14965

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/core/utils.ts [hunk 1]
```diff
@@ -639,3 +639,11 @@ export function getComponentCssSizeVar(size: string) {
             return 'var(--ig-size, var(--ig-size-large))';
     }
 }
+
+/**
+ * @param path - The URI path to be normalized.
+ * @returns string endoded using the encodeURI function.
```
Comment (SisIvanova) [inline projects/igniteui-angular/src/lib/core/utils.ts:645]:
```suggestion
 * @returns string encoded using the encodeURI function.
```

**Review by SisIvanova — DISMISSED** [review]
