### PR TITLE
Commit pending transactions on addRow - 8.0.x

### LINKED ISSUE #5214: Can not add new row when there is row in edit mode
## Description  
 * browser: all

## Steps to reproduce  

1. Open HierarchicalGridUpdating or TreeGrid dev samples
2. Enable row editing 
3. Enter edit mode for some row
4. Click to the button to add new row
5. Scroll to the bottom of the grid

## Result  
The row is not added.

## Expected result  
The new row should be added in the grid.

### PR DESCRIPTION
**Pull request by jackofdiamond5**
Closes #5214 

Entering edit mode creates an internal transaction in a pending state. This prevents the addition of a new row since it has not completed. Now if you are in edit mode and you attempt to add a new row - the previous pending state will be committed.

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/grid-base.component.ts [hunk 1]
```diff
@@ -3486,6 +3486,12 @@ export abstract class IgxGridBaseComponent extends DisplayDensityBase implements
      * @memberof IgxGridBaseComponent
      */
     public addRow(data: any): void {
+        // If row editing is enabled and there is a row in edit mode
+        if (this.rowEditable && this.crudService.row) {
+            // Commit all pending states
+            this.transactions.endPending(true);
```
Comment (wnvko) [inline projects/igniteui-angular/src/lib/grids/grid-base.component.ts]: better call:

this.endEdit(true)

This will call a lot of events and so on.

File: projects/igniteui-angular/src/lib/grids/grid-base.component.ts [hunk 2]
```diff
@@ -3486,6 +3486,12 @@ export abstract class IgxGridBaseComponent extends DisplayDensityBase implements
      * @memberof IgxGridBaseComponent
      */
     public addRow(data: any): void {
+        // If row editing is enabled and there is a row in edit mode
+        if (this.rowEditable && this.crudService.row) {
```
Comment (wnvko) [inline projects/igniteui-angular/src/lib/grids/grid-base.component.ts]: Looking at this now I believe we should exit edit mode in all cases, regardless of if there is or there is no row edit enabled. So you can remove this check.
