### PR TITLE
fix(grid): Consider min/max width when setting defaultWidth property

### LINKED ISSUE #9145: Calculated column width should respect minWidth
## Description  
When minWidth is set, width of the column should not be smaller.

 * igniteui-angular version: 11.1
 * browser: Chrome, Firefox

## Steps to reproduce  

1. Open [https://stackblitz.com/edit/github-str5ty?file=src/app/grid/grid-resizing-sample/grid-resizing-sample.component.html](url)

## Result  
Column width does not respect minWidth parameter

## Expected result  
Column width should have the same minWidth or should be bigger then minWidth attribute when grid is rendered.

## Attachments  
column-min-width

### PR DESCRIPTION
**Pull request by dkamburov**
Closes #9145

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/grid-base.directive.ts [hunk 1]
```diff
@@ -6081,13 +6081,42 @@ export abstract class IgxGridBaseDirective extends DisplayDensityBase implements
...
         this.resetCachedWidths();
     }
 
+    /**
+     * @hidden
+     * @internal
+     */
+    protected getExtremumBasedColWidth(column: IgxColumnComponent): string {
+        let width = this._columnWidth;
+        const minWidth = this._columnWidth.indexOf('%') === -1 ? column.minWidthPx : column.minWidthPercent;
```
Comment (3phase) [inline projects/igniteui-angular/src/lib/grids/grid-base.directive.ts:6098]: According to the docs, one could set the `columnWidth` property of the grid in the following fashion:
`<igx-grid ... [columnWidth]="100"></igx-grid>`
That setting will break the `getExtremumBasedColWidth` function, because this check `this._columnWidth.indexOf('%')` implicates that the _columnWidth property is a string. 
It should rather take into account scenarios when the variable has a numeric value as well.

**Review by 3phase — CHANGES_REQUESTED** [review]

File: projects/igniteui-angular/src/lib/grids/grid-base.directive.ts (hunk 1 above)
Comment (dkamburov) [reply projects/igniteui-angular/src/lib/grids/grid-base.directive.ts]: @3phase shouldn't throw an error now

**Review by MayaKirova — APPROVED** [review]

**Review by rkaraivanov — APPROVED** [review]
