### PR TITLE
fix(combo): fix error in searchvalue handling - 10.2.x

### LINKED ISSUE #8018: [IgxCombo] "ERROR TypeError: Cannot read property 'trim' of null" occurs if onSearchInput event is conditionally cancelled.
## Description  
[IgxCombo] "ERROR TypeError: Cannot read property 'trim' of null" occurs if onSearchInput event is conditionally cancelled.

 * igniteui-angular version:  10.1.0
 * browser: Chrome

## Steps to reproduce  

1. Run the attached sample and open it in browser.
2. Click the dropdown to open it.
3. Type "101-" at the search input box.

## Result  
"ERROR TypeError: Cannot read property 'trim' of null" occurs.

## Expected result  
The event should be cancelled with no error.

## Attachments  
image
[kb3950-app1.zip](https://github.com/IgniteUI/igniteui-angular/files/5100032/kb3950-app1.zip)

### PR DESCRIPTION
**Pull request by ViktorSlavov**
Closes #8018

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/combo/combo.component.ts [hunk 1]
```diff
@@ -165,12 +165,15 @@ export class IgxComboComponent extends DisplayDensityBase implements IgxComboBas
     public filteringOptions: IComboFilteringOptions = {
         caseSensitive: false
     };
+    /* @hidden @internal */
```
Comment (damyanpetev) [inline projects/igniteui-angular/src/lib/combo/combo.component.ts:168]:
```suggestion
    /** @hidden @internal */
```
To actually get the tags working :)
Also not a huge fan of this being underscore prefixed, kind of inconsistent with the rest

File: projects/igniteui-angular/src/lib/combo/combo.component.ts [hunk 2]
```diff
@@ -1036,8 +1046,7 @@ export class IgxComboComponent extends DisplayDensityBase implements IgxComboBas
             };
             this.onSearchInput.emit(args);
             if (args.cancel) {
-                this.searchValue = null;
-                return;
```
Comment (damyanpetev) [inline projects/igniteui-angular/src/lib/combo/combo.component.ts:1040]: I think this could probably stay, as the match check is still unnecessary in this case
