### PR TITLE
fix(slider): improve accessibility by correcting ARIA attributes and tab index - master

### LINKED ISSUE #14262: Slider accessibility issues
## Description  
The following accessibility issues are present in the component at the moment: 
 - it's missing `ariavalue-now`
 - `tab-index` is 1 (it should be 0)
 - missing accessible name (it needs to be  implemented by [aria-labelledby](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/slider_role#best_practices)
 - all of the ARIA attributes are not on the focusable element (the thumb)

### PR DESCRIPTION
**Pull request by georgianastasov**
Closes #14262   

The slider control element now follows ARIA guidelines, including:
- **tabindex** correct **0** value, ensuring the thumb components are correctly focusable within the tab order.
- **role** set to **slider** for the thumbs focusable elements.
- **aria-valuenow** for the current slider value, **aria-valuemin** for the minimum value, and **aria-valuemax** for the maximum value.
- **aria-valuetext** is used when the current value is not user-friendly (e.g., converting numeric values to readable text).
- **aria-label** is used to provide accessible labeling.
- **aria-orientation** is set to "horizontal" by default.
-  **aria-disabled** to the thumb components when they are disabled to indicate the element's state.

The slider thumb component has been updated to follow ARIA accessibility guidelines as per [WAI-ARIA slider pattern](https://www.w3.org/WAI/ARIA/apg/patterns/slider/) and the implementations outlined in the [IgniteUI Web Components Slider specification](https://github.com/IgniteUI/igniteui-webcomponents/wiki/Slider-Specification#5-accessibility).

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/slider/thumb/thumb-slider.component.ts [hunk 1]
```diff
@@ -78,6 +78,16 @@ export class IgxSliderThumbComponent implements OnInit, OnDestroy {
     @HostBinding('attr.z-index')
     public zIndex = 0;
 
+    @HostBinding('attr.aria-valuenow')
+    public get ariaValueNow() {
+        return this.value;
+    }
+
+    @HostBinding('attr.aria-labelledby')
```
Comment (hanastasov) [inline projects/igniteui-angular/src/lib/slider/thumb/thumb-slider.component.ts:86]: `aria-labelledby` is expected to contain a refreence to a label element, isnt it? I assume we need to se just aria-label attr? Please check that

**Review by hanastasov — CHANGES_REQUESTED** [review]

**Review by hanastasov — APPROVED** [review]
