### PR TITLE
fix(splitter): Don't change resizable property on expand/collapse and reset sibling size only if resizable

### LINKED ISSUE #7122: Splitter pane size and resizable not respected after expand/collapse
## Description  
Splitter pane size and resize ignored after collapsing other panes

 * igniteui-angular version: 9.1.x
 * browser: N/A

## Steps to reproduce  

1. Setup 3 panes with the first two on auto (defalts) and the third with `size="200px" [resizable]="false"`
2. Collapse the second pane
3. Expand the second pane (third pane size changed)
2. Collapse the third pane
3. Expand the third pane (third pane now resizable)

## Result  
The third pane has now lost it's 200px size and can be resized freely as well

## Expected result  
The pane that has fixed size and cannot be resized should remain with it's original size if possible.

## Attachments  
Attach a sample if available, and screenshots, if applicable.

### PR DESCRIPTION
**Pull request by VMihalkov**
Closes #7122 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/splitter/splitter-bar/splitter-bar.component.ts [hunk 1]
```diff
@@ -198,6 +198,11 @@ export class IgxSplitBarComponent {
         return !!relatedTabs.find(x => x.resizable === false);
     }
 
+    protected get panesHidden() {
```
Comment (MayaKirova) [inline projects/igniteui-angular/src/lib/splitter/splitter-bar/splitter-bar.component.ts:201]: This looks very similar to resizeDisallowed. Check can be moved there. There does not seem to be need of an additional getter.
