### PR TITLE
Resolve buttons not selected if initialized after the group

### LINKED ISSUE #13961: ButtonGroup selected attribute doesn't work if buttons are rendered after the buttonGroup
## Description  
ButtonGroup selected attribute doesn't work if buttons are rendered after the buttonGroup

 * igniteui-angular version: 17.1.0-rc.0
 * browser:  chrome 122.0.6261.69

## Steps to reproduce  

1. Add button group
2. Add selected = true to one of the buttons
3. Make sure that the buttons are rendered after the button group 
4. Examine the result

## Result  
The button with selected = true is not initially selected
https://stackblitz.com/edit/qfvsnv-psdqq9?file=src%2Fapp%2Fbutton-group-sample-1%2Fbutton-group-sample-1.component.html

## Expected result  
The button should be initially selected after render

## Attachments  
---

### PR DESCRIPTION
**Pull request by IvanKitanov17**
Closes #13961   

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/buttonGroup/buttonGroup.component.ts [hunk 1]
```diff
@@ -462,14 +462,19 @@ export class IgxButtonGroupComponent extends DisplayDensityBase implements After
...
-
         this.mutationObserver = this.setMutationsObserver();
 
+        this.viewButtons.changes.pipe(takeUntil(this.queryListNotifier$)).subscribe(() => {
+            this.mutationObserver.disconnect();
+            initButtons();
+        });
+        this.templateButtons.changes.pipe(takeUntil(this.queryListNotifier$)).subscribe(() => {
+            this.mutationObserver.disconnect();
+            initButtons();
```
Comment (deyvidnenchev) [inline projects/igniteui-angular/src/lib/buttonGroup/buttonGroup.component.ts:473]: After InitButtons you have to re-attach the mutation observer (like on line 478)
