### PR TITLE
Bypass all calls to browsers' object when not on browser platform

### LINKED ISSUE #4426: NavDrawer breaks server-side rendering
## Description  
I tried to build and app-shell that uses the nav-drawer in the app.component, and the build fails.

 * igniteui-angular version: 7.2.2
 * browser: N/A

## Steps to reproduce  

1. Create a default cli project with side-nav.
2. Add an app-shell and build.

## Result  
Build fails.

## Expected result  
Build should pass.

## Attachments  

> Hammer is not defined
> ReferenceError: Hammer is not defined
>     at new HammerGesturesManager (D:\GitHub\angular-training\node_modules\igniteui-angular\bundles\igniteui-angular.umd.js:67038:29)
>

### PR DESCRIPTION
**Pull request by wnvko**
There were some places in `touch.ts` as well as in `IgxNavDrawer` where we were calling browser related things, like `requestAnimationFrame`. Now we are checking if there platform where build runs is browser platform. If not, e.g. server side rendering, we skip calling browsers' methods.

Closes #4426   

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/navigation-drawer/navigation-drawer.component.ts [hunk 1]
```diff
@@ -612,18 +614,26 @@ export class IgxNavigationDrawerComponent implements
     }
 
     private getWindowWidth() {
+        if (!this.platformUtil.isPlatformBrowser()) {
```
Comment (damyanpetev) [inline projects/igniteui-angular/src/lib/navigation-drawer/navigation-drawer.component.ts]: This can likely stay (though I'd prefer a return value of something at least (0)).
Frankly, this only affects `checkPinThreshold` and while the current logic there will is fin like that, the whole check is pointless if there's no window to measure so it should be prevented instead.

File: projects/igniteui-angular/src/lib/navigation-drawer/navigation-drawer.component.ts [hunk 2]
```diff
@@ -805,19 +815,27 @@ export class IgxNavigationDrawerComponent implements
...
-            } else {
-                this.renderer.setElementStyle(this.drawer, 'transform', x ? 'translate3d(' + x + 'px,0,0)' : '');
-                this.renderer.setElementStyle(this.drawer, '-webkit-transform',
-                    x ? 'translate3d(' + x + 'px,0,0)' : '');
-            }
-            if (opacity !== undefined) {
-                this.renderer.setElementStyle(this.overlay, 'opacity', opacity);
-            }
-        });
+        if (this.platformUtil.isPlatformBrowser()) {
```
Comment (damyanpetev) [inline projects/igniteui-angular/src/lib/navigation-drawer/navigation-drawer.component.ts]: This one shouldn't need a fallback, in fact this is only called during pan interaction, but if you want to make it safe just for future uses - just interrupt the method at start.

File: projects/igniteui-angular/src/lib/navigation-drawer/navigation-drawer.component.spec.ts [hunk 3]
```diff
@@ -532,8 +525,8 @@ describe('Navigation Drawer', () => {
         window.dispatchEvent(new Event('resize'));
 
         // wait for debounce
-        await wait(200);
-        expect(fixture.componentInstance.viewChild.pin).toBe(false, `Shouldn't change state on resize if window width is the same`);
+        await wait(2000);
```
[the remark this answers is not in the document]
Comment (wnvko) [reply projects/igniteui-angular/src/lib/navigation-drawer/navigation-drawer.component.spec.ts]: yes it can

File: projects/igniteui-angular/src/lib/navigation-drawer/navigation-drawer.component.ts (hunk 1 above)
Comment (wnvko) [reply projects/igniteui-angular/src/lib/navigation-drawer/navigation-drawer.component.ts]: Actually in PWA with app shell, while building the app `ngAfterContentInit` is called. This calls `checkPinThreshold`. I am moving now the check to `checkPinThreshold` as it seams to be the only place where `getWindowWidth` is called with no browser.

File: projects/igniteui-angular/src/lib/navigation-drawer/navigation-drawer.component.ts (hunk 2 above)
Comment (wnvko) [reply projects/igniteui-angular/src/lib/navigation-drawer/navigation-drawer.component.ts]: yeah, will remove that check

File: projects/igniteui-angular/src/lib/core/utils.ts [hunk 4]
```diff
@@ -228,13 +231,23 @@ export function isFirefox(): boolean {
...
-    static isIOS(): boolean {
-        const iosBrowser = typeof window !== 'undefined' && /iPad|iPhone|iPod/.test(navigator.userAgent) && !('MSStream' in window);
+    private platformBrowser: boolean;
+
+    constructor(@Inject(PLATFORM_ID) private platformId: Object) {
+        this.platformBrowser = isPlatformBrowser(this.platformId);
+    }
+
+    public get isIOS(): boolean {
+        const iosBrowser = this.platformBrowser && /iPad|iPhone|iPod/.test(navigator.userAgent) && !('MSStream' in window);
```
Comment (rkaraivanov) [inline projects/igniteui-angular/src/lib/core/utils.ts]: Can't this just be a static property on the class itself?
Do we expect the this check to return a different value after script evaluation in the browser?

Comment (damyanpetev) [reply projects/igniteui-angular/src/lib/core/utils.ts]: Need instance to get the platform through DI before we can inspect user agent

Comment (wnvko) [reply projects/igniteui-angular/src/lib/core/utils.ts]: we finish with simple public fields
