### PR TITLE
fix(date picker): dropdown mode scroll strategy

### LINKED ISSUE #4205: IgxCalendar overlay, rendered from cell in edit mode, goes outside the grid  when scrolling
## Description  
The embedded IgxDatePicker in IgxGrid triggers an IgxCalendar overlay that floats eveywhere in the body. 

 * igniteui-angular version: 7.2.x
 * browser: all

## Steps to reproduce  
Set a grid with editable date column and apply edit to a cell

## Result  
The calendar that is rendered can be reached anywhere in the body

## Expected result  
The Calendar should accessible only in its corresponding IgxGrid scope

## Attachments  
ezgif com-video-to-gif 6

### PR DESCRIPTION
**Pull request by SAndreeva**
Closes #4205

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts [hunk 1]
```diff
@@ -37,7 +37,8 @@ import {
     VerticalAlignment,
     HorizontalAlignment,
     PositionSettings,
-    ConnectedPositioningStrategy
+    ConnectedPositioningStrategy,
+    AbsoluteScrollStrategy
```
Comment (bkulov) [inline projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts]: Shouldn't we import the scrolling strategy from the exact file where it's defined? `../services/overlay/scroll/absolute-scroll-strategy`

Comment (SAndreeva) [reply projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts]: Both are fine.
