### PR TITLE
fix(hgrid): adding foreign key #3868

### LINKED ISSUE #3868: Expose foreign key for hierarchical grid

### PR DESCRIPTION
**Pull request by ChronosSF**
Closes #3868 

### Additional information (check all that apply):
 - [ ] Bug fix
 - [x] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [x] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [x] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts [hunk 1]
```diff
@@ -177,6 +177,18 @@ export class IgxHierarchicalGridComponent extends IgxHierarchicalGridBaseCompone
...
+    /**
+     * Gets the unique identifier of the parent row. It may be a `string` or `number` if `primaryKey` of the
+     * parent grid is set or an object reference of the parent record otherwise.
+     * ```typescript
+     * const foreignKey = this.grid.foreignKey;
+     * ```
+     * @memberof IgxHierarchicalGridComponent
+     */
+    public get foreignKey() {
+        return this.parent.hgridAPI.getParentRowId(this);
```
Comment (skrustev) [inline projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts]: If this is the root grid isn't this.parent = null?
