### PR TITLE
Fixes errors in setFilteredSortedData when data is undefined

### LINKED ISSUE #7261: Error while setting grid data after initialization of component view
## Description  
When one uses the `ngAfterViewInit` hook to set the grid's data, an error is being thrown.

 * igniteui-angular version: 9.1

## Steps to reproduce  

1. Create a grid, without binding the `[data]` property of the component to a variable.
2. In the `ngAfterViewInit` hook, create a subscription to a data source.
3. Assign the result of the resolved subscription to the grid's `.data` property.

## Result  
An error core.js:6185 ERROR TypeError: Cannot read property 'map' of undefined is thrown and no data is rendered in the grid.

## Attachments  
image

### PR DESCRIPTION
**Pull request by 3phase**
Closes #7261   

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/grid-base.directive.ts [hunk 1]
```diff
@@ -2998,6 +2998,7 @@ export class IgxGridBaseDirective extends DisplayDensityBase implements
      * @internal
      */
     public setFilteredSortedData(data, pinned: boolean) {
+        if (data === undefined) { data = []; }
```
Comment (MayaKirova) [inline projects/igniteui-angular/src/lib/grids/grid-base.directive.ts:3001]: Could be shortened: 
data = data ? data.map(rec => rec.ghostRecord !== undefined ? rec.recordRef : rec) : [];

**Comment by 3phase** [comment]
@MayaKirova thank you for your remarks, I have fixed them.

File: projects/igniteui-angular/src/lib/grids/grid-base.directive.ts [hunk 2]
```diff
@@ -2998,7 +2998,7 @@ export class IgxGridBaseDirective extends DisplayDensityBase implements
      * @internal
      */
     public setFilteredSortedData(data, pinned: boolean) {
-        data = data.map(rec => rec.ghostRecord !== undefined ? rec.recordRef : rec);
+        data = data ? data.map(rec => rec.ghostRecord !== undefined ? rec.recordRef : rec) : [];
```
Comment (MayaKirova) [inline projects/igniteui-angular/src/lib/grids/grid-base.directive.ts:3001]: After testing this I noticed that the data is never passed wrapped as a ghost record, hence the mapping here seems unnecessary. The whole line can be removed.
