### PR TITLE
Convert input value to number for number columns

### LINKED ISSUE #4057: Number and date filters do not work.
## Description  
Equals operator doesn't filter correctly number values 

 * igniteui-angular version: 7.2
 * browser: NA

## Steps to reproduce  

1. Open dev demos - Grid Column Moving 
2. Open excel style filter for Employees column - Number filter - Equals
3. Enter existing number 68

## Result  
No records found

## Expected result  
Existing filtered record should be displayed

### PR DESCRIPTION
**Pull request by sstoyanovIG**
Closes #4057  

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-default-expression.component.ts [hunk 1]
```diff
@@ -96,6 +96,16 @@ export class IgxExcelStyleDefaultExpressionComponent implements AfterViewInit {
         return this.grid.resourceStrings['igx_grid_filter_row_placeholder'];
     }
 
+    get type() {
+        switch (this.column.dataType) {
+            case DataType.String:
+            case DataType.Boolean:
+                return 'text';
+            case DataType.Number:
```
Comment (bkulov) [inline projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-default-expression.component.ts]: use default clause and return `text`.
