### PR TITLE
Fix error when pressing backspace in an empty dateTime filter

### LINKED ISSUE #13106: Grid: Javascript error in dateTime filter
## Description  
When inside a grid filter for a dateTime column pressing Backspace or Delete throws a javascript error.

 * igniteui-angular version: 16.0.5

## Steps to reproduce  

1. Open a filter for a dateTime column
2. Press Backspace or Delete key

## Result  
Javascript error is thrown:
```
TypeError: Cannot read properties of null (reading 'target')
    at IgxGridFilteringRowComponent.onInput
```

## Expected result  
There should be no error.

## Attachments  
https://stackblitz.com/edit/angular-tc333n-b3vw6u

2023-06-13_08h45_47

### PR DESCRIPTION
**Pull request by onlyexeption**
Closes #13106 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Review by igdmdimitrov — APPROVED** [review]

File: projects/igniteui-angular/src/lib/grids/filtering/base/grid-filtering-row.component.ts [hunk 1]
```diff
@@ -343,6 +343,10 @@ export class IgxGridFilteringRowComponent implements AfterViewInit, OnDestroy {
      * Event handler for input on the input.
      */
     public onInput(eventArgs) {
+        if (eventArgs === null) {
```
Comment (kdinev) [inline projects/igniteui-angular/src/lib/grids/filtering/base/grid-filtering-row.component.ts:346]: Check for falsy instead of explicit `null`.

**Review by kdinev — CHANGES_REQUESTED** [review]

**Review by kdinev — APPROVED** [review]
