### PR TITLE
fix(hierarchical-grid): emit column events for child grid #8644

### LINKED ISSUE #8644: IgxHierarchicalGrid: hiddenChange is not emitted for the row islands
## Description  
hiddenChange event is not fired for row islands when a column is hidden/shown via ColumnHiding UI

## Steps to reproduce  

1. Open [this](https://stackblitz.com/edit/hgrid-hiddenchage-issue?file=src/app/hierarchical-grid/hierarchical-grid-column-hiding/hierarchical-grid-hiding.component.html) sample.
2. Expand one of the rows and hide some columns in the child grid via the column hiding UI in the toolbar.

## Result  
The column is hidden/shown, however, the event is not fired, and in this case, the event argument is not printed on the console.

## Expected result  
The event to be fired like in the parent grid.

### PR DESCRIPTION
**Pull request by MonikaKirkova**
Closes #8644 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/hierarchical-grid/row-island.component.ts [hunk 1]
```diff
@@ -293,7 +293,6 @@ export class IgxRowIslandComponent extends IgxHierarchicalGridBaseDirective
 
         // handle column changes so that they are passed to child grid instances when onColumnChange is emitted.
         this.ri_columnListDiffer.diff(this.childColumns);
-        this.childColumns.toArray().forEach(x => x.onColumnChange.pipe(takeUntil(x.destroy$)).subscribe(() => this.updateColumnList()));
```
Comment (MayaKirova) [inline projects/igniteui-angular/src/lib/grids/hierarchical-grid/row-island.component.ts:296]: This handles changes from the row island column properties and applies them to already existing child grids so that the change is reflected in them. Removing it will probably break that scenario. For example, if a child grid is already expanded and a property on the related row island column is changed (for example, `header` prop is changed) after this, this change will never be reflected on this existing child grid.

**Review by MayaKirova — APPROVED** [review]

**Comment by kdinev** [comment]
@MonikaKirkova Please resolve the conflict and I'll merge the PR.

**Review by kdinev — APPROVED** [review]
