### PR TITLE
Disable combo checkbox animations on scroll 

### LINKED ISSUE #3243: Selected item checkboxes are flickering on scroll
### Description  
Selected checkboxes should not flicker when combo drop down is scrolled. The same problem as in #2523.

### Steps to reproduce  

1. Select multiple combo items
2. Scroll drop down

### Result  
Checkboxes are flickering

### Expected result  
Checkboxes should not flicker

### PR DESCRIPTION
**Pull request by Lipata**
Closes #3243 

### Additional information (check all that apply):
 - [x] Bug fix

### Checklist:
 - [x] All relevant tags have been applied to this PR

### CODE REVIEW

File: projects/igniteui-angular/src/lib/combo/combo-dropdown.component.ts [hunk 1]
```diff
@@ -377,10 +390,16 @@ export class IgxComboDropDownComponent extends IgxDropDownBase implements OnDest
         this.verticalScrollContainer.getVerticalScroll().scrollTop = this._scrollPosition;
     }
 
+    public ngAfterViewInit() {
+        this._vScrollListener = this.verticalScrollHandler.bind(this);
+        this.verticalScrollContainer.getVerticalScroll().addEventListener('scroll', this._vScrollListener);
```
Comment (damyanpetev) [inline projects/igniteui-angular/src/lib/combo/combo-dropdown.component.ts]: Can you convert `this.verticalScrollHandler` to an arrow function and just use it directly for event binding (drop the extra ref `_vScrollListener`)

File: projects/igniteui-angular/src/lib/drop-down/drop-down.base.ts [hunk 2]
```diff
@@ -271,6 +271,11 @@ export abstract class IgxDropDownBase implements OnInit, IToggleView {
         return this.elementRef.nativeElement;
     }
 
+    /**
+     * @hidden
```
Comment (damyanpetev) [inline projects/igniteui-angular/src/lib/drop-down/drop-down.base.ts]: `@internal`

File: projects/igniteui-angular/src/lib/combo/combo-item.component.ts [hunk 3]
```diff
@@ -35,7 +36,7 @@ export class IgxComboItemComponent extends IgxDropDownItemBase {
 
     constructor(
         @Inject(IGX_COMBO_COMPONENT) private combo: IgxComboBase,
-        public dropDown: IgxDropDownBase,
+        public dropDown: IgxComboDropDownComponent,
```
[the remark this answers is not in the document]
Comment (Lipata) [reply projects/igniteui-angular/src/lib/combo/combo-item.component.ts]: I don't see any errors, when compiling target is > es2016
