### PR TITLE
Keep months order after selecting a month from the YearView

### LINKED ISSUE #6375: Keep months order after selecting a month from the YearView
* igniteui-angular version: 8.2.12

## Steps to reproduce  

1. Open a multi view calendar
2. Change to YearView from last month header:
image

3. Choose another month from the YearView

## Result  
The month selected is placed first in the calendar

## Expected result  
The month selected to take the place of the month, where the user initiated the action.

## Attachments  
Attach a sample if available, and screenshots, if applicable.

### PR DESCRIPTION
**Pull request by Aleksandyr**
Closes #6375 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/calendar/calendar.component.ts [hunk 1]
```diff
@@ -126,23 +127,7 @@ export class IgxCalendarComponent extends IgxMonthPickerBaseDirective implements
...
-                    viewDate: nextMonthDate
-                };
-                this.dayViews.push(monthView);
-            }
-            this._monthsViewNumber = val;
-        } else {
-            this.dayViews.splice(val, this.dayViews.length - val);
-            this._monthsViewNumber = val;
-        }
+        this._monthsViewNumber = val;
```
Comment (hanastasov) [inline projects/igniteui-angular/src/lib/calendar/calendar.component.ts]: Add validation, setting 0 or -1 should not be accepted

File: projects/igniteui-angular/src/lib/calendar/calendar.component.html [hunk 2]
```diff
@@ -4,11 +4,11 @@
 </ng-template>
 
 <ng-template let-result #defaultMonth let-obj>
-    <span tabindex="0" #monthsBtn (keydown)="activeViewYearKB(getViewDate(obj.index), $event)" (click)="activeViewYear(getViewDate(obj.index), $event)"
+    <span tabindex="0" #monthsBtn (keydown)="onActiveViewYearKB(getViewDate(obj.index), $event, obj.index)" (click)="onActiveViewYear(getViewDate(obj.index), obj.index)"
```
Comment (hanastasov) [inline projects/igniteui-angular/src/lib/calendar/calendar.component.html]: I think $event argument should not be passed, it can be removed to achieve a clearer template.

File: projects/igniteui-angular/src/lib/calendar/calendar.component.html [hunk 3]
```diff
@@ -4,11 +4,11 @@
...
         class="igx-calendar-picker__date">
         {{ formattedMonth(getViewDate(obj.index)) }}
     </span>
-    <span tabindex="0" #yearsBtn (keydown)="activeViewDecadeKB($event, getViewDate(obj.index))" (click)="activeViewDecade(getViewDate(obj.index))"
+    <span tabindex="0" #yearsBtn (keydown)="onActiveViewDecadeKB($event, getViewDate(obj.index), obj.index)" (click)="onActiveViewDecade(getViewDate(obj.index), obj.index)"
```
Comment (hanastasov) [inline projects/igniteui-angular/src/lib/calendar/calendar.component.html]: I think $event argument should not be passed, it can be removed to achieve a clearer template.

File: projects/igniteui-angular/src/lib/calendar/calendar.component.ts [hunk 4]
```diff
@@ -552,38 +538,55 @@ export class IgxCalendarComponent extends IgxMonthPickerBaseDirective implements
...
             this.monthsView.date = args;
-            this.focusMonth(event.target);
+            this.focusMonth(monthViewIdx);
         });
     }
 
-    private focusMonth(target: HTMLElement) {
-        const month = this.monthsView.dates.find((date) =>
-            date.index === parseInt(target.parentElement.attributes['data-month'].value, 10));
+    private focusMonth(monthVieiwIdx: number) {
```
Comment (hanastasov) [inline projects/igniteui-angular/src/lib/calendar/calendar.component.ts]: monthVieiwIdx to be monthViewIdx

File: projects/igniteui-angular/src/lib/calendar/days-view/days-view.component.ts [hunk 5]
```diff
@@ -98,8 +98,8 @@ export class IgxDaysViewComponent extends IgxCalendarBaseDirective implements Do
     /**
      * @hidden
      */
-    constructor(public navService: IgxDaysViewNavigationService) {
-        super();
+    constructor(public daysNavService: IgxDaysViewNavigationService, public calendarNavService: IgxCalendarNavigationService) {
+        super(calendarNavService);
```
Comment (hanastasov) [inline projects/igniteui-angular/src/lib/calendar/days-view/days-view.component.ts]: Is it neccessary for calendarNavService to be injected here ?

File: projects/igniteui-angular/src/lib/calendar/navigation.service.ts [hunk 6]
```diff
@@ -180,3 +189,39 @@ export class IgxDaysViewNavigationService {
...
 }
+
+/**
+ * @hidden
+ * Temporary service managing the multi view calendar interactions.
+ * https://github.com/IgniteUI/igniteui-angular/issues/6375
+ * TODO: should be combined with @IgxDaysViewNavigationService
+ */
+@Injectable()
+export class IgxCalendarNavigationService {
```
Comment (hanastasov) [inline projects/igniteui-angular/src/lib/calendar/navigation.service.ts]: Is it needed for this logic to be part of the Navigation service ? It brings dependency to the Calendar, and also it is just a calculation logic that has nothing to do with navigation.

File: projects/igniteui-angular/src/lib/calendar/calendar.ts [hunk 7]
```diff
@@ -326,6 +334,26 @@ export class Calendar {
         return result;
     }
 
+    public getDatePerMonthView(date: Date, interval: string, monthViewIdx: number) {
```
Comment (hanastasov) [inline projects/igniteui-angular/src/lib/calendar/calendar.ts]: This function name does not represent what it does, because it does not return a date PER a given month, it always returns the date for the FIRST month view in the calendar. IMO it should be renamed to smth like "getFirstMonthViewDate" or "getDateFirstMonthView"

**Comment by Aleksandyr** [comment]
@rkaraivanov the pipes have been introduced. Could you review the changes again?

File: projects/igniteui-angular/src/lib/calendar/months-view.pipe.ts [hunk 8]
```diff
@@ -0,0 +1,25 @@
+import { Pipe, PipeTransform } from '@angular/core';
+import { Calendar } from './calendar';
+
+@Pipe({
+    name: 'monthViewsSlots'
```
Comment (rkaraivanov) [inline projects/igniteui-angular/src/lib/calendar/months-view.pipe.ts]: Maybe prefix the name with `igx`

File: projects/igniteui-angular/src/lib/calendar/months-view.pipe.ts [hunk 9]
```diff
@@ -0,0 +1,25 @@
...
+})
+export class IgxMonthViewsGen implements PipeTransform {
```
Comment (rkaraivanov) [inline projects/igniteui-angular/src/lib/calendar/months-view.pipe.ts]: Add a Pipe suffix. Easier to grok what kind of Angular component that class is.

File: projects/igniteui-angular/src/lib/calendar/months-view.pipe.ts [hunk 10]
```diff
@@ -0,0 +1,25 @@
...
+    public transform(monthViews) {
```
Comment (rkaraivanov) [inline projects/igniteui-angular/src/lib/calendar/months-view.pipe.ts]: Add types

File: projects/igniteui-angular/src/lib/calendar/months-view.pipe.ts [hunk 11]
```diff
@@ -0,0 +1,25 @@
...
+        return new Array(monthViews);
+    }
+}
+
+@Pipe({
+    name: 'getViewDate'
```
Comment (rkaraivanov) [inline projects/igniteui-angular/src/lib/calendar/months-view.pipe.ts]: As above

File: projects/igniteui-angular/src/lib/calendar/months-view.pipe.ts [hunk 12]
```diff
@@ -0,0 +1,25 @@
...
+})
+export class IgxGetViewDate implements PipeTransform {
```
Comment (rkaraivanov) [inline projects/igniteui-angular/src/lib/calendar/months-view.pipe.ts]: As above
