### PR TITLE
Bypass all calls to browsers' object when not on browser platform

### LINKED ISSUE #4426: NavDrawer breaks server-side rendering
## Description  
I tried to build and app-shell that uses the nav-drawer in the app.component, and the build fails.

 * igniteui-angular version: 7.2.2
 * browser: N/A

## Steps to reproduce  

1. Create a default cli project with side-nav.
2. Add an app-shell and build.

## Result  
Build fails.

## Expected result  
Build should pass.

## Attachments  

> Hammer is not defined
> ReferenceError: Hammer is not defined
>     at new HammerGesturesManager (D:\GitHub\angular-training\node_modules\igniteui-angular\bundles\igniteui-angular.umd.js:67038:29)
>

### PR DESCRIPTION
**Pull request by wnvko**
There were some places in `touch.ts` as well as in `IgxNavDrawer` where we were calling browser related things, like `requestAnimationFrame`. Now we are checking if there platform where build runs is browser platform. If not, e.g. server side rendering, we skip calling browsers' methods.

Closes #4426 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-cell.component.ts [hunk 1]
```diff
@@ -27,10 +28,11 @@ export class IgxHierarchicalGridCellComponent extends IgxGridCellComponent imple
...
         private helement: ElementRef,
         protected zone: NgZone,
-        touchManager: HammerGesturesManager
+        touchManager: HammerGesturesManager,
+        protected platformUtil: PlatformUtil
         ) {
-            super(selectionService, crudService, gridAPI, selection, cdr, helement, zone, touchManager);
-            this.hSelection = <IgxHierarchicalSelectionAPIService>selection;
+            super(selectionService, crudService, gridAPI, selection, cdr, helement, zone, touchManager, platformUtil);
+            // this.hSelection = <IgxHierarchicalSelectionAPIService>selection;
```
Comment (damyanpetev) [inline projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-cell.component.ts]: This doesn't seem related to the change

Comment (wnvko) [reply projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-cell.component.ts]: Yech, the cherry pick from 8.3.x has introduced some hard to merge conflicts. I missed this one - thank you.
