### PR TITLE
Handle number/string date values in sorting, filtering, ESF - 10.2.x

### LINKED ISSUE #8350: Filtering/sorting result over a column with dates in ISO strings is not correct
If a column is of type dataType='date' and values come as ISO strings (`2011-10-05T14:48:00.000Z`), or as number representing the time miliseconds, filtering and sorting results are not correct.

 * igniteui-angular version: 9.1, 10.1, 10.2

## Steps to reproduce  

1. Open gridCellEditing sample in dev demos
2. Sort/filter the OrderDate column

## Result  
Result is not correct

## Expected result  
Result to be correct

### PR DESCRIPTION
**Pull request by hanastasov**
Closes #8350  #8351 

Behaviral changes: See **Values formatting** under [ESF Specification](https://github.com/IgniteUI/igniteui-angular/wiki/Excel-Style-Filtering):

- [x] Implementation
- [x] Tests
> Values in the ESF list should be formatted in the same way as values in the column itself, according to the grid locale property and column pipeArgs property values, or according to the column formatter. If formatter is available, it takes precedence. If the formatter formats the blank values too, the label for blank values in the ESF should be formatted accordingly.

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [x] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [x] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Review by DiyanDimitrov — APPROVED** [review]

**Comment by hanastasov** [comment]
Last commit resolves the following bug:

1. Open the grid formatting sample
2. Open ESF dialog for OrderDate2 column
3. Select more than two items to filter.
4. Apply filtering and close the ESF dialog.
5. Open again the ESF dialog.

Result:
The filtered items are not selected

**Comment by hanastasov** [comment]
Last commit(https://github.com/IgniteUI/igniteui-angular/pull/8454/commits/9cf05cf6400aef56219b38bab80b7c93d4832c75) removes the date timezone formatting in the inputs of the `igxDatePicker`, because `igxDatePicker` picks a **date** and formatting that may be misleading for the user.

File: projects/igniteui-angular/src/lib/core/utils.ts [hunk 1]
```diff
@@ -98,10 +98,43 @@ export function isObject(value: any): boolean {
...
     return Object.prototype.toString.call(value) === '[object Date]';
 }
 
+/**
+ * Parse provided input to Date.
+ * @param value input to parse
+ * @returns Date if parse succeed or null
+ * @hidden
+ */
+export function parseDate(value: any): Date | null {
```
Comment (kdinev) [inline projects/igniteui-angular/src/lib/core/utils.ts:111]: I don't think you need to perform the type checking for number. Just reduce this to returning `new Date(value)` if the value is not instance of Date.

**Review by kdinev — DISMISSED** [review]

File: projects/igniteui-angular/src/lib/core/utils.ts (hunk 1 above)
Comment (hanastasov) [reply projects/igniteui-angular/src/lib/core/utils.ts:111]: I kept the check for `value`, otherwise for `null` values of `value`, the method would return `Invalid Date` or `01 Jan 1970`

File: projects/igniteui-angular/src/lib/core/utils.ts [hunk 2]
```diff
@@ -98,10 +98,38 @@ export function isObject(value: any): boolean {
  * @returns true if provided variable is Date
  * @hidden
  */
-export function isDate(value: any) {
+export function isDate(value: any): boolean {
     return Object.prototype.toString.call(value) === '[object Date]';
```
Comment (kdinev) [inline projects/igniteui-angular/src/lib/core/utils.ts:102]: Shouldn't this be `value instanceof Date'?

Comment (hanastasov) [reply projects/igniteui-angular/src/lib/core/utils.ts:102]: Sounds cleaner to me too.

**Review by zdrawku — APPROVED** [review]
