### PR TITLE
fix(docs): Fixing documentation issues #2100

### LINKED ISSUE #2100: Improve docs
### Description  
Several issues inside the docs should be addressed 

 * igniteui-angular version: 6.1.0
 * browser:  N/A

### Steps to reproduce  

1. Missing members description: ignite-ui-angular/docs/typescript/enums/igxcombostate.html 

2. IPositionStrategy is listed twice in "Implements" section:
ignite-ui-angular/docs/typescript/classes/autopositionstrategy.html

3.1 onSearchInput > "Emitted when an the search input's input event is triggered". This needs to be explained better 
3.2 groupKey > "Combo item group". This needs to be explained better.
3.3 close > "A method that closes the dialog". -> Closes the **dropdown list.**
3.4 onArrowDown > Description needs to be provided
3.5 open > "A method that opens the dialog".  -> Opens the **combo**.
3.6 setDisabledState > Dexcription needs to be provided
3.7 IgxDropDownBase entire description starting from `-Documentation` link until the `Example:` (including the example) should be moved to igxComboComponent.
ignite-ui-angular/docs/typescript/classes/igxcombocomponent.html

4.1 onToggleClosing > Description needed
4.2 updateScrollPosition > Description needed
ignite-ui-angular/docs/typescript/classes/igxcombodropdowncomponent.html

5. transform method > Description needed
ignite-ui-angular/docs/typescript/classes/igxcombofilterconditionpipe.html
 
 6. Descriptions needed > ignite-ui-angular/docs/typescript/classes/igxcombofilteringpipe.html
 
 7. Descriptions needed > ignite-ui-angular/docs/typescript/classes/igxcombogroupingpipe.html
 
 8.1 -  itemHeight > Description needed
 8.2 - clicked > Descrition needed
 8.3 - markItemSelected > Descrition needed
 ignite-ui-angular/docs/typescript/classes/igxcomboitemcomponent.html
 
 9. markItemSelected - Description needed > ignite-ui-angular/docs/typescript/classes/igxdropdownitembase.html
 
 10. Descriptions needed
 ignite-ui-angular/docs/typescript/classes/igxnavdraweritemdirective.html
 
 11. template - description needed: ignite-ui-angular/docs/typescript/classes/igxnavdrawerminitemplatedirective.html
 
 12. Descriptions needed
 ignite-ui-angular/docs/typescript/classes/igxnavigationclosedirective.html
 
 13. Descriptions needed
ignite-ui-angular/docs/typescript/classes/igxoverlayservice.html
 
 14. Hidden accsessors visible
ignite-ui-angular/docs/typescript/classes/igxnavigationdrawercomponent.html

### PR DESCRIPTION
**Pull request by dafo**
Closes #2100  .

### CODE REVIEW

**Comment by damyanpetev** [comment]
Kind of a similar question with `DataTypes` - either don't export it or describe it's usage and rename it to something like `[Igx]ComboDataTypes`

File: projects/igniteui-angular/src/lib/combo/combo.component.ts [hunk 1]
```diff
@@ -680,8 +696,11 @@ export class IgxComboComponent implements AfterViewInit, ControlValueAccessor, O
         return compareFunc;
     }
 
-    @HostListener('keydown.ArrowDown', ['$event'])
-    @HostListener('keydown.Alt.ArrowDown', ['$event'])
+    /**
+     * @hidden
+     */
+    // @HostListener('keydown.ArrowDown', ['$event'])
+    // @HostListener('keydown.Alt.ArrowDown', ['$event'])
```
Comment (damyanpetev) [inline projects/igniteui-angular/src/lib/combo/combo.component.ts]: @dafo @Lipata You guys sure those host bindings are not needed?

Comment (damyanpetev) [inline projects/igniteui-angular/src/lib/combo/combo.component.ts]: Yeah that's the only binding for `onArrowDown`, so those should be uncommented
