### PR TITLE
Range picker keyboard navigation - 10.2.x

### LINKED ISSUE #9048: Range picker does not expand on Alt + ArrowDown when in dialog mode
* igniteui-angular version: 10.2.x, 11.0.x, 11.1.x
 * browser: n/a

## Steps to reproduce  

1. Open this [link](https://www.infragistics.com/products/ignite-ui-angular/angular/components/date-range-picker)
2. Navigate to the first sample.
3. Focus the picker.
4. Press `Alt` + `ArrowDown`
5. Observe

## Result  
Nothing happens.

## Expected result  
The calendar pops up in `dialog` mode and the current date is selected.

### PR DESCRIPTION
**Pull request by jackofdiamond5**
Closes #9048

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.ts [hunk 1]
```diff
@@ -599,13 +599,11 @@ export class IgxDateRangePickerComponent extends DisplayDensityBase
...
     /** @hidden */
     public ngAfterViewInit(): void {
-        if (this.mode === InteractionMode.DropDown) {
-            this.attachOnKeydown();
-        }
         this.subscribeToDateEditorEvents();
         this.configPositionStrategy();
         this.configOverlaySettings();
         this.cacheFocusedInput();
+        this.attachOnKeydown();
```
Comment (damyanpetev) [inline projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.ts:606]: Just make this a `HostListener` at this point, since it's no longer under a condition. This will also let you easily properly test the open portion (which currently triggers on the (not visible) calendar.. to open it)

**Review by damyanpetev — APPROVED** [review]
