### PR TITLE
Checkbox indeterminate state, ripple, and label position

### LINKED ISSUE #527: igx-checkbox should be inline element
### Description  
igx-checkbox should be inline element.

### Steps to reproduce  

1. Unzip [igx-checkbox 2.zip](https://github.com/IgniteUI/igniteui-angular/files/1675688/igx-checkbox.2.zip)
2. npm install
3. ng serve -o

### Result  
igx-checkbox is block-level element, so that the following text starts on a new line. 

### Expected result  
igx-checkbox should be inline element and the following text should be on the same line.

### Attachments  
[igx-checkbox 2.zip](https://github.com/IgniteUI/igniteui-angular/files/1675688/igx-checkbox.2.zip)

### LINKED ISSUE #787: igx-checkbox indeterminate state
### Description  
Add a third - indeterminate - state to the `igx-checkbox`.

### PR DESCRIPTION
**Pull request by simeonoff**
Closes #527, closes #787

### CODE REVIEW

File: src/checkbox/checkbox.component.ts [hunk 1]
```diff
@@ -60,12 +80,25 @@ export class IgxCheckboxComponent implements ControlValueAccessor {
         this.checked = !!this._value;
     }
 
+    public get labelClass(): string {
+        switch (this.labelPosition) {
+            case LabelPosition.BEFORE:
+            case "before":
```
Comment (rkaraivanov) [inline src/checkbox/checkbox.component.ts]: If the `LabelPosition` is a string enumeration then this check is kind of redundant.

**Comment by simeonoff** [comment]
Closes #527, closes #787
