### PR TITLE
fix(excel-exporter): export date columns as valid dates in Excel

### LINKED ISSUE #8481: Excel Exporter export ISO strings/numbers, instead of date values
* igniteui-angular version: 9.1, 10.1, 10.2

## Steps to reproduce  

1. Go to Grid Formatting dev sample
2. Enable grid toolbar with export to excel:
```html
<igx-grid [showToolbar]="true" [exportExcel]="true"></igx-grid>
```
3. Export the grid to Excel\
4. Open the Excel file

## Result  
Date columns contain ISO string values

## Expected result  
Date columns to contain valid Excel date values

### PR DESCRIPTION
**Pull request by onlyexeption**
Closes #8481 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/services/exporter-common/base-export-service.ts [hunk 1]
```diff
@@ -232,8 +233,14 @@ export abstract class IgxBaseExporter {
...
-                    const rawValue = this._isTreeGrid ? resolveNestedPath(rowData.data, e.field) : resolveNestedPath(rowData, e.field);
-                    a[e.header] = e.formatter && !e.skipFormatter ? e.formatter(rawValue) : rawValue;
+                    let rawValue = this._isTreeGrid ? resolveNestedPath(rowData.data, e.field) : resolveNestedPath(rowData, e.field);
+                    const shouldApplyFormatter = e.formatter && !e.skipFormatter;
+
+                    if (e.dataType === 'date' && !shouldApplyFormatter && rawValue !== undefined && rawValue !== null) {
+                        rawValue = new Date(rawValue);
+                    }
+
+                    a[e.header] = shouldApplyFormatter ? e.formatter(rawValue) : rawValue;
```
Comment (DiyanDimitrov) [inline projects/igniteui-angular/src/lib/services/exporter-common/base-export-service.ts:243]: If there is formatter we should not parse the value to Date.

**Review by DiyanDimitrov — CHANGES_REQUESTED** [review]
Add tests for grid export with a column with dataType date and ISO strings/numbers.

File: projects/igniteui-angular/src/lib/services/exporter-common/base-export-service.ts [hunk 2]
```diff
@@ -232,8 +233,14 @@ export abstract class IgxBaseExporter {
...
             row = this._columnList.reduce((a, e) => {
                 if (!e.skip) {
-                    const rawValue = this._isTreeGrid ? resolveNestedPath(rowData.data, e.field) : resolveNestedPath(rowData, e.field);
-                    a[e.header] = e.formatter && !e.skipFormatter ? e.formatter(rawValue) : rawValue;
+                    let rawValue = this._isTreeGrid ? resolveNestedPath(rowData.data, e.field) : resolveNestedPath(rowData, e.field);
+                    const shouldApplyFormatter = e.formatter && !e.skipFormatter;
+
+                    if (e.dataType === 'date' && !shouldApplyFormatter && rawValue !== undefined && rawValue !== null) {
+                        rawValue = new Date(rawValue);
+                    }
```
Comment (DiyanDimitrov) [inline projects/igniteui-angular/src/lib/services/exporter-common/base-export-service.ts:241]: If the value is a Date object we should not convert it.

**Review by DiyanDimitrov — CHANGES_REQUESTED** [review]

**Review by DiyanDimitrov — DISMISSED** [review]

**Review by DiyanDimitrov — APPROVED** [review]
