### PR TITLE
fix(slider): properly adjusting bounds #13403

### LINKED ISSUE #13403: igx-slider quick mouse move
## Description  
When reviewing [https://www.infragistics.com/products/ignite-ui-angular/angular/components/slider/slider](https://www.infragistics.com/products/ignite-ui-angular/angular/components/slider/slider), we're noticing issues where if you move the cursor quickly, the slider stops moving, and the value does not end at the min or max value (stops at some random values).  If you review the attached .gif, the issue is not regarding skipping values in the middle of the slider, when sliding horizontally. The issue is when the cursor goes beyond the min/max value, and the last value captured in the input box displays a number that is not the min/max value. Since the slider exceeded the range, it should stop at the min or max when sliding horizontally.  We are in the process of upgrading an application from Angular 11 -> 16. After each version upgrade we perform regression testing. This issue was not present with Angular 11, and it has just been noticed when going from 13 to 14 ("@infragistics/igniteui-angular": "~14.2.40").
 
This behavior is not shown with Angular Material slider: [https://material.angular.io/components/slider/overview#formatting-the-thumb-label](https://material.angular.io/components/slider/overview#formatting-the-thumb-label) (quickly sliding back and forth always ends at 0 or 100k).

Reviewed with support and they recommended I submit a bug report.  The behavior was present in the sample application provided by support: [https://stackblitz.com/edit/5ffbqi?file=src%2Fapp%2Fslider-sample-2%2Fslider-sample-2.component.html](https://stackblitz.com/edit/5ffbqi?file=src%2Fapp%2Fslider-sample-2%2Fslider-sample-2.component.html)

 * igniteui-angular version: 14.2.40+
 * browser: Chrome 116.0.5845.111

## Steps to reproduce  

1. Click and hold the upper or lower slider
2. Move the slider left and right (quickly), exceeding the min / max values

## Result  
What is the actual result after following the steps to reproduce?
When moving to the left of the min value, the min value observed in the input box is not always the min value.
When moving to the right of the max value, the max value observed in the input box is not always the max value.

## Expected result  
What is the expected result after following the steps to reproduce?
When moving to the left of the min value, the min value observed in the input box shall always be the min value.
When moving to the right of the max value, the max value observed in the input box shall always be the max value.

## Attachments  
See attached .gif file

slider-mouse-issue-v2

### PR DESCRIPTION
**Pull request by kdinev**
Closes #13403  

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/slider/slider.component.ts [hunk 1]
```diff
@@ -1122,28 +1124,26 @@ export class IgxSliderComponent implements
 
         if (this.isRange) {
             if (thumbType === SliderHandle.FROM) {
-                const newLower = this.lowerValue + value;
-                if (newLower >= this.lowerBound && newLower <= this.upperValue) {
-                    this._lowerValue = newLower;
-                    this.lowerValueChange.emit(this._lowerValue);
+                if (this.lowerValue + value > this.upperValue) {
+                    this.upperValue = this.lowerValue + value;
```
Comment (hanastasov) [inline projects/igniteui-angular/src/lib/slider/slider.component.ts:1128]: Hm, I dont think this makes sense. It seems upperValue is restricted in range, so it make no sense to set it to `this.lowerValue + value`

I believe it was only the if statement in original code that was causing errors, and now in new code it is just enough to remove the if clause and just keeps this.lowerValuye += value and this.upperValue += value.

Comment (kdinev) [reply projects/igniteui-angular/src/lib/slider/slider.component.ts:1128]: I tried without adjusting the upper and lower values and it didn't work. The handle was getting stuck at the upper value when moving the lower handle beyond it, and at lower, when moving upper handle beyond it. I made the upper and lower adjust to the other handle if the interaction is still in the provided bounds.

Comment (hanastasov) [reply projects/igniteui-angular/src/lib/slider/slider.component.ts:1128]: Thanks for explaining. I tested thoroughly once again and in my observation is that adjusting the `upperValue` and `lowerValue` in the if statement did not make difference. Still this is not so important anyway.

I confirm the problematic behavior is now gone and `lowerValue` and `upperValue` are updated as expected on lines 1130 and 1135.

Based on my testing, I logged another issue - https://github.com/IgniteUI/igniteui-angular/issues/13490 which may be planned as a minor enhancement for near sprints.

**Review by hanastasov — APPROVED** [review]
