### PR TITLE
fix(query-builder): delete empty groups - master

### LINKED ISSUE #14882: Query Builder: Extra space remains when a group is deleted
## Description  
Extra space remains when a group is deleted

 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Open QueryBuilder samples - https://www.infragistics.com/products/ignite-ui-angular/angular/components/query-builder
2. Add new 'And' group
3. Select the chips in the group
4. Create 'Or' group
5. Click on the 'Or' group operator line
6. Delete the group

QB_issue10

## Result  
There is extra space above the action buttons
image

## Expected result  
image

### PR DESCRIPTION
**Pull request by igdmdimitrov**
Closes #14882   

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/query-builder/query-builder.component.ts [hunk 1]
```diff
@@ -768,10 +768,26 @@ export class IgxQueryBuilderComponent implements AfterViewInit, OnDestroy {
...
+                    parent = parent.parent;
+                }
+    
+                if (parent) {
+                    index = parent.children.indexOf(childGroup);
+                    parent.children.splice(index, 1);
+                } else {
+                    this.rootGroup = null;
+                }
+            }
```
Comment (gedinakova) [inline projects/igniteui-angular/src/lib/query-builder/query-builder.component.ts:790]: We have some code repetiotion here that I believe is possible to be made simpler, probably with a `while` construct.

**Review by gedinakova — CHANGES_REQUESTED** [review]

File: projects/igniteui-angular/src/lib/query-builder/query-builder.component.ts [hunk 2]
```diff
@@ -768,10 +768,26 @@ export class IgxQueryBuilderComponent implements AfterViewInit, OnDestroy {
      */
     public deleteGroup() {
         const selectedGroup = this.contextualGroup;
```
Comment (gedinakova) [inline projects/igniteui-angular/src/lib/query-builder/query-builder.component.ts:770]: In order to avoid repetition, we could change the logic here to smth like:
```suggestion
       let selectedGroup = this.contextualGroup;
        let parent = selectedGroup.parent;
        if (!parent)
            this.rootGroup = null;

        while (parent) {
            let index = parent.children.indexOf(selectedGroup);
            parent.children.splice(index, 1);                     
            selectedGroup = parent;
            parent = parent.children.length === 0 ? parent.parent : null;
        }

        if (this.rootGroup?.children.length === 0) {
            this.rootGroup = null;
        }
```

**Review by gedinakova — CHANGES_REQUESTED** [review]

**Review by gedinakova — APPROVED** [review]
