### PR TITLE
Makes filter value nullable when setting grid in data selector

### LINKED ISSUE #11050: Handle null filters value within the pivot configuration in the data selector component
Related to #10736 

## Description  
The `IPivotConfiguration` does not require the filters-property and defaults to null if it's not present, so the case when there's no filters in the configuration should be handled in order to avoid the error below.

 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Set the filters in the pivot configuration within the pivot dev-sample to null
2. Open the sample and observe the error

## Expected result  
What is the expected result after following the steps to reproduce?

## Attachments  
Attach a sample if available, and screenshots, if applicable.

### PR DESCRIPTION
**Pull request by 3phase**
Closes #11050

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Review by dkamburov — DISMISSED** [review]

File: projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-data-selector.component.ts [hunk 1]
```diff
@@ -170,7 +170,7 @@ export class IgxPivotDataSelectorComponent {
         this.dims = [
```
Comment (MayaKirova) [inline projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-data-selector.component.ts:170]: Since all collections could potentially be set to null same should be applied to the other collections or you can use the `allDimensions` property in the pivot grid.

Comment (3phase) [reply projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-data-selector.component.ts]: The requested changes are done

**Review by MayaKirova — APPROVED** [review]
