### PR TITLE
fix(grid): recalculate grid body size when changing allowFiltering dynamically

### LINKED ISSUE #3290: Filtering Row covers the first row of igxGrid when it is dynamically activated and Multi Column Headers are used
### Description  
Filtering Row covers the first row of igxGrid when it is dynamically activated and Multi Column Headers are used

 * igniteui-angular version: 7.0.x
 * browser: all

### Steps to reproduce  

1. Open dev demos and go to grid-column-groups.sample.html
2. Remove [allowFiltering]="true" .
3. Add button :
```
<button type="button" (click)="setFilter()">Set Filtering</button>
```
4. Add handler in typescript:
```
    setFilter() {
        this.grid.allowFiltering = !this.grid.allowFiltering;
        this.grid.cdr.markForCheck();
      }
```
5. Run the demos and click the button.
6. Click filter chip.

### Result  
5. The filtering row appears over the first grid row.
6. The filtering UI appears above the filtering row.

### Expected result  
5. The filtering row should push down the first grid row.
6. The filtering UI should replace the filtering row.

Note: everything works as expected if there are no Multi Column Headers used.

### Attachments  
filteringtest

### PR DESCRIPTION
**Pull request by SAndreeva**
Closes #3290

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/grid-base.component.ts [hunk 1]
```diff
@@ -2379,6 +2389,10 @@ export abstract class IgxGridBaseComponent extends DisplayDensityBase implements
         }
     }
 
+    get defaultFilterRowHeight(): number {
```
Comment (bkulov) [inline projects/igniteui-angular/src/lib/grids/grid-base.component.ts]: This doesn't need to be property. You could make it protected constant.
