### PR TITLE
fix(IgxGrid): Don't use spread operator for large collections.

### LINKED ISSUE #15681: Grid Grouping doesn't work with big data set
## Description  
Grouping can throw errors when the grid has lots of data.

 * igniteui-angular version: 19.1.6

## Steps to reproduce  

1. https://stackblitz.com/edit/d6z2qjjz-u4ddpzwy
2. Group by Order Time

## Result  
The grouping doesn't work and an exception is thrown:

Image

Image

### PR DESCRIPTION
**Pull request by MayaKirova**
Closes #15681   

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/common/strategy.ts [hunk 1]
```diff
@@ -117,23 +117,24 @@ export class IgxSorting implements IGridSortingStrategy {
             fullResult.metadata.push(null);
             if (level < expressions.length - 1) {
                 recursiveResult = this.groupDataRecursive(group, state, level + 1, groupRow,
-                    expanded ? metadata : [], grid, groupsRecords, fullResult);
+                    [], grid, groupsRecords, fullResult);
                 if (expanded) {
-                    result = result.concat(recursiveResult);
+                    result = result.concat(recursiveResult.data);
```
Comment (skrustev) [inline projects/igniteui-angular/src/lib/grids/common/strategy.ts:122]: This is good to turn into practice imo. `concat` is much faster for large arrays anyway.

**Review by skrustev — APPROVED** [review]
