### PR TITLE
fix(h-grid): add null checks for child data - 20.0.x

### LINKED ISSUE #15908: [Elements] Hierarchical grid Advanced filtering does not open with WC 6.0.0-beta.0
## Description  
Hierarchical grid with Advanced filtering in the toolbar does not open when you click the Advanced Filtering button.

You can refer to this sample: https://staging.infragistics.com/products/ignite-ui-web-components/web-components/components/grids/hierarchical-grid/advanced-filtering#web-components-hierarchical-grid-advanced-filtering-example

 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Click the advanced filtering button on the root level of the grid.

## Result  
Error is thrown: 

ERROR TypeError: Cannot read properties of undefined (reading '0')
    at 1623.a2d35d56.chunk.js:8:585747
    at Array.reduce (<anonymous>)
    at wl.reduce (1623.a2d35d56.chunk.js:2:554487)
    at e.generateChildEntity (1623.a2d35d56.chunk.js:8:585686)
    at 1623.a2d35d56.chunk.js:8:585321
    at Array.reduce (<anonymous>)
    at wl.reduce (1623.a2d35d56.chunk.js:2:554487)
    at e.generateSchema (1623.a2d35d56.chunk.js:8:585292)
    at get schema (1623.a2d35d56.chunk.js:8:576158)
    at e.generateEntity (1623.a2d35d56.chunk.js:2:1578003)

And dialog does not open.

## Expected result  
Dialog opens with no error.

## Attachments  
Attach a sample if available, and screenshots, if applicable.

### PR DESCRIPTION
**Pull request by igdmdimitrov**
Closes #15908 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts [hunk 1]
```diff
@@ -1289,7 +1291,9 @@ export class IgxHierarchicalGridComponent extends IgxHierarchicalGridBaseDirecti
             if (!firstRowData) {
                 return null;
             }
-            return acc.concat(this.generateChildEntity(childRowIsland, firstRowData[childRowIsland.key][0]));
+            const childFirstRowData = firstRowData?.length > 0 && firstRowData[childRowIsland.key]?.length > 0 ?
```
Comment (gedinakova) [inline projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts]:
```suggestion
            const childFirstRowData = firstRowData.length > 0 && firstRowData[childRowIsland.key]?.length > 0 ?
```
