### PR TITLE
Emmiting onSortingDone in chip. (master)

### LINKED ISSUE #3257: onSortingDone is not fired when sorting indicator of a header in the group by area is clicked.
### Description  
onSortingDone is not fired when sorting indicator of a header in the group by area is clicked.

 * igniteui-angular version: 7.0.1
 * browser: N/A

### Steps to reproduce  

1. Run the attached sample application.
2. Next, drag one of the headers to the group by area. -> onGroupingDone is fired (expected)
3. Click the sorting indicator in the group-by chip.

### Result  
onSortingDone is not fired.
If it were fired, an alert message would be displayed.)

### Expected result  
onSortingDone is fired.

### Attachments  
Attach a sample if available, and screenshots, if applicable.  
[my-app2.zip](https://github.com/IgniteUI/igniteui-angular/files/2638204/my-app2.zip)

### PR DESCRIPTION
**Pull request by MartinKamenov**
Closes #3257 

### Additional information (check all that apply):
 - [x] Bug fix

### Checklist:
 - [x] All relevant tags have been applied to this PR

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/grid/grid.component.ts [hunk 1]
```diff
@@ -743,6 +743,12 @@ export class IgxGridComponent extends IgxGridBaseComponent implements OnInit, Do
         const columnExpr = sortingExpr.find((expr) => expr.fieldName === event.owner.id);
         columnExpr.dir = 3 - columnExpr.dir;
         this.sort(columnExpr);
+        this.onSortingDone.emit({
```
Comment (kdinev) [inline projects/igniteui-angular/src/lib/grids/grid/grid.component.ts]: The event is emitted from the wrong component, before and after your fix. The event should be emitted by the grid, whenever `sort()` is called.

Currently it's emitted by the `IgxHeaderComponent` on click, or by the `IgxChip` in the group by area on click. Both should be removed and `onSortingDone` should be emitted by the `sort()` method, as just mentioned.

**Comment by ChronosSF** [comment]
Please, resolve the merge conflicts from the base branch so we can review again.
