### PR TITLE
fix(autocomplete): close dropdown when list is empty - 10.2.x

### LINKED ISSUE #3977: There is a shadow, when autocomplete list is empty
## Description  
When autocomplete is filtered so that there are no items left, there is still a shadow.

## Attachments  
image

### PR DESCRIPTION
**Pull request by ViktorSlavov**
Closes #3977

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/directives/autocomplete/autocomplete.directive.ts [hunk 1]
```diff
@@ -293,31 +293,20 @@ export class IgxAutocompleteDirective extends IgxDropDownItemNavigationDirective
...
         this.target.close();
-        this.dropDownOpened$.next();
     }
 
     /**
      * Opens autocomplete drop down
      */
     public open() {
-        if (this.disabled || !this.collapsed) {
+        if (this.disabled || !this.collapsed || this._lastListLength === 0 || this._opening) {
```
Comment (damyanpetev) [inline projects/igniteui-angular/src/lib/directives/autocomplete/autocomplete.directive.ts:302]: Yeah, if we're going to to use a flag anyway, this seems like the harder way to do it - since it's harder to manage more flags and it's easier to miss sometimes:
1. Type a repeat letter fast ("dd") that doesn't match on the second char
2. You get the second filter during animation, thus the opened event never fires before the close
3. DD now permanently stuck in closed state 
image


Alternative, that's a bit easier to follow - setup a `shouldBeOpen` flag on `open()` and `close()` and use it during the list change to determine if you need to do something

**Review by damyanpetev — CHANGES_REQUESTED** [review]

File: projects/igniteui-angular/src/lib/directives/autocomplete/autocomplete.directive.ts [hunk 2]
```diff
@@ -354,7 +343,24 @@ export class IgxAutocompleteDirective extends IgxDropDownItemNavigationDirective
...
+    public ngAfterViewInit() {
+        this.target.children.changes.pipe(takeUntil(this.destroy$)).subscribe(() => {
+            if (this.target.children.length) {
+                if (!this.collapsed) {
+                    this.highlightFirstItem();
+                } else if (this._shouldBeOpen) {
+                    this.open();
+                }
+            } else {
+                this.highlightFirstItem();
```
Comment (damyanpetev) [inline projects/igniteui-angular/src/lib/directives/autocomplete/autocomplete.directive.ts:359]: Feels a bit odd - should it be `.target.clearSelection()` on close?

Comment (damyanpetev) [reply projects/igniteui-angular/src/lib/directives/autocomplete/autocomplete.directive.ts:359]: Also seems to work just fine without this call as far as I can tell.

File: projects/igniteui-angular/src/lib/directives/autocomplete/autocomplete.directive.spec.ts [hunk 3]
```diff
@@ -130,24 +130,54 @@ describe('IgxAutocomplete', () => {
...
+        it('Should close the dropdown when no items match the filter', fakeAsync(() => {
+            expect((autocomplete as any).collapsed).toEqual(true);
+            spyOn(autocomplete, 'close').and.callThrough();
+            spyOn(autocomplete, 'open').and.callThrough();
+            spyOn(autocomplete.target, 'open').and.callThrough();
+            expect(autocomplete.close).not.toHaveBeenCalled();
+            UIInteractions.setInputElementValue(input, 'a', fixture);
+            tick();
+            expect(autocomplete.open).toHaveBeenCalledTimes(1);
+            expect(autocomplete.target.open).toHaveBeenCalledTimes(1);
```
Comment (damyanpetev) [inline projects/igniteui-angular/src/lib/directives/autocomplete/autocomplete.directive.spec.ts:143]: You can also check `target.collapsed` is in the correct state

**Review by damyanpetev — APPROVED** [review]
