### PR TITLE
Use visible index of the column

### LINKED ISSUE #4230: When the last column is hidden button RIGHT for the last visible column should be disabled
## Description  
When the last column is hidden button RIGHT for the last visible column should be disabled

 * igniteui-angular version: 7.2
 * browser: N/A

## Steps to reproduce  

1. Open Dev sample gridColumnMoving
2. Hide the last column (Contact)
3. Open excel filter for column DateCreated

## Result  
Button RIGHT is enabled, but when click on it nothing happens and the console an error is previewed

## Expected result  
Button RIGHT should be disabled

## Attachments  
image

### PR DESCRIPTION
**Pull request by sstoyanovIG**
Closes #4230   

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-column-moving.component.ts [hunk 1]
```diff
@@ -51,6 +52,10 @@ export class IgxExcelStyleColumnMovingComponent {
         this.grid.moveColumn(this.column, targetColumn, moveDirection);
     }
 
+    private get visibleColumns() {
```
Comment (bkulov) [inline projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-column-moving.component.ts]: You could move this property up in the file and place it where the other properties are.

Comment (sstoyanovIG) [reply projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-column-moving.component.ts]: done
