### PR TITLE
FIX- when column groups are hidden the grid layout is broken

### LINKED ISSUE #11239: Collapsible Column Groups the group is not expanded
When the group is the last column in the grid in the grid, and there are no other groups, and the hidden fields are not the last fields in the group, it does not expand the group, and all keyboard navigation fails, and in other cases, the Grid doesn't re-work itself for the space created. I'll add a video

https://www.screencast.com/t/eRNVGkpg

1) Make the group is the last column in the grid and the only one group column
2) Hide some columns from the group (not the last columns)
3) Try to expand the group

## Result  
 it does not expand the group
all keyboard navigation fails, and in other cases, the Grid doesn't re-work itself for the space created

## Expected result  
Group is expanded

## Attachments  
[Attach a sample if available, and screenshots, if applicable.  ](https://www.screencast.com/t/eRNVGkpg)

### PR DESCRIPTION
**Pull request by ddincheva**
Closes #11239 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by ddincheva** [comment]
When performing testing, please verify that issue #10664 is not reintroduced with this bug fix.

**Review by dobromirts — DISMISSED** [review]

File: projects/igniteui-angular/src/lib/grids/grid-base.directive.ts [hunk 1]
```diff
@@ -3555,7 +3555,7 @@ export abstract class IgxGridBaseDirective extends DisplayDensityBase implements
         });
 
         this.verticalScrollContainer.contentSizeChange.pipe(filter(() => !this._init), destructor).subscribe(() => {
```
Comment (MayaKirova) [inline projects/igniteui-angular/src/lib/grids/grid-base.directive.ts:3557]: Shouldn't there be a throttleTime here as well, like in the PRs to 13.2.x and 14.0.x?

**Review by MayaKirova — APPROVED** [review]

**Review by hanastasov — APPROVED** [review]
