### PR TITLE
fix(grid): Add check for shadowRoot

### LINKED ISSUE #10106: DragDrop is not possible when using Shadow Dom
## Description  
The dropable area is not identified when dispatching a drag event.

 * igniteui-angular version: latest
 * browser: any

## Steps to reproduce  

1. Open the app builder front end and back end with dev branch SAndreeva/grid-properties-v1
2. Enable Column Moving and GroupBy Features.
3. It is not possible to perform drop action

## Expected result  
Should be able to drop
test

## Attachments  
image

Should be
image

### PR DESCRIPTION
**Pull request by zdrawku**
Closes #10106 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Review by hanastasov — APPROVED** [review]

File: projects/igniteui-angular/src/lib/directives/drag-drop/drag-drop.directive.ts [hunk 1]
```diff
@@ -1211,10 +1211,18 @@ export class IgxDragDirective implements AfterContentInit, OnDestroy {
             originalEvent
         };
 
-        const elementsFromPoint = this.getElementsAtPoint(pageX, pageY);
+        let elementsFromPoint = this.getElementsAtPoint(pageX, pageY);
+
+        // Check for shadowRoot instance and use it if present
+        for (const elFromPoint of elementsFromPoint) {
```
Comment (skrustev) [inline projects/igniteui-angular/src/lib/directives/drag-drop/drag-drop.directive.ts:1217]: If there is a regular element without shadow root above the one with shadow root, would this for cycle skip that element above it?

**Review by skrustev — APPROVED** [review]

File: projects/igniteui-angular/src/lib/directives/drag-drop/drag-drop.directive.ts (hunk 1 above)
Comment (zdrawku) [reply projects/igniteui-angular/src/lib/directives/drag-drop/drag-drop.directive.ts:1217]: Thank you, Svetlio. @dobromirts lets create and app that will have a grid in iframe and a overlapping dialog that will consist two draggable/dropabble elements within. After the grid iframe is loaded, open the dialog and try to move the draggable elements. Check if the element could be dropped. Use this application as a starting point:

https://stackblitz.com/edit/github-ilmjhj?file=src%2Fapp%2Fdialog-sample-1%2Fdialog-sample-1.component.ts
