### PR TITLE
Date Picker: fix InvalidDate error in IE11

### LINKED ISSUE #5087: [igx-date-picker] Console errors in date picker dev demo in IE
## Description  
Errors in date-picker demo in IE

 * igniteui-angular version: NA
 * browser: IE

## Steps to reproduce  

1. Open date-picker dev demo
2. Open 'Retemplated Date Picker'.

## Result  
Console errors 
InvalidPipeArgument: 'Unable to convert "Invalid Date" into a date' for pipe 'DatePipe'

## Expected result  
No errorrs

## Attachments  
Attach a sample if available, and screenshots, if applicable.

### PR DESCRIPTION
**Pull request by SAndreeva**
Closes #5087

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts [hunk 1]
```diff
@@ -1240,6 +1240,17 @@ export class IgxDatePickerComponent implements IDatePicker, ControlValueAccessor
     }
 
     private _setLocaleToDate(value: Date): string {
+        if (isIE()) {
+            // the replace() is a workaround fixing the following IE11 issue:
```
Comment (bkulov) [inline projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts]: This comment is no longer valid.
