### PR TITLE
Combo - properly update FormControl touched

### LINKED ISSUE #6475: Combo doesn't update FormControl.touched appropriately
## Description  
Similar as #6370, FormControl.touched not updated on focus/blur per `ControlValueAccessor` implementation. Since the FormControl manages value updates internally, setting `updateOn: 'blur'` without updating `touched`, the control never updates and value is never committed to the bound model.

 * igniteui-angular version: 8.2.x

## Steps to reproduce  

1. Run https://stackblitz.com/edit/angular-t7rmew
4. Focus the combo and observe the `touched` state
2. Select something in the combo
3. Focus out and observe the model `touched` state and value

## Result  
Form control touched should be updated and when updating on blur the bound model value should update and the model validity should reflect that.

## Expected result  
Touched is never set and the model value is never updated, causing the combo to be out of sync with the model - combo with selection and empty invalid model:
image

### PR DESCRIPTION
**Pull request by damyanpetev**
Closes #6475

### Additional information (check all that apply):
 - [X] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [X] All relevant tags have been applied to this PR
 - [X] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/combo/combo-dropdown.component.ts [hunk 1]
```diff
@@ -87,6 +87,7 @@ export class IgxComboDropDownComponent extends IgxDropDownComponent implements I
     public navigatePrev() {
         if (this._focusedItem && this._focusedItem.index === 0 && this.virtDir.state.startIndex === 0) {
             this.combo.focusSearchInput(false);
+            this.toggle();
```
Comment (ViktorSlavov) [inline projects/igniteui-angular/src/lib/combo/combo-dropdown.component.ts]: This will lead to the drop-down closing when navigating from the 1st list item w/ `ArrowUp`.
The toggle removed from the `focusSearchInput` is wrapped in a second `if`, so moving it here would change the combo's behavior.
