### PR TITLE
fix(sassdoc): normalize sassdoc json paths

### LINKED ISSUE #3053: Normalize typedoc josn file path in order to work on MAC
### Description  
Normalize sassdoc josn file path in order to work on MAC

### PR DESCRIPTION
**Pull request by Aleksandyr**
Closes #3053

### CODE REVIEW

File: gulpfile.js [hunk 1]
```diff
@@ -270,12 +270,12 @@ const TRANSLATIONS_REPO = {
...
 };
 
-const DOCS_OUTPUT_PATH = 'dist\\igniteui-angular\\docs'
+const DOCS_OUTPUT_PATH = path.join(__dirname, 'dist', 'igniteui-angular', 'docs');
 
 const TYPEDOC = {
-    EXPORT_JSON_PATH: 'dist\\igniteui-angular\\docs\\typescript-exported',
-    PROJECT_PATH: 'projects\\igniteui-angular\\src',
-    TEMPLATE_STRINGS_PATH: 'extras\\template\\strings\\shell-strings.json'
+    EXPORT_JSON_PATH: path.join('dist', 'igniteui-angular', 'docs', 'typescript-exported'),
```
Comment (zdrawku) [inline gulpfile.js]:
```suggestion
    EXPORT_JSON_PATH: path.join(__dirname, 'dist', 'igniteui-angular', 'docs', 'typescript-exported'),
```
