### PR TITLE
fix(grid): set min width to header groups programmatically

### LINKED ISSUE #3071: IgxGridHeaderGroupComponent should have preset min width
### Description  
IgxGridHeaderGroupComponent should have preset min width

 * igniteui-angular version: 6.2.x
 * browser:  N/A

### Steps to reproduce  

1.  Switch to  **SAndreeva/header-group-component-6.2.x**
2.  Run **Grid Column Moving** demo
3.  Inspect the the 'ID' column header group

### Result  
**IgxGridHeaderGroupComponent** is sized to 40px as this is the width set on the column. **IgxGridHeaderComponent** and **IgxGridFilteringCellComponent** are 48px as they have paddings.
Therefore cells and headers looked misaligned, the resize handler on the header is not shown at the expected place.

### Expected result  
The  **IgxGridHeaderGroupComponent** should not be able to go below a certain min width.

### PR DESCRIPTION
**Pull request by SAndreeva**
Closes #3071 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/grid-base.component.ts [hunk 1]
```diff
@@ -2391,6 +2391,22 @@ export abstract class IgxGridBaseComponent extends DisplayDensityBase implements
         }
     }
 
+    /**
+     * Returns the `IgxGridHeaderGroupComponent`'s minimum allloed width.
```
Comment (bkulov) [inline projects/igniteui-angular/src/lib/grids/grid-base.component.ts]: Typo `allloed`.

File: projects/igniteui-angular/src/lib/grids/grid-base.component.ts [hunk 2]
```diff
@@ -2391,6 +2391,22 @@ export abstract class IgxGridBaseComponent extends DisplayDensityBase implements
...
+     * Used internally for restricting header group component width.
+     * The values below depend on the header cell default right/left padding values.
+	 * @memberof IgxGridBaseComponent
+     */
+    get defaultHeaderGroupMinWidth(): number {
+        if (this.isCosy()) {
+            return 32;
```
Comment (bkulov) [inline projects/igniteui-angular/src/lib/grids/grid-base.component.ts]: Could you please set those magic numbers as constants.

File: projects/igniteui-angular/src/lib/grids/grid-base.component.ts [hunk 3]
```diff
@@ -2475,6 +2491,20 @@ export abstract class IgxGridBaseComponent extends DisplayDensityBase implements
...
     }
 
+    /**
+     * Returns the `width` to be set on `IgxGridHeaderGroupComponent`.
+	 * @memberof IgxGridBaseComponent
+     */
+    public getHeaderGroupWidth(column: IgxColumnComponent): string {
+
+        const minWidth = this.defaultHeaderGroupMinWidth;
+        if (parseInt(column.width, 10) < this.defaultHeaderGroupMinWidth) {
```
Comment (bkulov) [inline projects/igniteui-angular/src/lib/grids/grid-base.component.ts]: Use `minWidth` instead of `this.defaultHeaderGroupMinWidth`.

File: projects/igniteui-angular/src/lib/grids/grid/column-resizing.spec.ts [hunk 4]
```diff
@@ -719,6 +720,29 @@ describe('IgxGrid - Deferred Column Resizing', () => {
...
         expect(column.width).toEqual('111px');
     }));
+
+    it('should size headers correctly when column width is below the allowed minimum.', fakeAsync(() => {
+        const fixture = TestBed.createComponent(ColGridComponent);
+        fixture.detectChanges();
+
+        const headers = fixture.debugElement.queryAll(By.css(COLUMN_HEADER_CLASS));
+        const headerGroups = fixture.debugElement.queryAll(By.css(COLUMN_HEADER_GROUP_CLASS));
+        const filteringCells = fixture.debugElement.queryAll(By.css('igx-grid-filtering-cell'));
```
Comment (bkulov) [inline projects/igniteui-angular/src/lib/grids/grid/column-resizing.spec.ts]: Could you please extract `igx-grid-filtering-cell` class as constant similar to the ones above.

File: projects/igniteui-angular/src/lib/grids/grid/column-resizing.spec.ts [hunk 5]
```diff
@@ -719,6 +720,29 @@ describe('IgxGrid - Deferred Column Resizing', () => {
...
+        expect(headers[2].nativeElement.getBoundingClientRect().width).toBe(49);
+
+        expect(filteringCells[0].nativeElement.getBoundingClientRect().width).toBe(49);
+        expect(filteringCells[1].nativeElement.getBoundingClientRect().width).toBe(50);
+        expect(filteringCells[2].nativeElement.getBoundingClientRect().width).toBe(49);
+
+        expect(headerGroups[0].nativeElement.getBoundingClientRect().width).toBe(48);
+        expect(headerGroups[1].nativeElement.getBoundingClientRect().width).toBe(50);
+        expect(headerGroups[2].nativeElement.getBoundingClientRect().width).toBe(48);
+
```
Comment (bkulov) [inline projects/igniteui-angular/src/lib/grids/grid/column-resizing.spec.ts]: Remove those extra empty lines.

File: projects/igniteui-angular/src/lib/grids/grid/column-resizing.spec.ts [hunk 6]
```diff
@@ -827,3 +851,24 @@ export class NullColumnsComponent implements OnInit {
         this.data = SampleTestData.contactInfoData();
     }
 }
+
```
Comment (bkulov) [inline projects/igniteui-angular/src/lib/grids/grid/column-resizing.spec.ts]: Remove the extra empty line.

File: projects/igniteui-angular/src/lib/grids/grid-base.component.ts (hunk 2 above)
Comment (SAndreeva) [reply projects/igniteui-angular/src/lib/grids/grid-base.component.ts]: I will refactor the whole get method once [this PR](https://github.com/IgniteUI/igniteui-angular/pull/3282) is merged.
