### PR TITLE
Fix - Transactions - Gird Transactions + Paging interactions - Master

### LINKED ISSUE #3425: When transactions are enabled and delete a row page is changed to first page
### Description  
When transactions are enabled and delete a row page is changed to first page

 * igniteui-angular version: 7.1.x
 * browser: N/A

### Steps to reproduce  

1. Open dev sample gridRowEdit
2. In second grid go to page 2
3. Click on button delete for a row

### Result  
Page is changed to page 1

### Expected result  
Page should not be changed

### Attachments  
Attach a sample if available, and screenshots, if applicable.

### PR DESCRIPTION
**Pull request by ViktorSlavov**
Closes #3425

### Additional information (check all that apply):
 - [x] Bug fix

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/grid-base.component.ts [hunk 1]
```diff
@@ -3075,10 +3081,13 @@ export abstract class IgxGridBaseComponent extends DisplayDensityBase implements
         this.deleteRowFromData(rowId, index);
         this._pipeTrigger++;
         this.cdr.markForCheck();
-
+        const dataAfterDelete = !this.transactions.enabled ? data : this.dataWithAddedInTransactionRows;
```
Comment (damyanpetev) [inline projects/igniteui-angular/src/lib/grids/grid-base.component.ts]: The api `get_all_data` method from above already does the same check. Also take `this.dataWithAddedInTransactionRows` only when transactions are not enabled?

Comment (damyanpetev) [reply projects/igniteui-angular/src/lib/grids/grid-base.component.ts]: Also put a comment you need recalculated data with transactions (if any) after the delete.

File: projects/igniteui-angular/src/lib/grids/grid-base.component.ts [hunk 2]
```diff
@@ -3075,10 +3081,13 @@ export abstract class IgxGridBaseComponent extends DisplayDensityBase implements
...
         this.refreshSearch();
-        if (data.length % this.perPage === 0 && this.isLastPage && this.page !== 0) {
-            this.page--;
+        if (dataAfterDelete.length % this.perPage === 0 && this.isLastPage && this.page !== 0) {
```
Comment (damyanpetev) [inline projects/igniteui-angular/src/lib/grids/grid-base.component.ts]: These checks and the one below could be simplified to something like 
```suggestion
        if (dataAfterDelete.length % this.perPage === 0 && dataAfterDelete.length / this.perPage - 1 < this.page) {
```
where `dataAfterDelete.length / this.perPage` is pretty much a recalculated `totalPages`.
Actually, when you have transactions, the `onStateChange` emitter will actually retrigger the pipes and `totalPages` is up to date at this point and you can probably use it
