### PR TITLE
fix(tabs): fixes and improvements on kb navigation and routing

### LINKED ISSUE #6845: [igx-tabs] integration with router outlet is not considering guards and updates UI incorrectly
## Description  
When using guards (canActivate or canDeactivate), igx-tabs updates the UI according to which tab(url) the user clicked even though the guard blocked that path.

 * igniteui-angular version: 9.0.1
 * browser: Chrome 80.0.3987.116

## Steps to reproduce  

1. Open the example at https://stackblitz.com/edit/angular-whxt3t (copied and adapted from https://www.infragistics.com/products/ignite-ui-angular/angular/components/tabs.html#integration-with-router-outlet-container)
2. Click on "Canceled" tab (this url is blocked by a canActivate guard)
3. The UI is highlighted on the "Canceled" tab, but the view does not show its contents

## Result  
What is the actual result after following the steps to reproduce?
The UI is highlighted on the "Canceled" tab, even though the view does not show its contents

## Expected result  
Since the url is blocked by the guard, the UI tab should be updated to the current url.

## Attachments  
Attach a sample if available, and screenshots, if applicable.  
n/a

## Observation
Just an example of a real scenario - We have a form in one of the tabs view, and we have a `canDeactivate` guard to show a confirmation dialog to the user in case they are sure to leave the page without saving the data. When they decide to stay in the same page, they still see the highlighted tab is the wrong one.

### PR DESCRIPTION
**Pull request by igdmdimitrov**
Closes #6845 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/tabs/tabs.component.ts [hunk 1]
```diff
@@ -229,6 +230,11 @@ export class IgxTabsComponent implements IgxTabsBase, AfterViewInit, OnDestroy {
      */
     public offset = 0;
 
+    /**
+     * @hidden
+     */
+    public focusedIndex: number;
```
Comment (DiyanDimitrov) [inline projects/igniteui-angular/src/lib/tabs/tabs.component.ts]: There should be no need to persist the focusedIndex on a tabs level.

File: projects/igniteui-angular/src/lib/tabs/tab-item.component.ts [hunk 2]
```diff
@@ -289,15 +313,68 @@ export class IgxTabItemComponent extends IgxTabItemBase implements AfterViewInit
         this.tabindex = newValue ? 0 : -1;
     }
 
-    private onKeyDown(isLeftArrow: boolean, index = null): void {
+    private onKeyDown(key: string): void {
```
Comment (DiyanDimitrov) [inline projects/igniteui-angular/src/lib/tabs/tab-item.component.ts]: Remove the different HostListeners for keydown event and add one for all keys here.

File: projects/igniteui-angular/src/lib/tabs/tab-item.component.ts [hunk 3]
```diff
@@ -202,7 +208,25 @@ export class IgxTabItemComponent extends IgxTabItemBase implements AfterViewInit
...
+        this.clickFocusedTab();
+    }
+
+    /**
+     * @hidden
+     */
+    @HostListener('keydown.space', ['$event'])
+    public onKeydownSpace(event: KeyboardEvent) {
+        event.preventDefault();
+        this.clickFocusedTab();
```
Comment (DiyanDimitrov) [inline projects/igniteui-angular/src/lib/tabs/tab-item.component.ts]: These should be performed only when autogenerated is false.

File: projects/igniteui-angular/src/lib/tabs/tab-item.component.ts [hunk 4]
```diff
@@ -73,6 +73,10 @@ export class IgxTabItemComponent extends IgxTabItemBase implements AfterViewInit
         this._label = newValue;
     }
 
+    /**@hidden*/
+    @Input()
+    public autogenerated: boolean;
```
Comment (DiyanDimitrov) [inline projects/igniteui-angular/src/lib/tabs/tab-item.component.ts]: Rename to auto**G**enerated.

File: projects/igniteui-angular/src/lib/tabs/tab-item.component.ts [hunk 5]
```diff
@@ -168,41 +172,78 @@ export class IgxTabItemComponent extends IgxTabItemBase implements AfterViewInit
...
     /**
      * @hidden
      */
-    @HostListener('keydown.arrowright', ['$event'])
-    public onKeydownArrowRight(event: KeyboardEvent) {
-        this.onKeyDown(false);
-    }
+    @HostListener('keydown', ['$event'])
+    public onKeydown(event: KeyboardEvent) {
+        event.preventDefault();
```
Comment (DiyanDimitrov) [inline projects/igniteui-angular/src/lib/tabs/tab-item.component.ts]: We should not call preventDefault() here since this is stopping the tab navigation.

File: projects/igniteui-angular/src/lib/tabs/tab-item.component.ts [hunk 6]
```diff
@@ -168,41 +172,78 @@ export class IgxTabItemComponent extends IgxTabItemBase implements AfterViewInit
...
-    /**
-     * @hidden
-     */
-    @HostListener('keydown.arrowleft', ['$event'])
-    public onKeydownArrowLeft(event: KeyboardEvent) {
-        this.onKeyDown(true);
-    }
+        const tabsArray = this._tabs.tabs.toArray();
+        const startIndex = tabsArray.indexOf(this);
+        let tab: IgxTabItemBase;
```
Comment (DiyanDimitrov) [inline projects/igniteui-angular/src/lib/tabs/tab-item.component.ts]: This could be moved down where it is used as a const.

File: projects/igniteui-angular/src/lib/tabs/tab-item.component.ts [hunk 7]
```diff
@@ -168,41 +172,78 @@ export class IgxTabItemComponent extends IgxTabItemBase implements AfterViewInit
...
 
-    /**
-     * @hidden
-     */
-    @HostListener('keydown.end', ['$event'])
-    public onKeydownEnd(event: KeyboardEvent) {
-        event.preventDefault();
-        this.onKeyDown(false, this._tabs.tabs.toArray().length - 1);
+            if (this.autoGenerated) {
+                tab.nativeTabItem.nativeElement.click();
```
Comment (DiyanDimitrov) [inline projects/igniteui-angular/src/lib/tabs/tab-item.component.ts]: You can call `tab.select()` directly.

File: projects/igniteui-angular/src/lib/tabs/tab-item.component.ts [hunk 8]
```diff
@@ -73,6 +73,10 @@ export class IgxTabItemComponent extends IgxTabItemBase implements AfterViewInit
         this._label = newValue;
     }
 
+    /**@hidden*/
+    @Input()
+    public autoGenerated: boolean;
+
```
Comment (rkaraivanov) [inline projects/igniteui-angular/src/lib/tabs/tab-item.component.ts]: While this prop seems like private for the component, please document what it does.
