### PR TITLE
Handle keydown and iterate items by first character, if no item matched typed input - master

### LINKED ISSUE #8436: When you type fast the same letter in the select, the items are not navigated
## Description  
When igxSelect has items in the list, with the same first letter, then when that same letter is typed fast, then those items are not navigated and the highlighted item is only the first one.

 * igniteui-angular version: 10.2.0
 * browser: any

## Steps to reproduce  

1. Open the following igxSelect [demo](https://stackblitz.com/github/IgniteUI/igniteui-live-editing-samples/tree/master/angular-demos/data-entries/select-sample-2).
2. Open the select component
3. Type fast and multiple times 'p'

## Result  
Notice that the only 'Potato' is selected.

## Expected result  
When typing 'p' multiple times, the navigation should move between 'Potato' to 'Pepper'.

### PR DESCRIPTION
**Pull request by IvayloG**
Closes #8436   

- Make the component feel more responsive now as if no exact match is found for the current input stream, a next item with the same start letter will be selected (if such an item).
- Behave more like a native HTML select in terms of fast searching through items by 1st character, and yet do not suffer from the negative downside of not matching same second character if holding down or typing fast same char. Native select basically ignores selecting items via the current input stream while the same char is continuously typed as it seems to prioritize fast items iteration by first char instead.

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/select/select-navigation.directive.ts [hunk 1]
```diff
@@ -112,6 +118,15 @@ export class IgxSelectItemNavigationDirective extends IgxDropDownItemNavigationD
         this.target.navigateItem(items.indexOf(nextItem));
     }
 
+    private findNextItem(items: IgxSelectItemComponent[],  text: string) {
+        const activeItemIndex = items.indexOf(this.target.focusedItem as IgxSelectItemComponent) || 0;
+
+        // Match next item in ddl items and wrap around if needed
+        const item = items.slice(activeItemIndex + 1).find(x => !x.disabled && (x.itemText.toLowerCase().startsWith(text.toLowerCase()))) ||
```
Comment (ViktorSlavov) [inline projects/igniteui-angular/src/lib/select/select-navigation.directive.ts:125]: No need to assign to a variable, you could just `return items.slice(...`

**Review by ViktorSlavov — CHANGES_REQUESTED** [review]

**Review by ViktorSlavov — APPROVED** [review]
