### PR TITLE
fix(tabs): fixes on tab related attributes 

### LINKED ISSUE #6920: Tab items have the same id attribute
## Description  
Tab items have the same id

 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Open https://www.infragistics.com/products/ignite-ui-angular/angular/components/tabs.html#tabs-demo
2. Inspect the tab items.

## Result  
The tab items have the same id - "igx-tab-item--1".

## Expected result  
The tab items should not have the same ids.

### PR DESCRIPTION
**Pull request by igdmdimitrov**
Closes #6920

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/tabs/tab-item.component.ts [hunk 1]
```diff
@@ -126,36 +126,6 @@ export class IgxTabItemComponent extends IgxTabItemBase implements AfterViewInit
...
-     * @hidden @internal
-     */
-    @HostBinding('attr.aria-disabled')
-    public ariaDisabled = this.disabled;
-
-    /**
-     * @hidden @internal
-     */
-    @HostBinding('attr.aria-selected')
-    public ariaSelected = this.isSelected;
```
Comment (DiyanDimitrov) [inline projects/igniteui-angular/src/lib/tabs/tab-item.component.ts:151]: You can keep those as they were before since they don't depend on the id attribute.

File: projects/igniteui-angular/src/lib/tabs/tabs-group.component.ts [hunk 2]
```diff
@@ -68,6 +65,16 @@ export class IgxTabsGroupComponent extends IgxTabsGroupBase implements AfterCont
         }
     }
 
+    /**
+     * Returns the native element of the tabs-group component
+     * ```typescript
+     *  const mytabsGroupElement: HTMLElement = tabsGroup.element;
+     * ```
+     */
+    public get element() {
```
Comment (DiyanDimitrov) [inline projects/igniteui-angular/src/lib/tabs/tabs-group.component.ts:74]: Rename this to nativeElement.

File: projects/igniteui-angular/src/lib/tabs/tabs.component.ts [hunk 3]
```diff
@@ -106,6 +110,22 @@ export class IgxTabsComponent implements IgxTabsBase, AfterViewInit, OnDestroy {
...
+     *
+     * @example
+     * ```html
+     * <igx-tabs id="my-first-tabs"></igx-tabs>
+     * ```
+     * @memberof IgxTabsComponent
+     */
+    @HostBinding('attr.id')
+    @Input()
+    public id = `igx-tabs-${NEXT_TABS_ID}`;
```
Comment (DiyanDimitrov) [inline projects/igniteui-angular/src/lib/tabs/tabs.component.ts:127]: This should be:
 ```public id = `igx-tabs-${this._currentTabsId}`;```

File: projects/igniteui-angular/src/lib/tabs/tabs.component.ts [hunk 4]
```diff
@@ -358,6 +381,14 @@ export class IgxTabsComponent implements IgxTabsBase, AfterViewInit, OnDestroy {
         }
     }
 
+    private setGroupsAttributes() {
+        for (let index = 0; index < this.groups.length; index++) {
+            const tabsGroup = Array.from(this.groups)[index] as IgxTabsGroupComponent;
```
Comment (DiyanDimitrov) [inline projects/igniteui-angular/src/lib/tabs/tabs.component.ts:386]: Create a const with the groups array before the for to avoid creating the array on each iteration.

File: projects/igniteui-angular/src/lib/tabs/tabs.component.ts [hunk 5]
```diff
@@ -460,6 +490,14 @@ export class IgxTabsComponent implements IgxTabsBase, AfterViewInit, OnDestroy {
         }
     }
 
+    private _getTabItemId(index: number): string {
+        return `igx-tab-item-${this._currentTabsId}-${index}`;
+    }
+
+    private _getTabsGroupId(index: number): string {
+        return `igx-tabs-group-${this._currentTabsId}-${index}`;
+    }
```
Comment (DiyanDimitrov) [inline projects/igniteui-angular/src/lib/tabs/tabs.component.ts:499]: The build is failing because these methods are private. Make them public and hidden.
