### PR TITLE
fix(grid-pinning): remove hide call in scrollToRow - 20.1.x

### LINKED ISSUE #16493: [Elements] Action strip closes when clicking jump to row action
## Description  
Action strip closes when clicking jump to row action. You have to then exit the row to show it agin.

 * igniteui-angular version: any
 * browser: any

## Steps to reproduce  

1. Open https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/grids/tree-grid/row-actions#custom-implementation
2. Pin a row
3. Scroll so the row is out of view
4. Click on the `Jump down` button of action strip

## Result  
The action strip closes.

## Expected result  
The action strip shouldn't close

## Attachments  

Image

### PR DESCRIPTION
**Pull request by IMinchev64**
Closes #16493 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by mddragnev** [comment]
Please cherry-pick your latest commit from master

**Comment by dkamburov** [comment]
@IMinchev64 seems to fail for that branch

File: projects/igniteui-angular/src/lib/grids/grid-base.directive.ts [hunk 1]
```diff
@@ -186,6 +186,7 @@ import { getCurrentResourceStrings } from '../core/i18n/resources';
 import { isTree, recreateTree, recreateTreeFromFields } from '../data-operations/expressions-tree-util';
 import { getUUID } from './common/random';
 import { DefaultMergeStrategy, IGridMergeStrategy } from '../data-operations/merge-strategy';
+import { IgxGridPinningActionsComponent } from 'igniteui-angular';
```
Comment (mddragnev) [inline projects/igniteui-angular/src/lib/grids/grid-base.directive.ts]: You are inroducing circular dependency. You can see the failing build. This component should be imported from the file using the relative path.

Comment (dkamburov) [reply projects/igniteui-angular/src/lib/grids/grid-base.directive.ts]: @copilot can you resolve the dependency here?
