### PR TITLE
fix(adv-filtering): transforming search value based on column type #6257

### LINKED ISSUE #6257: Grid advanced filtering is not working correctly when using "Equals" with numbers
## Description  
Grid advanced filtering is not working correctly when using "Equals" with numbers

 * igniteui-angular version: 8.2.x
 * browser: N/A

## Steps to reproduce  

1. Open dev demo - "Grid Filtering"
2. Remove the existing filter from Advanced Filtering
3. Create new filter with rule - "Employees = Equals 68"

## Result  
There are no matched records

## Expected result  
There should be 1 match

### PR DESCRIPTION
**Pull request by igdmdimitrov**
Closes #6257

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/filtering/advanced-filtering/advanced-filtering-dialog.component.ts [hunk 1]
```diff
@@ -301,13 +302,23 @@ export class IgxAdvancedFilteringDialogComponent implements AfterViewInit, OnDes
...
             this.editedExpression = null;
         }
     }
 
+    private transformValue(value): any {
+        if (this.selectedColumn.dataType === DataType.Number) {
+            value = parseFloat(value);
+        } else if (this.selectedColumn.dataType === DataType.Boolean) {
+            value = Boolean(value);
+        }
```
Comment (DiyanDimitrov) [inline projects/igniteui-angular/src/lib/grids/filtering/advanced-filtering/advanced-filtering-dialog.component.ts]: This code is not working as expected:
```js
var myBool = Boolean("false");  // == true
```

Actually we do not support non-unary conditions for boolean columns so this code can be deleted.

File: projects/igniteui-angular/src/lib/grids/filtering/advanced-filtering/advanced-filtering-dialog.component.ts [hunk 2]
```diff
@@ -301,13 +302,23 @@ export class IgxAdvancedFilteringDialogComponent implements AfterViewInit, OnDes
...
             this.editedExpression.expression.condition = this.selectedColumn.filters.condition(this.selectedCondition);
-            this.editedExpression.expression.searchVal = this.searchValue;
+            this.editedExpression.expression.searchVal = this.transformValue(this.searchValue);
 
             this.editedExpression.inEditMode = false;
             this.editedExpression = null;
         }
     }
 
+    private transformValue(value): any {
```
Comment (DiyanDimitrov) [inline projects/igniteui-angular/src/lib/grids/filtering/advanced-filtering/advanced-filtering-dialog.component.ts]: Since this method is copied on 3 different places, we should extract it to the filtering service.

File: projects/igniteui-angular/src/lib/grids/filtering/advanced-filtering/advanced-filtering-dialog.component.ts [hunk 3]
```diff
@@ -18,6 +18,7 @@ import { takeUntil, first } from 'rxjs/operators';
 import { Subject } from 'rxjs';
 import { KEYS } from '../../../core/utils';
 import { AbsoluteScrollStrategy, AutoPositionStrategy } from '../../../services/index';
+import { DataType, DataUtil } from './../../../data-operations/data-util';
```
Comment (DiyanDimitrov) [inline projects/igniteui-angular/src/lib/grids/filtering/advanced-filtering/advanced-filtering-dialog.component.ts]: Unnecessary import - `DataType`.

File: projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-default-expression.component.ts [hunk 4]
```diff
@@ -9,11 +9,11 @@ import {
     ViewChild
 } from '@angular/core';
 import { IgxColumnComponent } from '../../column.component';
-import { ExpressionUI } from '../grid-filtering.service';
+import { ExpressionUI, IgxFilteringService } from '../grid-filtering.service';
```
Comment (DiyanDimitrov) [inline projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-default-expression.component.ts]: Unnecessary import - `IgxFilteringService`.
