### PR TITLE
fix(pivot-strategy): set properties of undefined - master

### LINKED ISSUE #13319: TypeError: Cannot set properties of undefined (setting 'level') on Pivot Grid
### Description  
Describe the issue.

### Steps to reproduce  

1. Please go to https://staging.infragistics.com/products/ignite-ui-angular/angular/components/pivotGrid/pivot-grid
2. Open dev tools, check "Sales" and "Month" checkboxes
3. Click on Month filters and deselect June and December
image
4. click the 'x' icon 
image

### Result  
image

### PR DESCRIPTION
**Pull request by IMinchev64**
Closes #13319  

### Additional information (check all that apply):
 - [ ] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/data-operations/pivot-strategy.ts [hunk 1]
```diff
@@ -151,7 +151,7 @@ export class DimensionValuesFilteringStrategy extends FilteringStrategy {
         const dim = enabledDimensions.find(x => x.memberName === column.field);
         const allValuesHierarchy = PivotUtil.getFieldsHierarchy(
             data,
-            [dim],
+            dim ? [dim] : [],
```
Comment (skrustev) [inline projects/igniteui-angular/src/lib/data-operations/pivot-strategy.ts:154]: This will do in this case, but maybe if we want to fix it further we could use the possibility to improve the `flatten` function that it is used deeper in the chain to not perform any actions on elements that are undefined as well?

**Review by skrustev — APPROVED** [review]
