### PR TITLE
Change cursor in iOS

### LINKED ISSUE #5853: IgxOverlay does not close on outside click on iOS
## Description  
Clicking outside of the overlay content does not close the overlay on iOS device.

 * igniteui-angular version: 8.1.7
 * browser: Safary

## Steps to reproduce  

1. Open this [Stackblitz](https://stackblitz.com/edit/angular-xf2njr?file=src/app/interactions/overlay/overlay-main-2/overlay-main-sample-2.component.ts) is Safari on iOS device
2. Click on the button.
3. Click outside the card and not on the button

## Result  
Overlay does not close

## Expected result  
Overlay should close

## Additional info
If you set `modal` to `true` issue does not reproduce

### PR DESCRIPTION
**Pull request by wnvko**
Before we add listener to the document we are checking now if we are under iOS. If so we change the cursor to `pointer`. This forces the document body to handle click events.

Closes #5853 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/services/overlay/overlay.ts [hunk 1]
```diff
@@ -685,6 +689,15 @@ export class IgxOverlayService implements OnDestroy {
                 this._overlayInfos.filter(x => x.settings.closeOnOutsideClick && !x.settings.modal &&
                     x.closeAnimationPlayer &&
                     x.closeAnimationPlayer.hasStarted()).length === 1) {
+
+                // click event is not fired on iOS. To make element "clickable" we are
+                // setting the cursor to pointer
+                if (this.platformUtil.isIOS && !this._cursorStyleIsSet) {
```
Comment (ViktorSlavov) [inline projects/igniteui-angular/src/lib/services/overlay/overlay.ts:695]: There could be a unit test, w/ something like `expect(mockDocument.body.style.cursor).toEqual('pointer')`  when `platformUtil.isIOS` is mocked to be `true`.
This will not test the actual integration, but the logic will be covered.
It might be a bit overkill though, up to you if you want to include it.

**Review by ViktorSlavov — APPROVED** [review]
Wow... never had the idea this worked that!

**Review by jackofdiamond5 — DISMISSED** [review]

File: projects/igniteui-angular/src/lib/services/overlay/overlay.ts (hunk 1 above)
Comment (wnvko) [reply projects/igniteui-angular/src/lib/services/overlay/overlay.ts:695]: great idea!!!
Will do it now.
Thanks!

File: projects/igniteui-angular/src/lib/services/overlay/overlay.spec.ts [hunk 2]
```diff
@@ -188,6 +188,80 @@ describe('igxOverlay', () => {
...
+            defaultView: mockElement,
+            createElement: () => mockElement,
+            appendChild: () => { },
+            addEventListener: (type: string, listener: (this: HTMLElement, ev: MouseEvent) => any) => { },
+            removeEventListener: (type: string, listener: (this: HTMLElement, ev: MouseEvent) => any) => { }
+        };
+        const mockNgZone: any = {};
+        const mockPlatformUtil: any = { isIOS: false };
+
+        const overlay = new IgxOverlayService(
```
Comment (ViktorSlavov) [inline projects/igniteui-angular/src/lib/services/overlay/overlay.spec.ts:235]: This config is great! I think it should be moved in a `beforeEach` statement - in case we end up adding more unit tests and don't want to take a chance on the overlay instance being "polluted".

**Review by ViktorSlavov — CHANGES_REQUESTED** [review]

**Review by ViktorSlavov — DISMISSED** [review]

**Review by jackofdiamond5 — APPROVED** [review]

**Review by ViktorSlavov — APPROVED** [review]
