### PR TITLE
fix(select): always focus the selected item in igx-select

### LINKED ISSUE #4010: IgxSelect - first key nav on closed select with initial value is incorrect
## Description  
When attempting to navigate through an `igx-select`'s item list for the very first item, if the `igx-select` has an initially selected value, the selection resets on navigation

 * igniteui-angular version: 7.2.x
 * browser: N/A

## Steps to reproduce  

1. In `select.sample.ts` do the following adjustments:
 -  In the definition of ` public users: Person []`, add a new person to the **start** of the array:
```typescript
public users: Person [] = [
        { name: 'George', favoriteFood: 'Bananas' } , // added line
        { name: 'Maria', favoriteFood: 'Steak' },
        { name: 'Doe', favoriteFood: 'Pizza' },
        { name: 'Anton', favoriteFood: 'Apples' }
```
 -  Under `private _createMySelectForm()`, change the initial selection of the people select to "Maria":
```typescript
this.mySelectForm.setValue({
            name: this.users[1].name,
            favoriteFood: this.users[1].favoriteFood
        });
```
2. Open the dev demos and navigate to the select sample
3. Under the **Select in Form** section, click on the 1st input and navigate to the people select using `Tab`, w/o opening it
4. Press `Arrow Down` once

## Result  
The people select's value is now `George`

## Expected result  
The poeple select's value is now `Doe`

### PR DESCRIPTION
**Pull request by ViktorSlavov**
Closes #4010

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/select/select.component.ts [hunk 1]
```diff
@@ -268,6 +268,7 @@ export class IgxSelectComponent extends IgxDropDownComponent implements IgxSelec
     /** @hidden @internal */
     private setSelection(item: IgxDropDownItemBase) {
         if (item && item.value !== undefined && item.value !== null) {
+            this.navigateItem(item.index);
```
Comment (IvayloG) [inline projects/igniteui-angular/src/lib/select/select.component.ts]: It may be best if we use focus and blur handlers, in order to cover all focus scenarios and synch with the selected item like:             
(focus)="this.focusedItem = this.selectedItem"
