### PR TITLE
fix(grid): revert certain lastSearchInfo changes - 16.0.x

### LINKED ISSUE #13051: [Angular Elements Grid] Grid's lastSearchInfo is undefined.
## Description  

Note that the prop is public but also hidden/internal: https://github.com/IgniteUI/igniteui-angular/blob/master/projects/igniteui-angular/src/lib/grids/grid-base.directive.ts#L2832

While also described in our public docs:  https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/search#display-results-count

 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Run any wc grid sample and try to access the lastSearchInfo prop.

## Result  
It's undefined.

## Expected result  
It should be defined.

### LINKED ISSUE #13334: Grid LastSearchInfo matchInfoCache missing/wrong docs
I've noticed another thing
image
this is from your angular docs
But in reality
image

_Originally posted by @fexxdev in https://github.com/IgniteUI/igniteui-angular/issues/13265#issuecomment-1655437725_

Edit: Related to issue #13051

### PR DESCRIPTION
**Pull request by onlyexeption**
Closes #13051
Closes #13334 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/common/events.ts [hunk 1]
```diff
@@ -98,15 +98,19 @@ export interface IColumnSelectionEventArgs extends CancelableEventArgs, IBaseEve
     readonly event?: Event;
 }
 
-export interface ISearchInfo {
+export interface IBaseSearchInfo {
```
Comment (damyanpetev) [inline projects/igniteui-angular/src/lib/grids/common/events.ts:101]: Only not sure we care to have the base interface public (which this becomes in this file). Other than that, this looks fine

Comment (ChronosSF) [reply projects/igniteui-angular/src/lib/grids/common/events.ts:101]: Please move the interface to a file that is not exported so that it remains private.

**Review by ChronosSF — APPROVED** [review]

**Review by ChronosSF — APPROVED** [review]
