### PR TITLE
Combo - Refactor combo navigation

### LINKED ISSUE #2999: igxCombo keyboard navigation not working
### Description  
Describe the issue.

 * igniteui-angular version: 6.2.0
 * browser: N/A

### Steps to reproduce  

1. Navigate to https://www.infragistics.com/products/ignite-ui-angular/angular/components/combo_features.html
2. open the combo
3. hold arrow down key

### Result  
The combo selection is not moved accordingly

### Expected result  
The combo selection should move down correctly while the arrow down key is hold.

### PR DESCRIPTION
**Pull request by ViktorSlavov**
Closes #2999 

Refactor combo keyboard navigation:

**Properly works** with new `igxForOf.scrollTo`
Separate logic for performing focus after virtual scroll and performing regular focus
Separate logic for navigating **up** and navigating **down**
Add comments

### CODE REVIEW

File: projects/igniteui-angular/src/lib/combo/combo-dropdown.component.ts [hunk 1]
```diff
@@ -205,127 +205,107 @@ export class IgxComboDropDownComponent extends IgxDropDownBase implements OnDest
...
-        if (this.isScrolledToLast && direction === Navigate.Down) { // If on the bottom most item, do not subscribe
-            return;
-        }
-        // If on the topmost item, do not subscribe
-        if (this.verticalScrollContainer.getVerticalScroll().scrollTop === 0 && direction === Navigate.Up) {
+    private navigateDown(allData: any[], vContainer: IgxForOfDirective<any>, extraScroll: number, newIndex?: number) {
+        const focusedItem = this.focusedItem;
+        const items = this.items;
+        const children = this.children.toArray();
+        if (focusedItem && (focusedItem.value === allData[allData.length - 1] || focusedItem.value === 'ADD ITEM')) { // If very last item
```
Comment (Lipata) [inline projects/igniteui-angular/src/lib/combo/combo-dropdown.component.ts]: Here you can just separate the logic between the last item and add item. First you are checking that it is last or add, then the internal if is checking if it is not add item.

this.combo.isAddButtonVisible() && focusedItem.value === 'ADD ITEM' => return
focusedItem && (focusedItem.value === allData[allData.length - 1] =>this.focusItem(items.length - 1);

Even you can introduce methods similar focusComboSearch for add button, or some of the other code below.

File: projects/igniteui-angular/src/lib/combo/combo-dropdown.component.ts [hunk 2]
```diff
@@ -205,127 +205,107 @@ export class IgxComboDropDownComponent extends IgxDropDownBase implements OnDest
...
+            }
+        } else if (this.isScrolledToLast && targetDataIndex === lastLoadedIndex) { // If already at bottom and target is last item
+            this.focusItem(items.length - 1 - extraScroll); // Focus the last item (excluding Add Button)
+        } else { // If scroll is required
+            // If item is header, find next non-header index
+            const addedIndex = allData[targetDataIndex].isHeader ?
+            [...allData].splice(targetDataIndex, allData.length - 1).findIndex(e => !e.isHeader) : 0;
+            targetDataIndex += addedIndex; // Add steps to the target index
+            if (addedIndex === -1 && this.combo.isAddButtonVisible()) { // If there are no more non-header items & add button is visible
+                this.focusItem(items.length);
```
Comment (Lipata) [inline projects/igniteui-angular/src/lib/combo/combo-dropdown.component.ts]: I'm trying to figure out if focusItem in the combo-drop-down, is not almost the same as navigateItem in the parent drop-down. If so, this means that instead of this.focusItem we can call super.navigateItem and simplify the code. If not, please ignore that.

File: projects/igniteui-angular/src/lib/combo/combo-dropdown.component.ts [hunk 3]
```diff
@@ -205,127 +205,107 @@ export class IgxComboDropDownComponent extends IgxDropDownBase implements OnDest
...
+            if (this.isScrolledToLast && targetDataIndex === vContainer.state.startIndex) {
+                 // If virt scrollbar is @ bottom, first item is in DOM but not visible
+                vContainer.scrollTo(targetDataIndex); // This will not trigger `onChunkLoad`
+                this.focusItem(0); // Focus first visible item
+            } else {
+                super.navigateItem(newIndex); // Use normal navigation
+            }
+        } else { // Perform virtual scroll
+            // If item is header, find next non-header index
+            const addedIndex = allData[targetDataIndex].isHeader ?
```
Comment (Lipata) [inline projects/igniteui-angular/src/lib/combo/combo-dropdown.component.ts]: This can be in a separate method, like findNonHeaderIndex or similar.
