### PR TITLE
fix(radio): can't select radio on click

### LINKED ISSUE #9136: igx-radio emits multiple change event with ngModel
## Description  
Using igx-radio and ngModel does not work as expected. Inside the method triggered by event "change" we set up the value and trigger again the event. In version 10.1.4 wasn't doing that.

 * igniteui-angular version: 10.2.15
 * browser: Microsoft Edge Version 89.0.774.50

## Steps to reproduce  

1. Navigate to stackblitz example: https://stackblitz.com/edit/angular-igniteui-radio?file=src%2Fapp%2Fapp.module.ts
2. Select Option 1
3. check logs, select again option 2

## Result  
Changing the ngModel does not trigger the change event

## Expected result  
Changing the ngModel does not trigger the change event

## Attachments  
1. Navigate to stackblitz example:
https://stackblitz.com/edit/angular-igniteui-radio?file=src%2Fapp%2Fapp.module.ts

### PR DESCRIPTION
**Pull request by simeonoff**
Closes #9136  

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Review by kdinev — APPROVED** [review]

File: projects/igniteui-angular/src/lib/radio/radio.component.ts [hunk 1]
```diff
@@ -142,7 +142,7 @@ export class IgxRadioComponent implements ControlValueAccessor, EditorProvider {
      * @memberof IgxRadioComponent
      */
     @Input()
-    public value: any;
+    public value: string;
```
Comment (kdinev) [inline projects/igniteui-angular/src/lib/radio/radio.component.ts:145]: Change the value type back to `any` because in strict template checks numeric fields will be rejected.

**Review by kdinev — CHANGES_REQUESTED** [review]

**Review by kdinev — APPROVED** [review]
