### PR TITLE
fix(cell selection): Fixed copy-paste behavior #8818

### LINKED ISSUE #8818: igx-grid cell selection = none has strange copy-paste behavior
## Description  
I have a grid with `cellSelection="none"` and upon copy on an active cell and window focus change, the cell gets selected.

 * igniteui-angular version: 11.0.11
 * browser: all

## Steps to reproduce  

1. Define a grid with `cellSelection="none"`
2. Activate a cell.
3. Ctrl+C
4. Alt+Tab to change to another window
5. Alt+Tab to come back to the grid window

## Result  
The active cell value is not added to the clipboard on copy. The active cell is selected after returning focus to the window. Upon changing the active cell and copy + alt+tab, the newly activated cell is added to the selection and previous selection is added to the clipboard on copy.

## Expected result  
Copy should copy the cell value to the clipboard and the cell should not be selected upon returning focus to the grid window.

## Attachments  
Attach a sample if available, and screenshots, if applicable.

### PR DESCRIPTION
**Pull request by dobromirts**
Closes #8818 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by ddincheva** [comment]
After performing some testing, I found a problem in the following scenario:
when cell selection is set to none;
click over some cell in order to activate it;
leave the current tab and return again to it;
Click outside the grid;
As you can notice the cell is selected 
cellSelectionNone

File: projects/igniteui-angular/src/lib/grids/cell.component.ts [hunk 1]
```diff
@@ -925,6 +925,10 @@ export class IgxGridCellComponent implements OnInit, OnChanges, OnDestroy {
         const node = this.selectionNode;
         const shouldEmitSelection = !this.selectionService.isActiveNode(node);
 
+        if (this.cellSelectionMode === GridSelectionMode.none || this.cellSelectionMode === GridSelectionMode.single) {
+            this.selectionService.clear();
+        }
+
```
Comment (ddincheva) [inline projects/igniteui-angular/src/lib/grids/cell.component.ts:931]: This check should not be placed in the method /as you can see in the comment there are still issues with this fix/.. try to remove it and the fix should be better performed in focusTbody() method in the grid navigation service.

**Comment by ddincheva** [comment]
@dobromirts , all the issues have been addressed and the fix works good, so just please delete the commented code

**Review by ddincheva — APPROVED** [review]

**Review by kdinev — APPROVED** [review]
