### PR TITLE
fix(pivot): Set correct data type when creating custom IgxPivotDateDi…

### LINKED ISSUE #11738: [PivotGrid] Date Sorting
## Question  

For date type dimensions, we are using IgxPivotDateDimension with everything on false in terms of options apart from "fullDate", which is on true. We've noticed that if we use "memberFunction" and try to sort, it seems it will do a string sorting rather than a date one. Without "memberFunction", the sorting is done okay. Should the method return a different type than string?

 * igniteui-angular version: 13.2.1
 * browser: Chrome

date-sorting

### PR DESCRIPTION
**Pull request by mddragnev**
…mension

Closes #11738   

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid-dimensions.ts [hunk 1]
```diff
@@ -46,6 +47,11 @@ export interface IPivotDateDimensionOptions {
 export class IgxPivotDateDimension implements IPivotDimension {
     /** Enables/Disables a particular dimension from pivot structure. */
     public enabled = true;
+    
+    /**
+     * Gets/Sets data type
+     */
+    public dataType?: GridColumnDataType;
```
Comment (MayaKirova) [inline projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid-dimensions.ts:54]: I think for the date dimensions we should set the column type to be Date by default, so that the user does not have to explicitly set it every time. In most cases you would always use this for date values anyway.

File: projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid-dimensions.ts [hunk 2]
```diff
@@ -94,6 +100,8 @@ export class IgxPivotDateDimension implements IPivotDimension {
             return;
         }
 
+        this.dataType = inBaseDimension.dataType;
```
Comment (MayaKirova) [inline projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid-dimensions.ts:103]: Shouldn't the child dimensions below also apply a data type? Otherwise I assume they won't be sorted as dates but as strings as well.

**Review by MayaKirova — CHANGES_REQUESTED** [review]

**Review by MayaKirova — DISMISSED** [review]

**Comment by mddragnev** [comment]
@dkamburov please note that this pr should be tested after https://github.com/IgniteUI/igniteui-angular/pull/11820 this is merged.

**Review by skrustev — APPROVED** [review]

**Review by MayaKirova — APPROVED** [review]
