### PR TITLE
fix(input-group): theme CSS prop not retreived

### LINKED ISSUE #9367: Issue with IgxInputGroup type 'border'/'box' in IgxDialog
## Description  
When IgxInput with a type property set to 'border'/'box' is inside of IgxDialog component, the border is not displayed.

 * igniteui-angular version: 11.1.4
 * browser: Chrome

## Steps to reproduce  

1. open [this](https://stackblitz.com/edit/dialog-with-input-group-type-border?file=package.json) sample
2. open the dialog

## Result  
The border is not visible

## Expected result  
The border should be displayed like in the input group outside of the dialog

### PR DESCRIPTION
**Pull request by simeonoff**
Closes #9367   

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [x] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Review by kdinev — APPROVED** [review]

File: projects/igniteui-angular/src/lib/input-group/input-group.component.ts [hunk 1]
```diff
@@ -246,6 +249,10 @@ export class IgxInputGroupComponent extends DisplayDensityBase implements IgxInp
         private platform: PlatformUtil
     ) {
         super(_displayDensityOptions);
+
+        this._theme$.pipe(delay(0)).subscribe(value => {
```
Comment (kdinev) [inline projects/igniteui-angular/src/lib/input-group/input-group.component.ts:253]: Do you need the `delay(0)`?

Comment (simeonoff) [reply projects/igniteui-angular/src/lib/input-group/input-group.component.ts:253]: Yep, this is to prevent `Expression has changed after it was checked` error.

Comment (rkaraivanov) [inline projects/igniteui-angular/src/lib/input-group/input-group.component.ts:253]:
```suggestion
        this._theme$.asObservable().subscribe(value => {
```

File: projects/igniteui-angular/src/lib/input-group/input-group.component.ts [hunk 2]
```diff
@@ -451,6 +445,22 @@ export class IgxInputGroupComponent extends DisplayDensityBase implements IgxInp
     public set filled(val) {
         this._filled = val;
     }
+
+    /** @hidden @internal */
+    public ngAfterViewInit() {
+        if (!this._theme) {
+            if(this.platform.isIE) {
+                this._theme$.next(IgxInputGroupTheme.Material);
```
Comment (rkaraivanov) [inline projects/igniteui-angular/src/lib/input-group/input-group.component.ts:453]:
```suggestion
                Promise.resolve().then(() => this._theme$.next(IgxInputGroupTheme.Material));
```

File: projects/igniteui-angular/src/lib/input-group/input-group.component.ts [hunk 3]
```diff
@@ -451,6 +445,22 @@ export class IgxInputGroupComponent extends DisplayDensityBase implements IgxInp
...
+            } else {
+                const cssProp = this.document.defaultView
+                    .getComputedStyle(this.element.nativeElement)
+                    .getPropertyValue('--theme')
+                    .trim();
+
+                this._theme$.next(cssProp);
```
Comment (rkaraivanov) [inline projects/igniteui-angular/src/lib/input-group/input-group.component.ts:460]:
```suggestion
                Promise.resolve().then(() => this._theme$.next(cssProp));
```

**Review by rkaraivanov — COMMENTED** [review]
@simeonoff 
You may try the changes I suggested.
It should avoid the `Expression changed after checked` and hopefully
you won't have to modify all the unit tests to `fakeAsync`

**Comment by simeonoff** [comment]
> @simeonoff
> You may try the changes I suggested.
> It should avoid the `Expression changed after checked` and hopefully
> you won't have to modify all the unit tests to `fakeAsync`

Thank you, this did the trick!

File: projects/igniteui-angular/src/lib/input-group/input-group.component.ts [hunk 4]
```diff
@@ -137,7 +139,8 @@ export class IgxInputGroupComponent extends DisplayDensityBase implements IgxInp
 
     private _type: IgxInputGroupType = null;
     private _filled = false;
-    private _variant: IgxInputGroupTheme;
+    private _theme: IgxInputGroupTheme;
+    private _theme$ = new Subject();
```
Comment (rkaraivanov) [inline projects/igniteui-angular/src/lib/input-group/input-group.component.ts:143]:
```suggestion
    private _theme$ = new Subject();
    private _subscription: Subscription;
```

File: projects/igniteui-angular/src/lib/input-group/input-group.component.ts [hunk 5]
```diff
@@ -246,6 +249,10 @@ export class IgxInputGroupComponent extends DisplayDensityBase implements IgxInp
         private platform: PlatformUtil
     ) {
         super(_displayDensityOptions);
+
+        this._theme$.asObservable().subscribe(value => {
+            this._theme = value as IgxInputGroupTheme;
+        });
```
Comment (rkaraivanov) [inline projects/igniteui-angular/src/lib/input-group/input-group.component.ts:255]:
```suggestion
        this._subscription = this._theme$.asObservable().subscribe(value => {
            this._theme = value as IgxInputGroupTheme;
            this.cdr.detectChanges();
        });
```

File: projects/igniteui-angular/src/lib/input-group/input-group.component.ts [hunk 6]
```diff
@@ -246,6 +249,10 @@ export class IgxInputGroupComponent extends DisplayDensityBase implements IgxInp
         private platform: PlatformUtil
```
Comment (rkaraivanov) [inline projects/igniteui-angular/src/lib/input-group/input-group.component.ts:249]: Remove the `renderer` as it seems to be unused.
Add a `ChangeDetectorRef`

File: projects/igniteui-angular/src/lib/input-group/input-group.component.ts [hunk 7]
```diff
@@ -451,6 +445,31 @@ export class IgxInputGroupComponent extends DisplayDensityBase implements IgxInp
...
+                Promise.resolve().then(() => {
+                    this._theme$.next(cssProp);
+                });
+            }
+        }
+    }
+
+    /** @hidden @internal */
+    public ngOnDestroy() {
+        this._theme$.unsubscribe();
```
Comment (rkaraivanov) [inline projects/igniteui-angular/src/lib/input-group/input-group.component.ts:471]:
```suggestion
        this._subscription.unsubscribe();
```

**Review by rkaraivanov — APPROVED** [review]

File: projects/igniteui-angular/src/lib/input-group/input-group.component.ts [hunk 8]
```diff
@@ -242,10 +246,15 @@ export class IgxInputGroupComponent extends DisplayDensityBase implements IgxInp
...
-        private renderer: Renderer2,
-        private platform: PlatformUtil
+        private platform: PlatformUtil,
+        private cdr: ChangeDetectorRef
     ) {
         super(_displayDensityOptions);
+
+        this._subscription = this._theme$.asObservable().subscribe(value => {
+            this._theme = value as IgxInputGroupTheme;
+            this.cdr.detectChanges();
```
Comment (wnvko) [inline projects/igniteui-angular/src/lib/input-group/input-group.component.ts:256]: this should work and with `this.cdr.markForCheck()`

Comment (simeonoff) [reply projects/igniteui-angular/src/lib/input-group/input-group.component.ts:256]: ok, does it have any performance implications?

Comment (rkaraivanov) [reply projects/igniteui-angular/src/lib/input-group/input-group.component.ts:256]: @wnvko 
Technically it should, however if we don't want to adjust all editing tests for the grid that use the input group, I suggest we leave it as it is. This will be called usually once only at initialization and the performance hit should be negligible.

**Review by wnvko — APPROVED** [review]
