### PR TITLE
fix(esf): assigning the correct overlay id for custom dialog #11404

### LINKED ISSUE #11404: Igx Grid advanced filtering dialog not closing bug in Excel style filter
## Description  
I am using **igx-grid** in my component. I am using excel template for Excel Style Filter as shown in [https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/excel-style-filtering#templates](url).

I have added **igx-excel-style-conditional-filter** in the template.

When I open advanced filter dialog it doesnt close when I click on cancel or apply.
I have attached a zip file from stackblitz example here : [eq8ahu--run.zip](https://github.com/IgniteUI/igniteui-angular/files/8488784/eq8ahu--run.zip)

 * igniteui-angular version: 13.1.9
 * browser: Chrome

## Steps to reproduce  

1. Create an **igx-grid** component.
2. Add **igx-grid-excel-style-filtering** template with **igx-excel-style-conditional-filter**.
3. Start the application and open filter. Click on advanced filter and try to close or apply filters.

## Result  
What is the actual result after following the steps to reproduce?

Ans : The dialog doesnt close and gives error as shown in image below
image

## Expected result  
What is the expected result after following the steps to reproduce?
Ans : The dialog should close and should apply the selected filters correctly.

## Attachments  
A screenshot of example on Stackblitz 
image

### PR DESCRIPTION
**Pull request by ChronosSF**
Closes #11404   

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-custom-dialog.component.ts [hunk 1]
```diff
@@ -130,6 +130,7 @@ export class IgxExcelStyleCustomDialogComponent implements AfterViewInit {
                 this.grid.rootGrid ? this.grid.rootGrid.nativeElement : this.grid.nativeElement :
                 esf;
         this.toggle.open(this._customDialogOverlaySettings);
+        this.overlayComponentId = this.toggle.overlayId;
```
Comment (wnvko) [inline projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-custom-dialog.component.ts:133]: we should also clear the `overlayComponentId` on close. Otherwise first time the target will be the `esf` and each next time the target will be the grid's ` nativeElement`.

Comment (ChronosSF) [reply projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-custom-dialog.component.ts:133]: Sure, I added a clear. The sample did indeed started opening the dialog with the grid as parent . Still unsure why it works like that but with the clear, the sample seems to be working like before.

**Review by wnvko — APPROVED** [review]
