### PR TITLE
Use columnList internally, keep public columns prop

### LINKED ISSUE #7681: When use grid.columns getter the error is thrown in the console
## Description  

 * browser: all

## Steps to reproduce  

1. Open the following [sample](https://stackblitz.com/edit/angular-pskbsu)
2. Open the browser console

## Result  

image

## Expected result  

No errors should be thrown in the console

### PR DESCRIPTION
**Pull request by hanastasov**
Closes #7681

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Review by kdinev — APPROVED** [review]

File: projects/igniteui-angular/src/lib/grids/grouping/group-by-area.directive.ts [hunk 1]
```diff
@@ -122,7 +122,7 @@ export abstract class IgxGroupByAreaDirective {
         const drag: IgxColumnMovingDragDirective = event.detail.owner;
         if (drag instanceof IgxColumnMovingDragDirective) {
             const column = drag.column;
-            if (this.grid.columns.indexOf(column) < 0) {
+            if (this.grid.columnList.find(c => c === column).index < 0) {
```
Comment (rkaraivanov) [inline projects/igniteui-angular/src/lib/grids/grouping/group-by-area.directive.ts:125]:
```suggestion
            if (this.grid.columnList.find(c => c === column)) {

```
The old code was testing if the column is in the grid column collection, not its index

**Review by rkaraivanov — CHANGES_REQUESTED** [review]

**Review by rkaraivanov — APPROVED** [review]
