### PR TITLE
fix(toast): add margin to the toast component

### LINKED ISSUE #6911: The shadow of the toast component in Bootstrap theme is chopped
## Description  
The shadow on the top and on the bottom of the toast component is chopped when a Bootstrap theme is applied

## Steps to reproduce  

1. Open https://staging.infragistics.com/products/ignite-ui-angular/angular/components/toast.html
2. Apply Bootstrap theme

## Result  
The shadow is not fully visible

## Expected result  
The shadow should be visible

## Attachments  
Screen Shot 2020-03-12 at 5 41 42 PM

### PR DESCRIPTION
**Pull request by SisIvanova**
Closes #6911

### Additional information (check all that apply):
 - [x] Bug fix
 - [x] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [x] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [x] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/toast/toast.component.ts [hunk 1]
```diff
@@ -304,26 +305,22 @@ export class IgxToastComponent implements IToggleView, OnInit, OnDestroy {
...
-    public mapPositionToClassName(): any {
-        if (this.position === IgxToastPosition.Top) {
-            return this.CSS_CLASSES.IGX_TOAST_TOP;
-        }
 
-        if (this.position === IgxToastPosition.Middle) {
-            return this.CSS_CLASSES.IGX_TOAST_MIDDLE;
-        }
+    @HostBinding('class.igx-toast--top')
+    public get cssClassTop(): boolean {
```
Comment (simeonoff) [inline projects/igniteui-angular/src/lib/toast/toast.component.ts:310]: No need to specify the return type, it's implicitly implied by TypeScript;

File: projects/igniteui-angular/src/lib/toast/toast.component.ts [hunk 2]
```diff
@@ -304,26 +305,22 @@ export class IgxToastComponent implements IToggleView, OnInit, OnDestroy {
...
+       return this.position === IgxToastPosition.Top;
+    }
 
-        if (this.position === IgxToastPosition.Bottom) {
-            return this.CSS_CLASSES.IGX_TOAST_BOTTOM;
-        }
+    @HostBinding('class.igx-toast--middle')
+    public get cssClassMiddle(): boolean {
```
Comment (simeonoff) [inline projects/igniteui-angular/src/lib/toast/toast.component.ts:315]: No need to specify the return type, it's implicitly implied by TypeScript;

File: projects/igniteui-angular/src/lib/toast/toast.component.ts [hunk 3]
```diff
@@ -304,26 +305,22 @@ export class IgxToastComponent implements IToggleView, OnInit, OnDestroy {
...
+       return this.position === IgxToastPosition.Middle;
+    }
+
+    @HostBinding('class.igx-toast--bottom')
+    public get cssClassBottom(): boolean {
```
Comment (simeonoff) [inline projects/igniteui-angular/src/lib/toast/toast.component.ts:320]: No need to specify the return type, it's implicitly implied by TypeScript;

File: src/app/toast/toast.sample.css [hunk 4]
```diff
@@ -2,23 +2,17 @@
...
-}
-
 .btn-group {
     display: flex;
     width: 300px;
     margin-top: 16px;
     justify-content: space-between;
 }
+
+.igx-toast--bottom {
```
Comment (simeonoff) [inline src/app/toast/toast.sample.css:12]: This should be part of the toast theme, not the sample. Delete from here and add to the theme.

File: src/app/toast/toast.sample.css [hunk 5]
```diff
@@ -2,23 +2,17 @@
...
+    margin-bottom: 16px;
+}
+
+.igx-toast--top {
+    margin-top: 16px;
```
Comment (simeonoff) [inline src/app/toast/toast.sample.css:17]: This should be part of the toast theme, not the sample. Delete from here and add to the theme.

File: src/app/toast/toast.sample.html [hunk 6]
```diff
@@ -23,12 +23,12 @@ <h4 class="sample-title">Middle Position</h4>
             <h4 class="sample-title">Top Position</h4>
             <div class="preview top"></div>
             <div class="btn-group">
-                <button igxButton="raised" igxRipple="white" (click)="showToast(toast, 'top')" [disabled]="toast.isVisible">Show Toast</button>
-                <button igxButton="raised" igxRipple="white" (click)="toast.hide()" [disabled]="!toast.isVisible">Hide Toast</button>
+                <button igxButton="raised" igxRipple="white" (click)="toast.toggle()">Toggle Toast</button>
```
Comment (simeonoff) [inline src/app/toast/toast.sample.html:26]: I am an idiot :) Could you please revert it to how it was before? Thanks!

**Comment by simeonoff** [comment]
@SisIvanova, also, update the changelog.
