### PR TITLE
Slider ticks enhancements

### LINKED ISSUE #6225: When set to 1, secondaryTicks are not rendered
## Description  
secondaryTicks set to 1 does not render secondary ticks

 * igniteui-angular version: 9.0.0-beta.4
## Steps to reproduce  

1. Add a slider with 1 secondary tick:
`<igx-slider [maxValue]="50" [primaryTicks]="6" [secondaryTicks]="1" [showTicks]="true" [step]="10" [type]="type"></igx-slider>`

## Result  
 Secondary ticks are not rendered

## Expected result  
 Secondary ticks to be rendered

### LINKED ISSUE #6228: Slider ticks refactoring
## Description  
Slider improvements:
- [x] Remove isCountinuous input.
- [x] Remove Hummer module
- [x] Remove ngZone dependency injection.
- [x] Remove all unused imports
- [x] All Enum values to pascal case.
- [x] Update stepDistance only when you change the step input. (stepChange evt)

### PR DESCRIPTION
**Pull request by Aleksandyr**
Closes #6228 
Closes #6225  

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/slider/slider.component.ts [hunk 1]
```diff
@@ -409,30 +404,6 @@ export class IgxSliderComponent implements
...
-     * ```typescript
-     * @ViewChild("slider2")
-     * public slider: IgxSliderComponent;
-     * ngAfterViewInit(){
-     *     let continuous = this.slider.continuous;
-     * }
-     * ```
-     */
-    @Input()
-    @DeprecateProperty(`IgxSliderComponent \`isContinuous\` property is deprecated.\nUse \`continuous\` instead.`)
```
Comment (kdinev) [inline projects/igniteui-angular/src/lib/slider/slider.component.ts]: I can't find which version we've deprecated this in?

File: projects/igniteui-angular/src/lib/slider/slider.component.ts [hunk 2]
```diff
@@ -1004,6 +976,12 @@ export class IgxSliderComponent implements
         // Set track travel zone
         this._pMin = this.valueToFraction(this.lowerBound) || 0;
         this._pMax = this.valueToFraction(this.upperBound) || 1;
+
+        this._resizeNotify.pipe(takeUntil(this._destroyer$)).subscribe(() => {
+            this._ngZone.runTask(() => {
+                this.stepDistance = this.calculateStepDistance();
+            });
+        });
```
Comment (rkaraivanov) [inline projects/igniteui-angular/src/lib/slider/slider.component.ts]: Not a fan of triggering a zone run task for this callback.
IMO it would be better to leave the observer in the zone and throttle the resize observer events.

File: projects/igniteui-angular/src/lib/slider/slider.component.ts (hunk 1 above)
Comment (Aleksandyr) [reply projects/igniteui-angular/src/lib/slider/slider.component.ts]: As I see from the changelog [here](https://github.com/IgniteUI/igniteui-angular/pull/4994/files#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR65) this change was made in [7.3.4 ](https://github.com/IgniteUI/igniteui-angular/releases/tag/7.3.4) release, even though the label that was set to the related [issues](https://github.com/IgniteUI/igniteui-angular/pull/4994) is 8.0.x. I've gone through all releases we've made so far and in [7.3.4](https://github.com/IgniteUI/igniteui-angular/releases/tag/7.3.4) is the last place where we are setting **isContinuous** as deprecated.
