### PR TITLE
fix(grid): add return type and return value to endEdit method

### LINKED ISSUE #13433: IgxGrid: endEdit method no longer returns a value
## Description  
In version [10.2.x](https://github.com/IgniteUI/igniteui-angular/blob/10.2.x/projects/igniteui-angular/src/lib/grids/grid-base.directive.ts#L6690) grid's endEdit method returns whether the edit event is canceled, however, since version [11.2.x](https://github.com/IgniteUI/igniteui-angular/blob/11.2.x/projects/igniteui-angular/src/lib/grids/grid-base.directive.ts#L5975) there is no return value.
Returning this value could be useful in scenarios when is required to check if the event was canceled and end the editing through the code in such cases.

 * igniteui-angular version: 14, 15, 16
 * browser: 

## Steps to reproduce  

1. Step 1
2. Step 2
3. ...

## Result  
grid.endEdit() method does not return value

## Expected result  
grid.endEdit() method returns a value - whether the edit event was canceled.

### PR DESCRIPTION
**Pull request by teodosiah**
Closes #13433   

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.component.ts [hunk 1]
```diff
@@ -1404,7 +1404,7 @@ export class IgxPivotGridComponent extends IgxGridBaseDirective implements OnIni
     /**
      * @hidden @internal
      */
-    public override endEdit(_commit = true, _event?: Event) {
+    public override endEdit(_commit = true, _event?: Event): any {
```
Comment (ddincheva) [inline projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.component.ts:1407]: please avoid 'any' as a type ... the return type for this method should be boolean

**Review by ddincheva — APPROVED** [review]
