### PR TITLE
Ensure there is no initial placeholder value

### LINKED ISSUE #4236: Select's label is positioned incorrectly
## Description  
The label of the IgxSelect is positioned in the upper right corner of the component.

 * igniteui-angular version:  7.2.0-rc4
 * browser: all

## Steps to reproduce  

1. Open the [StackBlitz](https://stackblitz.com/angular/earalgkryaav) select sample
2. Observe select's label

## Result  
The label is in the upper right corner of the component.

## Expected result  
Label should be placed in the input in the same way as placeholder is shown

### PR DESCRIPTION
**Pull request by IvayloG**
Closes #4236

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/select/select.component.ts [hunk 1]
```diff
@@ -118,7 +118,7 @@ export class IgxSelectComponent extends IgxDropDownComponent implements IgxSelec
      * An @Input property that sets input placeholder.
      *
      */
-    @Input() public placeholder = '';
+    @Input() public placeholder;
```
Comment (kdinev) [inline projects/igniteui-angular/src/lib/select/select.component.ts]: Why don't you just host bind the attribute placeholder?

Comment (IvayloG) [reply projects/igniteui-angular/src/lib/select/select.component.ts]: For the placeholder to work as expected, I need to pass it to the actual input element. So I am using an igxSelect   **@input** named as well "**placeholder**" to pass the user defined one to the **input's** placeholder attribute. 

Using the  **attr.placeholder** is needed, because otherwise the **@input** is evaluated as string and thus from the component's perspective there is always a placeholder (and the corresponding styles applied) even if it is an **empty string**, **null** or **undefined**.
