### PR TITLE
Prevents child overlay from disappearing when scrolling in hierarchical grid

### LINKED ISSUE #9917: IgxHierarchicalGrid: on the second level or further the row editing overlay disappears when scrolling
## Description  
If a row that is not on the root level is being edited and the grid is being scrolled the row editing overlay will be disappearing.

 * igniteui-angular version: 12.0.7
 * browser: all

## Steps to reproduce  

1. Open the first demo of the Hierarchical Grid Row Adding topic – [here ](https://www.infragistics.com/products/ignite-ui-angular/angular/components/hierarchicalgrid/row-adding)
2. Expand the second row.
3. Start editing a row on the second level of the grid.
4. Scroll the grid.

## Result  
The row editing overlay is disappearing.

## Expected result  
The row editing overlay should be visible.

## Attachments  
hgrid-scroll-on-second-level

### PR DESCRIPTION
**Pull request by 3phase**
Closes #9917  

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Review by ChronosSF — DISMISSED** [review]

**Review by damyanpetev — DISMISSED** [review]

File: projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts [hunk 1]
```diff
@@ -340,6 +340,15 @@ export class IgxHierarchicalGridComponent extends IgxHierarchicalGridBaseDirecti
         }
     }
 
+    /**
+     * @hidden
+     */
+    public get parentRowOutletDirective() {
+        // Targeting parent outlet in order to prevent hiding when outlet
+        // is present at a child grid and is attached to a row.
+        return this.parent.rowOutletDirective;
```
Comment (MayaKirova) [inline projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts:349]: Add a check if there is a parent since if this is a root grid that has <=2 rows this would throw an error.

**Review by MayaKirova — CHANGES_REQUESTED** [review]

File: projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts (hunk 1 above)
Comment (3phase) [reply projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts]: Thanks for noticing. It's done now.

**Review by MayaKirova — APPROVED** [review]

**Review by damyanpetev — APPROVED** [review]
