### PR TITLE
Explicitly trigger grid pipes on markForCheck call

### LINKED ISSUE #9246: When paging is enabled, grid does not update its view
* igniteui-angular version: 10.2

## Steps to reproduce  

Without paging
1. Open Grid Nested Props Update dev demo
2. Click Update
3. Observe how values are changed

With paging
1. Enable paging for the grid
2. Click Update
3. Observe how values are NOT changed

## Result  
Values in grid are NOT updated

## Expected result  
Values in grid to be updated when paging is enabled

### PR DESCRIPTION
**Pull request by hanastasov**
Closes #9246

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/grid-base.directive.ts [hunk 1]
```diff
@@ -4297,14 +4297,29 @@ export abstract class IgxGridBaseDirective extends DisplayDensityBase implements
...
+     * ```
      *
      * @example
      * ```typescript
-     * this.grid1.markForCheck();
+     * grid.markForCheck();
      * ```
      */
     public markForCheck() {
+        this.pipeTrigger++;
```
Comment (kdinev) [inline projects/igniteui-angular/src/lib/grids/grid-base.directive.ts:4322]: There's quite a few properties and methods where both `pipeTrigger++` and `markForCheck()` are called. Now there's redundant pipe trigger increments.

Comment (hanastasov) [reply projects/igniteui-angular/src/lib/grids/grid-base.directive.ts:4322]: Internally the code base uses `grid.cdr.markForCheck` and not `grid.markForCheck`. There were few places calling directly `markForCheck` that this PR changes to use `cdr.detectChanges()` in order to avoid pipeTrigger incremention.

**Review by kdinev — DISMISSED** [review]

**Comment by rkaraivanov** [comment]
See #9444 for review comments

**Review by rkaraivanov — APPROVED** [review]
