### PR TITLE
fix(time-picker): fix time picker pan event #9717

### LINKED ISSUE #9717: Swipe not working in time picker in touch devices
## Description  
When opening the time picker in mobile/ touch devices, unable to swipe through the hours and minutes list.

 * igniteui-angular version: all
 * browser: chrome, Firefox, safari iOS

## Steps to reproduce  

1. Open the time picker in any mobile device
2. Try to swipe through the time list

## Result  
Unable to swipe through the hours/minutes. Time can be changed by tapping on the top or bottom of the list.

## Expected result  
User should be able to swipe through the list in touch UI or some other option should be  given that is easy to understand (like up and down arrows on the top and bottom of the list on clicking which user can change the time).
Also the it would be nice if the input in the header is editable.

## Attachments  
Attach a sample if available, and screenshots, if applicable.

### PR DESCRIPTION
**Pull request by PlamenaMiteva**
Closes #9717 

### Additional information (check all that apply):
 - [X] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [X] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Review by ViktorSlavov — CHANGES_REQUESTED** [review]
Is it possible to add a test for the scenario?

**Review by ViktorSlavov — APPROVED** [review]

File: projects/igniteui-angular/src/lib/time-picker/time-picker.directives.ts [hunk 1]
```diff
@@ -166,55 +170,23 @@ export class IgxItemListDirective {
...
-                }
-                case 'ampmList': {
-                    this.timePicker.nextAmPm(delta);
-                    break;
-                }
-            }
-        }
+    public ngOnInit() {
+        const hammerOptions: HammerOptions = { recognizers: [[Hammer.Pan, { direction: Hammer.DIRECTION_VERTICAL, threshold: 5 }]] };
+        this.touchManager.addEventListener(this.elementRef.nativeElement, 'pan', this.onPanMove, hammerOptions);
```
Comment (jackofdiamond5) [inline projects/igniteui-angular/src/lib/time-picker/time-picker.directives.ts:182]: I think it's a good idea to destroy the `touchManager`  in `ngOnDestroy` since it may cause memory leaks.

**Review by ViktorSlavov — APPROVED** [review]

**Review by jackofdiamond5 — APPROVED** [review]

**Comment by Lipata** [comment]
Having threshold 10 for hammer.js config seems fine for both Android and iOS devices. However, because there isn't a scroll animation and inertia the experience seems that can be improved a lot. There is a separate issue for that: #6292.
