### PR TITLE
fix(grid-pinning): remove hide call in scrollToRow - master

### LINKED ISSUE #16493: [Elements] Action strip closes when clicking jump to row action
## Description  
Action strip closes when clicking jump to row action. You have to then exit the row to show it agin.

 * igniteui-angular version: any
 * browser: any

## Steps to reproduce  

1. Open https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/grids/tree-grid/row-actions#custom-implementation
2. Pin a row
3. Scroll so the row is out of view
4. Click on the `Jump down` button of action strip

## Result  
The action strip closes.

## Expected result  
The action strip shouldn't close

## Attachments  

Image

### PR DESCRIPTION
**Pull request by IMinchev64**
Closes #16493   

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by mddragnev** [comment]
@skrustev @IMinchev64 The change is fine. However, if the action strip is set as menu this behavior is not perfect IMO.
I think that when having the action strip as menu we should close the menu on every action click
https://github.com/user-attachments/assets/635939be-2a58-4f49-830e-0fa6898cc35a

**Comment by IMinchev64** [comment]
@mddragnev I added a condition to continue hiding the strip when the action strip is a menu.

Note that testing this in elements would be a bit of a hassle currently as:
1. The fix for this issue (#16834) would need to be merged in both master and 21.0.x as the action strip is broken in elements for the respective branches 
2. Even when the action strip works as a whole, using it as a menu is broken in elements as the moment we try to hover over the menu, the action strip gets hidden. This should be logged and fixed separately.

**Comment by mddragnev** [comment]
The issue still reproduces when the record you try to scroll to is out of view

**Comment by IMinchev64** [comment]
> The issue still reproduces when the record you try to scroll to is out of view

I am failing to reproduce this scenario with the same result

**Comment by IMinchev64** [comment]
Replaced the unconditional action-strip hide/reset on vertical scroll with a conditional check: keep it only when the current context row is pinned, still connected to the DOM, and hovered; otherwise keep the previous hide + context reset behavior. This preserves virtualization cleanup while preventing the strip from disappearing during pinned-row jump/scroll scenarios.

**Comment by dkamburov** [comment]
@IMinchev64 please click on **resolve conversation** button if the review comments are ready.

File: projects/igniteui-angular/grids/grid/src/grid-base.directive.ts [hunk 1]
```diff
@@ -7798,7 +7798,7 @@ export abstract class IgxGridBaseDirective implements GridType,
         const keepActionStrip =
             !!context?.pinned &&
             !!contextEl?.isConnected &&
-            !!context?.asMenuItems;
+            !context?.asMenuItems;
```
Comment (mddragnev) [inline projects/igniteui-angular/grids/grid/src/grid-base.directive.ts]: The context is the row element here. The row does not have asMenuItems property, thus this will evaluate to undefined every time. You should get the info you need from the actionstrip

**Review by mddragnev — APPROVED** [review]
