### PR TITLE
Mask refactoring

### LINKED ISSUE #6454: Mask refactoring
Related to #6271

Some refactoring is needed for the `mask directive` since the new `igxDateTimeEditorDirective` will inherit some of the mask's functionality.

### LINKED ISSUE #6710: Mask directive doesn't handle drag & drop
## Description  
When you drag and drop text over a mask editor the text is allowed to exceed the limits of the mask and is not parsed as a value.

 * igniteui-angular version: 9
 * browser: N/A

## Steps to reproduce  

1. Open https://www.infragistics.com/products/ignite-ui-angular/angular/components/mask.html#mask-demo
2. Select the text from the first input
3. Drag and drop it to the mask editor below

## Result  
The text is allowed go outside of the mask limits and you can 'delete' parts of the mask and literals:
mask-drag-drop

## Expected result  
The dropped text should be treated as paste and applied over the mask. Ideally, when dragging, the mask should appear with the browser cursor to allow to determine the drop location.

### PR DESCRIPTION
**Pull request by jackofdiamond5**
Closes #6454, -tested
Fixes #6710, -tested
Fixes https://github.com/IgniteUI/igniteui-angular/issues/6784, -tested
Fixes https://github.com/IgniteUI/igniteui-angular/issues/6783,
Fixes https://github.com/IgniteUI/igniteui-angular/issues/6712, -tested
Fixes https://github.com/IgniteUI/igniteui-angular/issues/6832 -tested

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/directives/mask/mask.directive.ts [hunk 1]
```diff
@@ -37,17 +31,15 @@ export class IgxMaskDirective implements OnInit, ControlValueAccessor {
      * ```html
      * <input [promptChar] = "'/'">
      * ```
-     * @memberof IgxMaskDirective
      */
     @Input()
-    public promptChar: string;
+    public promptChar = '_';
```
Comment (damyanpetev) [inline projects/igniteui-angular/src/lib/directives/mask/mask.directive.ts]: 👍

File: projects/igniteui-angular/src/lib/directives/mask/mask.directive.ts [hunk 2]
```diff
@@ -26,7 +21,6 @@ export class IgxMaskDirective implements OnInit, ControlValueAccessor {
      * ```html
      * <input [igxMask] = "'00/00/0000'">
      * ```
-     * @memberof IgxMaskDirective
      */
     @Input('igxMask')
     public mask: string;
```
Comment (damyanpetev) [inline projects/igniteui-angular/src/lib/directives/mask/mask.directive.ts]: Didn't the mask have a default value as well?

File: projects/igniteui-angular/src/lib/directives/mask/mask.directive.ts [hunk 3]
```diff
@@ -57,24 +49,22 @@ export class IgxMaskDirective implements OnInit, ControlValueAccessor {
      * ```html
      * <input placeholder = "enter text...">
      * ```
-     * @memberof IgxMaskDirective
      */
+    @DeprecateProperty('"placeholder" is deprecated, use native placeholder instead.')
```
Comment (damyanpetev) [inline projects/igniteui-angular/src/lib/directives/mask/mask.directive.ts]: Yeah this will likely trigger deprecation warnings along with normal attribute assignment due to it being an Input.
Might need to find a better way to handle this.

File: projects/igniteui-angular/src/lib/directives/mask/mask.directive.ts [hunk 4]
```diff
@@ -105,271 +92,156 @@ export class IgxMaskDirective implements OnInit, ControlValueAccessor {
     @Output()
     public onValueChange = new EventEmitter<IMaskEventArgs>();
 
-    /**
-     *@hidden
-     */
-    private get value() {
+    /** @hidden @internal; */
```
Comment (damyanpetev) [inline projects/igniteui-angular/src/lib/directives/mask/mask.directive.ts]:
```suggestion
    /** @hidden @internal */
```
Also, probably no surprise here - what's with making this public? Guessing related to future PR's, but I'd rather see it change in that PR so I know what the use for it is.

**Comment by Lipata** [comment]
We will not merge this, until igniteui-angular@9.0.0 is release, becasue it is needed for the component for the next milestone.

**Comment by Lipata** [comment]
Paste should be supported in IE

File: projects/igniteui-angular/src/lib/directives/mask/mask-parsing.service.ts [hunk 5]
```diff
@@ -1,45 +1,48 @@
...
-    DELETE : 46
-  };
-
+    Ctrl: 17,
+    Z: 90,
+    Y: 89,
+    X: 88,
+    BACKSPACE: 8,
+    DELETE: 46
+};
```
Comment (rkaraivanov) [inline projects/igniteui-angular/src/lib/directives/mask/mask-parsing.service.ts]: Can you merge these with [those](https://github.com/IgniteUI/igniteui-angular/blob/9c70ca8c48510bc0c113d297ef8aa31c36991a25/projects/igniteui-angular/src/lib/core/utils.ts#L133) an use them instead of redeclaring similar enumerations in the lib?

File: projects/igniteui-angular/src/lib/directives/mask/mask-parsing.service.ts [hunk 6]
```diff
@@ -0,0 +1,251 @@
+import { Injectable } from '@angular/core';
```
Comment (damyanpetev) [inline projects/igniteui-angular/src/lib/directives/mask/mask-parsing.service.ts]: Huh, apparently really hard for github to display the rename +diff...

Comment (damyanpetev) [reply projects/igniteui-angular/src/lib/directives/mask/mask-parsing.service.ts]: Nvm, `git log --follow` shows the old file history just fine, it's just `git diff` that can't handle the rename with that much changes apparently :/

Comment (damyanpetev) [reply projects/igniteui-angular/src/lib/directives/mask/mask-parsing.service.ts]: Sigh.
`rename projects/igniteui-angular/src/lib/directives/mask/{mask-helper.ts => mask-parsing.service.ts} (42%)`. We went over the threshold there, Skippy.
@jackofdiamond5 Can you do the file rename in a separate PR (will merge first) so this can have  a decent diff?

File: projects/igniteui-angular/src/lib/directives/mask/mask.directive.ts [hunk 7]
```diff
@@ -105,264 +87,214 @@ export class IgxMaskDirective implements OnInit, ControlValueAccessor {
...
         }
+        this._onTouchedCallback();
+    }
 
-        const rawVal = this.maskParser.restoreValueFromMask(this.value, this._maskOptions);
-
-        this.dataValue = this.includeLiterals ? this.value : rawVal;
-        this._onChangeCallback(this.dataValue);
+    /** @hidden */
+    @HostListener('dragover')
```
Comment (damyanpetev) [inline projects/igniteui-angular/src/lib/directives/mask/mask.directive.ts]: `dragover` is a very chatty event, `dragenter` should do just fine. Should also add `dragleave` to reset the state

File: projects/igniteui-angular/src/lib/directives/mask/mask.directive.ts [hunk 8]
```diff
@@ -105,264 +88,213 @@ export class IgxMaskDirective implements OnInit, ControlValueAccessor {
...
-     */
-    private _valOnPaste;
+    private get nativeElement(): HTMLInputElement {
+        return this.elementRef.nativeElement;
+    }
 
+    private _key: number;
+    private _oldVal: any;
+    private _end = 0;
+    private _start: number;
```
Comment (damyanpetev) [inline projects/igniteui-angular/src/lib/directives/mask/mask.directive.ts]: Might not be a bad idea to have an initial value (0?)

File: projects/igniteui-angular/src/lib/directives/mask/mask.directive.ts [hunk 9]
```diff
@@ -105,264 +88,213 @@ export class IgxMaskDirective implements OnInit, ControlValueAccessor {
...
-            this.maskParser.data = (this._key === KEYS.BACKSPACE) || (this._key === KEYS.DELETE);
+        const rawVal = this.maskParser.parseValueFromMask(this.inputValue, this.maskOptions);
+        this._dataValue = this.includeLiterals ? this.inputValue : rawVal;
+        this._onChangeCallback(this._dataValue);
 
-            this.value = this._selection && this._selection !== 0 ?
-                this.maskParser.parseValueByMaskUponSelection(this.value, this._maskOptions, currentCursorPos - 1, this._selection) :
-                this.maskParser.parseValueByMask(this.value, this._maskOptions, currentCursorPos - 1);
+        this.onValueChange.emit({ rawValue: rawVal, formattedValue: this.inputValue });
+        // this.afterInput();
```
Comment (damyanpetev) [inline projects/igniteui-angular/src/lib/directives/mask/mask.directive.ts]: Is this commented out for a reason?

File: projects/igniteui-angular/src/lib/directives/mask/mask.directive.ts [hunk 10]
```diff
@@ -105,264 +88,213 @@ export class IgxMaskDirective implements OnInit, ControlValueAccessor {
...
 
-    /**
-     *@hidden
-     */
-    private setCursorPosition(start: number, end: number = start): void {
-        this.nativeElement.setSelectionRange(start, end);
+    private afterInput() {
+        this._oldVal = this.inputValue;
+        this._hasDropAction = false;
+        this._end = 0;
```
Comment (damyanpetev) [inline projects/igniteui-angular/src/lib/directives/mask/mask.directive.ts]: perhaps also reset start?

File: projects/igniteui-angular/src/lib/directives/mask/mask.directive.ts [hunk 11]
```diff
@@ -105,264 +88,213 @@ export class IgxMaskDirective implements OnInit, ControlValueAccessor {
...
+        this.renderer.setAttribute(this.nativeElement, 'placeholder',
+            this.placeholder ? this.placeholder : this.maskOptions.format);
+    }
 
-        this._maskOptions.format = this.mask ? this.mask : 'CCCCCCCCCC';
-        this._maskOptions.promptChar = this.promptChar ? this.promptChar : '_';
-        this.nativeElement.setAttribute('placeholder', this.placeholder ? this.placeholder : this._maskOptions.format);
+    /** @hidden */
+    public ngAfterViewChecked(): void {
+        this._oldVal = this.inputValue;
```
Comment (damyanpetev) [inline projects/igniteui-angular/src/lib/directives/mask/mask.directive.ts]: In theory definitely **not** the place to save old value. Kinda chatty hook this one. 
The mask is in control of this value, right? Why should it come from the native input, when you can save it when the mask assigns it there (afterInput, onFocus / showMask)?
