### PR TITLE
fix(tree-grid): dont generate child key column #10925

### LINKED ISSUE #10925: igx-tree-grid with autoGenerate=true should ignore the childDataKey column when generating
## Description  
Currently, if I have an `igx-tree-grid` with `autoGenerate="true"` and `childDataKey` defined, the auto column generation includes the child column in the parent.

 * igniteui-angular version: all
 * browser: all

## Steps to reproduce  

1. Define a tree grid with auto column generation and child data key
2. Pass a data source to the tree grid

## Result  
The child data key column is also rendered in the parents

## Expected result  
The child data key column should be excluded in the rendering.

## Attachments  
image

### PR DESCRIPTION
**Pull request by kdinev**
Closes #10925   

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/grid-base.directive.ts [hunk 1]
```diff
@@ -6677,14 +6677,16 @@ export abstract class IgxGridBaseDirective extends DisplayDensityBase implements
...
+        const factory = this.resolver.resolveComponentFactory(IgxColumnComponent);
         const fields = this.generateDataFields(data);
         const columns = [];
 
         fields.forEach((field) => {
-            const newColumn = new IgxColumnComponent(this, this.cdr, this.platform);
-            newColumn.field = field;
-            newColumn.dataType = this.resolveDataTypes(data[0][field]);
-            columns.push(newColumn);
+            const ref = factory.create(this.viewRef.injector);
```
Comment (rkaraivanov) [inline projects/igniteui-angular/src/lib/grids/grid-base.directive.ts:6685]: You can still remove the deprecated factory instantiation:
```typescript
const ref = this.viewRef.createComponent(IgxColumnComponent)
```

Comment (kdinev) [reply projects/igniteui-angular/src/lib/grids/grid-base.directive.ts:6685]: @rkaraivanov I'll work on this, because removing the deprecated factory is a bit larger in terms of a change, because it's used in other places as well.

File: projects/igniteui-angular/src/lib/grids/grid-base.directive.ts [hunk 2]
```diff
@@ -6677,12 +6677,11 @@ export abstract class IgxGridBaseDirective extends DisplayDensityBase implements
...
-        const factory = this.resolver.resolveComponentFactory(IgxColumnComponent);
         const fields = this.generateDataFields(data);
         const columns = [];
 
         fields.forEach((field) => {
-            const ref = factory.create(this.viewRef.injector);
+            const ref = this.viewRef.createComponent(IgxColumnComponent, { injector: this.injector, ngModuleRef: this.moduleRef });
             ref.instance.field = field;
             ref.instance.dataType = this.resolveDataTypes(data[0][field]);
             ref.changeDetectorRef.detectChanges();
```
Comment (kdinev) [inline projects/igniteui-angular/src/lib/grids/grid-base.directive.ts:6687]: @rkaraivanov Can you tell me if the `detectChanges()` call is really necessary here. If it's needed, I suppose calling it once outside of the loop would be better.

File: projects/igniteui-angular/src/lib/grids/grid-base.directive.ts (hunk 1 above)
Comment (kdinev) [reply projects/igniteui-angular/src/lib/grids/grid-base.directive.ts]: @rkaraivanov I decided to remove it completely in a separate PR.

File: projects/igniteui-angular/src/lib/grids/grid-base.directive.ts (hunk 2 above)
Comment (rkaraivanov) [reply projects/igniteui-angular/src/lib/grids/grid-base.directive.ts:6687]: AFAIK it is needed since column components are OnPush and we are changing the initial input values (I recall that Angular did not call ngOnChanges with dynamic components and OnPush, but that could be fixed).
As for the `detectChanges()` call, it is on the component instance itself, not on the host view, so I'm not entirely sure if we can batch it in a single call. Could be tested though..

**Review by damyanpetev — APPROVED** [review]

File: projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts [hunk 3]
```diff
@@ -2212,7 +2233,7 @@ describe('IgxGrid Component Tests #grid', () => {
             });
         }));
 
-        beforeEach(fakeAsync(/** height/width setter rAF */() => {
+        beforeEach(waitForAsync(() => {
```
[the remark this answers is not in the document]
Comment (kdinev) [reply projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts:2236]: @damyanpetev I'm not going to change this now, since `waitForAsync` should go sync when there's nothing to wait for.

**Review by damyanpetev — APPROVED** [review]
