### PR TITLE
fix(filtering): Make unary condition committable #5627

### LINKED ISSUE #5627: When add filter condition Null cannot add any other filters for this column
## Description  
Describe the issue.

 * igniteui-angular version: 7.3
 * browser: n/a

## Steps to reproduce  

1. Open dev sample gridGroupBy
2. Open filter for a column
3. For condition select Empty,Not Empty,Null, Not null
4. In the chip click Done icon 

Note: Same is valid for date filter like Today, Yesterday, etc
## Result  
Chip is not closed and cannot add other chips

## Expected result  
The chip should be closed and should be able to add other chip[s

## Attachments  
Attach a sample if available, and screenshots, if applicable.

### PR DESCRIPTION
**Pull request by astaev**
Closes #5627 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by nrobakova** [comment]
@astaev now when open filter row for Boolean column and click to open the drop down or click on button closed in the console an error is previewed.
Steps to reproduce:
1. Open dev sample gridFiltering
2. open filtering for column Contact
3. Open filtering drop down or click on button close

File: projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts [hunk 1]
```diff
@@ -129,6 +129,9 @@ export class IgxGridFilteringRowComponent implements AfterViewInit {
     @ViewChild('inputGroup', { read: ElementRef, static: false })
     protected inputGroup: ElementRef;
 
+    @ViewChild('dropDownTarget', { read: ElementRef, static: false })
+    protected inputGroupDate: ElementRef;
```
Comment (DiyanDimitrov) [inline projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts]: You could try to re-use the `inputGroup` element ref if you put the same id on the datepicker's input group.
