### PR TITLE
fix(date-picker): Fix for re-templating dropdown date-picker 

### LINKED ISSUE #4229: [igx-date-picker] Dropdown mode gets error when using igxDatePickerTemplate
## Description  
`igx-date-picker` Dropdown mode gets error when using `igxDatePickerTemplate`.

 * igniteui-angular version: 7.2.0-rc.3
 * browser: 

## Steps to reproduce  

1. Go to https://stackblitz.com/edit/igx-date-picker-igxdatepickertemplate-issue
2. Open console
3. Click a calendar icon

## Result  
An error occurs and calendar won't show up.

## Expected result  
An error should not occur and calendar should show up.

## Attachments  
https://stackblitz.com/edit/igx-date-picker-igxdatepickertemplate-issue

### PR DESCRIPTION
**Pull request by sboykova**
Closes #4229  

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [x] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts [hunk 1]
```diff
@@ -886,7 +892,13 @@ export class IgxDatePickerComponent implements IDatePicker, ControlValueAccessor
                 this.hasHeader = false;
                 const dropDownOverlay =
                     (this.dropDownOverlaySettings !== undefined) ? this._dropDownOverlay : this._dropDownOverlaySettings;
-                dropDownOverlay.positionStrategy.settings.target = this.editableInputGroup.nativeElement;
+                if (this.editableInputGroup) {
+                    dropDownOverlay.positionStrategy.settings.target = this.editableInputGroup.nativeElement;
+                } else {
+                    // if the date picker is retemplated, set an element marked with #dropDownTarget as a target to the drop-down
+                    dropDownOverlay.positionStrategy.settings.target = this.templateDropDownTarget.nativeElement;
```
Comment (bkulov) [inline projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts]: If the user has retemplated the dropdown but didn't set the id `#dropDownTarget` to any element, this line will throw exception because `this.templateDropDownTarget` will be null.

Comment (sboykova) [reply projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts]: Added error message that #dropDownTarget should be set.
