### PR TITLE
fix(combo): don't clear items when disabled #8200

### LINKED ISSUE #8200: igxCombo: Clear button is active when disabled property is set to true.
## Description  
Selected items can be cleared by clicking a clear button when disabled property is set to true.

 * igniteui-angular version: 10.1.5
 * browser: Google Chrome

## Steps to reproduce  

1. Run the sample.
2. Click the clear button.

## Result  
Selection is cleared.

## Expected result  
Selection should not be cleared.

## Attachments  
[igxCombo.zip](https://github.com/IgniteUI/igniteui-angular/files/5279773/igxCombo.zip)

### PR DESCRIPTION
**Pull request by Lipata**
Closes #8200   

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Review by PlamenaMiteva — DISMISSED** [review]

File: projects/igniteui-angular/src/lib/combo/combo.component.ts [hunk 1]
```diff
@@ -1324,11 +1324,13 @@ export class IgxComboComponent extends DisplayDensityBase implements IgxComboBas
      * @hidden @internal
      */
     public handleClearItems(event: Event): void {
-        this.deselectAllItems(true, event);
-        if (this.collapsed) {
-            this.getEditElement().focus();
-        } else {
-            this.focusSearchInput(true);
+        if (!this.disabled) {
```
Comment (ViktorSlavov) [inline projects/igniteui-angular/src/lib/combo/combo.component.ts:1327]: Could this be moved above the other logic w/ a `return` statement?:
```
if (this.disable) {
    return;
}
...
```

I know it would change the logic and the event will not be stopped from propagating, but the click handler for opening should still have a `disabled` check, so we should be fine

File: projects/igniteui-angular/src/lib/combo/combo.component.spec.ts [hunk 2]
```diff
@@ -2541,13 +2572,6 @@ describe('igxCombo', () => {
                 expect(combo.valid).toEqual(IgxComboState.INITIAL);
                 expect(combo.comboInput.valid).toEqual(IgxInputState.INITIAL);
             });
-            it('should not open on click if combo is disabled', () => {
```
Comment (ViktorSlavov) [inline projects/igniteui-angular/src/lib/combo/combo.component.spec.ts:2544]: Does this behavior change?

**Review by ViktorSlavov — CHANGES_REQUESTED** [review]

File: projects/igniteui-angular/src/lib/combo/combo.component.ts (hunk 1 above)
Comment (Lipata) [reply projects/igniteui-angular/src/lib/combo/combo.component.ts]: You are right that onInputClick is called, where we already have event.stopPropogation().

File: projects/igniteui-angular/src/lib/combo/combo.component.spec.ts (hunk 2 above)
Comment (Lipata) [reply projects/igniteui-angular/src/lib/combo/combo.component.spec.ts:2544]: I've just made and old test to be a unit test.

**Review by ViktorSlavov — APPROVED** [review]
