### PR TITLE
fix(igxGrid): Prevent any unneccesary size recalcs on data changing. …

### LINKED ISSUE #6211: Grid scrolling has poor performance
## Description  
Describe the issue.

 * igniteui-angular version: 9.0.0-beta.3
 * browser: any

## Steps to reproduce  

1. Open [FinJS sample](https://www.infragistics.com/angular-demos/finjs-sample)
2. Set records to 8200 and Frequency to 100ms
3. Hit Live-all prices button

## Result
The vertical scroll is not smooth

### PR DESCRIPTION
**Pull request by MayaKirova**
…Updating auto-sizing tests to be async and wait for the resize observer to update them as needed.

Closes #6211  

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by ChronosSF** [comment]
@zdrawku , @rkaraivanov , could you please confirm that Maya's changes return the performance to where it should be?

File: projects/igniteui-angular/src/lib/grids/grid/grid.component.ts [hunk 1]
```diff
@@ -145,7 +145,7 @@ export class IgxGridComponent extends IgxGridBaseDirective implements GridType,
         if (this.shouldGenerate) {
             this.setupColumns();
         }
-        this.notifyChanges(true);
+        this.cdr.markForCheck();
```
Comment (nrobakova) [inline projects/igniteui-angular/src/lib/grids/grid/grid.component.ts]: This need to be changed in the tree-grid.component.ts, also.
Because now the issue is fixed for the grid, but it is still reproducible in the treeGrid

**Comment by nrobakova** [comment]
Hi @MayaKirova, now the issue for the treeGrid is fixed, but when change the grid data the grid is not resized correct.
Steps to reproduce:
1. open dev sample gridRowEdit
2. In the grid (Grid without row editing and with transactions)
3. Click on button delete for all the rows
4. Click button commit
 In the place of the scroll bar there is an empty space:
image

Note: this is not reprodusible in master

**Comment by nrobakova** [comment]
Hi @MayaKirova the issue is still reproducible. If in the described steps I click in the beginning button 'Set container height px' again the grid is not resized correct also if in the gridGroupBy sample filter with no values found same result is displayed.
