### PR TITLE
fix(pivot): Fix wrongly selected column when selecting rows

### LINKED ISSUE #10706: [igxPivot] Clicking on empty row header  cell selects the whole row column
## Description  
Clicking either on empty row header or  outside of the div which holds the header value selects the whole column.

 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Open any pivot sample with row and column selection set to single
2. Click on any of the edges of any row header cells
3. Observe

## Result  
whole column in the row header area gets selected

## Expected result 
The column should not be selected

## Attachments  

selection

### PR DESCRIPTION
**Pull request by mddragnev**
Closes #10706   

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-row-dimension-header.component.ts [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+        @Inject(IGX_GRID_BASE) public grid: GridType,
+        public colResizingService: IgxColumnResizingService,
+        public cdr: ChangeDetectorRef,
+        private refInstance: ElementRef<HTMLElement>
+    ) {
+        super(grid, colResizingService, cdr, refInstance);
+    }
+
+    @HostListener('click', ['$event'])
+    public onClick(event: MouseEvent) {
```
Comment (dkamburov) [inline projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-row-dimension-header.component.ts:28]: @mddragnev if we extend this we can also remove the pivot specific check in `IgxGridHeaderComponent`'s `onClick` method. We should revert the change from:
```
        if (!this.grid.isPivot || !this.grid.navigation.isRowHeaderActive) {
            this.grid.theadRow.nativeElement.focus();
        }
```
to:

```
    this.grid.theadRow.nativeElement.focus();
```

**Review by dkamburov — APPROVED** [review]
