### PR TITLE
fix(selection): accept 0 as itemID

### LINKED ISSUE #2581: IgxSelectionAPIService allows to add items with id which is undefined
### Description  
When using the set() method of the IgxSelectionAPIService  and pass `undefined` for id, then value is associated with `undefined`. This is because the JavaScript Set allows undefined to be added as id.

### Expected result  
Nothing is added to the selection collection, when id is `undefined`.

### PR DESCRIPTION
**Pull request by DiyanDimitrov**
Closes #2581.

### CODE REVIEW

File: projects/igniteui-angular/src/lib/core/selection.ts [hunk 1]
```diff
@@ -60,7 +60,7 @@ export class IgxSelectionAPIService {
         if (sel === undefined) {
             sel = this.get_empty();
         }
-        if (!itemID) {
+        if (itemID == null) {
```
Comment (Lipata) [inline projects/igniteui-angular/src/lib/core/selection.ts]: Even though `undefined == null`, returns true, it's clear and easier to understand `itemID === null || itemID === undefined` (I've checked our source code and the second approach is used). In addition when `itemID === ''` then this will not be handled.

Comment (DiyanDimitrov) [reply projects/igniteui-angular/src/lib/core/selection.ts]: Modified to check for all falsy values except 0 `!itemID && itemID !== 0`.
