### PR TITLE
fix(ssr): Fix igx-tabs SSR rendering

### LINKED ISSUE #6540: igx-tabs breaks SSR
## Description  
Routes with `igx-tabs` hang during SSR.

`Unhandled Promise rejection: Cannot read property 'disconnect' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'disconnect' of undefined`

 * igniteui-angular version: 8.2.16
 * browser: PlatformServer

## Steps to reproduce  

1. Create a page with tabs
2. Enable angular universal
3. Serve the route with tabs

## Result  
The route hangs

## Expected result  
The route should return a view.

### PR DESCRIPTION
**Pull request by MayaKirova**
Closes #6540   

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/tabs/tabs.component.ts [hunk 1]
```diff
@@ -317,29 +318,32 @@ export class IgxTabsComponent implements IgxTabsBase, AfterViewInit, OnDestroy {
...
+        if (this.platformUtil.isBrowser) {
+            requestAnimationFrame(() => {
+                const newTab = this.tabs.toArray()[this._selectedIndex];
+                if (newTab) {
+                    this.performSelection(newTab);
+                } else {
+                    this.hideIndicator();
+                }
+            });
+            if (this.platformUtil.isBrowser) {
```
Comment (ChronosSF) [inline projects/igniteui-angular/src/lib/tabs/tabs.component.ts]: Aren't you already in a ```if (this.platformUtil.isBrowser) {``` case here?
