### PR TITLE
fix(drop-down): properly overwrite selection w/ onSelection args, #6208

### LINKED ISSUE #6208: [IgxDropDown] Selection cannot be overwritten in `onSelection` event
## Description  
The selection of an `igx-drop-down` cannot be changed when subscribing to its `onSelection` event.
The API documentation for the emitter specifies that this happens _before_ the selection has changed and thus the user could try to overwrite the selection (same as they can currently `cancel` it).

The `igx-combo`, for example, allows for it's selection to be changed during its `onSelectionChange` event.

 * igniteui-angular version: 8.1.x +
 * browser: N/A

## Steps to reproduce  

1. Open the [following sample](https://stackblitz.com/edit/drop-down-item-bug?file=src/app/dropdown-sample-4/dropdown-sample-4.component.ts)
2. Under the `.ts` file's `ngAfterViewInit`, there's a subscription that should always select a specific drop-down item.
3. Try to select any item except the last one.

## Result  
The item is selected.

## Expected result  
The selection should be overwritten and `Special Item` should be selected

### PR DESCRIPTION
**Pull request by ViktorSlavov**
Closes #6208 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/drop-down/drop-down.component.ts [hunk 1]
```diff
@@ -538,17 +538,23 @@ export class IgxDropDownComponent extends IgxDropDownBase implements IDropDownBa
         this.onSelection.emit(args);
 
         if (!args.cancel) {
-            this.selection.set(this.id, new Set([newSelection]));
-            if (!this.virtDir) {
-                if (oldSelection) {
-                    oldSelection.selected = false;
+            if (args.newSelection === null ||
+                (args.newSelection.hasOwnProperty('value') && args.newSelection.hasOwnProperty('index') && this.virtDir) ||
```
Comment (Lipata) [inline projects/igniteui-angular/src/lib/drop-down/drop-down.component.ts]: Please, put that validation in a separate method with an appropriate name. Thanks!

File: projects/igniteui-angular/src/lib/drop-down/drop-down.component.ts [hunk 2]
```diff
@@ -538,19 +538,29 @@ export class IgxDropDownComponent extends IgxDropDownBase implements IDropDownBa
...
-            }
-            if (event) {
-                this.toggleDirective.close();
+            } else {
+                throw new Error('Please provide a valid drop-down item for the selection!');
             }
         }
     }
+
+    protected isSelectionValid(selection: any): boolean {
```
Comment (Lipata) [inline projects/igniteui-angular/src/lib/drop-down/drop-down.component.ts]: You can a brief comment describing different cases.
