### PR TITLE
Fix - Selection - Undefined values should not be accepted as ids

### LINKED ISSUE #2581: IgxSelectionAPIService allows to add items with id which is undefined
### Description  
When using the set() method of the IgxSelectionAPIService  and pass `undefined` for id, then value is associated with `undefined`. This is because the JavaScript Set allows undefined to be added as id.

### Expected result  
Nothing is added to the selection collection, when id is `undefined`.

### PR DESCRIPTION
**Pull request by DiyanDimitrov**
Closes #2581.

### CODE REVIEW

File: projects/igniteui-angular/src/lib/core/selection.ts [hunk 1]
```diff
@@ -19,7 +19,9 @@ export class IgxSelectionAPIService {
      * @param newSelection The new component selection to be set.
      */
     public set(componentID: string, newSelection: Set<any>) {
-        this.selection.set(componentID, newSelection);
+        if (componentID) {
```
Comment (kdinev) [inline projects/igniteui-angular/src/lib/core/selection.ts]: Shouldn't there be an exception if the component ID is `undefined`? To me this scenario is not valid.
