### PR TITLE
fix(grid): rem throtttime lead of event

### LINKED ISSUE #13000: Error thrown by ResizeObserver
* igniteui-angular version: master
 *** browser:**

  -- Chrome 113.0.5672.92 - reproduce
  -- Edge 113.0.5672.92 - reproduce
  -- Firefox 110.0.1 - **does not reproduce**

## Steps to reproduce  

1. Run dev demos, go to grid sample http://localhost:4200/grid

## Result  
image

### PR DESCRIPTION
**Pull request by tishko0**
Closes #13000

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/slider/slider.component.ts [hunk 1]
```diff
@@ -1050,7 +1050,7 @@ export class IgxSliderComponent implements
 
         this._ngZone.runOutsideAngular(() => {
             resizeObservable(this._el.nativeElement).pipe(
-                throttleTime(40),
+                throttleTime(40, undefined, { leading: false, trailing: true }),
```
Comment (MayaKirova) [inline projects/igniteui-angular/src/lib/slider/slider.component.ts:1053]: I don't think the slider is related. If there's some issue with its resize observer - log it separately.

File: projects/igniteui-angular/src/lib/stepper/stepper.component.spec.ts [hunk 2]
```diff
@@ -56,13 +56,13 @@ const getStepperPositions = (): string[] => {
 const testAnimationBehvior = (
     val: any,
     fix: ComponentFixture<IgxStepperSampleTestComponent>,
+    activeChangeSpy: jasmine.Spy,
```
Comment (MayaKirova) [inline projects/igniteui-angular/src/lib/stepper/stepper.component.spec.ts:59]: I don't think the stepper is related. Why were these  changes necessary?

**Review by MayaKirova — CHANGES_REQUESTED** [review]

File: projects/igniteui-angular/src/lib/test-utils/list-components.spec.ts [hunk 3]
```diff
@@ -203,6 +203,7 @@ export class ListWithPanningTemplatesComponent extends ListWithPanningComponent
         <div [style.height]="'240px'" [style.overflow]="'hidden'" [style.position]="'relative'">
             <igx-list-item
                 [index]="i"
+                [style.height]="'30px'"
```
Comment (MayaKirova) [inline projects/igniteui-angular/src/lib/test-utils/list-components.spec.ts:206]: Shouldn't this also be `40px` so that it matches the itemSize set below?

File: projects/igniteui-angular/src/lib/slider/slider.component.ts [hunk 4]
```diff
@@ -1050,7 +1050,7 @@ export class IgxSliderComponent implements
 
         this._ngZone.runOutsideAngular(() => {
             resizeObservable(this._el.nativeElement).pipe(
-                throttleTime(40),
+                throttleTime(40, undefined),
```
Comment (MayaKirova) [inline projects/igniteui-angular/src/lib/slider/slider.component.ts:1053]: Could just be `throttleTime(40)` as it was originally.

File: projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.navigation.spec.ts [hunk 5]
```diff
@@ -157,6 +159,7 @@ describe('IgxHierarchicalGrid Navigation', () => {
         });
 
         it('should allow navigating to start in child grid when child grid target row moves outside the parent view port.', async () => {
+            hierarchicalGrid.navigateTo(2);
```
Comment (MayaKirova) [inline projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.navigation.spec.ts:162]: Isn't this the same as the next line that does `scrollTo(2)`? There shouldn't be a need to call both. Just one or the other.

**Review by MayaKirova — CHANGES_REQUESTED** [review]
