### PR TITLE
Summaries calculated on filteredData result 

### LINKED ISSUE #953: Show summaries only for the present grid rows, not for all data rows
### Description  
When filtering or remote data binding is applied, column summaries should be calculated based on the filtered/remote data binded rows, and not for all grid records.

### Notes
Once this is ready, update the Grid Summaries doc

### LINKED ISSUE #980: igx-grid - summary row can't be horizontally scrolled with igniteui-angular@5.3.0-beta.1
### Description  
With igniteui-angular@5.3.0-beta.1, summary row can't be horizontally scrolled.

### Steps to reproduce  

1. Go to https://stackblitz.com/edit/igx-grid-summary-issue
2. Grab horizontal scrollbar and move it to the right and left.

### Result  
Header and data rows can be scrolled. summary row can't be scrolled.

### Expected result  
Summary row should be able to be scrolled as well.

By the way, with igniteui-angular@5.3.0-beta.0, there was no problem. It seems a regression bug.

### LINKED ISSUE #981: igx-grid - summary cells of "number" or "date" are cut off when they come up after being horizontally scrolled.
### Description  
Summary cells of "number" or "date" are cut off when they come up after being horizontally scrolled.

### Steps to reproduce  

1. Go to https://stackblitz.com/edit/igx-grid-summary-issue2
  Due to #980, this issue can't be demostrated with @5.3.0-beta.1., so this sample uses @5.3.0-beta.0.
2. Grab horizontal scrollbar and move it to the right.

### Result  
Summary cells of "number" or "date" are cut off.

### Expected result  
Summary cells of "number" or "date" should not be cut off. In other words, igx-grid should have enough height of summary row at initial rendering.

### PR DESCRIPTION
**Pull request by ddincheva**
Closes #953 
Closes #980 
Closes #981

### CODE REVIEW

File: src/grid/grid.component.ts [hunk 1]
```diff
@@ -141,6 +141,9 @@ export class IgxGridComponent implements OnInit, OnDestroy, AfterContentInit, Af
         if (this.rowSelectable) {
             this.updateHeaderChecboxStatusOnFilter(this._filteredData);
         }
+        if (this.hasSummarizedColumns) {
```
Comment (kdinev) [inline src/grid/grid.component.ts]: You don't need this line. The setter is already at the top of the method.

File: src/grid/grid.component.ts [hunk 2]
```diff
@@ -838,7 +842,7 @@ export class IgxGridComponent implements OnInit, OnDestroy, AfterContentInit, Af
                 maxSummaryLength = currentLength;
             }
         });
-        return maxSummaryLength * (this.tfoot.nativeElement.clientHeight ? this.tfoot.nativeElement.clientHeight : 36);
+        return maxSummaryLength * (this.tfoot.nativeElement.clientHeight ? this.tfoot.nativeElement.clientHeight : 36.36);
```
Comment (kdinev) [inline src/grid/grid.component.ts]: Make this `36.36` a `const` declaration somewhere in the component. Where is the number coming from anyways?

Comment (zdrawku) [reply src/grid/grid.component.ts]: We are going to change this behavior, although for now we are going to declare a const in the component.
