### PR TITLE
fix(*): Add a min/max size splitter check when ending movement

### LINKED ISSUE #9724: Error minSize on igx-splitter
## Description  
there is a bug on the splitter control, if you put a "minSize" and in any case you manage to overcome it by dropping with the cursor over the limit, the splitter repositions itself over the limit. 

https://stackblitz.com/edit/github-jzhedd

 * igniteui-angular version: 12.0.4
 * browser: latest chrome

## Steps to reproduce  

1. grab the splitter
2. put the cursor over the limit of 200px
3. drop the splitter

## Result  
The splitter will drop over the 200px limit

## Expected result  
The splitter will resize at 200px

## Attachments  
https://stackblitz.com/edit/github-jzhedd

### PR DESCRIPTION
**Pull request by mddragnev**
Closes #9724 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/splitter/splitter.component.ts [hunk 1]
```diff
@@ -216,8 +216,14 @@ export class IgxSplitterComponent implements AfterContentInit {
     }
 
     public onMoveEnd(delta: number) {
+        const min = parseInt(this.pane.minSize, 10) || 0;
```
Comment (MayaKirova) [inline projects/igniteui-angular/src/lib/splitter/splitter.component.ts:219]: Should also apply constraints on sibling, otherwise the sibling can be resized beyond its min/max size.

**Review by MayaKirova — CHANGES_REQUESTED** [review]

File: projects/igniteui-angular/src/lib/splitter/splitter.component.ts (hunk 1 above)
Comment (3phase) [reply projects/igniteui-angular/src/lib/splitter/splitter.component.ts:219]: @MayaKirova The issue should be resolved now.

**Review by MayaKirova — APPROVED** [review]
