### PR TITLE
Fix condition select position strategy

### LINKED ISSUE #5884: Condition dropdown in Advanced Filtering Dialog has incorrect position
## Description  
Condition dropdown in Advanced Filtering Dialog has incorrect position.

 * igniteui-angular version: 8.2.x
 * browser: NA

## Steps to reproduce  

1. Open the Grid Filtering dev demo.
2. Collapse the navigation drawer.
3. Open the advanced filtering dialog.
4. Enter in edit mode on the first expression.
5. Click the condition dropdown to open it.
6. Exit edit mode.
7. Enter edit mode again.
8. Open the condition dropdown.
9. Start pressing arrow down key until the last item is scrolled.

## Result  
The condition's dropdown is position in the top left corner of the page.

## Expected result  
The condition's dropdown should be position below the select component.

## Attachments  
image

### PR DESCRIPTION
**Pull request by DiyanDimitrov**
Closes #5884

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/filtering/advanced-filtering/advanced-filtering-dialog.component.ts [hunk 1]
```diff
@@ -459,17 +457,18 @@ export class IgxAdvancedFilteringDialogComponent implements AfterViewInit, OnDes
         expressionItem.inEditMode = true;
         this.editedExpression = expressionItem;
 
-        requestAnimationFrame(() => {
-            this.columnSelectOverlaySettings.positionStrategy.settings.target = this.columnSelect.element;
+        this.cdr.detectChanges();
```
Comment (tachojelev) [inline projects/igniteui-angular/src/lib/grids/filtering/advanced-filtering/advanced-filtering-dialog.component.ts]: Do we need this **detectChanges()** ?

File: projects/igniteui-angular/src/lib/grids/filtering/advanced-filtering/advanced-filtering-dialog.component.html [hunk 2]
```diff
@@ -144,36 +144,25 @@ <h6 class="igx-filter-empty__title">
                     </igx-select-item>
                 </igx-select>
```
Comment (tachojelev) [inline projects/igniteui-angular/src/lib/grids/filtering/advanced-filtering/advanced-filtering-dialog.component.html]: If applicable, we should add a test for this issue.
