### PR TITLE
Include grid's unpinnedWidth and totalWidth in cell width calculation

### LINKED ISSUE #3462: Summary cell of last column not aligned according to the data cells
### Description  
Summary cell of last column not aligned according to the data cells.

 * igniteui-angular version: 7.1.x
 * browser: any

**NOTES:**
- The issue is reproduced when there is no horizontal scrollbar and the last column has summaries.
- The issue is reproduced for both the IgxGrid and the IgxTreeGrid.

### Steps to reproduce  

1. Open the "grid-summaries.sample.html" file and comment the last two columns, so the new last column has summaries enabled and there is no horizontal scrollbar.
2. Run the "Grid Summary" dev demo.

### Result  
Summary cell of last column is **not** aligned according to the data cells.

### Expected result  
Summary cell of last column is aligned according to the data cells.

### Attachments  

image

### PR DESCRIPTION
**Pull request by tachojelev**
Closes #3462 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/column.component.ts [hunk 1]
```diff
@@ -1198,6 +1198,31 @@ export class IgxColumnComponent implements AfterContentInit {
         }
     }
 
+    /**
+     *@hidden
+     */
+    public get getCellWidth() {
```
Comment (DiyanDimitrov) [inline projects/igniteui-angular/src/lib/grids/column.component.ts]: Make this to be just a method. There is no need to be get property.
