### PR TITLE
fix(autocomplete): allow autocomplete drop-down width to be adjustable - 8.2.x

### LINKED ISSUE #6247: [IgxAutocomplete] Drop-down width cannot be adjusted
## Description  
The width of the autocomplete's drop-down cannot be adjusted via the `width` input - the item container always has the same width as the input.

In the [directive's spec](https://github.com/IgniteUI/igniteui-angular/wiki/igxAutocomplete-Specification), it is stated that the width of the drop-down's **default** value is equal to the width of the input, but it is not mentioned that it cannot be adjusted.

We should either allow the width to be adjusted or update the spec accordingly.

 * igniteui-angular version: 8.2.x
 * browser: N/A

## Steps to reproduce  

1. Open this [StackBlitz](https://stackblitz.com/angular/vmqoyelkvmb)
2. Pass a value to the drop-down's `[width]` input (e.g. `width="600px"`) 
3. Open the drop-down

## Result  
The width of the items container is equal to the input's width.

## Expected result  
The width of the items container is equal to the value passed in the drop-down's width input.

## Additional Information

It is possible to **work around** the strict width by attaching a handler to the drop-down's `onOpening` emitter and manually setting the width to the desired value: [StackBlitz](https://stackblitz.com/edit/autocomplete-width?file=src/app/autocomplete/autocomplete.component.ts)

### PR DESCRIPTION
**Pull request by ViktorSlavov**
Closes #6247

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/directives/autocomplete/autocomplete.directive.ts [hunk 1]
```diff
@@ -277,7 +277,7 @@ export class IgxAutocompleteDirective extends IgxDropDownItemNavigationDirective
         if (this.disabled || !this.collapsed) {
             return;
         }
-        this.target.width = this.parentElement.clientWidth + 'px';
+        this.target.width = this.target.width || (this.parentElement.clientWidth + 'px');
```
Comment (Lipata) [inline projects/igniteui-angular/src/lib/directives/autocomplete/autocomplete.directive.ts]: Please add a comment describing that if not defined width of the drop down will be the width of the input the autocomplete is attached to. You can add also a test.

**Comment by Lipata** [comment]
We will add a test, before merging it.
