### PR TITLE
fix(Grid): fix and tests for #3513. Adding new prop from which to read actual px width for grid cols and using it in igxForOf calculations.

### LINKED ISSUE #3513: Horizontal scrollbar is not shown when column's width is set to a percentage value.
### Description  
Describe the issue.

 * igniteui-angular version: 7.1.x, 6.2.x
 * browser: N/A

### Steps to reproduce  

1. Start Dev Demos
2. Go to Grid Selection Demo
3. Set the first column width to 80%

### Result  
The last column gets partially out of view but the horizontal scrollbar is not shown.

### Expected result  
Horizontal scrollbar should be shown as the sum of columns' widths becomes greater than the grid's width.

### Attachments  
Attach a sample if available, and screenshots, if applicable.  
image

### PR DESCRIPTION
**Pull request by MayaKirova**
Closes #3513

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts [hunk 1]
```diff
@@ -249,6 +255,7 @@ export class IgxForOfDirective<T> implements OnInit, OnChanges, DoCheck, OnDestr
     public ngOnInit(): void {
         let totalSize = 0;
         const vc = this.igxForScrollContainer ? this.igxForScrollContainer._viewContainer : this._viewContainer;
+        this.igxForSizePropName = this.igxForSizePropName ? this.igxForSizePropName : 'width';
```
Comment (ChronosSF) [inline projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts]: prettier:

```typescript
this.igxForSizePropName = this.igxForSizePropName || 'width';
```
