### PR TITLE
 Еmit onSelection event when expected - master

### LINKED ISSUE #9629: IgxSelect - Event order changes depending on the overlay settings configuration
## Description  
Event order changes when overlay settings contains closeAnimation and openAnimation as undefined.

 * igniteui-angular version: 11.1.12
 * browser: n/a

## Steps to reproduce  

1. Run the sample 
2. Open browser console
3. Select an item from IgxSelect

## Result  
IgxSelect emits events "onClosed" --> "onSelection" in order.

## Expected result  
IgxSelect emits events "onSelection" --> "onClosed" in order.

## Attachments  
[igx-select-events.zip](https://github.com/IgniteUI/igniteui-angular/files/6581420/igx-select-events.zip)

### PR DESCRIPTION
**Pull request by IvayloG**
Closes #9629   

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/select/select.component.ts [hunk 1]
```diff
@@ -363,10 +363,12 @@ export class IgxSelectComponent extends IgxDropDownComponent implements IgxSelec
     public selectItem(newSelection: IgxDropDownItemBaseDirective, event?) {
```
Comment (wnvko) [inline projects/igniteui-angular/src/lib/select/select.component.ts:363]: this method should be called `selectItemAndCloseDropDownIfNeeded` 😢 
We may consider refactor this and call `toggleClose` after call `selectItem`

**Review by wnvko — APPROVED** [review]

**Review by ViktorSlavov — CHANGES_REQUESTED** [review]
Could you please add a test for the specific use case?
I feel like the event order can be tested w/o much hassle.

**Review by ViktorSlavov — APPROVED** [review]

**Comment by ViktorSlavov** [comment]
@IvayloG 
Bit of a nit-pick, but since this is a bug fix, could you add a comment for the fix as per our [Coding Guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/General-Naming-and-Coding--Guidelines-for-Ignite-UI-for-Angular#coding-conventions)
