### PR TITLE
fix(dialog): exposed opened property-10.1.x #8320

### LINKED ISSUE #8320: igx-dialog - isOpen is not bindable
## Description  

The property `isOpen` in `IgxDialog` is not bindable. It's declared as an `@Input()` but it only has a getter, which leads to errors.

```ts
export class IgxDialogComponent implements IToggleView, OnInit, OnDestroy, AfterContentInit {
    ...
    @Input()
    get isOpen() {
        return !this.toggleRef.collapsed;
    }
    ....
```

 * igniteui-angular version: "10.1.0"
 * browser: any

## Steps to reproduce

```html
<igx-dialog title="My Dialog"
    [isOpen]="this.myDialogShouldBeOpen"
>
    Content
</igx-dialog>
```

## Result  

In runtime the console prints this error:
> TypeError: Cannot set property isOpen of [object Object] which has only a getter

## Expected result  
The binding works and the dialog is open if and only if the binding is `true`.

## Why?

Right now Dialog can only be opened using imperative API, if this property is bindable I could use it in a fully declarative way. Furthermore, I could remove the dialog entirely when it's not needed (ngIf):

```html
<igx-dialog
    *ngIf="this.myDialogShouldBeOpen"
    title="My Dialog"
    [isOpen]="true"
>
    Content
</igx-dialog>
```

### PR DESCRIPTION
**Pull request by dobromirts**
Closes #8320

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/dialog/dialog.component.ts [hunk 1]
```diff
@@ -368,11 +368,35 @@ export class IgxDialogComponent implements IToggleView, OnInit, OnDestroy, After
...
     }
 
+
+    /**
+     * An @Input property that allows you to open the dialog declaratively.
+     * ```typescript
+     * @ViewChild("MyDialog")
+     * public dialog: IgxDialogComponent;
+     * ngAfterViewInit() {
+     *     let dialogOpen = this.dialog.opened=true;
```
Comment (HristoP96) [inline projects/igniteui-angular/src/lib/dialog/dialog.component.ts:383]:
```suggestion
     *     this.dialog.opened=true;
```

**Review by HristoP96 — CHANGES_REQUESTED** [review]

File: projects/igniteui-angular/src/lib/dialog/dialog.component.ts [hunk 2]
```diff
@@ -359,19 +366,37 @@ export class IgxDialogComponent implements IToggleView, OnInit, OnDestroy, After
...
-     * Returns whether the dialog is visible to the end user.
+     * State of the dialog.
+     *
      * ```typescript
-     * @ViewChild("MyDialog")
-     * public dialog: IgxDialogComponent;
-     * ngAfterViewInit() {
-     *     let dialogOpen = this.dialog.isOpen;
-     * }
+     * * // get
```
Comment (HristoP96) [inline projects/igniteui-angular/src/lib/dialog/dialog.component.ts:372]:
```suggestion
     *  // get
```

**Review by HristoP96 — CHANGES_REQUESTED** [review]

**Review by HristoP96 — APPROVED** [review]

**Review by zdrawku — APPROVED** [review]
