### PR TITLE
fix(expansion-panel): disabled panel header is not focusable w/ click - 11.1.x

### LINKED ISSUE #9696: [IgxExpansionPanel] - Disabled header is focusable w/ mouse click
## Description  
A disabled expansion panel header is still focusable with mouse click

 * igniteui-angular version: all
 * browser: N/A 

## Steps to reproduce  

1. Create an expansion panel and add `[disabled]="true"` to the `igx-expansion-panel-header` tag
2. Click on the header

## Result  
Document active element  === igx-expansion-panel-header

## Expected result  
Document active element  !== igx-expansion-panel-header

### PR DESCRIPTION
**Pull request by ViktorSlavov**
Closes #9696

header.disabled was incorrectly setting `tabIndex === -1`, which still allows elements to be focused via mouse click.
No tab index makes the element non-focusable and `pointer-events: none` style prevents flickering.

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Review by desig9stein — APPROVED** [review]

File: projects/igniteui-angular/src/lib/expansion-panel/expansion-panel-header.component.ts [hunk 1]
```diff
@@ -173,7 +173,7 @@ export class IgxExpansionPanelHeaderComponent {
     public set disabled(val: boolean) {
         this._disabled = val;
         if (val) {
-            this.tabIndex = -1;
+            this.tabIndex = null;
```
Comment (wnvko) [inline projects/igniteui-angular/src/lib/expansion-panel/expansion-panel-header.component.ts:176]:
```suggestion
            delete this.tabIndex;
```
a little better like this

**Review by wnvko — APPROVED** [review]
