### PR TITLE
fix(hgrid): remerge cells after activation clears - master

### LINKED ISSUE #16575: Unmerged cell in hierarchical grid is not cleared even after activation/selection is moved to another grid.
## Description  
Merged cell in hierarchical grid is not cleared even after activation is moved to another grid.

 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Run a sample with hierarchical grid, with cell merging on the row island's columns. For example: https://staging.infragistics.com/products/ignite-ui-angular/angular/components/hierarchicalgrid/cell-merging#angular-cell-merging-example
2. Click on a merge group inside one of the child grids.
4. Then click some cell on the root or in another child grid.

Image

## Result  
The child grid no longer has activation/selection but the cells remain unmerged.

## Expected result  
They merge back.

## Attachments  
Attach a sample if available, and screenshots, if applicable.

### PR DESCRIPTION
**Pull request by IMinchev64**
Closes #16575  

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

**Comment by IMinchev64** [comment]
The original `focusout` logic only cleared the active node when the event target was `tbody/thead/tfoot`, which missed valid focus‑leave cases (e.g., clicking a parent grid). 
This resulted in stale active state in child grids and kept merged cells unmerged. 

Using a `document:focusin` check lets us reliably detect when focus moves outside the grid, regardless of which internal section triggered the event, and clear the active node consistently. This seems simpler, would cover the missing scenario, and avoids relying on specific section elements while also keeping the behavior stable for in‑grid focus changes.

File: projects/igniteui-angular/grids/grid/src/grid-base.directive.ts [hunk 1]
```diff
@@ -3711,6 +3711,14 @@ export abstract class IgxGridBaseDirective implements GridType,
         const destructor = takeUntil<any>(this.destroy$);
         fromEvent(this.nativeElement, 'focusout').pipe(filter(() => !!this.navigation.activeNode), destructor).subscribe((event) => {
             const activeNode = this.navigation.activeNode;
+
+            // In hierarchical grids, activation can be cleared by child highlight logic, leaving an empty object.
+            // If merging is enabled, clear cached active indexes to allow merge state to restore.
+            if (!Object.keys(activeNode).length && this.hasCellsToMerge) {
```
Comment (MayaKirova) [inline projects/igniteui-angular/grids/grid/src/grid-base.directive.ts]: @IMinchev64 I don't think this is the best place to clear `_activeRowIndexes `, especially since this is very specific to the hierarchical grid. 

Maybe in the `clearActivation` method in the hgrid navigation service, since that seems to be the thing that clears the active node:

Image

Or alternatively maybe emit the `activeNodeChange` event, since there's already an handler that listens for that event and updates the collection.
