### PR TITLE
fix(ssr): resize observe and animation player errors

### LINKED ISSUE #15081: Grid with Angular SSR throwing a server error
## Description  
When trying to use the grid in Angular SSR project it throws an error

 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Open the attached sample
2. Observe the error

## Result  
getResizeObserver is not a constructor error

## Expected result  
The grid should work fine

## Attachments  
Attach a sample if available, and screenshots, if applicable.  
[angular--sr.zip](https://github.com/user-attachments/files/17797390/angular--sr.zip)

### PR DESCRIPTION
**Pull request by mddragnev**
Closes #15081   

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [ ] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/services/animation/angular-animation-player.ts [hunk 1]
```diff
@@ -23,7 +23,9 @@ export class IgxAngularAnimationPlayer implements AnimationPlayer {
         // To workaround this we are getting the positions from the inner player.
         //  This is logged in Angular here - https://github.com/angular/angular/issues/18891
         //  As soon as this is resolved we can remove this hack
-        this._innerPlayer = innerRenderer.engine.players[innerRenderer.engine.players.length - 1];
+        const rendererEngine = innerRenderer.engine || innerRenderer.delegate.engine;
+        // A workaround because of Angular SSR is using some delegation.
+        this._innerPlayer = rendererEngine.players[rendererEngine.players.length - 1];
```
Comment (damyanpetev) [inline projects/igniteui-angular/src/lib/services/animation/angular-animation-player.ts:28]: Yeah, anything after accessing the internal `_renderer` can fail at any point. @wnvko it does seem like the referenced issue is resolved, how about we check if this can be removed entirely.

File: projects/igniteui-angular/src/lib/tabs/tabs/tabs.component.ts [hunk 2]
```diff
@@ -138,10 +138,11 @@ export class IgxTabsComponent extends IgxTabsDirective implements AfterViewInit,
     constructor(
         @Inject(IgxAngularAnimationService) animationService: AnimationService,
         cdr: ChangeDetectorRef,
+        platform: PlatformUtil,
         private ngZone: NgZone,
         dir: IgxDirectionality,
     ) {
-        super(animationService, cdr, dir);
+        super(animationService, cdr, platform, dir);
```
Comment (damyanpetev) [inline projects/igniteui-angular/src/lib/tabs/tabs/tabs.component.ts:145]: Eh, why push it to the base if it's not needed? You can keep it as prop for this class like the zone, but also you can do the same check as in utils and check `getResizeObserver()` actually resolves. Would make for the smallest change.

Comment (damyanpetev) [reply projects/igniteui-angular/src/lib/tabs/tabs/tabs.component.ts:145]: PS: Not for this fix, but would be nice if all the uses of the resize observer used the one util method.

**Review by damyanpetev — APPROVED** [review]
