### PR TITLE
The grid should update groupsRecords before raising the onGroupingDone event - 6.2.x,  #2967

### LINKED ISSUE #2967: igx-grid - groupsRecords is not updated yet at the time of onGroupingDone event.
### Description  
`groupsRecords` is not updated yet at the time of onGroupingDone event.

 * igniteui-angular version: 6.2.0
 * browser: N/A

### Steps to reproduce  

1. Go to https://stackblitz.com/edit/igx-grid-ongroupingdone-620
2. Open the console.
3. Drag and drop a column to the group area.

### Result  
Although `onGroupingDone` event is emitted, `groupsRecords` is not updated yet. We get the previous value.

### Expected result  
Until 6.1.8, this value had been updated as expected.
https://stackblitz.com/edit/igx-grid-ongroupingdone-618

### PR DESCRIPTION
**Pull request by PavlovVasil**
Closes #2967  .  

Additional information related to this pull request:

### CODE REVIEW

**Comment by mpavlinov** [comment]
NB: From what I understand this one cannot be automated, so adding a new tag "not-automated".

File: projects/igniteui-angular/src/lib/grids/grid/grid.component.ts [hunk 1]
```diff
@@ -189,6 +189,7 @@ export class IgxGridComponent extends IgxGridBaseComponent implements OnInit, Do
             ungroupedColsArr.forEach((elem) => {
                 ungroupedCols.push(this.getColumnByName(elem.fieldName));
             }, this);
+            this.ngDoCheck();
```
Comment (MayaKirova) [inline projects/igniteui-angular/src/lib/grids/grid/grid.component.ts]: @PavlovVasil Instead of directly calling the lifecycle ngDoCheck handler It would be better to call detectChanges instead.
