### PR TITLE
Reset carousel animation when it  is  playing and change slide

### LINKED ISSUE #6826: Slide is not visible
## Description  
Slide of `IgxCarousel` becomes invisible at some point.

 * igniteui-angular version: 9.0.2
 * browser: Chrome and Opera

## Steps to reproduce  

1. Run this [Stackblitz](https://stackblitz.com/edit/hdfkskhf?file=src%2Fapp%2Fcarousel-sample-1%2Fcarousel-sample-1.component.html).
2. Open a new tab in the browser.
3. Get back to the tab with Stackblitz sample.
4. At some point one of the slides becomes invisible.

## Result  
One of the carousel's slides is not visible.

## Expected result  
All slides should be visible when becomes active slide.

## Attachments  
Sample video showing the issue
[blank_slide.zip](https://github.com/IgniteUI/igniteui-angular/files/4254027/blank_slide.zip)

## Notes
I do not have exact steps to reproduce this. However, leaving the carousel to loop trough slides, going to some other pages, and then go back to carousel usually demonstrates the issue.
What I've found is the blank slide is missing the `igx-slide--current` class.

### PR DESCRIPTION
**Pull request by nrobakova**
Closes #6826 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/carousel/carousel.component.ts [hunk 1]
```diff
@@ -481,6 +481,12 @@ export class IgxCarouselComponent implements OnDestroy, AfterContentInit {
                 if (this.animationType !== CarouselAnimationType.none) {
                     if (animationWasStarted) {
                         requestAnimationFrame(() => {
+                            if (this.leaveAnimationPlayer) {
```
Comment (wnvko) [inline projects/igniteui-angular/src/lib/carousel/carousel.component.ts:484]: you can also check if animation has started like this:
```
if (this.leaveAnimationPlayer && this.leaveAnimationPlayer.hasStarted()) {
```

File: projects/igniteui-angular/src/lib/carousel/carousel.component.ts [hunk 2]
```diff
@@ -505,13 +511,8 @@ export class IgxCarouselComponent implements OnDestroy, AfterContentInit {
         if (this.previousSlide && this.previousSlide.previous) {
             this.previousSlide.previous = false;
         }
-        if (this.leaveAnimationPlayer) {
+        if (this.leaveAnimationPlayer || this.enterAnimationPlayer) {
```
Comment (wnvko) [inline projects/igniteui-angular/src/lib/carousel/carousel.component.ts:514]: I would put this logic in separate method, e.g. `animationStarted`.
Now you have `finishAnimations` method which does not finish animations anymore but returns if the any animation is started.
Go like this leave `finishAnimation` as it was. Add `animationStarted` method and call it where you need to check if any animation was started.
