### PR TITLE
fix(date-picker): date picker outlet removed 

### LINKED ISSUE #5090: [igx-date-picker] While opening of the calendar, the dev sample page flickers in IE
## Description  
Open the date-picker dev demo

 * igniteui-angular version: NA
 * browser: IE 11

## Steps to reproduce  

1. Open date picker dev demo
2. Open one of the date pickers

## Result  
The page disappears for a second

## Expected result  
No flickering

## Attachments  
Attach a sample if available, and screenshots, if applicable.

### PR DESCRIPTION
**Pull request by sboykova**
Closes #5090 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts [hunk 1]
```diff
@@ -800,21 +794,23 @@ export class IgxDatePickerComponent implements IDatePicker, ControlValueAccessor
...
             modal: false,
             scrollStrategy: new AbsoluteScrollStrategy(),
             positionStrategy: new AutoPositionStrategy(this._positionSettings),
-            outlet: outlet
         };
 
         this._modalOverlaySettings = {
             closeOnOutsideClick: true,
             modal: true,
-            outlet: outlet
```
Comment (damyanpetev) [inline projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts]: You can still pass `this.outlet` and let the service do the check :)
