### PR TITLE
Apply expected changes on update to v15

### LINKED ISSUE #12603: Migrations for ver.15 do not update $gray
## Description  
Migrations for ver.15 do not update `$grays` variable when they are supposed to do it: https://github.com/IgniteUI/igniteui-angular/pull/12409/files

 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Run the attached sample (generated from AppBuilder production), that is having igniteui-angular ver.14. (angular is already updated to 15 for easy reproduction)
2. run `ng update @infragistics/igniteui-angular`

## Result  
Note that `$grays` variables are still presented and not replaced with `$gray`.

## Expected result  
With version 15 the variable name should be `$gray`.

In addition, the following improvements in the migrations should be done:

 - message should not be presented for projects that are not with SSR:
image

- migration for igx-typography -> ig-typography and igx-scrollbar -> ig-scrollbar
- removing ~minireset prefix (if possible)

## Attachments  
[Movie App_angular_14.zip](https://github.com/IgniteUI/igniteui-angular/files/10554558/Movie.App_angular_14.zip)

### PR DESCRIPTION
**Pull request by Lipata**
Closes #12603

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/migrations/update-15_0_0/index.ts [hunk 1]
```diff
@@ -47,4 +47,38 @@ export default (): Rule => async (host: Tree, context: SchematicContext) => {
...
+    const indexPath = '/src/index.html';
+    if (host.exists(indexPath)) {
+        host.overwrite(indexPath, updateTypographyAndScrollbar(host.read(indexPath).toString()));
+    }
+
+    update.templateFiles.forEach(path =>
+        host.overwrite(path, updateTypographyAndScrollbar(host.read(path).toString()))
+    );
+
+    const graysVar = /\$grays:\s{0,}(#\w+)(\r\n|\r|\n|,)/s,
```
Comment (wnvko) [inline projects/igniteui-angular/migrations/update-15_0_0/index.ts:68]: this will fail if `$grays` is set to anything but hexadecimal syntax. All these will not be replaced:
$grays: red,
$grays: rgb(204, 102, 153),
$grays: rgba(107, 113, 127, 0.8),
$grays: hsl(228, 7%, 86%),
$grays: hsla(20, 20%, 85%, 0.7),

**Review by wnvko — DISMISSED** [review]

File: projects/igniteui-angular/migrations/update-15_0_11/index.ts [hunk 2]
```diff
@@ -0,0 +1,48 @@
+import {
+    Rule,
+    SchematicContext,
+    Tree
+} from '@angular-devkit/schematics';
+import { UpdateChanges } from '../common/UpdateChanges';
+
+const version = '15.0.4';
```
Comment (jackofdiamond5) [inline projects/igniteui-angular/migrations/update-15_0_11/index.ts:8]:
```suggestion
const version = '15.0.11';
```

File: projects/igniteui-angular/schematics/utils/dependency-handler.ts [hunk 3]
```diff
@@ -175,7 +175,6 @@ const addStylePreprocessorOptions =
             `It could require you to manually update it to "stylePreprocessorOptions": { "includePaths": ["node_modules"] }`;
 
         if (!projectOptions) {
-            context.logger.warn(warn);
```
Comment (wnvko) [inline projects/igniteui-angular/schematics/utils/dependency-handler.ts:178]: this method does nothing now!

**Review by wnvko — APPROVED** [review]
