### PR TITLE
Don't clear sorting if column is grouped

### LINKED ISSUE #4119: When change sorting from the excel filter it is not applied for the grouped column
## Description  
When change sorting from the excel filter it is not applied for the grouped column

 * igniteui-angular version: 7.2
 * browser: N/A

## Steps to reproduce  

1. Open dev sample gridColumnMoving
2. Group by a column
3. Open excelfilter for this column and remove sortig
4. Click on DESCENDING button

Note: after that cannot change sort order from the grouped column

## Result  
The change is not applied for the grouped column 

## Expected result  
The change should be applied

## Attachments  
image

### PR DESCRIPTION
**Pull request by sstoyanovIG**
Closes #4119   

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-sorting.component.ts [hunk 1]
```diff
@@ -31,8 +31,16 @@ export class IgxExcelStyleSortingComponent {
     constructor() {}
 
     public onSortButtonClicked(sortDirection) {
+        let isColumnGrouped;
+        if (this.grid instanceof IgxGridComponent) {
```
Comment (bkulov) [inline projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-sorting.component.ts]: Excel style filtering is applicable to all grids we currently have. Casting the current grid instance to one grid type is not a good solution.
In my opinion you should add a method in the base class which will return if a given column from the current grid instance is grouped or not. This method will return actual result only for the grid and for the hierarchical and tree-grid it will return false.
That way we wont make a dependency to one grid type in the feature which is applicable to all grid types.

Comment (sstoyanovIG) [reply projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-sorting.component.ts]: The reason for this is that only IgxGrid supports grouping and only it has 'groupingExpressions' property.

Comment (bkulov) [reply projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-sorting.component.ts]: Sure, but my comment is still valid. We shouldn't introduce dependency to one grid type here. Tomorrow some of the other grids may support grouping and this code will fail.

Comment (sstoyanovIG) [reply projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-sorting.component.ts]: Ok, I got your point, I will add a getter in the base class that will return false and I will override it in the IgxGrid only.

File: projects/igniteui-angular/src/lib/grids/grid/grid.component.ts [hunk 2]
```diff
@@ -638,6 +638,17 @@ export class IgxGridComponent extends IgxGridBaseComponent implements IGridDataB
         this._gridAPI.sort_multiple(this.id, this._groupingExpressions);
     }
 
+    /**
+     * @hidden
+     */
+    public isColumnGrouped(fieldName: string): boolean {
+        if (this.groupingExpressions.find(exp => exp.fieldName === fieldName)) {
```
Comment (bkulov) [inline projects/igniteui-angular/src/lib/grids/grid/grid.component.ts]: Just return the expression here.
