### PR TITLE
fix(date-picker): Dropdown is opened above if there is no space below…

### LINKED ISSUE #4241: DatePicker's DropDown does not appear above the component when the DatePicker is at the bottom of the page
## Description  
DatePicker's DropDown does not appear above the component when DatePicker is at the bottom of the page.

 * igniteui-angular version: 7.2.x
 * browser: NA

## Steps to reproduce  

1. Open the DatePicker dev demo.
2. Resize the browser so that the 'Editable Drop Down Date Picker' is at the bottom of the page.
3. Click the calendar icon to expand the DropDown.

## Result  
The DropDown appears below the DatePicker and the page is resized and scrolled down.

## Expected result  
The DropDown should expand above the DatePicker when there is no place below it.

### PR DESCRIPTION
**Pull request by sboykova**
Closes #4241  

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts [hunk 1]
```diff
@@ -884,9 +889,16 @@ export class IgxDatePickerComponent implements IDatePicker, ControlValueAccessor
...
-                const dropDownOverlay =
-                    (this.dropDownOverlaySettings !== undefined) ? this._dropDownOverlay : this._dropDownOverlaySettings;
-                dropDownOverlay.positionStrategy.settings.target = this.editableInputGroup.nativeElement;
+                let dropDownOverlay;
+
+                if (this.dropDownOverlaySettings !== undefined) {
+                    dropDownOverlay = this._dropDownOverlay;
+                } else {
+                    dropDownOverlay = this._dropDownOverlaySettings;
+                    dropDownOverlay.positionStrategy.settings.target = this.editableInputGroup.nativeElement;
```
Comment (bkulov) [inline projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts]: This code won't work in case the input group is retemplated.

File: projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts [hunk 2]
```diff
@@ -480,6 +481,61 @@ describe('IgxDatePicker', () => {
         expect(month.innerText.trim()).toBe(expectedResult.trim());
     }));
 
+    describe('Drop-down opening', () => {
```
Comment (bkulov) [inline projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts]: Do we have a test with retemplated datepicker? If not please write one.

Comment (sboykova) [reply projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts]: yes, there are already tests for retemplated dropdown and dialog date-picker.
