### PR TITLE
Set mask to TimePicker's editor on clear

### LINKED ISSUE #8146: Can't entry a time from the keyboard after resetting the time with the reset button.
## Description  
Can't entry a time from the keyboard after resetting the time with the reset button.

 * igniteui-angular version: 10.1.2
 * browser: Chrome

## Steps to reproduce  

Sample
https://bnmiogaba.github.stackblitz.io
(Source : https://stackblitz.com/github/bnmiogaba)

1. Click time icon.
1. Set hour and minutes.
2. Click reset button.
3. Entry hour and minutes from the keyboard.

sample

## Result  
Can't entry hour and minutes after click reset button.

## Expected result  
Allow enter hour and minutes after click reset button.

## Attachments  
Sample
https://bnmiogaba.github.stackblitz.io
(Source : https://stackblitz.com/github/bnmiogaba)
sample

### PR DESCRIPTION
**Pull request by jackofdiamond5**
Closes #8146

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts [hunk 1]
```diff
@@ -1952,7 +1952,11 @@ export class IgxTimePickerComponent implements
 
             const oldVal = new Date(this.value);
 
-            this.displayValue = '';
+            this.displayValue = this.parseMask(false);
+            requestAnimationFrame(() => {
+                this._setCursorPosition(0);
+            });
+            // TODO: refactoring - this.value should be null #8135
             this.value.setHours(0, 0);
```
Comment (wnvko) [inline projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts:1960]: Two issues here, probably related with #8135

- if I start with time picker in drop down `mode` with no value, e.g. `<igx-time-picker [mode]="'DropDown'"></igx-time-picker>` this on first place has `clear` button. On second place if I click `clear` button I end up with error `Cannot read property 'setHours' of undefined`. Same behavior on master!
- if I have value, press back space until value is completely deleted. Then I enter some value and press the `clear` button value is not cleared. It is only moves the cursor to the start of input. This does not happen on master, where the value is cleared.

Again, not sure if this is related to above mentioned issue, but if this is, IMO we should first fix the other issue.

**Review by wnvko — CHANGES_REQUESTED** [review]

File: projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts [hunk 2]
```diff
@@ -1971,35 +1974,34 @@ export class IgxTimePickerComponent implements
...
             this.isNotEmpty = false;
-
-            this.value.setHours(0, 0);
-            this.displayValue = val;
-
-            if (oldVal.getTime() !== this.value.getTime()) {
+            // TODO: refactoring - this.value should be null #6585
+            this.value?.setHours(0, 0, 0);
+            this.displayValue = inputMask;
+            if (oldVal.getTime() !== this.value?.getTime()) {
```
Comment (wnvko) [inline projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts:2004]: in case there is no initial value, and you delete the entire mask the component will fire `onValueChanged` which is wrong. This is better in this PR as on master this throws an exception. Please add a comment for future refactoring to stop emit this event in this case.

**Review by wnvko — CHANGES_REQUESTED** [review]

**Review by wnvko — APPROVED** [review]

**Review by wnvko — APPROVED** [review]
