### PR TITLE
fix(grid): Allow copiyng from quick filtering input

### LINKED ISSUE #11765: Grids: copying from quick filtering input sets no data in the clipboard
## Description  
In any of the grids (`IgxGrid`, `IgxTreeGrid`. `IgxHierarchicalGrid`) for Quick filtering mode, copying the filtering input value does not work as expected and nothing is copied.

 * igniteui-angular version: any
 * browser: any

## Steps to reproduce  

1. Open the [Grid Filtering demo](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/filtering) in the docs.
2. Press the 'Filter' chip for any column.
3. Enter any vlaue in the filter input and copy it, either with Ctrl + C or through the browser context menu.
4. Attempt pasting anywhere.

## Result  
The selected text is not copied.

## Expected result  
To have the selected text in the clipboard. 
For reference, copying from Advanced filtering and ESF UI's inputs works as expected.

## Attachments  
copying-filter

### PR DESCRIPTION
**Pull request by viktorkombov**
Closes #11765 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/grid-base.directive.ts [hunk 1]
```diff
@@ -5607,6 +5607,11 @@ export abstract class IgxGridBaseDirective extends DisplayDensityBase implements
      * @internal
      */
     public copyHandler(event) {
+        if (event.path?.map(el => el.tagName).includes('IGX-GRID-FILTERING-ROW') ||
```
Comment (ChronosSF) [inline projects/igniteui-angular/src/lib/grids/grid-base.directive.ts:5610]: `event.path` is non-standardized and is undefined in Firefox. Use `event.composedPath()` instead.

Comment (ChronosSF) [reply projects/igniteui-angular/src/lib/grids/grid-base.directive.ts:5610]: Also you are mapping the path twice when you can only do it once. In addition, tagName being all upper case is not always true. If you google search it you'll find cases where it can be  lowercase. You should normalize the search by applying toLower/UpperCase in the mapping.

**Review by ChronosSF — CHANGES_REQUESTED** [review]

**Review by ChronosSF — APPROVED** [review]
