### PR TITLE
fix(time-picker): exclude from SSR toggle events #15135

### LINKED ISSUE #15135: Error with ssr/prerendering of igx-time-picker
## Description  
When I try to prerender a route containing an `igx-time-picker` I get an error message.

 * igniteui-angular version: 19.0.x
 * browser: Server

## Steps to reproduce  

1. Create a project with SSR
2. Add a time picker
3. Build

## Result  
`ERROR TypeError: this._inputGroup.element.nativeElement.getBoundingClientRect is not a function`

## Expected result  
No error should be thrown

### PR DESCRIPTION
**Pull request by Lipata**
Closes #15135

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts [hunk 1]
```diff
@@ -734,7 +734,10 @@ export class IgxTimePickerComponent extends PickerBaseDirective
     public override ngAfterViewInit(): void {
         super.ngAfterViewInit();
         this.subscribeToDateEditorEvents();
-        this.subscribeToToggleDirectiveEvents();
+
+        if (this.platform.isBrowser) {
```
Comment (jackofdiamond5) [inline projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts:738]: The `subscribeToToggleDirectiveEvents` is responsible for binding to the `toggle directive` events. And then the `time picker` will emit its own events on `toggleRef.opened`/`toggleRef.closed` etc.

The error that this PR attempts to fix comes from `time-picker.component.ts#1256`. The `this._inputGroup.element.nativeElement.getBoundingClientRect` function cannot be used when the app is served in server mode as the `getBoundingClientRect` is browser specific API.

With the current approach we are also wrapping the events that we want to listen for in all cases. 

Instead, let's check if the platform is browser right before we execute the browser-specific API. This way we ensure that there can be no cases where we don't listen for the `toggle directive` events.
