### PR TITLE
fix(grid): Fix calculate height when initially grid has no data #3950

### LINKED ISSUE #3950: igx-grid: Incorrect height calculation when setting height in percent and binding empty data.
## Description  
There is a problem with height calculation when setting height in percent and binding empty data.

 * igniteui-angular version: 7.1.7
 * browser: N/A

## Steps to reproduce  

1. Run the attached sample.

## Result  
Although I set `igx-grid` height to `100%`, `igx-grid` doesn't fit to its parent.

## Expected result  
`igx-grid` should fit to its parent.

## Attachments  
[my-app.zip](https://github.com/IgniteUI/igniteui-angular/files/2878857/my-app.zip)

### PR DESCRIPTION
**Pull request by mpavlinov**
Closes #3950 #3949 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [x] This PR includes unit tests covering all the new code
 - [ ] This PR includes API docs for newly added methods/properties
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/grids/grid-base.component.ts [hunk 1]
```diff
@@ -3574,7 +3574,7 @@ export abstract class IgxGridBaseComponent extends DisplayDensityBase implements
      * Sets this._height
      */
     protected _derivePossibleHeight() {
-        if ((this._height && this._height.indexOf('%') === -1) || !this._height || !this.isAttachedToDom) {
+        if ((this._height && this._height.indexOf('%') === -1) || !this._height || !this.isAttachedToDom || this.rowBasedHeight === 0) {
```
Comment (kdinev) [inline projects/igniteui-angular/src/lib/grids/grid-base.component.ts]: Please transfer your changes from the 6.2.x branch here.

Comment (mpavlinov) [reply projects/igniteui-angular/src/lib/grids/grid-base.component.ts]: @kdinev Done
