### PR TITLE
Fix animations when content is flipped

### LINKED ISSUE #8238: Auto position strategy use wrong animation when flipped
## Description  
In `IgxOverlay` when using `AutoPositionStrategy` in case the content is flipped, e.g. initially should show in down direction, but there is not space and it shows in upper direction, the animation is not changed.

 * igniteui-angular version: 9.1.x; 10.1.x; 10.2.x
 * browser: all

## Steps to reproduce  

Show overlay with `AutoPositionStrategy` forcing the content to be flipped.

## Result  
Animation starts from the top of the content.

## Expected result  
Overlay should use the opposite animation - from bottom to top.

### PR DESCRIPTION
**Pull request by wnvko**
New util function is introduced - `oppositeAnimationResolver`. Passing an animation to this function returns opposite animation if one exists. By the help of this function, when content shown in overlay is flipped by the auto position strategy, we are changing and provided animations.

Closes #8238 

### Additional information (check all that apply):
 - [x] Bug fix
 - [ ] New functionality
 - [ ] Documentation
 - [ ] Demos
 - [ ] CI/CD

### Checklist:
 - [x] All relevant tags have been applied to this PR
 - [ ] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
 - [ ] This PR includes API docs for newly added methods/properties ([api docs guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Documentation-Guidelines))
 - [ ] This PR includes `feature/README.MD` updates for the feature docs
 - [ ] This PR includes general feature table updates in the root `README.MD`
 - [ ] This PR includes `CHANGELOG.MD` updates for newly added functionality
 - [ ] This PR contains breaking changes
 - [ ] This PR includes `ng update` migrations for the breaking changes ([migrations guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Update-Migrations))
 - [ ] This PR includes behavioral changes and the feature specification has been updated with them

### CODE REVIEW

File: projects/igniteui-angular/src/lib/core/utils.ts [hunk 1]
```diff
@@ -451,3 +471,125 @@ export function yieldingLoop(count: number, chunkSize: number, callback: (index:
 }
 
 export function mkenum<T extends { [index: string]: U }, U extends string>(x: T) { return x; }
+
+export function reverseAnimationResolver(animation: AnimationReferenceMetadata): AnimationReferenceMetadata {
+    return oppositeAnimation.get(animation) ?? animation;
+}
+
+const oppositeAnimation: Map<AnimationReferenceMetadata, AnimationReferenceMetadata> = new Map([
```
Comment (ViktorSlavov) [inline projects/igniteui-angular/src/lib/core/utils.ts:487]: I feel like the animation breakup could be expanded. Currently, we don't differentiate between animations regarding the X and Y axis. In a case where we're only flipping the container horizontally, but the animation is vertical, it would still be "flipped" (even though it doesn't need to, since the overlay would still appear, for example, on the bottom of the target)

Comment (ViktorSlavov) [reply projects/igniteui-angular/src/lib/core/utils.ts:487]: Also, some animations are both vertical and horizonal.
For example, to display a container to the `VerticalAlignment.Top` and `HorizontalAlignment.Left` side of a component, you'd use `scaleInBr`.
Depending on the viewport, the autoposition could force several different display flips:
`HorizontalAlignment` changes to `Left` - animation should change to `scaleInBl`.  
`VerticalAlignment` changes to `Bottom` - animation should change to `scaleInTr`.
If **both** `Horizontal` and `VerticalAlignment` change - animation should change to `scaleInTl`.

**Review by ViktorSlavov — CHANGES_REQUESTED** [review]

**Review by simeonoff — DISMISSED** [review]

**Review by ViktorSlavov — DISMISSED** [review]

**Review by ViktorSlavov — APPROVED** [review]
